/**
 * NCLEX Client Needs dataset.
 *
 * Each entry is tagged with one of the four official NCLEX Client Needs
 * categories. Every clinical fact yields 10 unique questions, so 10 facts per
 * category produces exactly 100 questions per category.
 *
 * Format: [clientNeed, condition, [ [finding, priorityAction, keyDrug, keyLab], ... ]]
 */

export type ClientNeedFact = [finding: string, action: string, drug: string, lab: string];

export const CLIENT_NEEDS = [
  "Safe and Effective Care Environment",
  "Health Promotion and Maintenance",
  "Psychosocial Integrity",
  "Clinical Judgement",
] as const;

export type ClientNeed = (typeof CLIENT_NEEDS)[number];

export const CLIENT_NEED_DATA: [clientNeed: ClientNeed, condition: string, facts: ClientNeedFact[]][] = [
  // ── Safe and Effective Care Environment ─────────────────────────
  ["Safe and Effective Care Environment", "client identification safety", [
    ["two clients on the ward with the same surname", "verify identity using two identifiers before any intervention", "not applicable", "identification band"],
    ["an identification band that does not match the prescription", "stop the medication and clarify with the prescriber", "not applicable", "prescription chart"],
    ["a confused client trying to remove the identification band", "reapply the band and inform the team", "not applicable", "not applicable"],
    ["a client arriving from theatre with no band", "apply a new band and verify details with a second nurse", "not applicable", "identification band"],
    ["an unconscious client with no relatives present", "follow the policy for identifying unknown clients", "not applicable", "not applicable"],
    ["a prescription being prepared for the wrong bed number", "stop and verify the correct client before administering", "not applicable", "prescription chart"],
    ["a newborn at risk of being mixed up in the nursery", "follow the matching tag and verification protocol", "not applicable", "not applicable"],
    ["a nurse relying on memory rather than the wrist band", "always check the band with two identifiers", "not applicable", "not applicable"],
    ["a relative collecting medicines for a client", "verify the identity and the authority to collect", "not applicable", "not applicable"],
    ["a client transferred between wards with a missing record", "reconcile the records before continuing treatment", "not applicable", "not applicable"],
  ]],
  ["Safe and Effective Care Environment", "delegation and supervision", [
    ["a stable client needing routine vital signs", "delegate to the support worker and follow up", "not applicable", "not applicable"],
    ["a client with a changing neurological observation", "assess personally rather than delegating", "not applicable", "neurological assessment"],
    ["teaching a newly diagnosed diabetic client", "retain teaching because it cannot be delegated", "not applicable", "not applicable"],
    ["a support worker unsure about a delegated task", "explain the task and supervise until competent", "not applicable", "not applicable"],
    ["a newly qualified nurse managing a busy ward alone", "provide supervision and structured support", "not applicable", "supervision record"],
    ["a student asked to give intravenous medicines", "decline and inform the supervising registered nurse", "not applicable", "competency record"],
    ["a complex wound assessment needed on a busy shift", "perform the assessment yourself rather than delegate", "not applicable", "not applicable"],
    ["a support worker reporting an abnormal observation", "assess the client promptly and act on the finding", "not applicable", "vital signs"],
    ["a team unclear about who is responsible for a task", "clarify accountability before the task is carried out", "not applicable", "not applicable"],
    ["a task delegated without any follow up", "always follow up on every delegated task", "not applicable", "not applicable"],
  ]],
  ["Safe and Effective Care Environment", "safety and fall prevention", [
    ["an unsteady client prescribed a new sedative", "keep the bed low and the call bell within reach", "not applicable", "fall risk score"],
    ["a client found on the floor beside the bed", "assess for injury and complete an incident report", "not applicable", "neurological assessment"],
    ["wet flooring beside a confused client", "clean and dry the area and add supervision", "not applicable", "not applicable"],
    ["a client climbing over cot sides at night", "reassess the need and use a safer alternative", "not applicable", "not applicable"],
    ["a client with a history of falls wanting to walk alone", "supervise the walk and provide a walking aid", "not applicable", "not applicable"],
    ["a dimly lit corridor used by unsteady clients", "improve the lighting and report the hazard", "not applicable", "not applicable"],
    ["a client wearing loose slippers on a polished floor", "provide well-fitting non-slip footwear", "not applicable", "not applicable"],
    ["a bed left in the highest position after care", "lower the bed and lock the wheels", "not applicable", "not applicable"],
    ["equipment with a frayed electrical cable in use", "remove it from service and label it for repair", "not applicable", "not applicable"],
    ["a client who smokes while on oxygen therapy", "stop the smoking immediately and educate the family", "oxygen", "oxygen saturation"],
  ]],
  ["Safe and Effective Care Environment", "infection control practice", [
    ["hand hygiene skipped between two client contacts", "perform hand hygiene between every client contact", "not applicable", "not applicable"],
    ["the same syringe used for several clients", "use a new sterile syringe for every injection", "not applicable", "not applicable"],
    ["soiled linen carried uncovered through a corridor", "transport and process the linen safely", "not applicable", "not applicable"],
    ["sharps mixed with general waste in a bin", "segregate the waste into the correct colour-coded bins", "not applicable", "waste audit"],
    ["a coughing client with no screening or mask offered", "screen, triage and offer a mask", "not applicable", "not applicable"],
    ["equipment shared between clients without decontamination", "decontaminate and sterilise before reuse", "chlorine solution", "sterilisation record"],
    ["gloves not worn during a procedure with blood spillage", "use protective equipment and follow the exposure protocol", "post-exposure prophylaxis", "baseline screening"],
    ["an isolation room with no signage or instructions", "display clear signage and brief the staff", "not applicable", "not applicable"],
    ["a needle stick injury washed and forgotten with no report", "wash, report and start post-exposure prophylaxis", "post-exposure prophylaxis", "baseline HIV test"],
    ["staff reusing disposable masks to save supplies", "report the shortage and follow the safety standard", "not applicable", "not applicable"],
  ]],
  ["Safe and Effective Care Environment", "legal and ethical practice", [
    ["a client being prepared for surgery who does not understand the operation", "pause and ask the clinician to re-explain before signing", "not applicable", "consent form"],
    ["a nurse discussing a client's HIV status in the corridor", "stop the discussion and remind the colleague about confidentiality", "not applicable", "not applicable"],
    ["a nurse posting a client's photograph online", "remove it and follow the confidentiality policy", "not applicable", "not applicable"],
    ["a client's treatment decided by relatives against her wish", "respect the client's own informed decision", "not applicable", "not applicable"],
    ["client records left open on a desk in a public area", "secure the records and follow the confidentiality policy", "not applicable", "not applicable"],
    ["a nurse accepting an expensive gift from a client's family", "politely decline and explain professional boundaries", "not applicable", "not applicable"],
    ["misconduct by a colleague ignored by everyone", "report through the proper channel", "not applicable", "incident report"],
    ["a complaint dismissed without any investigation", "listen, investigate and respond to the complaint", "not applicable", "complaint register"],
    ["a nurse giving a double dose and hiding the error", "assess the client, report the error and complete an incident form", "not applicable", "incident report"],
    ["a client asking for information about a living will", "provide information and involve the appropriate team", "not applicable", "not applicable"],
  ]],
  ["Safe and Effective Care Environment", "emergency management", [
    ["an unresponsive client with no normal breathing", "call for help and start chest compressions at 30:2", "adrenaline", "rhythm strip"],
    ["a deteriorating client managed alone for too long", "call for senior help early", "not applicable", "vital signs"],
    ["an emergency managed with no record of the drugs given", "document times, drugs and responses accurately", "not applicable", "not applicable"],
    ["an unstable client transferred with no oxygen or escort", "stabilise and transfer with the right escort and equipment", "oxygen", "vital signs"],
    ["an emergency trolley left empty after a resuscitation", "restock and check the trolley immediately after use", "not applicable", "trolley checklist"],
    ["a client with chest pain left waiting behind minor cases", "prioritise the acutely ill client immediately", "not applicable", "ECG"],
    ["several staff performing the same task during an arrest", "follow clear team roles during resuscitation", "not applicable", "not applicable"],
    ["a family left waiting with no information for hours", "update the family regularly and with compassion", "not applicable", "not applicable"],
    ["a deceased client left uncovered in view of others", "treat the body with dignity and respect the family", "not applicable", "not applicable"],
    ["many casualties arriving at once after a bus crash", "triage using the priority categories and treat the most salvageable first", "not applicable", "triage tag"],
  ]],

  // ── Health Promotion and Maintenance ────────────────────────────
  ["Health Promotion and Maintenance", "antenatal health education", [
    ["a woman at 28 weeks who has not attended antenatal care", "trace and counsel her on the benefits of skilled care", "ferrous sulphate", "haemoglobin level"],
    ["a pregnant woman sleeping without a treated bed net", "provide a treated net and teach its correct use", "insecticide-treated net", "not applicable"],
    ["a woman unaware of pregnancy danger signs", "teach the danger signs and when to seek help", "not applicable", "antenatal card"],
    ["a pregnant woman taking unwashed raw vegetables", "teach safe food handling to prevent infection", "not applicable", "not applicable"],
    ["a woman with no birth preparedness plan", "help her develop a plan for transport and support", "not applicable", "antenatal card"],
    ["a pregnant woman smoking and drinking alcohol", "counsel on the risks and offer support to stop", "not applicable", "not applicable"],
    ["a woman with no plan for a skilled birth attendant", "counsel on the benefits of facility delivery", "not applicable", "not applicable"],
    ["a mother worried about normal pregnancy discomforts", "reassure and explain the expected changes", "not applicable", "not applicable"],
    ["a pregnant woman with poor weight gain", "assess the diet and refer for nutritional support", "not applicable", "weight chart"],
    ["a woman asking about the benefits of breastfeeding", "counsel on exclusive breastfeeding for six months", "not applicable", "not applicable"],
  ]],
  ["Health Promotion and Maintenance", "child growth and development", [
    ["a child not weighed for six months at the clinic", "weigh the child and plot the growth chart", "not applicable", "growth chart"],
    ["a two-year-old who cannot walk without support", "refer for developmental assessment", "not applicable", "developmental assessment"],
    ["a child crossing downwards on the growth chart", "assess feeding and refer for nutritional review", "not applicable", "growth chart"],
    ["a caregiver unsure what to feed a six-month-old", "teach the introduction of thick complementary foods", "not applicable", "growth chart"],
    ["a baby force-fed by a caregiver at every meal", "teach feeding in response to the baby's cues", "not applicable", "growth chart"],
    ["a child with no immunisation card at the clinic", "start a card and plan the catch-up schedule", "vaccine", "immunisation card"],
    ["a child missing a measles dose at 18 months", "update the card and schedule catch-up vaccination", "measles vaccine", "immunisation card"],
    ["a hospitalised child with no play or stimulation for a week", "provide play and age-appropriate stimulation", "not applicable", "not applicable"],
    ["a child vaccinated at the wrong interval between doses", "follow the national schedule and correct the interval", "vaccine", "immunisation card"],
    ["a caregiver asking when a child should start walking", "explain the normal range and when to refer", "not applicable", "developmental assessment"],
  ]],
  ["Health Promotion and Maintenance", "chronic disease self-management", [
    ["a client who stopped antihypertensive medicines because he felt well", "explain lifelong treatment and the risk of stroke", "amlodipine", "blood pressure"],
    ["a diabetic client eating large servings of starchy food three times daily", "teach portion control and a balanced plate", "metformin", "random blood glucose"],
    ["a client with asthma using a reliever inhaler several times daily", "review the technique and the preventer adherence", "beclomethasone", "peak expiratory flow"],
    ["a client with a new diagnosis who is frightened", "provide clear information and involve the family", "not applicable", "not applicable"],
    ["a client returning to clinic with no self-monitoring record", "teach home monitoring and record keeping", "not applicable", "not applicable"],
    ["a client stopping a medicine because of mild side effects", "explain the effects and review the treatment options", "not applicable", "not applicable"],
    ["a client with a foot ulcer from untreated diabetes", "teach daily foot inspection and urgent reporting", "not applicable", "random blood glucose"],
    ["a client who does not understand why follow-up matters", "explain the purpose of monitoring and book the review", "not applicable", "not applicable"],
    ["a client with a family history of hypertension asking about prevention", "counsel on diet, exercise and regular screening", "not applicable", "blood pressure"],
    ["a client self-medicating with herbal remedies alongside prescriptions", "ask about herbal use and advise on interactions", "not applicable", "not applicable"],
  ]],
  ["Health Promotion and Maintenance", "preventive screening", [
    ["a woman over 30 who has never had a cervical screening test", "offer cervical cancer screening and counselling", "not applicable", "cervical screening result"],
    ["a client with a family history of colon cancer refusing screening", "counsel on the benefits and address the fears", "not applicable", "not applicable"],
    ["a man over 40 with no blood pressure check for years", "check the blood pressure and advise on risk factors", "not applicable", "blood pressure"],
    ["a woman with bleeding after intercourse who is frightened", "refer urgently for gynaecological assessment", "not applicable", "cervical biopsy"],
    ["a client with no immunisation record for hepatitis B", "screen and offer vaccination", "hepatitis B vaccine", "not applicable"],
    ["a client with a chronic cough who has never been tested for tuberculosis", "collect sputum samples for testing", "not applicable", "sputum AFB"],
    ["a pregnant woman with no syphilis screening at booking", "offer screening and treat if positive", "benzathine penicillin", "rapid syphilis test"],
    ["a client with diabetes asking how often to check the eyes", "explain the annual retinal screening schedule", "not applicable", "retinal screening"],
    ["a client who has never tested for HIV", "offer pre-test counselling and screening", "not applicable", "HIV rapid test"],
    ["a client asking why screening matters when they feel well", "explain that early disease often has no symptoms", "not applicable", "not applicable"],
  ]],
  ["Health Promotion and Maintenance", "lifestyle and nutrition counselling", [
    ["a caregiver unable to prepare a balanced weaning food", "run a practical cooking demonstration with local foods", "not applicable", "growth chart"],
    ["a client with a body mass index of 35 wanting to lose weight", "set realistic goals for diet and activity", "not applicable", "body mass index"],
    ["a client eating fewer than two servings of vegetables a day", "counsel on increasing fruit and vegetable intake", "not applicable", "not applicable"],
    ["a mother skipping meals to feed her baby", "counsel her to eat and drink adequately to make milk", "not applicable", "haemoglobin level"],
    ["a client drinking several sugary soft drinks daily", "teach the sugar content and offer alternatives", "not applicable", "not applicable"],
    ["a client starting an exercise plan after years of inactivity", "advise gradual progression to avoid injury", "not applicable", "not applicable"],
    ["a client with a high salt intake and raised blood pressure", "teach practical ways to reduce dietary salt", "not applicable", "blood pressure"],
    ["a family cooking with reused deep-fried oil", "counsel on the health risks and safer alternatives", "not applicable", "not applicable"],
    ["a client unsure how to read a food label", "teach label reading for salt, sugar and fat", "not applicable", "not applicable"],
    ["a client with anaemia eating a diet with no iron-rich foods", "counsel on iron-rich local foods and absorption", "ferrous sulphate", "haemoglobin level"],
  ]],
  ["Health Promotion and Maintenance", "reproductive and family planning education", [
    ["a mother asking when she can start a contraceptive method", "counsel on options and respect her informed choice", "progestogen-only pill", "not applicable"],
    ["a mother believing she cannot conceive while breastfeeding", "explain that breastfeeding is not a reliable contraceptive", "not applicable", "not applicable"],
    ["a woman with five children requesting a long-acting method", "counsel on options and obtain informed consent", "levonorgestrel implant", "pregnancy test"],
    ["a teenager afraid to ask for contraception", "provide confidential and non-judgemental counselling", "not applicable", "not applicable"],
    ["a husband refusing to allow his wife to use contraception", "invite him for counselling and explain the benefits", "not applicable", "not applicable"],
    ["a woman asking about the return of fertility after delivery", "counsel her on fertility and contraception options", "not applicable", "not applicable"],
    ["a client using only hormonal contraception with a new partner", "counsel on dual protection against infections", "condoms", "not applicable"],
    ["a mother asking about the breastfeeding contraceptive method", "explain the strict criteria required for it to work", "not applicable", "not applicable"],
    ["a woman presenting within 72 hours of unprotected intercourse", "counsel and give emergency contraception as prescribed", "levonorgestrel", "not applicable"],
    ["a couple distressed after two years of trying to conceive", "counsel and refer both partners for assessment", "not applicable", "semen analysis"],
  ]],
  ["Health Promotion and Maintenance", "newborn and infant care education", [
    ["a family applying herbs to the umbilical stump", "teach clean, dry cord care and the danger of infection", "chlorhexidine gel", "cord assessment"],
    ["a mother giving water and herbs to her newborn", "counsel on exclusive breastfeeding for six months", "not applicable", "not applicable"],
    ["a family discarding the first yellow milk", "teach them that colostrum protects the baby", "not applicable", "not applicable"],
    ["a baby sleeping on its front on a soft pillow", "teach the family to place the baby on the back", "not applicable", "not applicable"],
    ["a mother with no knowledge of newborn danger signs", "teach the danger signs and when to return to the facility", "not applicable", "not applicable"],
    ["a baby discharged without any immunisation", "give the birth vaccines and complete the card", "BCG and oral polio vaccine", "immunisation card"],
    ["a mother using herbs to treat her baby's jaundice", "explain the danger and refer for proper treatment", "phototherapy", "serum bilirubin"],
    ["a mother asking how to keep her newborn warm at night", "teach skin-to-skin contact and appropriate wrapping", "not applicable", "temperature"],
    ["a mother asking why her baby's stools change colour", "explain the normal stool progression in newborns", "not applicable", "not applicable"],
    ["a mother unsure how to clean her baby's eyes", "teach gentle cleaning with clean water and cotton", "not applicable", "not applicable"],
  ]],

  // ── Psychosocial Integrity ──────────────────────────────────────
  ["Psychosocial Integrity", "suicide risk", [
    ["a client saying life is not worth living with a plan", "initiate one-to-one observation and remove means", "not applicable", "risk assessment"],
    ["a client giving away possessions and writing a note", "assess the risk urgently and keep the client safe", "not applicable", "risk assessment"],
    ["a client asked about suicidal ideas in front of many people", "assess risk privately and sensitively", "not applicable", "risk assessment"],
    ["a client refusing to talk about suicidal thoughts", "assess directly and document the findings", "not applicable", "risk assessment"],
    ["a client discharged after a suicide attempt", "arrange follow-up and involve the family safely", "not applicable", "risk assessment"],
    ["a client with access to medicines at home and low mood", "teach the family to remove means of self-harm", "not applicable", "risk assessment"],
    ["a client becoming suddenly calm after a period of despair", "increase observation as this may signal a decision", "not applicable", "risk assessment"],
    ["a client with a previous attempt and current low mood", "assess the risk and agree a safety plan", "not applicable", "risk assessment"],
    ["a client afraid to disclose thoughts of self-harm", "provide a confidential and non-judgemental space", "not applicable", "not applicable"],
    ["a family unsure how to support a suicidal relative", "teach the family warning signs and support options", "not applicable", "not applicable"],
  ]],
  ["Psychosocial Integrity", "acute psychosis", [
    ["a client hearing voices commanding them to harm others", "ask directly about the voices and assess safety", "haloperidol", "not applicable"],
    ["a client refusing food believing it is poisoned", "offer sealed alternatives and build trust", "not applicable", "not applicable"],
    ["a disorganised client unable to meet basic needs", "assist with hygiene and provide a calm environment", "antipsychotic", "not applicable"],
    ["an aggressive client escalating on the ward", "use verbal de-escalation before any restraint", "not applicable", "not applicable"],
    ["a client with rigid muscles and a fever on antipsychotics", "treat as neuroleptic malignant syndrome and refer urgently", "not applicable", "serum creatine kinase"],
    ["a client becoming withdrawn and sleepless before a relapse", "recognise the early signs and act quickly", "not applicable", "not applicable"],
    ["a client bathed in public view on the ward", "protect the client's privacy and dignity", "not applicable", "not applicable"],
    ["a family blaming the client for the illness", "educate the family and reduce the blame", "not applicable", "not applicable"],
    ["a client with both psychosis and alcohol dependence", "address both problems together in the care plan", "not applicable", "not applicable"],
    ["a client stopping medicine because of stigma at work", "plan adherence support and involve a trusted person", "antipsychotic", "not applicable"],
  ]],
  ["Psychosocial Integrity", "anxiety and panic", [
    ["hyperventilation with a sense of impending doom", "stay with the client and teach slow breathing", "not applicable", "oxygen saturation"],
    ["a client unable to speak during a panic attack", "remain calm, use short sentences and stay present", "not applicable", "not applicable"],
    ["chest pain with a normal ECG during an anxious episode", "assess fully before attributing it to anxiety", "not applicable", "ECG"],
    ["a client avoiding all social situations for months", "refer for psychological therapy and support", "not applicable", "not applicable"],
    ["a client using alcohol to control anxiety", "assess for dependence and offer support", "not applicable", "not applicable"],
    ["a client with palpitations and fear of dying with no physical cause", "stay with the client and teach slow breathing", "not applicable", "not applicable"],
    ["a client refusing to leave the ward after a panic attack", "support gradual re-exposure and reassurance", "not applicable", "not applicable"],
    ["a client with disturbed sleep from persistent worry", "teach relaxation techniques and refer for review", "not applicable", "not applicable"],
    ["a client embarrassed about being anxious", "normalise the experience and reduce the stigma", "not applicable", "not applicable"],
    ["a client asking whether anxiety is a real illness", "explain that anxiety is a genuine and treatable condition", "not applicable", "not applicable"],
  ]],
  ["Psychosocial Integrity", "substance use and withdrawal", [
    ["tremor and sweating 48 hours after the last drink", "institute seizure precautions and give benzodiazepines", "diazepam", "withdrawal score"],
    ["visual hallucinations two days after stopping alcohol", "assess the withdrawal score and give treatment", "diazepam", "withdrawal score"],
    ["a seizure in a client withdrawing from alcohol", "protect from injury and give prescribed benzodiazepine", "diazepam", "not applicable"],
    ["a client with thiamine deficiency and confusion", "give thiamine before any glucose infusion", "thiamine", "not applicable"],
    ["a client wanting to stop drinking for good", "arrange counselling and relapse prevention support", "not applicable", "not applicable"],
    ["a client denying any alcohol use despite the signs", "use a non-confrontational approach and build trust", "not applicable", "not applicable"],
    ["a client with a substance use problem and no family support", "arrange community and peer support services", "not applicable", "not applicable"],
    ["a client using substances to cope with grief", "address both the grief and the substance use", "not applicable", "not applicable"],
    ["a client asking whether recovery is possible", "offer hope with realistic information about recovery", "not applicable", "not applicable"],
    ["a client with relapse after a period of abstinence", "explore the triggers and restart support without blame", "not applicable", "not applicable"],
  ]],
  ["Psychosocial Integrity", "grief and loss", [
    ["a client crying quietly after being told of a death", "sit with the client and allow silence", "not applicable", "not applicable"],
    ["a client asking why the death happened to them", "listen without giving false reassurance", "not applicable", "not applicable"],
    ["a client unable to sleep or eat six weeks after a loss", "assess for depression and offer support", "not applicable", "not applicable"],
    ["a grieving client told to stop crying and be strong", "allow the client to grieve and listen without judgement", "not applicable", "not applicable"],
    ["a family disagreeing about funeral arrangements", "facilitate communication and involve counselling", "not applicable", "not applicable"],
    ["a mother grieving a miscarriage and blaming herself", "counsel her sensitively and support the family", "not applicable", "not applicable"],
    ["a grieving mother refusing to see her stillborn baby", "give her time, choice and sensitive support", "not applicable", "not applicable"],
    ["a client planning to visit the grave alone tomorrow", "respect the choice and check their support network", "not applicable", "not applicable"],
    ["a child asking about the death of a parent", "answer honestly in age-appropriate language", "not applicable", "not applicable"],
    ["a nurse feeling distressed after a client's death", "offer peer support and encourage debriefing", "not applicable", "not applicable"],
  ]],
  ["Psychosocial Integrity", "mental health in the community", [
    ["a client with epilepsy tied up at home by relatives", "educate the family and link the client to care", "carbamazepine", "not applicable"],
    ["a family attributing mental illness to spiritual causes", "respect their beliefs while explaining the need for treatment", "not applicable", "not applicable"],
    ["a client with severe illness managed only with prayers", "respect their beliefs and refer for psychiatric care", "not applicable", "referral note"],
    ["an older client wandering and forgetting to eat", "maintain a routine and ensure safety with nutrition", "not applicable", "cognitive assessment"],
    ["a mother with persistent low mood after delivery", "screen with a validated tool and refer for support", "sertraline", "screening score"],
    ["a client with a new confusion treated as normal ageing", "assess for a treatable cause such as infection", "not applicable", "urinalysis"],
    ["a client with mental illness excluded from community life", "educate the community and support inclusion", "not applicable", "not applicable"],
    ["a client with no family support after a mental health crisis", "arrange community follow-up and peer support", "not applicable", "not applicable"],
    ["a client hiding a mental illness from employers", "offer confidential support and discuss disclosure options", "not applicable", "not applicable"],
    ["a community with no access to mental health services", "advocate for services and use available referral pathways", "not applicable", "referral note"],
  ]],
  ["Psychosocial Integrity", "therapeutic communication", [
    ["a client crying silently after receiving bad news", "sit with the client and allow silence", "not applicable", "not applicable"],
    ["a client asking why this is happening to them", "listen without giving false reassurance", "not applicable", "not applicable"],
    ["a nurse saying everything will be fine to calm a client", "stop using false reassurance and explore the concern", "not applicable", "not applicable"],
    ["a client changing the subject when asked about feelings", "allow silence and return gently to the concern", "not applicable", "not applicable"],
    ["a client asking a personal question about the nurse", "redirect the conversation back to the client", "not applicable", "not applicable"],
    ["a client speaking very little during an interview", "use open-ended questions to encourage discussion", "not applicable", "not applicable"],
    ["a client becoming angry during a conversation", "remain calm and acknowledge the client's feelings", "not applicable", "not applicable"],
    ["a client with a hearing difficulty in a busy ward", "communicate clearly, face the client and reduce noise", "not applicable", "not applicable"],
    ["a client who does not speak the local language", "arrange a professional interpreter rather than a relative", "not applicable", "not applicable"],
    ["a client asking to be left alone to think", "respect the request and return at an agreed time", "not applicable", "not applicable"],
  ]],

  // ── Clinical Judgement ──────────────────────────────────────────
  ["Clinical Judgement", "recognising deterioration", [
    ["a rising pulse with a falling blood pressure over two hours", "recognise the trend and escalate immediately", "not applicable", "vital signs"],
    ["a respiratory rate rising from 16 to 30 per minute", "assess the client and call for urgent review", "not applicable", "respiratory rate"],
    ["a new confusion developing on the ward", "assess for a treatable cause and escalate", "not applicable", "not applicable"],
    ["an oxygen saturation falling from 96 to 88 percent", "give oxygen and assess the client urgently", "oxygen", "oxygen saturation"],
    ["a urine output falling below 0.5 mL/kg/hr", "assess fluid status and escalate", "not applicable", "urine output"],
    ["a temperature rising with a new productive cough", "assess for infection and escalate", "not applicable", "temperature"],
    ["a client becoming increasingly drowsy after surgery", "assess the airway and neurological status", "not applicable", "conscious level"],
    ["abdominal pain increasing despite analgesia", "reassess for a complication and escalate", "not applicable", "not applicable"],
    ["a wound becoming more painful and inflamed", "assess for infection and notify the surgeon", "not applicable", "wound swab"],
    ["reduced consciousness after a head injury", "protect the airway and arrange urgent imaging", "not applicable", "CT of the head"],
  ]],
  ["Clinical Judgement", "prioritising multiple clients", [
    ["four clients needing attention at the same time", "assess the client with an airway concern first", "not applicable", "not applicable"],
    ["a client with chest pain and another asking for a drink", "assess the client with chest pain first", "not applicable", "ECG"],
    ["a stable client and one with new breathlessness", "assess the client with new breathlessness first", "oxygen", "oxygen saturation"],
    ["a client bleeding and another requesting discharge papers", "assess the bleeding client first", "not applicable", "not applicable"],
    ["a client with a changing conscious level and one needing a bath", "assess the changing conscious level first", "not applicable", "conscious level"],
    ["an acute problem and a chronic stable complaint", "assess the acute problem first", "not applicable", "not applicable"],
    ["a client with a new fever and one needing routine medicine", "assess the client with the new fever first", "not applicable", "temperature"],
    ["a post-operative client with no urine output for six hours", "assess that client before routine care", "not applicable", "urine output"],
    ["a client with sudden severe pain and one with mild pain", "assess the client with sudden severe pain first", "not applicable", "pain score"],
    ["a client who is confused and one requesting a phone call", "assess the confused client for a cause first", "not applicable", "not applicable"],
  ]],
  ["Clinical Judgement", "interpreting assessment data", [
    ["crackles with a raised jugular venous pressure", "interpret as fluid overload and act on it", "not applicable", "not applicable"],
    ["a bounding pulse with a wide pulse pressure", "assess for fluid overload and report", "not applicable", "blood pressure"],
    ["a metallic taste with a low urine output", "assess for renal impairment and report", "not applicable", "serum creatinine"],
    ["a falling blood pressure with a rising pulse", "interpret as shock and act immediately", "intravenous fluids", "vital signs"],
    ["a rigid abdomen with absent bowel sounds", "interpret as a possible perforation and escalate", "not applicable", "abdominal x-ray"],
    ["a sudden confusion with a low blood glucose", "treat the hypoglycaemia immediately", "intravenous dextrose", "blood glucose"],
    ["a temperature with a rising heart rate and low pressure", "interpret as sepsis and follow the bundle", "intravenous antibiotics", "serum lactate"],
    ["a new murmur with fever after surgery", "assess for endocarditis and report", "not applicable", "blood cultures"],
    ["a swollen calf with sudden breathlessness", "interpret as a possible embolism and escalate", "heparin", "D-dimer"],
    ["a sudden severe headache with vomiting", "assess for a haemorrhage and escalate urgently", "not applicable", "CT of the head"],
  ]],
  ["Clinical Judgement", "evaluating care effectiveness", [
    ["pain not reduced an hour after analgesia", "reassess and escalate rather than repeating blindly", "not applicable", "pain score"],
    ["oxygen saturation unchanged after increasing oxygen", "reassess the underlying cause and escalate", "not applicable", "arterial blood gases"],
    ["a wound not improving after a week of treatment", "take a swab and review the treatment plan", "not applicable", "wound swab"],
    ["blood pressure still high on maximum medication", "report for a treatment review", "not applicable", "blood pressure"],
    ["blood glucose still high after a dose adjustment", "review the diet, adherence and doses", "not applicable", "blood glucose"],
    ["oedema unchanged after diuretic therapy", "assess adherence and kidney function", "not applicable", "serum electrolytes"],
    ["no improvement in breathing after a nebuliser", "reassess and escalate urgently", "not applicable", "oxygen saturation"],
    ["a client still anxious after a first counselling session", "continue the plan and review progress", "not applicable", "not applicable"],
    ["a client readmitted with the same problem", "review the discharge plan and education", "not applicable", "not applicable"],
    ["a care goal not met by the target date", "revise the plan and update the care record", "not applicable", "not applicable"],
  ]],
  ["Clinical Judgement", "clinical decision making", [
    ["a nurse unsure about a prescribed dose", "verify with a second nurse or the pharmacist", "not applicable", "not applicable"],
    ["a client deteriorating with no clear cause", "reassess systematically from airway to circulation", "not applicable", "vital signs"],
    ["two plausible interventions with conflicting evidence", "follow the current clinical guideline", "not applicable", "not applicable"],
    ["a client refusing a treatment the nurse believes is needed", "respect the refusal and inform the provider", "not applicable", "not applicable"],
    ["an abnormal finding that does not fit the diagnosis", "report the finding and seek further assessment", "not applicable", "not applicable"],
    ["a colleague's assessment the nurse disagrees with", "discuss the difference and reassess the client", "not applicable", "not applicable"],
    ["a busy shift with limited time for a complex client", "prioritise by clinical risk and seek support", "not applicable", "not applicable"],
    ["a client whose symptoms do not match the observations", "trust the clinical picture and reassess", "not applicable", "not applicable"],
    ["a decision with an ethical dimension", "involve the appropriate team and document the process", "not applicable", "not applicable"],
    ["a new symptom appearing during treatment", "stop, reassess and consider a complication", "not applicable", "not applicable"],
  ]],
];
