/** Topic seeds for the Ghana NMC Licensing Examination (Registered General Nursing). */
export type GhanaTopic = {
  name: string;
  finding: string;
  action: string;
  drug: string;
  lab: string;
};

export const GHANA_NMC_CATEGORIES: {
  category: string;
  clientNeed: string;
  topics: GhanaTopic[];
}[] = [
  {
    category: "Ghana Health System & CHPS",
    clientNeed: "Community Health Practice",
    topics: [
      { name: "the Community-based Health Planning and Services (CHPS) strategy", finding: "a community with no functional CHPS compound and low immunisation coverage", action: "plan community outreach and involve the community health committee", drug: "not applicable", lab: "DHIMS2 coverage data" },
      { name: "the National Health Insurance Scheme (NHIS)", finding: "a patient who cannot afford out-of-pocket payment for essential medicines", action: "verify the patient's NHIS membership and refer for enrolment", drug: "not applicable", lab: "NHIS membership record" },
      { name: "the Ghana Standard Treatment Guidelines", finding: "a prescriber ordering a medicine outside the Essential Medicines List without justification", action: "clarify the order against the Standard Treatment Guidelines before administration", drug: "essential medicines list items", lab: "prescription chart" },
      { name: "the referral system from CHPS to district hospital", finding: "a patient in obstructed labour at a CHPS compound", action: "stabilise, complete the referral note and arrange transport to the district hospital", drug: "intravenous fluids", lab: "vital signs record" },
      { name: "the Integrated Management of Childhood Illness (IMCI) approach", finding: "a child with cough who is breathing fast and unable to drink", action: "classify the illness using IMCI and refer urgently", drug: "oral amoxicillin", lab: "respiratory rate chart" },
      { name: "the Expanded Programme on Immunisation in Ghana", finding: "a child who has missed measles-rubella vaccine at 18 months", action: "update the EPI card and schedule catch-up vaccination", drug: "measles-rubella vaccine", lab: "EPI card record" },
      { name: "community health nursing home visits", finding: "a household with no insecticide-treated bed net and standing water nearby", action: "educate on bed net use and support environmental sanitation", drug: "insecticide-treated net", lab: "household visit record" },
      { name: "the Ghana Health Service chain of command", finding: "a recurrent medicine stock-out at the health centre", action: "document the stock-out and report through the district health management team", drug: "not applicable", lab: "stock record" },
      { name: "school health education programmes", finding: "several schoolchildren with skin infections and poor hand hygiene", action: "organise health education on handwashing and personal hygiene", drug: "not applicable", lab: "school health record" },
      { name: "data reporting through DHIMS2", finding: "monthly facility data not submitted by the deadline", action: "compile and submit the returns through the district data officer", drug: "not applicable", lab: "DHIMS2 returns" },
      { name: "infection prevention in a resource-limited facility", finding: "no running water and reuse of single-use gloves", action: "stop the unsafe practice and implement hand hygiene with available alternatives", drug: "chlorine solution", lab: "IPC audit" },
      { name: "nutrition rehabilitation in the community", finding: "a child with mid-upper arm circumference in the red zone", action: "refer for severe acute malnutrition management", drug: "ready-to-use therapeutic food", lab: "MUAC measurement" },
    ],
  },
  {
    category: "Medical-Surgical Nursing (Ghana)",
    clientNeed: "Clinical Nursing Practice",
    topics: [
      { name: "severe malaria", finding: "fever with altered consciousness and passage of dark urine", action: "start parenteral antimalarial therapy and check the blood glucose", drug: "intravenous artesunate", lab: "thick and thin blood film" },
      { name: "sickle cell crisis", finding: "severe bone pain with fever and dehydration", action: "give oxygen, fluids, analgesia and treat infection", drug: "pentazocine", lab: "haemoglobin electrophoresis" },
      { name: "hypertensive emergency", finding: "a blood pressure of 220/130 mmHg with blurred vision", action: "lower the blood pressure carefully and monitor neurological status", drug: "intravenous hydralazine", lab: "blood pressure record" },
      { name: "diabetic foot sepsis", finding: "a foul-smelling ulcer with necrotic tissue in a diabetic patient", action: "debride, dress and start prescribed antibiotics with glycaemic control", drug: "intravenous metronidazole", lab: "random blood glucose" },
      { name: "acute kidney injury", finding: "urine output below 0.5 mL/kg/hr with a rising creatinine", action: "review nephrotoxic drugs and complete a strict fluid balance", drug: "intravenous fluids", lab: "serum creatinine" },
      { name: "typhoid perforation", finding: "sudden generalised abdominal pain with guarding after a febrile illness", action: "keep the patient nil by mouth and prepare for emergency surgery", drug: "intravenous ceftriaxone", lab: "abdominal x-ray" },
      { name: "road traffic accident with head injury", finding: "a deteriorating Glasgow Coma Scale score with unequal pupils", action: "stabilise the airway and refer for urgent CT scan", drug: "intravenous mannitol", lab: "Glasgow Coma Scale" },
      { name: "severe anaemia", finding: "pallor with an haemoglobin below 5 g/dL and fast breathing", action: "crossmatch and transfuse packed cells as prescribed", drug: "packed red blood cells", lab: "haemoglobin level" },
      { name: "hepatic encephalopathy", finding: "drowsiness with flapping tremor in a patient with liver disease", action: "give prescribed lactulose and reduce protein intake", drug: "lactulose", lab: "serum ammonia" },
      { name: "snake envenomation", finding: "progressive swelling and bleeding at the bite site", action: "immobilise the limb and administer antivenom as prescribed", drug: "polyvalent antivenom", lab: "clotting profile" },
      { name: "tuberculosis treatment adherence", finding: "a patient who stopped anti-TB medicines after two months", action: "trace the patient and resume directly observed therapy", drug: "rifampicin", lab: "sputum AFB" },
      { name: "chronic obstructive pulmonary disease", finding: "worsening breathlessness with a productive cough in a smoker", action: "sit upright, give prescribed oxygen and nebulised bronchodilators", drug: "salbutamol nebuliser", lab: "oxygen saturation" },
    ],
  },
  {
    category: "Pharmacology & Ghana STG",
    clientNeed: "Medicines Management",
    topics: [
      { name: "artemisinin-based combination therapy", finding: "vomiting within 30 minutes of taking the antimalarial dose", action: "repeat the dose and monitor for tolerance", drug: "artemether-lumefantrine", lab: "blood film" },
      { name: "iron and folate supplementation", finding: "dark stools after starting iron tablets", action: "reassure the patient that dark stools are expected and continue", drug: "ferrous sulphate", lab: "haemoglobin level" },
      { name: "antiretroviral therapy adherence", finding: "a patient missing doses to avoid clinic stigma", action: "plan adherence support and involve a treatment buddy", drug: "tenofovir-lamivudine-dolutegravir", lab: "viral load" },
      { name: "quinine infusion safety", finding: "tinnitus and sweating during a quinine infusion", action: "slow the infusion rate and monitor for cinchonism", drug: "intravenous quinine", lab: "blood glucose" },
      { name: "heparin and low molecular weight heparin", finding: "bleeding gums during heparin therapy", action: "stop the infusion and report for protamine consideration", drug: "heparin", lab: "activated partial thromboplastin time" },
      { name: "gentamicin toxicity", finding: "reduced urine output with tinnitus on aminoglycoside therapy", action: "report for dose review and monitor renal function", drug: "gentamicin", lab: "serum creatinine" },
      { name: "oral contraceptive counselling", finding: "a patient who missed two combined oral contraceptive pills", action: "advise on missed-pill rules and additional contraception", drug: "combined oral contraceptive", lab: "not applicable" },
      { name: "paracetamol overdose", finding: "right upper quadrant pain after a deliberate paracetamol overdose", action: "administer prescribed N-acetylcysteine and monitor liver function", drug: "N-acetylcysteine", lab: "liver enzymes" },
      { name: "metronidazole and alcohol", finding: "flushing and vomiting after drinking alcohol on metronidazole", action: "explain the disulfiram-like reaction and prohibit alcohol", drug: "metronidazole", lab: "vital signs" },
      { name: "insulin storage in a hot climate", finding: "insulin vials left in direct sunlight at the clinic", action: "discard heat-exposed insulin and replace it", drug: "insulin", lab: "random blood glucose" },
      { name: "deworming and mass drug administration", finding: "a community member asking whether albendazole is safe in pregnancy", action: "advise according to guidelines and refer for prescriber review", drug: "albendazole", lab: "not applicable" },
      { name: "multidrug-resistant tuberculosis therapy", finding: "no improvement after standard anti-TB therapy", action: "support drug sensitivity testing and adhere to the retreatment regimen", drug: "second-line anti-TB medicines", lab: "sputum culture" },
    ],
  },
  {
    category: "Community Health Nursing",
    clientNeed: "Primary Health Care",
    topics: [
      { name: "cholera outbreak response", finding: "several households with acute watery diarrhoea after a funeral", action: "notify the disease control officer and start oral rehydration", drug: "oral rehydration salts", lab: "stool culture" },
      { name: "measles outbreak investigation", finding: "clusters of fever with rash in unvaccinated children", action: "report the suspected outbreak and plan mass vaccination", drug: "measles vaccine", lab: "serology" },
      { name: "malaria vector control", finding: "stagnant water and broken gutters around the community", action: "organise larval source reduction and distribute treated nets", drug: "insecticide-treated net", lab: "entomological survey" },
      { name: "water, sanitation and hygiene promotion", finding: "open defecation near the only water source", action: "convene a community meeting on latrine use and sanitation", drug: "not applicable", lab: "water quality test" },
      { name: "antenatal clinic attendance promotion", finding: "a pregnant woman who has not attended antenatal care by 28 weeks", action: "trace and counsel her on the benefits of skilled antenatal care", drug: "ferrous sulphate and folic acid", lab: "haemoglobin level" },
      { name: "family planning uptake", finding: "a patient with five children requesting a long-acting method", action: "counsel on options and obtain informed consent for the chosen method", drug: "levonorgestrel implant", lab: "pregnancy test" },
      { name: "adolescent reproductive health education", finding: "rising teenage pregnancy in the community", action: "run age-appropriate reproductive health education in schools", drug: "not applicable", lab: "community data" },
      { name: "malnutrition prevention", finding: "several under-five children with yellow-zone mid-upper arm circumference", action: "enrol the children in supplementary feeding and educate caregivers", drug: "supplementary feed", lab: "MUAC measurement" },
      { name: "HIV testing services", finding: "a patient who fears knowing their HIV status", action: "provide pre-test counselling and obtain informed consent", drug: "antiretroviral therapy", lab: "HIV rapid test" },
      { name: "tuberculosis contact tracing", finding: "a household contact of a smear-positive TB patient with a chronic cough", action: "screen the household contacts and collect sputum samples", drug: "isoniazid preventive therapy", lab: "sputum AFB" },
      { name: "elderly care in the community", finding: "an older person living alone with uncontrolled blood pressure", action: "plan a home visit schedule and teach medication adherence", drug: "amlodipine", lab: "blood pressure record" },
      { name: "mental health in the community", finding: "a patient with epilepsy tied up at home by relatives", action: "educate the family and link the patient to psychiatric care", drug: "carbamazepine", lab: "not applicable" },
    ],
  },
  {
    category: "Maternal & Newborn Care",
    clientNeed: "Reproductive Health",
    topics: [
      { name: "pre-eclampsia", finding: "a blood pressure of 165/115 mmHg with proteinuria and headache", action: "start magnesium sulfate as prescribed and institute seizure precautions", drug: "magnesium sulfate", lab: "urine protein" },
      { name: "postpartum haemorrhage", finding: "soaking more than one pad in an hour with a boggy uterus", action: "massage the uterus, empty the bladder and call for help", drug: "oxytocin", lab: "haemoglobin level" },
      { name: "malaria in pregnancy", finding: "fever with anaemia in the third trimester", action: "treat with a pregnancy-safe antimalarial and give iron therapy", drug: "quinine or artemether-lumefantrine", lab: "blood film" },
      { name: "severe anaemia in pregnancy", finding: "pallor with breathlessness at 34 weeks", action: "transfuse as prescribed and monitor for fluid overload", drug: "packed red blood cells", lab: "haemoglobin level" },
      { name: "HIV in pregnancy", finding: "a newly positive HIV test at antenatal clinic", action: "enrol the mother on lifelong antiretroviral therapy and plan infant prophylaxis", drug: "tenofovir-lamivudine-dolutegravir", lab: "viral load" },
      { name: "obstructed labour", finding: "prolonged labour with a caput and moulding on the fetal head", action: "prepare for referral and emergency caesarean section", drug: "intravenous fluids", lab: "partograph" },
      { name: "newborn asphyxia", finding: "a newborn who is not breathing well at one minute", action: "start resuscitation with bag and mask ventilation", drug: "oxygen", lab: "Apgar score" },
      { name: "neonatal sepsis", finding: "a three-day-old baby who is feeding poorly with a low temperature", action: "refer urgently for parenteral antibiotics", drug: "intravenous ampicillin and gentamicin", lab: "blood culture" },
      { name: "neonatal jaundice", finding: "yellow palms and soles on the third day of life", action: "refer for phototherapy and bilirubin assessment", drug: "phototherapy", lab: "serum bilirubin" },
      { name: "exclusive breastfeeding", finding: "a mother giving water and herbs to a newborn", action: "counsel on exclusive breastfeeding for six months", drug: "not applicable", lab: "infant weight" },
      { name: "eclampsia", finding: "convulsions in a pregnant woman at term", action: "protect from injury and give prescribed magnesium sulfate", drug: "magnesium sulfate", lab: "blood pressure" },
      { name: "unsafe abortion complications", finding: "heavy vaginal bleeding with abdominal pain after an unsafe abortion", action: "resuscitate, treat infection and refer for surgical review", drug: "intravenous fluids and antibiotics", lab: "haemoglobin level" },
    ],
  },
  {
    category: "Child Health (Ghana)",
    clientNeed: "Paediatric Nursing",
    topics: [
      { name: "severe acute malnutrition", finding: "visible wasting with oedema of both feet", action: "begin F-75 therapeutic feeding and treat infection", drug: "F-75 therapeutic milk", lab: "MUAC measurement" },
      { name: "pneumonia in a child", finding: "fast breathing with chest indrawing and fever", action: "give prescribed antibiotics and oxygen, and monitor breathing", drug: "intravenous amoxicillin", lab: "oxygen saturation" },
      { name: "diarrhoea with some dehydration", finding: "sunken eyes with reduced skin elasticity", action: "give oral rehydration solution over four hours", drug: "oral rehydration salts", lab: "stool chart" },
      { name: "severe dehydration in a child", finding: "lethargy with inability to drink and a weak pulse", action: "start intravenous rehydration urgently", drug: "intravenous Ringer's lactate", lab: "serum electrolytes" },
      { name: "measles complications", finding: "a rash with mouth ulcers and eye discharge", action: "give vitamin A and treat secondary infection", drug: "vitamin A", lab: "clinical assessment" },
      { name: "malaria with anaemia in a child", finding: "pallor with a positive malaria test and fast breathing", action: "transfuse as prescribed and give an antimalarial", drug: "packed red blood cells", lab: "haemoglobin level" },
      { name: "meningitis in a child", finding: "a stiff neck with a bulging fontanelle and fever", action: "refer urgently for lumbar puncture and antibiotics", drug: "intravenous ceftriaxone", lab: "cerebrospinal fluid" },
      { name: "neonatal tetanus", finding: "a two-week-old baby who cannot suck with muscle spasms", action: "keep the baby in a quiet dark room and refer urgently", drug: "tetanus antitoxin", lab: "clinical assessment" },
      { name: "burns management in a child", finding: "a scald on the chest with blistering", action: "cool the burn, cover it and assess fluid needs", drug: "intravenous fluids", lab: "haematocrit" },
      { name: "worm infestation", finding: "abdominal distension with pallor in a school-age child", action: "give prescribed deworming medicine and educate on hygiene", drug: "albendazole", lab: "haemoglobin level" },
      { name: "sickle cell disease in a child", finding: "dactylitis with fever in a young child", action: "hydrate, give analgesia and screen for infection", drug: "paracetamol and opioids", lab: "haemoglobin level" },
      { name: "congenital heart disease", finding: "a baby who becomes breathless and sweaty during feeding", action: "refer for cardiac assessment and support growth", drug: "not applicable", lab: "oxygen saturation" },
    ],
  },
  {
    category: "Mental Health Nursing",
    clientNeed: "Psychosocial Care",
    topics: [
      { name: "epilepsy in the community", finding: "a patient having a generalised seizure in the market", action: "protect from injury, position on the side and time the seizure", drug: "diazepam", lab: "electroencephalogram" },
      { name: "acute psychosis", finding: "a patient hearing voices and refusing to eat", action: "provide a calm environment and give prescribed antipsychotics", drug: "haloperidol", lab: "vital signs" },
      { name: "severe depression with suicidal ideas", finding: "a patient saying life is not worth living with a plan", action: "remove means of self-harm and place on close observation", drug: "fluoxetine", lab: "risk assessment" },
      { name: "substance use disorder", finding: "a young man with tremors and confusion after stopping alcohol", action: "institute seizure precautions and give prescribed benzodiazepines", drug: "diazepam", lab: "clinical institute withdrawal assessment" },
      { name: "bipolar disorder in mania", finding: "a patient who has not slept for three days and is overspending", action: "reduce stimulation and give prescribed mood stabiliser", drug: "lithium carbonate", lab: "serum lithium" },
      { name: "chlorpromazine adverse effects", finding: "a stiff neck with upward eye deviation after antipsychotic treatment", action: "give prescribed anticholinergic medicine and report", drug: "biperiden", lab: "not applicable" },
      { name: "community attitudes to mental illness", finding: "a family attributing mental illness to spiritual causes and stopping treatment", action: "respect their beliefs while explaining the need for continued treatment", drug: "not applicable", lab: "not applicable" },
      { name: "postnatal depression", finding: "a mother who is tearful and unable to care for her baby", action: "screen her, provide support and involve the family", drug: "sertraline", lab: "screening score" },
      { name: "dementia in an older person", finding: "an older patient who wanders and forgets to eat", action: "maintain a routine and ensure safety with nutrition", drug: "not applicable", lab: "cognitive assessment" },
      { name: "anxiety disorder", finding: "a patient with palpitations and fear of dying with no physical cause", action: "stay with the patient and teach slow breathing", drug: "diazepam", lab: "not applicable" },
      { name: "referral to psychiatric services", finding: "a patient with complex needs beyond the facility's capacity", action: "complete the referral note and arrange transport and escort", drug: "not applicable", lab: "referral note" },
      { name: "restraint and least restrictive practice", finding: "a patient becoming aggressive towards others on the ward", action: "attempt de-escalation before any restrictive intervention", drug: "intramuscular haloperidol", lab: "vital signs" },
    ],
  },
  {
    category: "Communicable Diseases (Ghana)",
    clientNeed: "Infection Prevention",
    topics: [
      { name: "Lassa fever suspicion", finding: "fever with bleeding gums unresponsive to antimalarials", action: "isolate the patient and notify the disease control officer immediately", drug: "ribavirin", lab: "polymerase chain reaction" },
      { name: "cholera management", finding: "professor rice-water stool with severe dehydration", action: "give rapid intravenous rehydration and doxycholate precautions", drug: "intravenous Ringer's lactate", lab: "stool culture" },
      { name: "meningococcal meningitis", finding: "fever with neck stiffness and a non-blanching rash", action: "isolate, notify and give prescribed antibiotics immediately", drug: "intravenous ceftriaxone", lab: "cerebrospinal fluid analysis" },
      { name: "tuberculosis infection control", finding: "a coughing patient waiting in a crowded outpatient area", action: "separate the patient and provide a surgical mask", drug: "not applicable", lab: "sputum AFB" },
      { name: "HIV post-exposure prophylaxis", finding: "a needle-stick injury from an HIV-positive patient", action: "wash the site and start prophylaxis within 72 hours", drug: "post-exposure prophylaxis regimen", lab: "baseline HIV test" },
      { name: "hepatitis B prevention", finding: "a patient with hepatitis B sharing razors at home", action: "educate on prevention and screen and vaccinate household contacts", drug: "hepatitis B vaccine", lab: "hepatitis B surface antigen" },
      { name: "COVID-19 and respiratory outbreak precautions", finding: "a patient with fever, cough and difficulty breathing", action: "isolate with appropriate personal protective equipment", drug: "supportive therapy", lab: "polymerase chain reaction" },
      { name: "tetanus prevention", finding: "a deep wound in a patient with an unknown tetanus status", action: "clean the wound thoroughly and give tetanus prophylaxis", drug: "tetanus toxoid", lab: "wound assessment" },
      { name: "yellow fever outbreak", finding: "fever with jaundice and bleeding in an unvaccinated patient", action: "notify immediately and support with fluids and monitoring", drug: "supportive therapy", lab: "serology" },
      { name: "sexually transmitted infection management", finding: "a urethral discharge in a sexually active patient", action: "treat both partners according to the syndromic approach", drug: "ceftriaxone and doxycycline", lab: "syndromic assessment" },
      { name: "buruli ulcer recognition", finding: "a painless swelling progressing to an ulcer in a riverine community", action: "refer early for surgical and antibiotic management", drug: "rifampicin and streptomycin", lab: "clinical assessment" },
      { name: "trachoma and eye infections", finding: "several children with red sticky eyes in the same household", action: "treat, promote face washing and refer chronic cases", drug: "azithromycin", lab: "clinical assessment" },
    ],
  },
  {
    category: "Professional Practice & NMC Ghana Code",
    clientNeed: "Professional and Ethical Practice",
    topics: [
      { name: "the NMC Ghana code of professional conduct", finding: "a colleague collecting money from a patient for services that should be free", action: "report the conduct to the appropriate authority", drug: "not applicable", lab: "incident report" },
      { name: "confidentiality of patient records", finding: "a nurse discussing a patient's HIV status in the corridor", action: "stop the discussion and remind the colleague about confidentiality", drug: "not applicable", lab: "not applicable" },
      { name: "informed consent for a procedure", finding: "a patient being prepared for surgery who does not understand the operation", action: "pause and ask the clinician to re-explain before the patient signs", drug: "not applicable", lab: "consent form" },
      { name: "professional accountability for delegated tasks", finding: "a student nurse asked to perform a procedure beyond their competence", action: "decline and inform the supervising registered nurse", drug: "not applicable", lab: "competency record" },
      { name: "documentation standards", finding: "an entry in the nurses' notes without the date, time or signature", action: "complete the record properly and follow facility policy", drug: "not applicable", lab: "nurses' notes" },
      { name: "raising concerns about poor practice", finding: "persistent shortage of staff endangering patient safety", action: "escalate in writing through the unit manager", drug: "not applicable", lab: "incident report" },
      { name: "continuing professional development", finding: "a nurse who has not attended any in-service training this year", action: "plan and attend approved continuing professional development sessions", drug: "not applicable", lab: "CPD portfolio" },
      { name: "cultural sensitivity in care", finding: "a patient refusing care from a male nurse for religious reasons", action: "respect the preference and arrange an alternative where possible", drug: "not applicable", lab: "care plan" },
      { name: "handling patient complaints", finding: "a patient angry about a long waiting time", action: "listen calmly, apologise and explain the process", drug: "not applicable", lab: "complaint register" },
      { name: "professional boundaries", finding: "a nurse accepting an expensive gift from a patient's family", action: "politely decline and explain professional boundaries", drug: "not applicable", lab: "not applicable" },
      { name: "safe medication practice and the rights of administration", finding: "a medicine about to be given without checking the patient's identity", action: "stop and verify the identity with two identifiers", drug: "not applicable", lab: "prescription chart" },
      { name: "emergency documentation and handover", finding: "incomplete handover at shift change on a busy ward", action: "use a structured handover and confirm outstanding tasks", drug: "not applicable", lab: "handover sheet" },
    ],
  },
  {
    category: "Emergency & Critical Care",
    clientNeed: "Emergency Nursing",
    topics: [
      { name: "cardiopulmonary resuscitation", finding: "an unresponsive patient with no normal breathing", action: "call for help and start chest compressions at 30:2", drug: "adrenaline", lab: "rhythm strip" },
      { name: "hypovolaemic shock from bleeding", finding: "a fast weak pulse with cold clammy skin after a road traffic accident", action: "control the bleeding and give rapid intravenous fluids", drug: "intravenous crystalloids", lab: "haemoglobin level" },
      { name: "anaphylaxis", finding: "sudden facial swelling with difficulty breathing after an injection", action: "give intramuscular adrenaline immediately", drug: "adrenaline 1:1000", lab: "vital signs" },
      { name: "status epilepticus", finding: "a seizure lasting more than five minutes", action: "protect the airway and give prescribed anticonvulsant", drug: "intravenous diazepam", lab: "blood glucose" },
      { name: "major burns", finding: "burns over 30 percent of the body surface with blistering", action: "calculate fluid needs and insert a urinary catheter", drug: "intravenous fluids", lab: "urine output" },
      { name: "poisoning and gastric lavage decisions", finding: "a patient who swallowed kerosene one hour ago", action: "do not induce vomiting and refer for assessment", drug: "not applicable", lab: "toxicology review" },
      { name: "organophosphate poisoning", finding: "excessive salivation with pinpoint pupils and muscle twitching", action: "give prescribed atropine and decontaminate the skin", drug: "atropine", lab: "clinical assessment" },
      { name: "spinal injury handling", finding: "a road traffic accident patient with neck pain and limb weakness", action: "immobilise the spine and log roll the patient", drug: "not applicable", lab: "x-ray" },
      { name: "severe pre-eclampsia in the emergency unit", finding: "convulsions in a pregnant patient in the casualty", action: "protect from injury and give prescribed magnesium sulfate", drug: "magnesium sulfate", lab: "blood pressure" },
      { name: "triage in a mass casualty event", finding: "many casualties arriving at once after a bus crash", action: "triage using the priority categories and treat the most salvageable first", drug: "not applicable", lab: "triage tag" },
      { name: "hypoglycaemic coma", finding: "an unconscious diabetic patient with a blood glucose of 2.2 mmol/L", action: "give intravenous dextrose and monitor the response", drug: "intravenous 50 percent dextrose", lab: "blood glucose" },
      { name: "chest injury with suspected pneumothorax", finding: "absent breath sounds with severe breathlessness and tracheal shift", action: "prepare for immediate needle decompression", drug: "oxygen", lab: "chest x-ray" },
    ],
  },
];
