/** Topic seeds for the Ghana NMC Licensing Examination (Registered General Nursing). */
export type GhanaTopic = {
  name: string;
  finding: string;
  action: string;
  drug: string;
  lab: string;
};

export const GHANA_NMC_CATEGORIES: {
  category: string;
  clientNeed: string;
  topics: GhanaTopic[];
}[] = [
  {
    category: "Ghana Health System & CHPS",
    clientNeed: "Community Health Practice",
    topics: [
      { name: "the Community-based Health Planning and Services (CHPS) strategy", finding: "a community with no functional CHPS compound and low immunisation coverage", action: "plan community outreach and involve the community health committee", drug: "not applicable", lab: "DHIMS2 coverage data" },
      { name: "the National Health Insurance Scheme (NHIS)", finding: "a patient who cannot afford out-of-pocket payment for essential medicines", action: "verify the patient's NHIS membership and refer for enrolment", drug: "not applicable", lab: "NHIS membership record" },
      { name: "the Ghana Standard Treatment Guidelines", finding: "a prescriber ordering a medicine outside the Essential Medicines List without justification", action: "clarify the order against the Standard Treatment Guidelines before administration", drug: "essential medicines list items", lab: "prescription chart" },
      { name: "the referral system from CHPS to district hospital", finding: "a patient in obstructed labour at a CHPS compound", action: "stabilise, complete the referral note and arrange transport to the district hospital", drug: "intravenous fluids", lab: "vital signs record" },
      { name: "the Integrated Management of Childhood Illness (IMCI) approach", finding: "a child with cough who is breathing fast and unable to drink", action: "classify the illness using IMCI and refer urgently", drug: "oral amoxicillin", lab: "respiratory rate chart" },
      { name: "the Expanded Programme on Immunisation in Ghana", finding: "a child who has missed measles-rubella vaccine at 18 months", action: "update the EPI card and schedule catch-up vaccination", drug: "measles-rubella vaccine", lab: "EPI card record" },
      { name: "community health nursing home visits", finding: "a household with no insecticide-treated bed net and standing water nearby", action: "educate on bed net use and support environmental sanitation", drug: "insecticide-treated net", lab: "household visit record" },
      { name: "the Ghana Health Service chain of command", finding: "a recurrent medicine stock-out at the health centre", action: "document the stock-out and report through the district health management team", drug: "not applicable", lab: "stock record" },
      { name: "school health education programmes", finding: "several schoolchildren with skin infections and poor hand hygiene", action: "organise health education on handwashing and personal hygiene", drug: "not applicable", lab: "school health record" },
      { name: "data reporting through DHIMS2", finding: "monthly facility data not submitted by the deadline", action: "compile and submit the returns through the district data officer", drug: "not applicable", lab: "DHIMS2 returns" },
      { name: "infection prevention in a resource-limited facility", finding: "no running water and reuse of single-use gloves", action: "stop the unsafe practice and implement hand hygiene with available alternatives", drug: "chlorine solution", lab: "IPC audit" },
      { name: "nutrition rehabilitation in the community", finding: "a child with mid-upper arm circumference in the red zone", action: "refer for severe acute malnutrition management", drug: "ready-to-use therapeutic food", lab: "MUAC measurement" },
    ],
  },
  {
    category: "Medical-Surgical Nursing (Ghana)",
    clientNeed: "Clinical Nursing Practice",
    topics: [
      { name: "severe malaria", finding: "fever with altered consciousness and passage of dark urine", action: "start parenteral antimalarial therapy and check the blood glucose", drug: "intravenous artesunate", lab: "thick and thin blood film" },
      { name: "sickle cell crisis", finding: "severe bone pain with fever and dehydration", action: "give oxygen, fluids, analgesia and treat infection", drug: "pentazocine", lab: "haemoglobin electrophoresis" },
      { name: "hypertensive emergency", finding: "a blood pressure of 220/130 mmHg with blurred vision", action: "lower the blood pressure carefully and monitor neurological status", drug: "intravenous hydralazine", lab: "blood pressure record" },
      { name: "diabetic foot sepsis", finding: "a foul-smelling ulcer with necrotic tissue in a diabetic patient", action: "debride, dress and start prescribed antibiotics with glycaemic control", drug: "intravenous metronidazole", lab: "random blood glucose" },
      { name: "acute kidney injury", finding: "urine output below 0.5 mL/kg/hr with a rising creatinine", action: "review nephrotoxic drugs and complete a strict fluid balance", drug: "intravenous fluids", lab: "serum creatinine" },
      { name: "typhoid perforation", finding: "sudden generalised abdominal pain with guarding after a febrile illness", action: "keep the patient nil by mouth and prepare for emergency surgery", drug: "intravenous ceftriaxone", lab: "abdominal x-ray" },
      { name: "road traffic accident with head injury", finding: "a deteriorating Glasgow Coma Scale score with unequal pupils", action: "stabilise the airway and refer for urgent CT scan", drug: "intravenous mannitol", lab: "Glasgow Coma Scale" },
      { name: "severe anaemia", finding: "pallor with an haemoglobin below 5 g/dL and fast breathing", action: "crossmatch and transfuse packed cells as prescribed", drug: "packed red blood cells", lab: "haemoglobin level" },
      { name: "hepatic encephalopathy", finding: "drowsiness with flapping tremor in a patient with liver disease", action: "give prescribed lactulose and reduce protein intake", drug: "lactulose", lab: "serum ammonia" },
      { name: "snake envenomation", finding: "progressive swelling and bleeding at the bite site", action: "immobilise the limb and administer antivenom as prescribed", drug: "polyvalent antivenom", lab: "clotting profile" },
      { name: "tuberculosis treatment adherence", finding: "a patient who stopped anti-TB medicines after two months", action: "trace the patient and resume directly observed therapy", drug: "rifampicin", lab: "sputum AFB" },
      { name: "chronic obstructive pulmonary disease", finding: "worsening breathlessness with a productive cough in a smoker", action: "sit upright, give prescribed oxygen and nebulised bronchodilators", drug: "salbutamol nebuliser", lab: "oxygen saturation" },
    ],
  },
  {
    category: "Pharmacology & Ghana STG",
    clientNeed: "Medicines Management",
    topics: [
      { name: "artemisinin-based combination therapy", finding: "vomiting within 30 minutes of taking the antimalarial dose", action: "repeat the dose and monitor for tolerance", drug: "artemether-lumefantrine", lab: "blood film" },
      { name: "iron and folate supplementation", finding: "dark stools after starting iron tablets", action: "reassure the patient that dark stools are expected and continue", drug: "ferrous sulphate", lab: "haemoglobin level" },
      { name: "antiretroviral therapy adherence", finding: "a patient missing doses to avoid clinic stigma", action: "plan adherence support and involve a treatment buddy", drug: "tenofovir-lamivudine-dolutegravir", lab: "viral load" },
      { name: "quinine infusion safety", finding: "tinnitus and sweating during a quinine infusion", action: "slow the infusion rate and monitor for cinchonism", drug: "intravenous quinine", lab: "blood glucose" },
      { name: "heparin and low molecular weight heparin", finding: "bleeding gums during heparin therapy", action: "stop the infusion and report for protamine consideration", drug: "heparin", lab: "activated partial thromboplastin time" },
      { name: "gentamicin toxicity", finding: "reduced urine output with tinnitus on aminoglycoside therapy", action: "report for dose review and monitor renal function", drug: "gentamicin", lab: "serum creatinine" },
      { name: "oral contraceptive counselling", finding: "a patient who missed two combined oral contraceptive pills", action: "advise on missed-pill rules and additional contraception", drug: "combined oral contraceptive", lab: "not applicable" },
      { name: "paracetamol overdose", finding: "right upper quadrant pain after a deliberate paracetamol overdose", action: "administer prescribed N-acetylcysteine and monitor liver function", drug: "N-acetylcysteine", lab: "liver enzymes" },
      { name: "metronidazole and alcohol", finding: "flushing and vomiting after drinking alcohol on metronidazole", action: "explain the disulfiram-like reaction and prohibit alcohol", drug: "metronidazole", lab: "vital signs" },
      { name: "insulin storage in a hot climate", finding: "insulin vials left in direct sunlight at the clinic", action: "discard heat-exposed insulin and replace it", drug: "insulin", lab: "random blood glucose" },
      { name: "deworming and mass drug administration", finding: "a community member asking whether albendazole is safe in pregnancy", action: "advise according to guidelines and refer for prescriber review", drug: "albendazole", lab: "not applicable" },
      { name: "multidrug-resistant tuberculosis therapy", finding: "no improvement after standard anti-TB therapy", action: "support drug sensitivity testing and adhere to the retreatment regimen", drug: "second-line anti-TB medicines", lab: "sputum culture" },
    ],
  },
  {
    category: "Community Health Nursing",
    clientNeed: "Primary Health Care",
    topics: [
      { name: "cholera outbreak response", finding: "several households with acute watery diarrhoea after a funeral", action: "notify the disease control officer and start oral rehydration", drug: "oral rehydration salts", lab: "stool culture" },
      { name: "measles outbreak investigation", finding: "clusters of fever with rash in unvaccinated children", action: "report the suspected outbreak and plan mass vaccination", drug: "measles vaccine", lab: "serology" },
      { name: "malaria vector control", finding: "stagnant water and broken gutters around the community", action: "organise larval source reduction and distribute treated nets", drug: "insecticide-treated net", lab: "entomological survey" },
      { name: "water, sanitation and hygiene promotion", finding: "open defecation near the only water source", action: "convene a community meeting on latrine use and sanitation", drug: "not applicable", lab: "water quality test" },
      { name: "antenatal clinic attendance promotion", finding: "a pregnant woman who has not attended antenatal care by 28 weeks", action: "trace and counsel her on the benefits of skilled antenatal care", drug: "ferrous sulphate and folic acid", lab: "haemoglobin level" },
      { name: "family planning uptake", finding: "a patient with five children requesting a long-acting method", action: "counsel on options and obtain informed consent for the chosen method", drug: "levonorgestrel implant", lab: "pregnancy test" },
      { name: "adolescent reproductive health education", finding: "rising teenage pregnancy in the community", action: "run age-appropriate reproductive health education in schools", drug: "not applicable", lab: "community data" },
      { name: "malnutrition prevention", finding: "several under-five children with yellow-zone mid-upper arm circumference", action: "enrol the children in supplementary feeding and educate caregivers", drug: "supplementary feed", lab: "MUAC measurement" },
      { name: "HIV testing services", finding: "a patient who fears knowing their HIV status", action: "provide pre-test counselling and obtain informed consent", drug: "antiretroviral therapy", lab: "HIV rapid test" },
      { name: "tuberculosis contact tracing", finding: "a household contact of a smear-positive TB patient with a chronic cough", action: "screen the household contacts and collect sputum samples", drug: "isoniazid preventive therapy", lab: "sputum AFB" },
      { name: "elderly care in the community", finding: "an older person living alone with uncontrolled blood pressure", action: "plan a home visit schedule and teach medication adherence", drug: "amlodipine", lab: "blood pressure record" },
      { name: "mental health in the community", finding: "a patient with epilepsy tied up at home by relatives", action: "educate the family and link the patient to psychiatric care", drug: "carbamazepine", lab: "not applicable" },
    ],
  },
  {
    category: "Maternal & Newborn Care",
    clientNeed: "Reproductive Health",
    topics: [
      { name: "pre-eclampsia", finding: "a blood pressure of 165/115 mmHg with proteinuria and headache", action: "start magnesium sulfate as prescribed and institute seizure precautions", drug: "magnesium sulfate", lab: "urine protein" },
      { name: "postpartum haemorrhage", finding: "soaking more than one pad in an hour with a boggy uterus", action: "massage the uterus, empty the bladder and call for help", drug: "oxytocin", lab: "haemoglobin level" },
      { name: "malaria in pregnancy", finding: "fever with anaemia in the third trimester", action: "treat with a pregnancy-safe antimalarial and give iron therapy", drug: "quinine or artemether-lumefantrine", lab: "blood film" },
      { name: "severe anaemia in pregnancy", finding: "pallor with breathlessness at 34 weeks", action: "transfuse as prescribed and monitor for fluid overload", drug: "packed red blood cells", lab: "haemoglobin level" },
      { name: "HIV in pregnancy", finding: "a newly positive HIV test at antenatal clinic", action: "enrol the mother on lifelong antiretroviral therapy and plan infant prophylaxis", drug: "tenofovir-lamivudine-dolutegravir", lab: "viral load" },
      { name: "obstructed labour", finding: "prolonged labour with a caput and moulding on the fetal head", action: "prepare for referral and emergency caesarean section", drug: "intravenous fluids", lab: "partograph" },
      { name: "newborn asphyxia", finding: "a newborn who is not breathing well at one minute", action: "start resuscitation with bag and mask ventilation", drug: "oxygen", lab: "Apgar score" },
      { name: "neonatal sepsis", finding: "a three-day-old baby who is feeding poorly with a low temperature", action: "refer urgently for parenteral antibiotics", drug: "intravenous ampicillin and gentamicin", lab: "blood culture" },
      { name: "neonatal jaundice", finding: "yellow palms and soles on the third day of life", action: "refer for phototherapy and bilirubin assessment", drug: "phototherapy", lab: "serum bilirubin" },
      { name: "exclusive breastfeeding", finding: "a mother giving water and herbs to a newborn", action: "counsel on exclusive breastfeeding for six months", drug: "not applicable", lab: "infant weight" },
      { name: "eclampsia", finding: "convulsions in a pregnant woman at term", action: "protect from injury and give prescribed magnesium sulfate", drug: "magnesium sulfate", lab: "blood pressure" },
      { name: "unsafe abortion complications", finding: "heavy vaginal bleeding with abdominal pain after an unsafe abortion", action: "resuscitate, treat infection and refer for surgical review", drug: "intravenous fluids and antibiotics", lab: "haemoglobin level" },
    ],
  },
  {
    category: "Child Health (Ghana)",
    clientNeed: "Paediatric Nursing",
    topics: [
      { name: "severe acute malnutrition", finding: "visible wasting with oedema of both feet", action: "begin F-75 therapeutic feeding and treat infection", drug: "F-75 therapeutic milk", lab: "MUAC measurement" },
      { name: "pneumonia in a child", finding: "fast breathing with chest indrawing and fever", action: "give prescribed antibiotics and oxygen, and monitor breathing", drug: "intravenous amoxicillin", lab: "oxygen saturation" },
      { name: "diarrhoea with some dehydration", finding: "sunken eyes with reduced skin elasticity", action: "give oral rehydration solution over four hours", drug: "oral rehydration salts", lab: "stool chart" },
      { name: "severe dehydration in a child", finding: "lethargy with inability to drink and a weak pulse", action: "start intravenous rehydration urgently", drug: "intravenous Ringer's lactate", lab: "serum electrolytes" },
      { name: "measles complications", finding: "a rash with mouth ulcers and eye discharge", action: "give vitamin A and treat secondary infection", drug: "vitamin A", lab: "clinical assessment" },
      { name: "malaria with anaemia in a child", finding: "pallor with a positive malaria test and fast breathing", action: "transfuse as prescribed and give an antimalarial", drug: "packed red blood cells", lab: "haemoglobin level" },
      { name: "meningitis in a child", finding: "a stiff neck with a bulging fontanelle and fever", action: "refer urgently for lumbar puncture and antibiotics", drug: "intravenous ceftriaxone", lab: "cerebrospinal fluid" },
      { name: "neonatal tetanus", finding: "a two-week-old baby who cannot suck with muscle spasms", action: "keep the baby in a quiet dark room and refer urgently", drug: "tetanus antitoxin", lab: "clinical assessment" },
      { name: "burns management in a child", finding: "a scald on the chest with blistering", action: "cool the burn, cover it and assess fluid needs", drug: "intravenous fluids", lab: "haematocrit" },
      { name: "worm infestation", finding: "abdominal distension with pallor in a school-age child", action: "give prescribed deworming medicine and educate on hygiene", drug: "albendazole", lab: "haemoglobin level" },
      { name: "sickle cell disease in a child", finding: "dactylitis with fever in a young child", action: "hydrate, give analgesia and screen for infection", drug: "paracetamol and opioids", lab: "haemoglobin level" },
      { name: "congenital heart disease", finding: "a baby who becomes breathless and sweaty during feeding", action: "refer for cardiac assessment and support growth", drug: "not applicable", lab: "oxygen saturation" },
    ],
  },
  {
    category: "Mental Health Nursing",
    clientNeed: "Psychosocial Care",
    topics: [
      { name: "epilepsy in the community", finding: "a patient having a generalised seizure in the market", action: "protect from injury, position on the side and time the seizure", drug: "diazepam", lab: "electroencephalogram" },
      { name: "acute psychosis", finding: "a patient hearing voices and refusing to eat", action: "provide a calm environment and give prescribed antipsychotics", drug: "haloperidol", lab: "vital signs" },
      { name: "severe depression with suicidal ideas", finding: "a patient saying life is not worth living with a plan", action: "remove means of self-harm and place on close observation", drug: "fluoxetine", lab: "risk assessment" },
      { name: "substance use disorder", finding: "a young man with tremors and confusion after stopping alcohol", action: "institute seizure precautions and give prescribed benzodiazepines", drug: "diazepam", lab: "clinical institute withdrawal assessment" },
      { name: "bipolar disorder in mania", finding: "a patient who has not slept for three days and is overspending", action: "reduce stimulation and give prescribed mood stabiliser", drug: "lithium carbonate", lab: "serum lithium" },
      { name: "chlorpromazine adverse effects", finding: "a stiff neck with upward eye deviation after antipsychotic treatment", action: "give prescribed anticholinergic medicine and report", drug: "biperiden", lab: "not applicable" },
      { name: "community attitudes to mental illness", finding: "a family attributing mental illness to spiritual causes and stopping treatment", action: "respect their beliefs while explaining the need for continued treatment", drug: "not applicable", lab: "not applicable" },
      { name: "postnatal depression", finding: "a mother who is tearful and unable to care for her baby", action: "screen her, provide support and involve the family", drug: "sertraline", lab: "screening score" },
      { name: "dementia in an older person", finding: "an older patient who wanders and forgets to eat", action: "maintain a routine and ensure safety with nutrition", drug: "not applicable", lab: "cognitive assessment" },
      { name: "anxiety disorder", finding: "a patient with palpitations and fear of dying with no physical cause", action: "stay with the patient and teach slow breathing", drug: "diazepam", lab: "not applicable" },
      { name: "referral to psychiatric services", finding: "a patient with complex needs beyond the facility's capacity", action: "complete the referral note and arrange transport and escort", drug: "not applicable", lab: "referral note" },
      { name: "restraint and least restrictive practice", finding: "a patient becoming aggressive towards others on the ward", action: "attempt de-escalation before any restrictive intervention", drug: "intramuscular haloperidol", lab: "vital signs" },
    ],
  },
  {
    category: "Communicable Diseases (Ghana)",
    clientNeed: "Infection Prevention",
    topics: [
      { name: "Lassa fever suspicion", finding: "fever with bleeding gums unresponsive to antimalarials", action: "isolate the patient and notify the disease control officer immediately", drug: "ribavirin", lab: "polymerase chain reaction" },
      { name: "cholera management", finding: "professor rice-water stool with severe dehydration", action: "give rapid intravenous rehydration and doxycholate precautions", drug: "intravenous Ringer's lactate", lab: "stool culture" },
      { name: "meningococcal meningitis", finding: "fever with neck stiffness and a non-blanching rash", action: "isolate, notify and give prescribed antibiotics immediately", drug: "intravenous ceftriaxone", lab: "cerebrospinal fluid analysis" },
      { name: "tuberculosis infection control", finding: "a coughing patient waiting in a crowded outpatient area", action: "separate the patient and provide a surgical mask", drug: "not applicable", lab: "sputum AFB" },
      { name: "HIV post-exposure prophylaxis", finding: "a needle-stick injury from an HIV-positive patient", action: "wash the site and start prophylaxis within 72 hours", drug: "post-exposure prophylaxis regimen", lab: "baseline HIV test" },
      { name: "hepatitis B prevention", finding: "a patient with hepatitis B sharing razors at home", action: "educate on prevention and screen and vaccinate household contacts", drug: "hepatitis B vaccine", lab: "hepatitis B surface antigen" },
      { name: "COVID-19 and respiratory outbreak precautions", finding: "a patient with fever, cough and difficulty breathing", action: "isolate with appropriate personal protective equipment", drug: "supportive therapy", lab: "polymerase chain reaction" },
      { name: "tetanus prevention", finding: "a deep wound in a patient with an unknown tetanus status", action: "clean the wound thoroughly and give tetanus prophylaxis", drug: "tetanus toxoid", lab: "wound assessment" },
      { name: "yellow fever outbreak", finding: "fever with jaundice and bleeding in an unvaccinated patient", action: "notify immediately and support with fluids and monitoring", drug: "supportive therapy", lab: "serology" },
      { name: "sexually transmitted infection management", finding: "a urethral discharge in a sexually active patient", action: "treat both partners according to the syndromic approach", drug: "ceftriaxone and doxycycline", lab: "syndromic assessment" },
      { name: "buruli ulcer recognition", finding: "a painless swelling progressing to an ulcer in a riverine community", action: "refer early for surgical and antibiotic management", drug: "rifampicin and streptomycin", lab: "clinical assessment" },
      { name: "trachoma and eye infections", finding: "several children with red sticky eyes in the same household", action: "treat, promote face washing and refer chronic cases", drug: "azithromycin", lab: "clinical assessment" },
    ],
  },
  {
    category: "Professional Practice & NMC Ghana Code",
    clientNeed: "Professional and Ethical Practice",
    topics: [
      { name: "the NMC Ghana code of professional conduct", finding: "a colleague collecting money from a patient for services that should be free", action: "report the conduct to the appropriate authority", drug: "not applicable", lab: "incident report" },
      { name: "confidentiality of patient records", finding: "a nurse discussing a patient's HIV status in the corridor", action: "stop the discussion and remind the colleague about confidentiality", drug: "not applicable", lab: "not applicable" },
      { name: "informed consent for a procedure", finding: "a patient being prepared for surgery who does not understand the operation", action: "pause and ask the clinician to re-explain before the patient signs", drug: "not applicable", lab: "consent form" },
      { name: "professional accountability for delegated tasks", finding: "a student nurse asked to perform a procedure beyond their competence", action: "decline and inform the supervising registered nurse", drug: "not applicable", lab: "competency record" },
      { name: "documentation standards", finding: "an entry in the nurses' notes without the date, time or signature", action: "complete the record properly and follow facility policy", drug: "not applicable", lab: "nurses' notes" },
      { name: "raising concerns about poor practice", finding: "persistent shortage of staff endangering patient safety", action: "escalate in writing through the unit manager", drug: "not applicable", lab: "incident report" },
      { name: "continuing professional development", finding: "a nurse who has not attended any in-service training this year", action: "plan and attend approved continuing professional development sessions", drug: "not applicable", lab: "CPD portfolio" },
      { name: "cultural sensitivity in care", finding: "a patient refusing care from a male nurse for religious reasons", action: "respect the preference and arrange an alternative where possible", drug: "not applicable", lab: "care plan" },
      { name: "handling patient complaints", finding: "a patient angry about a long waiting time", action: "listen calmly, apologise and explain the process", drug: "not applicable", lab: "complaint register" },
      { name: "professional boundaries", finding: "a nurse accepting an expensive gift from a patient's family", action: "politely decline and explain professional boundaries", drug: "not applicable", lab: "not applicable" },
      { name: "safe medication practice and the rights of administration", finding: "a medicine about to be given without checking the patient's identity", action: "stop and verify the identity with two identifiers", drug: "not applicable", lab: "prescription chart" },
      { name: "emergency documentation and handover", finding: "incomplete handover at shift change on a busy ward", action: "use a structured handover and confirm outstanding tasks", drug: "not applicable", lab: "handover sheet" },
    ],
  },
  {
    category: "Emergency & Critical Care",
    clientNeed: "Emergency Nursing",
    topics: [
      { name: "cardiopulmonary resuscitation", finding: "an unresponsive patient with no normal breathing", action: "call for help and start chest compressions at 30:2", drug: "adrenaline", lab: "rhythm strip" },
      { name: "hypovolaemic shock from bleeding", finding: "a fast weak pulse with cold clammy skin after a road traffic accident", action: "control the bleeding and give rapid intravenous fluids", drug: "intravenous crystalloids", lab: "haemoglobin level" },
      { name: "anaphylaxis", finding: "sudden facial swelling with difficulty breathing after an injection", action: "give intramuscular adrenaline immediately", drug: "adrenaline 1:1000", lab: "vital signs" },
      { name: "status epilepticus", finding: "a seizure lasting more than five minutes", action: "protect the airway and give prescribed anticonvulsant", drug: "intravenous diazepam", lab: "blood glucose" },
      { name: "major burns", finding: "burns over 30 percent of the body surface with blistering", action: "calculate fluid needs and insert a urinary catheter", drug: "intravenous fluids", lab: "urine output" },
      { name: "poisoning and gastric lavage decisions", finding: "a patient who swallowed kerosene one hour ago", action: "do not induce vomiting and refer for assessment", drug: "not applicable", lab: "toxicology review" },
      { name: "organophosphate poisoning", finding: "excessive salivation with pinpoint pupils and muscle twitching", action: "give prescribed atropine and decontaminate the skin", drug: "atropine", lab: "clinical assessment" },
      { name: "spinal injury handling", finding: "a road traffic accident patient with neck pain and limb weakness", action: "immobilise the spine and log roll the patient", drug: "not applicable", lab: "x-ray" },
      { name: "severe pre-eclampsia in the emergency unit", finding: "convulsions in a pregnant patient in the casualty", action: "protect from injury and give prescribed magnesium sulfate", drug: "magnesium sulfate", lab: "blood pressure" },
      { name: "triage in a mass casualty event", finding: "many casualties arriving at once after a bus crash", action: "triage using the priority categories and treat the most salvageable first", drug: "not applicable", lab: "triage tag" },
      { name: "hypoglycaemic coma", finding: "an unconscious diabetic patient with a blood glucose of 2.2 mmol/L", action: "give intravenous dextrose and monitor the response", drug: "intravenous 50 percent dextrose", lab: "blood glucose" },
      { name: "chest injury with suspected pneumothorax", finding: "absent breath sounds with severe breathlessness and tracheal shift", action: "prepare for immediate needle decompression", drug: "oxygen", lab: "chest x-ray" },
    ],
  },


  {
    category: "Ghana Health System & CHPS",
    clientNeed: "Community Health Practice",
    topics: [
      { name: "the levels of the Ghana health service", finding: "a patient with a complex condition attending a CHPS compound repeatedly", action: "explain the referral pathway and refer to the district hospital", drug: "not applicable", lab: "referral note" },
      { name: "the role of the community health nurse", finding: "a community health nurse limited to clinic work only", action: "plan home visits and community outreach as part of the role", drug: "not applicable", lab: "community register" },
      { name: "the district health management team", finding: "a recurrent equipment breakdown reported to nobody", action: "report the issue through the district health management team", drug: "not applicable", lab: "incident record" },
      { name: "the essential medicines list in Ghana", finding: "a facility dispensing medicines not on the essential list", action: "raise the issue and follow the national guidelines", drug: "essential medicines", lab: "stock record" },
      { name: "community entry protocols", finding: "a nurse starting a community programme without meeting the chiefs", action: "follow proper community entry and engage the leaders", drug: "not applicable", lab: "community record" },
      { name: "health information documentation", finding: "a register completed from memory at the end of the month", action: "record each patient contact immediately and accurately", drug: "not applicable", lab: "facility register" },
      { name: "outreach planning and logistics", finding: "an outreach session cancelled because no transport was arranged", action: "plan transport and logistics before the outreach date", drug: "not applicable", lab: "outreach plan" },
      { name: "the national immunisation policy", finding: "a child vaccinated with the wrong interval between doses", action: "follow the national schedule and correct the intervals", drug: "vaccine", lab: "EPI card" },
      { name: "growth monitoring in the community", finding: "a child not weighed for six months", action: "weigh the child and plot the growth chart", drug: "not applicable", lab: "growth chart" },
      { name: "environmental health collaboration", finding: "refuse heaps close to a community water source", action: "work with the environmental health officer on sanitation", drug: "not applicable", lab: "not applicable" },
      { name: "community based surveillance volunteers", finding: "no reports from the community surveillance volunteers", action: "train and support the volunteers to report diseases", drug: "not applicable", lab: "surveillance report" },
      { name: "health promotion in the market place", finding: "a market with no handwashing facilities for food sellers", action: "advocate for handwashing facilities and educate vendors", drug: "not applicable", lab: "not applicable" },
    ],
  },
  {
    category: "Medical-Surgical Nursing (Ghana)",
    clientNeed: "Clinical Nursing Practice",
    topics: [
      { name: "hypertension follow up in Ghana", finding: "a patient who stopped antihypertensive medicines because he felt well", action: "explain lifelong treatment and the risk of stroke", drug: "amlodipine", lab: "blood pressure" },
      { name: "stroke rehabilitation nursing", finding: "a patient with hemiplegia developing a shoulder pain on the weak side", action: "position the arm correctly and support passive movement", drug: "analgesia", lab: "not applicable" },
      { name: "chronic leg ulcer care", finding: "a leg ulcer present for one year with no improvement", action: "assess the cause and apply appropriate dressing and compression", drug: "not applicable", lab: "wound swab" },
      { name: "diabetes education in a Ghanaian diet", finding: "a patient taking large servings of banku three times daily", action: "teach portion control and a balanced diabetic plate", drug: "metformin", lab: "random blood glucose" },
      { name: "peptic ulcer disease care", finding: "epigastric pain relieved by eating in a patient who skips meals", action: "teach regular meals and avoid irritants", drug: "omeprazole", lab: "not applicable" },
      { name: "ascites management", finding: "an expanding abdominal girth with breathlessness in liver disease", action: "monitor weight and abdominal girth and restrict salt", drug: "spironolactone", lab: "serum electrolytes" },
      { name: "epilepsy and drug adherence", finding: "a patient with seizures after stopping anticonvulsants for a traditional remedy", action: "respect their belief while restarting prescribed therapy", drug: "carbamazepine", lab: "not applicable" },
      { name: "tracheostomy care in a district hospital", finding: "a tracheostomy tube with dried secretions blocking the inner tube", action: "clean or change the inner tube and suction as needed", drug: "not applicable", lab: "oxygen saturation" },
      { name: "blood transfusion safety", finding: "a patient transfused without a second nurse checking the unit", action: "stop and follow the two-nurse checking procedure", drug: "packed red blood cells", lab: "crossmatch record" },
      { name: "caring for a patient in isolation", finding: "an isolated patient who is lonely and refusing to eat", action: "communicate regularly and meet his psychological needs", drug: "not applicable", lab: "not applicable" },
      { name: "post operative wound dehiscence", finding: "a wound bursting open with a sudden cough on day six", action: "cover with sterile saline gauze and inform the surgeon", drug: "intravenous antibiotics", lab: "haemoglobin level" },
      { name: "oxygen therapy safety on the ward", finding: "a relative smoking beside a patient on oxygen", action: "stop the smoking immediately and educate the family", drug: "oxygen", lab: "oxygen saturation" },
      { name: "pain assessment on a busy ward", finding: "a patient in pain given analgesia without any assessment", action: "assess the pain with a scale before and after treatment", drug: "analgesia", lab: "pain score" },
      { name: "caring for the unconscious patient", finding: "an unconscious patient with dried secretions around the mouth", action: "suction and provide oral care to protect the airway", drug: "not applicable", lab: "not applicable" },
      { name: "nutrition for a patient with a surgical wound", finding: "poor wound healing with a very low protein intake", action: "refer to the dietitian for protein supplementation", drug: "protein supplement", lab: "serum albumin" },
    ],
  },
  {
    category: "Pharmacology & Ghana STG",
    clientNeed: "Medicines Management",
    topics: [
      { name: "the five rights of medication administration", finding: "a medicine about to be given to the wrong patient on a busy ward", action: "stop and verify identity with two identifiers", drug: "not applicable", lab: "prescription chart" },
      { name: "calculating paediatric doses", finding: "a child prescribed an adult tablet dose in error", action: "calculate the dose by weight and clarify the order", drug: "not applicable", lab: "weight record" },
      { name: "safe storage of vaccines", finding: "vaccines left outside the cold chain overnight", action: "quarantine the vaccines and report the cold chain breach", drug: "vaccine", lab: "cold chain record" },
      { name: "recognising anaphylaxis to medicines", finding: "a widespread rash with wheeze minutes after an injection", action: "stop the medicine and give intramuscular adrenaline", drug: "adrenaline 1:1000", lab: "vital signs" },
      { name: "patient education on completing antibiotics", finding: "a patient saving remaining antibiotics for the next illness", action: "teach the danger of incomplete courses and resistance", drug: "antibiotic", lab: "not applicable" },
      { name: "recording adverse drug reactions", finding: "a severe skin reaction after a medicine not reported to anyone", action: "document and report the adverse reaction", drug: "not applicable", lab: "adverse reaction form" },
      { name: "medication errors and honesty", finding: "a nurse giving a double dose and hiding the error", action: "assess the patient, report the error and complete an incident form", drug: "not applicable", lab: "incident report" },
      { name: "giving medicines to a pregnant patient", finding: "a medicine contraindicated in pregnancy prescribed at 20 weeks", action: "clarify the order with the prescriber before giving", drug: "not applicable", lab: "gestational age" },
      { name: "administering medicines to children", finding: "a child refusing oral medicine and the nurse forcing it", action: "use a calm approach and a suitable device such as a syringe", drug: "oral medicine", lab: "not applicable" },
      { name: "controlled medicines records", finding: "a controlled drug register entry that does not balance", action: "report the discrepancy immediately and investigate", drug: "pethidine", lab: "controlled drug register" },
      { name: " medicines and renal impairment", finding: "a patient with kidney injury given a full dose of a nephrotoxic drug", action: "review the dose with the prescriber", drug: "gentamicin", lab: "serum creatinine" },
      { name: "nasogastric medicine administration", finding: "tablets crushed and given down a nasogastric tube without checking", action: "confirm the medicine may be crushed and flush the tube", drug: "not applicable", lab: "tube position" },
      { name: "herbal medicine and drug interaction", finding: "a patient taking herbal preparations with prescribed antimalarials", action: "ask about herbal use and advise on possible interactions", drug: "antimalarial", lab: "not applicable" },
      { name: "reading a medicine label safely", finding: "two similar-looking medicines stored side by side", action: "separate them and label the storage clearly", drug: "not applicable", lab: "pharmacy audit" },
      { name: "expiry date checking", finding: "expired medicines found in the ward cupboard in use", action: "remove and quarantine the expired medicines", drug: "not applicable", lab: "stock record" },
    ],
  },
  {
    category: "Community Health Nursing",
    clientNeed: "Primary Health Care",
    topics: [
      { name: "home visiting priorities", finding: "a home visit spent only on a patient with a minor complaint", action: "assess the whole household and plan follow-up", drug: "not applicable", lab: "visit record" },
      { name: "the clinic appointment system", finding: "hundreds of patients waiting with no triage", action: "introduce triage and prioritise the acutely ill", drug: "not applicable", lab: "not applicable" },
      { name: "nutrition demonstration sessions", finding: "caregivers unable to prepare a balanced weaning food", action: "run a practical cooking demonstration with local foods", drug: "not applicable", lab: "growth chart" },
      { name: "immunisation defaulter tracing", finding: "several children defaulting from immunisation", action: "trace the defaulters and reschedule the doses", drug: "vaccine", lab: "EPI card" },
      { name: "school health screening", finding: "children with untreated skin and eye problems at school", action: "screen, treat and refer the children appropriately", drug: "not applicable", lab: "school health record" },
      { name: "adolescent health education", finding: "adolescents with no source of accurate health information", action: "provide age-appropriate health education sessions", drug: "not applicable", lab: "not applicable" },
      { name: "community diagnosis", finding: "a health programme planned without any community data", action: "collect and analyse community data before planning", drug: "not applicable", lab: "community profile" },
      { name: "caring for the elderly at home", finding: "an older patient with pressure sores and no caregiver", action: "teach the family repositioning and arrange support", drug: "not applicable", lab: "not applicable" },
      { name: "disability inclusion in the community", finding: "a disabled patient unable to reach the clinic", action: "arrange a home visit or community transport support", drug: "not applicable", lab: "not applicable" },
      { name: "health talks that change behaviour", finding: "health talks delivered in a language the community does not use", action: "deliver the talk in the local language with examples", drug: "not applicable", lab: "not applicable" },
      { name: "referral follow up in the community", finding: "patients referred to hospital with no follow-up record", action: "track referrals and confirm attendance", drug: "not applicable", lab: "referral register" },
      { name: "water treatment at household level", finding: "drinking water stored in an uncovered container", action: "teach safe storage and treatment of drinking water", drug: "not applicable", lab: "water quality test" },
      { name: "malaria case detection at community level", finding: "fever cases treated at home with no testing", action: "test fevers with a rapid diagnostic test", drug: "antimalarial", lab: "rapid diagnostic test" },
      { name: "recording births and deaths", finding: "births and deaths in the community not registered", action: "record and register all births and deaths", drug: "not applicable", lab: "birth and death register" },
      { name: "working with community health workers", finding: "community health workers given tasks with no training", action: "train and supervise them properly", drug: "not applicable", lab: "training record" },
    ],
  },
  {
    category: "Maternal & Newborn Care",
    clientNeed: "Reproductive Health",
    topics: [
      { name: "conducting a normal delivery", finding: "a delivery conducted without any hand hygiene", action: "follow hand hygiene and aseptic technique throughout", drug: "not applicable", lab: "not applicable" },
      { name: "assessing the fetal heart in labour", finding: "a fetal heart rate of 100 beats per minute in labour", action: "reposition the mother and refer for urgent assessment", drug: "not applicable", lab: "fetal heart rate" },
      { name: "the immediate needs of a newborn", finding: "a newborn not dried or kept warm after delivery", action: "dry, warm and place the baby skin-to-skin", drug: "not applicable", lab: "temperature" },
      { name: "checking the placenta and membranes", finding: "a placenta delivered with missing membranes", action: "examine the placenta and refer for retained products", drug: "not applicable", lab: "placenta examination" },
      { name: "perineal tear assessment", finding: "a tear extending into the anal sphincter", action: "refer for specialist repair of the tear", drug: "not applicable", lab: "wound assessment" },
      { name: "estimating gestational age at birth", finding: "a newborn with no assessment of maturity", action: "assess gestational age using a recognised method", drug: "not applicable", lab: "newborn examination" },
      { name: "supporting a woman in obstructed labour", finding: "an exhausted woman with a moulded head and no progress", action: "resuscitate and arrange emergency caesarean section", drug: "intravenous fluids", lab: "partograph" },
      { name: "the referral of a pregnant emergency", finding: "a woman with eclampsia referred without any treatment", action: "stabilise with magnesium sulfate before referral", drug: "magnesium sulfate", lab: "blood pressure" },
      { name: "managing a woman with anaemia in labour", finding: "a woman in labour with a haemoglobin of 6 g/dL", action: "crossmatch blood and monitor closely in labour", drug: "packed red blood cells", lab: "haemoglobin level" },
      { name: "preventing mother to child transmission", finding: "an HIV-positive woman delivering without any prophylaxis plan", action: "follow the prevention protocol for mother and baby", drug: "antiretroviral therapy", lab: "viral load" },
      { name: "care of a woman after a caesarean section", finding: "a post-caesarean patient with no pain assessment for many hours", action: "assess and manage her pain and monitor the wound", drug: "analgesia", lab: "vital signs" },
      { name: "encouraging skilled attendance at birth", finding: "a woman planning to deliver at home with no skilled attendant", action: "counsel her on the risks and encourage facility delivery", drug: "not applicable", lab: "not applicable" },
      { name: "managing the third stage complications", finding: "heavy bleeding with a soft uterus after delivery", action: "massage the uterus and give the prescribed uterotonic", drug: "oxytocin", lab: "blood loss" },
      { name: "the emotional needs of a labouring woman", finding: "a frightened teenager left alone in the labour room", action: "stay with her and provide continuous emotional support", drug: "not applicable", lab: "not applicable" },
      { name: "newborn feeding in the first hour", finding: "a newborn put to the breast only after six hours", action: "support breastfeeding within the first hour of life", drug: "not applicable", lab: "not applicable" },
    ],
  },
  {
    category: "Child Health (Ghana)",
    clientNeed: "Paediatric Nursing",
    topics: [
      { name: "assessing a sick child with IMCI", finding: "a child with cough assessed without checking for danger signs", action: "follow the IMCI steps and check all danger signs", drug: "not applicable", lab: "clinical assessment" },
      { name: "weighing and measuring a child", finding: "a child's age recorded incorrectly on the growth chart", action: "confirm the age and plot the measurement correctly", drug: "not applicable", lab: "growth chart" },
      { name: "giving oral medicines to a child", finding: "a child vomiting an oral medicine immediately after a dose", action: "assess whether the dose should be repeated", drug: "oral medicine", lab: "not applicable" },
      { name: "oxygen therapy for a child", finding: "a child with severe pneumonia and no oxygen available", action: "refer urgently and use oxygen as prescribed", drug: "oxygen", lab: "oxygen saturation" },
      { name: "feeding a child during illness", finding: "a sick child given no food for two days", action: "encourage small frequent feeding during and after illness", drug: "not applicable", lab: "weight" },
      { name: "caring for a child with a fever", finding: "a child with fever undressed and fanned in a cold room", action: "tepid sponge and give the prescribed antipyretic", drug: "paracetamol", lab: "temperature" },
      { name: "immunisation technique and site", finding: "a vaccine given into the wrong site with no record", action: "use the correct site and document it fully", drug: "vaccine", lab: "immunisation card" },
      { name: "preventing cross infection on a paediatric ward", finding: "children with diarrhoea sharing beds with others", action: "isolate the infectious cases and enforce hand hygiene", drug: "not applicable", lab: "not applicable" },
      { name: "counselling a caregiver about danger signs", finding: "a caregiver unaware that inability to drink is a danger sign", action: "teach the danger signs and when to return", drug: "not applicable", lab: "not applicable" },
      { name: "assessing dehydration in a child", finding: "a child assessed for dehydration without checking the eyes or fontanelle", action: "complete a full dehydration assessment", drug: "oral rehydration salts", lab: "not applicable" },
      { name: "play as part of child care", finding: "a hospitalised child with no play or stimulation for a week", action: "provide play and age-appropriate stimulation", drug: "not applicable", lab: "not applicable" },
      { name: "caring for a child in pain", finding: "a child in pain given no analgesia because he cried quietly", action: "assess the pain with a child-friendly scale and treat it", drug: "analgesia", lab: "pain score" },
      { name: "discharge planning for a child", finding: "a child discharged with no caregiver education", action: "teach the caregiver about medicines and danger signs", drug: "not applicable", lab: "not applicable" },
      { name: "protecting the child from abuse", finding: "a child with injuries that do not match the story given", action: "report the suspicion and protect the child", drug: "not applicable", lab: "safeguarding referral" },
      { name: "follow up after treatment", finding: "a child treated for malnutrition with no follow-up appointment", action: "schedule follow-up and monitor the growth", drug: "not applicable", lab: "growth chart" },
    ],
  },
  {
    category: "Mental Health Nursing",
    clientNeed: "Psychosocial Care",
    topics: [
      { name: "establishing a therapeutic relationship", finding: "a patient with no trust in the nurse after being shouted at", action: "apologise and build the relationship with consistent care", drug: "not applicable", lab: "not applicable" },
      { name: "assessing suicidal risk", finding: "a patient asked about suicidal ideas in front of many people", action: "assess risk privately and sensitively", drug: "not applicable", lab: "risk assessment" },
      { name: "caring for a patient during a seizure", finding: "a patient having a seizure with a spoon forced into the mouth", action: "stop the practice and protect the patient from injury", drug: "not applicable", lab: "not applicable" },
      { name: "medication adherence in mental health", finding: "a patient stopping medicine because of stigma at work", action: "plan adherence support and involve a trusted person", drug: "antipsychotic", lab: "not applicable" },
      { name: "the ward environment and safety", finding: "sharp objects left accessible on a mental health ward", action: "remove the hazards and follow the safety policy", drug: "not applicable", lab: "not applicable" },
      { name: "working with families in mental health", finding: "a family blaming the patient for the illness", action: "educate the family and reduce the blame", drug: "not applicable", lab: "not applicable" },
      { name: "recognising relapse warning signs", finding: "a patient becoming withdrawn and sleepless before a relapse", action: "recognise the early signs and act quickly", drug: "not applicable", lab: "not applicable" },
      { name: "dignity in mental health care", finding: "a patient bathed in public view on the ward", action: "protect the patient's privacy and dignity", drug: "not applicable", lab: "not applicable" },
      { name: "substance use and dual diagnosis", finding: "a patient with both psychosis and alcohol dependence", action: "address both problems together in the care plan", drug: "not applicable", lab: "not applicable" },
      { name: "caring for an older patient with confusion", finding: "an older patient with a new confusion treated as normal ageing", action: "assess for a treatable cause such as infection", drug: "not applicable", lab: "urinalysis" },
      { name: "documentation in mental health", finding: "a mental health record with only subjective opinions", action: "record objective observations and specific behaviour", drug: "not applicable", lab: "not applicable" },
      { name: "referral to specialist mental health services", finding: "a patient with severe illness managed only with prayers", action: "respect their beliefs and refer for psychiatric care", drug: "not applicable", lab: "referral note" },
      { name: "caring for a patient with epilepsy in the community", finding: "a patient with epilepsy excluded from school and work", action: "educate the community and support inclusion", drug: "anticonvulsant", lab: "not applicable" },
      { name: "managing aggression without restraint", finding: "an agitated patient restrained before any attempt at de-escalation", action: "use verbal de-escalation as the first response", drug: "not applicable", lab: "not applicable" },
      { name: "supporting a patient through bereavement", finding: "a grieving patient told to stop crying and be strong", action: "allow the patient to grieve and listen without judgement", drug: "not applicable", lab: "not applicable" },
    ],
  },
  {
    category: "Communicable Diseases (Ghana)",
    clientNeed: "Infection Prevention",
    topics: [
      { name: "hand hygiene moments in practice", finding: "hand hygiene skipped between two patients on a ward round", action: "perform hand hygiene between every patient contact", drug: "not applicable", lab: "IPC audit" },
      { name: "safe injection practices", finding: "the same syringe used for several patients in an outreach", action: "use a new sterile syringe for every injection", drug: "not applicable", lab: "not applicable" },
      { name: "handling linen from an infectious patient", finding: "soiled linen carried through a corridor uncovered", action: "transport and process the linen safely", drug: "not applicable", lab: "not applicable" },
      { name: "waste segregation at a health facility", finding: "sharps mixed with general waste in a bin", action: "segregate the waste into the correct colour-coded bins", drug: "not applicable", lab: "waste audit" },
      { name: "screening patients at the entrance", finding: "a coughing patient with no screening or mask offered", action: "screen, triage and offer a mask", drug: "not applicable", lab: "not applicable" },
      { name: "notifying a notifiable disease", finding: "a suspected outbreak not reported to the district", action: "notify immediately using the reporting system", drug: "not applicable", lab: "surveillance report" },
      { name: "caring for a patient with haemorrhagic fever", finding: "a suspected haemorrhagic fever case managed in an open ward", action: "isolate immediately with full protective equipment", drug: "supportive therapy", lab: "polymerase chain reaction" },
      { name: "decontaminating equipment", finding: "equipment shared between patients without decontamination", action: "decontaminate and sterilise before reuse", drug: "chlorine solution", lab: "sterilisation record" },
      { name: "protecting staff from blood borne viruses", finding: "gloves not worn during a procedure with blood spillage", action: "use protective equipment and follow the exposure protocol", drug: "post-exposure prophylaxis", lab: "baseline screening" },
      { name: "patient education on preventing reinfection", finding: "a patient reinfected after treatment because of poor hygiene", action: "teach prevention and involve the household", drug: "not applicable", lab: "not applicable" },
      { name: "vaccination of health workers", finding: "unvaccinated staff caring for infectious patients", action: "screen and vaccinate health workers", drug: "hepatitis B vaccine", lab: "not applicable" },
      { name: "managing a needle stick injury", finding: "a needle stick injury washed and forgotten with no report", action: "wash, report and start post-exposure prophylaxis", drug: "post-exposure prophylaxis", lab: "baseline HIV test" },
      { name: "isolation signage and communication", finding: "an isolation room with no signage or instructions", action: "display clear signage and brief the staff", drug: "not applicable", lab: "not applicable" },
      { name: "surveillance of hospital acquired infection", finding: "wound infections rising with no review of practice", action: "audit the practice and act on the findings", drug: "not applicable", lab: "infection rates" },
      { name: "personal protective equipment availability", finding: "staff reusing disposable masks to save supplies", action: "report the shortage and follow the safety standard", drug: "not applicable", lab: "not applicable" },
    ],
  },
  {
    category: "Professional Practice & NMC Ghana Code",
    clientNeed: "Professional and Ethical Practice",
    topics: [
      { name: "the scope of practice of a nurse", finding: "a nurse performing a procedure only a doctor may do", action: "stop and refer the task to the appropriate professional", drug: "not applicable", lab: "not applicable" },
      { name: "respecting a patient's choice", finding: "a patient's treatment decided by relatives against her wish", action: "respect the patient's own informed decision", drug: "not applicable", lab: "not applicable" },
      { name: "maintaining professional appearance", finding: "a nurse in uniform attending a bar in town", action: "maintain a professional image at all times in uniform", drug: "not applicable", lab: "not applicable" },
      { name: "punctuality and continuity of care", finding: "a nurse arriving late and leaving patients unattended", action: "report on time and ensure a proper handover", drug: "not applicable", lab: "handover record" },
      { name: "supervising junior colleagues", finding: "a newly posted nurse left to manage a ward alone", action: "provide supervision and support", drug: "not applicable", lab: "supervision record" },
      { name: "handling a patient's property", finding: "a patient's belongings lost with no record", action: "record and safeguard patient property", drug: "not applicable", lab: "property record" },
      { name: "obtaining consent for a student procedure", finding: "a student performing a procedure without the patient's agreement", action: "obtain consent and explain the student's role", drug: "not applicable", lab: "consent form" },
      { name: "reporting professional misconduct", finding: "misconduct by a colleague ignored by everyone", action: "report through the proper channel", drug: "not applicable", lab: "incident report" },
      { name: "using social media professionally", finding: "a nurse posting a patient's photograph online", action: "remove it and follow the confidentiality policy", drug: "not applicable", lab: "not applicable" },
      { name: "caring for a patient with a different faith", finding: "a patient's prayer time ignored during ward care", action: "accommodate the patient's religious practice", drug: "not applicable", lab: "not applicable" },
      { name: "seeking help when unsure", finding: "a nurse guessing a drug dose rather than asking", action: "ask for help rather than risk a patient's safety", drug: "not applicable", lab: "not applicable" },
      { name: "the duty to keep records confidential", finding: "patient records left open on a desk in a public area", action: "secure the records and follow the confidentiality policy", drug: "not applicable", lab: "not applicable" },
      { name: "responding to a patient's complaint", finding: "a complaint dismissed without any investigation", action: "listen, investigate and respond to the complaint", drug: "not applicable", lab: "complaint register" },
      { name: "team working on the ward", finding: "staff refusing to help each other during a busy shift", action: "promote teamwork for the safety of the patients", drug: "not applicable", lab: "not applicable" },
      { name: "continuing professional development records", finding: "a portfolio with no evidence of any training", action: "attend approved training and keep the portfolio current", drug: "not applicable", lab: "CPD portfolio" },
    ],
  },
  {
    category: "Emergency & Critical Care",
    clientNeed: "Emergency Nursing",
    topics: [
      { name: "the primary survey in an emergency", finding: "a trauma patient examined for injuries before the airway was checked", action: "follow the airway, breathing and circulation sequence", drug: "not applicable", lab: "vital signs" },
      { name: "calling for help early", finding: "a deteriorating patient managed alone for too long", action: "call for senior help early", drug: "not applicable", lab: "vital signs" },
      { name: "monitoring a patient in shock", finding: "a patient in shock with observations recorded only once an hour", action: "monitor closely at the required interval", drug: "intravenous fluids", lab: "vital signs" },
      { name: "oxygen therapy in an emergency", finding: "a cyanosed patient left without oxygen", action: "apply oxygen and monitor the saturation", drug: "oxygen", lab: "oxygen saturation" },
      { name: "the recovery position", finding: "an unconscious breathing patient left on the back", action: "place the patient in the recovery position", drug: "not applicable", lab: "not applicable" },
      { name: "checking blood glucose in an emergency", finding: "an unconscious patient not tested for low blood glucose", action: "check the glucose immediately in every unconscious patient", drug: "intravenous dextrose", lab: "blood glucose" },
      { name: "resuscitation team roles", finding: "several staff performing the same task during an arrest", action: "follow clear team roles during resuscitation", drug: "not applicable", lab: "not applicable" },
      { name: "documenting an emergency", finding: "an emergency managed with no record of the times or drugs given", action: "document times, drugs and responses accurately", drug: "not applicable", lab: "not applicable" },
      { name: "caring for relatives in an emergency", finding: "a family left waiting with no information for hours", action: "update the family regularly and with compassion", drug: "not applicable", lab: "not applicable" },
      { name: "handling a dead patient with dignity", finding: "a deceased patient left uncovered in view of others", action: "treat the body with dignity and respect the family", drug: "not applicable", lab: "not applicable" },
      { name: "prioritising multiple emergencies", finding: "a patient with chest pain left waiting behind minor cases", action: "prioritise the acutely ill patient immediately", drug: "not applicable", lab: "ECG" },
      { name: "transferring a critically ill patient", finding: "an unstable patient transferred with no oxygen or escort", action: "stabilise and transfer with the right escort and equipment", drug: "oxygen", lab: "vital signs" },
      { name: "recognising deterioration early", finding: "a rising pulse and falling pressure noted but not reported", action: "recognise the trend and escalate immediately", drug: "not applicable", lab: "vital signs" },
      { name: "infection control during resuscitation", finding: "resuscitation performed with no protective equipment", action: "use protective equipment during resuscitation", drug: "not applicable", lab: "not applicable" },
      { name: "restocking after an emergency", finding: "an emergency trolley left empty after a resuscitation", action: "restock and check the trolley immediately after use", drug: "not applicable", lab: "trolley checklist" },
    ],
  },
];
