/**
 * Ghana NMC Licensing Examination dataset — Registered General Nursing.
 *
 * Authored in the style of the NMC Ghana licensing examination: Ghana clinical
 * practice, the Ghana Health System, CHPS, the Standard Treatment Guidelines and
 * locally prevalent conditions.
 *
 * Format: [category, condition, [ [finding, priorityAction, keyDrug, keyLab], ... ]]
 * Each fact yields 10 unique questions.
 */

export type GhanaFact = [finding: string, action: string, drug: string, lab: string];

export const GHANA_NMC_DATA: [category: string, condition: string, facts: GhanaFact[]][] = [
  // ── Ghana Health System & CHPS ──────────────────────────────────
  ["Ghana Health System & CHPS", "the CHPS strategy", [
    ["a community with no functional CHPS compound and low immunisation coverage", "plan community outreach and involve the community health committee", "not applicable", "DHIMS2 coverage data"],
    ["a community health nurse covering twelve communities alone", "request additional staff and prioritise high-burden communities", "not applicable", "staffing record"],
    ["a chief who is unaware of a new outreach programme", "follow proper community entry and brief the traditional authority", "not applicable", "not applicable"],
    ["a CHPS compound with no essential medicines for a month", "report the stock-out through the district health management team", "not applicable", "stock record"],
    ["a community health worker reporting a cluster of fever cases", "investigate the report and notify the disease control officer", "not applicable", "surveillance report"],
    ["low facility delivery in a community with a functional CHPS compound", "counsel on the danger signs and benefits of skilled delivery", "not applicable", "delivery register"],
    ["a community demanding a health facility before any data is gathered", "conduct a community needs assessment first", "not applicable", "community profile"],
    ["poor attendance at a health education session held on a farming day", "reschedule the session to suit the community's routine", "not applicable", "not applicable"],
    ["a community with open defecation near the only water source", "convene a community meeting on latrine use and sanitation", "not applicable", "water quality test"],
    ["a volunteer who has stopped submitting surveillance reports", "trace, retrain and support the volunteer", "not applicable", "surveillance report"],
    ["a patient who cannot afford transport to the district hospital", "stabilise and coordinate support for emergency referral", "not applicable", "referral note"],
    ["a district with rising home deaths from malaria", "strengthen community case detection and referral", "antimalarial", "DHIMS2 mortality data"],
    ["a community durbar held without translating the health message", "deliver the talk in the local language with examples", "not applicable", "not applicable"],
    ["no birth register maintained at a CHPS compound", "record and register all births in the community", "not applicable", "birth register"],
    ["a nurse unsure which diseases must be reported immediately", "follow the national notifiable disease list and report promptly", "not applicable", "surveillance report"],
    ["a patient with a complex condition attending a CHPS compound repeatedly", "explain the referral pathway and refer to the district hospital", "not applicable", "referral note"],
    ["an outreach cancelled because no transport was arranged", "plan transport and logistics before the outreach date", "not applicable", "outreach plan"],
    ["a community health committee that has not met for a year", "reconstitute the committee and involve them in planning", "not applicable", "not applicable"],
    ["a woman in labour presenting at a CHPS compound at night", "stabilise, complete the referral note and arrange transport", "intravenous fluids", "vital signs"],
    ["a monthly report submitted late with missing figures", "compile and submit the returns through the district data officer", "not applicable", "DHIMS2 returns"],
  ]],
  ["Ghana Health System & CHPS", "the National Health Insurance Scheme", [
    ["a patient who cannot afford out-of-pocket payment for essential medicines", "verify the patient's NHIS membership and refer for enrolment", "not applicable", "NHIS membership record"],
    ["a patient whose NHIS card has expired", "advise renewal and provide the care that is urgently needed", "not applicable", "NHIS membership record"],
    ["a patient told a service is not covered by NHIS", "check the benefits list and clarify for the patient", "not applicable", "not applicable"],
    ["a long queue at the NHIS registration desk", "organise the queue and inform patients of the process", "not applicable", "not applicable"],
    ["a patient asked to pay for a service that should be free", "report the demand for payment through the proper channel", "not applicable", "incident report"],
    ["a pregnant woman unaware that antenatal care is covered", "counsel her on the free antenatal services available", "not applicable", "not applicable"],
    ["a patient confused about which medicines NHIS covers", "explain the covered essential medicines list", "not applicable", "not applicable"],
    ["a nurse collecting unofficial payment from a patient", "report the conduct to the appropriate authority", "not applicable", "incident report"],
    ["a patient whose NHIS claim was rejected in error", "follow up the claim with the district insurance office", "not applicable", "claims record"],
    ["a community with very low NHIS enrolment", "run a health education session on the benefits of enrolment", "not applicable", "not applicable"],
  ]],

  // ── Medical-Surgical Nursing (Ghana) ────────────────────────────
  ["Medical-Surgical Nursing (Ghana)", "severe malaria", [
    ["fever with altered consciousness and passage of dark urine", "start parenteral antimalarial therapy and check the blood glucose", "intravenous artesunate", "thick and thin blood film"],
    ["convulsions with a positive malaria test in a child", "give prescribed anticonvulsant and antimalarial treatment", "intravenous diazepam", "blood glucose"],
    ["jaundice with a high fever and a positive blood film", "treat the malaria and monitor for complications", "intravenous artesunate", "serum bilirubin"],
    ["a patient with malaria vomiting every oral dose", "give parenteral therapy instead of oral treatment", "intravenous artesunate", "not applicable"],
    ["hypoglycaemia in a patient being treated for severe malaria", "give intravenous dextrose and monitor the glucose", "intravenous dextrose", "blood glucose"],
    ["a patient with malaria who is passing very little urine", "assess for renal impairment and monitor the fluid balance", "not applicable", "serum creatinine"],
    ["a pregnant woman with severe malaria at 30 weeks", "refer urgently for parenteral therapy and fetal monitoring", "intravenous artesunate", "fetal heart rate"],
    ["a patient treated for malaria who is still febrile after 48 hours", "reassess the diagnosis and check the treatment", "not applicable", "blood film"],
    ["anaemia with a positive malaria test in an adult", "treat the malaria and assess the need for transfusion", "packed red blood cells", "haemoglobin level"],
    ["a patient discharged after malaria who returns with fever again", "reassess for treatment failure or reinfection", "not applicable", "blood film"],
  ]],
  ["Medical-Surgical Nursing (Ghana)", "sickle cell crisis", [
    ["severe bone pain with fever and dehydration", "give oxygen, fluids, analgesia and treat infection", "pentazocine", "haemoglobin electrophoresis"],
    ["a painful swollen hand in a young child with sickle cell disease", "hydrate, give analgesia and screen for infection", "paracetamol", "haemoglobin level"],
    ["a painful swollen calf with breathlessness in a sickle cell patient", "assess for embolism and refer urgently", "low molecular weight heparin", "Doppler ultrasound"],
    ["a painful erect priapism in a male patient in crisis", "refer urgently as this is an emergency", "intravenous fluids", "not applicable"],
    ["a patient in crisis refusing to drink water because of pain", "give intravenous fluids and control the pain first", "intravenous fluids", "not applicable"],
    ["pallor with a falling haemoglobin in a sickle cell patient", "assess for aplastic crisis and crossmatch blood", "packed red blood cells", "haemoglobin level"],
    ["a leg ulcer that has not healed for months in a sickle cell patient", "clean, dress and assess for infection", "not applicable", "wound swab"],
    ["a patient with sickle cell disease asking about having children", "counsel on genetic inheritance and partner screening", "not applicable", "haemoglobin electrophoresis"],
    ["a fever in a sickle cell patient with no obvious source", "treat infection promptly as it can precipitate a crisis", "antibiotic", "blood culture"],
    ["a patient in crisis whose pain is not controlled on regular analgesia", "reassess and escalate the analgesia", "opioid analgesia", "pain score"],
  ]],
  ["Medical-Surgical Nursing (Ghana)", "typhoid fever", [
    ["a prolonged fever with abdominal pain and constipation", "give prescribed antibiotics and monitor the abdomen", "intravenous ceftriaxone", "widál test"],
    ["sudden generalised abdominal pain with guarding after a febrile illness", "keep the patient nil by mouth and prepare for emergency surgery", "intravenous ceftriaxone", "abdominal x-ray"],
    ["a patient with typhoid passing loose stool and vomiting", "rehydrate and continue the prescribed antibiotic", "intravenous fluids", "serum electrolytes"],
    ["a patient who recovered from typhoid still passing the organism", "counsel on hygiene and follow up the stool culture", "not applicable", "stool culture"],
    ["a patient with typhoid who is confused and drowsy", "assess for encephalopathy and refer urgently", "intravenous fluids", "not applicable"],
    ["a family member with the same fever after sharing meals", "screen the household and teach food hygiene", "not applicable", "not applicable"],
    ["a patient treated for typhoid who stops the medicine early", "teach the importance of completing the full course", "not applicable", "not applicable"],
    ["a patient with typhoid and a distended abdomen with no bowel sounds", "assess for perforation and keep nil by mouth", "not applicable", "abdominal x-ray"],
    ["a food handler diagnosed with typhoid still at work", "advise the patient to stop work until cleared", "not applicable", "stool culture"],
    ["a patient with typhoid asking whether it can recur", "explain the possibility of relapse and the need for follow-up", "not applicable", "not applicable"],
  ]],
  ["Medical-Surgical Nursing (Ghana)", "diabetic foot sepsis", [
    ["a foul-smelling ulcer with necrotic tissue in a diabetic patient", "debride, dress and start prescribed antibiotics with glycaemic control", "intravenous metronidazole", "random blood glucose"],
    ["a diabetic ulcer with blackened toes", "refer for surgical assessment of the limb", "not applicable", "random blood glucose"],
    ["a diabetic patient who walks barefoot at home", "teach daily foot inspection and protective footwear", "not applicable", "not applicable"],
    ["a diabetic foot ulcer not healing after several weeks", "assess the blood glucose control and the wound", "insulin", "random blood glucose"],
    ["a diabetic patient with numb feet who did not notice an injury", "teach daily inspection as sensation is reduced", "not applicable", "not applicable"],
    ["a diabetic foot wound with pus and surrounding redness", "take a swab and start prescribed antibiotics", "intravenous antibiotics", "wound swab"],
    ["a diabetic patient with a foot ulcer and a glucose of 22 mmol/L", "control the glucose to allow the wound to heal", "insulin", "random blood glucose"],
    ["a patient with a diabetic ulcer who refuses amputation", "respect the decision and explain the risk clearly", "not applicable", "not applicable"],
    ["a diabetic foot ulcer dressed with a dirty cloth at home", "teach clean dressing technique to the family", "not applicable", "not applicable"],
    ["a patient with a foot ulcer asking about footwear", "advise on appropriate protective footwear", "not applicable", "not applicable"],
  ]],
  ["Medical-Surgical Nursing (Ghana)", "severe anaemia", [
    ["pallor with a haemoglobin below 5 g/dL and fast breathing", "crossmatch and transfuse packed cells as prescribed", "packed red blood cells", "haemoglobin level"],
    ["a patient with severe anaemia and a fast weak pulse", "transfuse as prescribed and monitor for overload", "packed red blood cells", "vital signs"],
    ["a patient with anaemia and a poor diet of mainly starch", "counsel on iron-rich local foods and give supplements", "ferrous sulphate", "haemoglobin level"],
    ["a patient with anaemia passing dark red urine after malaria", "treat the malaria and assess for haemolysis", "antimalarial", "urinalysis"],
    ["a patient with anaemia who is febrile and breathless", "treat the infection and transfuse as prescribed", "antibiotic", "haemoglobin level"],
    ["a patient transfused and then breathless with crackles", "stop the transfusion and assess for overload", "not applicable", "oxygen saturation"],
    ["a patient with anaemia who refuses a blood transfusion", "respect the refusal and explain the risks clearly", "not applicable", "not applicable"],
    ["a child with severe anaemia and a huge spleen", "refer for assessment of the underlying cause", "not applicable", "not applicable"],
    ["a patient with anaemia asking about iron injections", "explain that oral iron is usually preferred and safer", "ferrous sulphate", "haemoglobin level"],
    ["a patient with anaemia who is dizzy on standing", "advise slow position changes and monitor the blood pressure", "not applicable", "blood pressure"],
  ]],
  ["Medical-Surgical Nursing (Ghana)", "road traffic accident trauma", [
    ["a deteriorating Glasgow Coma Scale score with unequal pupils", "stabilise the airway and refer for urgent CT scan", "intravenous mannitol", "Glasgow Coma Scale"],
    ["a road traffic patient with a deformed painful thigh", "immobilise the limb and assess the circulation", "not applicable", "x-ray"],
    ["a trauma patient with a fast weak pulse and cold skin", "treat for shock and control the bleeding", "intravenous crystalloids", "haemoglobin level"],
    ["a trauma patient with neck pain and limb weakness", "immobilise the spine and log roll the patient", "not applicable", "x-ray"],
    ["a trauma patient with absent breath sounds on one side", "prepare for immediate needle decompression", "oxygen", "chest x-ray"],
    ["a trauma patient with a deep contaminated wound", "clean the wound and give tetanus prophylaxis", "tetanus toxoid", "wound assessment"],
    ["a trauma patient with a swollen painful deformed wrist", "immobilise and refer for an x-ray", "not applicable", "x-ray"],
    ["a trauma patient who is confused and smelling of alcohol", "assess the head injury rather than assuming drunkenness", "not applicable", "Glasgow Coma Scale"],
    ["a trauma patient with a bleeding scalp wound", "apply pressure to control the bleeding", "not applicable", "haemoglobin level"],
    ["a trauma patient referred with no record of the treatment given", "document all treatment before and during transfer", "not applicable", "referral note"],
  ]],
  ["Medical-Surgical Nursing (Ghana)", "chronic kidney disease", [
    ["a patient with kidney disease and a potassium of 6.4 mmol/L", "restrict potassium and give calcium gluconate", "intravenous calcium", "ECG"],
    ["a patient on dialysis who is anaemic and tired", "assess the erythropoietin therapy and iron status", "erythropoietin", "haemoglobin level"],
    ["a patient with kidney disease and severe itching", "give phosphate binders with meals and provide skin care", "calcium acetate", "serum phosphate"],
    ["a patient with kidney disease and deep rapid breathing", "assess the bicarbonate level and report", "sodium bicarbonate", "serum bicarbonate"],
    ["a patient with kidney disease asking about diet", "teach restriction of potassium, phosphate and salt", "not applicable", "serum potassium"],
    ["a patient with kidney disease and a high blood pressure", "monitor the pressure and give prescribed antihypertensives", "antihypertensive", "blood pressure"],
    ["a patient with kidney disease who has stopped attending dialysis", "explore the reasons and support the patient to return", "not applicable", "not applicable"],
    ["a patient with kidney disease and swollen legs", "restrict fluid as prescribed and monitor the weight", "not applicable", "daily weight"],
    ["a patient with kidney disease asking about a transplant", "refer for transplant assessment and counselling", "not applicable", "not applicable"],
    ["a patient with kidney disease on a herbal preparation", "advise on the risk of further kidney damage", "not applicable", "serum creatinine"],
  ]],
  ["Medical-Surgical Nursing (Ghana)", "hepatic encephalopathy", [
    ["drowsiness with flapping tremor in a patient with liver disease", "give prescribed lactulose and assess consciousness", "lactulose", "serum ammonia"],
    ["a patient with liver disease becoming aggressive and confused", "assess for encephalopathy and protect the patient", "lactulose", "not applicable"],
    ["a patient with liver disease and a distended abdomen", "monitor the weight and girth and restrict salt", "spironolactone", "serum sodium"],
    ["a patient with liver disease vomiting blood", "prepare for emergency endoscopy and transfusion", "terlipressin", "haemoglobin level"],
    ["a patient with liver disease and a low albumin with oedema", "restrict sodium and assess the nutritional needs", "albumin infusion", "serum albumin"],
    ["a patient with liver disease who is deeply jaundiced and itching", "assess the bilirubin and provide skin care", "not applicable", "serum bilirubin"],
    ["a patient with liver disease who drinks alcohol secretly", "assess honestly and arrange support for cessation", "not applicable", "not applicable"],
    ["a patient with liver disease on a high protein diet", "adjust the protein intake as prescribed", "not applicable", "serum ammonia"],
    ["a patient with liver disease and a fever with abdominal pain", "assess for spontaneous bacterial peritonitis", "intravenous antibiotics", "not applicable"],
    ["a patient with liver disease asking about the prognosis", "communicate honestly and involve the family", "not applicable", "not applicable"],
  ]],
  ["Medical-Surgical Nursing (Ghana)", "snake envenomation", [
    ["progressive swelling and bleeding at the bite site", "immobilise the limb and administer antivenom as prescribed", "polyvalent antivenom", "clotting profile"],
    ["a snake bite with drooping eyelids and difficulty swallowing", "prepare for assisted ventilation and antivenom", "polyvalent antivenom", "not applicable"],
    ["a snake bite with a tourniquet applied very tightly", "release the tourniquet carefully and assess the limb", "not applicable", "not applicable"],
    ["a snake bite with local swelling but no systemic signs", "observe closely and monitor the clotting profile", "not applicable", "clotting profile"],
    ["a snake bite treated with incisions and suction at home", "assess the wound and the blood loss", "not applicable", "haemoglobin level"],
    ["a snake bite patient who develops bleeding from the gums", "give antivenom and monitor the clotting", "polyvalent antivenom", "clotting profile"],
    ["a snake bite on a child with a rapid spreading swelling", "measure the swelling and give antivenom as prescribed", "polyvalent antivenom", "not applicable"],
    ["a snake bite patient who develops a rash after antivenom", "stop the antivenom and treat the reaction", "adrenaline", "vital signs"],
    ["a snake bite with a dead snake brought to the facility", "identify the species to guide the treatment", "not applicable", "not applicable"],
    ["a snake bite patient discharged the same day", "advise on warning signs and the need to return", "not applicable", "not applicable"],
  ]],
  ["Medical-Surgical Nursing (Ghana)", "chronic leg ulcer", [
    ["a leg ulcer present for one year with no improvement", "assess the cause and apply appropriate dressing and compression", "not applicable", "wound swab"],
    ["a leg ulcer with a large amount of exudate", "choose an absorbent dressing and protect the surrounding skin", "not applicable", "not applicable"],
    ["a leg ulcer with a foul smell and greenish discharge", "take a swab and start prescribed treatment", "antibiotic", "wound swab"],
    ["a leg ulcer in a patient with visible varicose veins", "assess the venous cause and apply compression", "not applicable", "not applicable"],
    ["a leg ulcer in a diabetic patient with reduced sensation", "assess for a neuropathic cause and offload pressure", "not applicable", "random blood glucose"],
    ["a leg ulcer patient who cannot afford dressings", "discuss affordable options and refer for support", "not applicable", "not applicable"],
    ["a leg ulcer with exposed tendon at the base", "refer for specialist wound assessment", "not applicable", "not applicable"],
    ["a leg ulcer patient who keeps the leg dependent all day", "teach elevation to reduce the swelling", "not applicable", "not applicable"],
    ["a leg ulcer with slough covering the wound bed", "assess for debridement and choose the correct dressing", "not applicable", "not applicable"],
    ["a leg ulcer that bleeds easily on dressing", "use a non-adherent dressing and be gentle", "not applicable", "not applicable"],
  ]],

  // ── Pharmacology & Ghana STG ────────────────────────────────────
  ["Pharmacology & Ghana STG", "artemisinin combination therapy", [
    ["vomiting within 30 minutes of taking an antimalarial dose", "repeat the dose and monitor for tolerance", "artemether-lumefantrine", "blood film"],
    ["a patient taking an antimalarial with fatty food as advised", "praise the patient as this improves absorption", "artemether-lumefantrine", "not applicable"],
    ["a patient stopping the antimalarial after two days because of feeling better", "teach the need to complete the full course", "artemether-lumefantrine", "not applicable"],
    ["a patient with malaria who is pregnant at 20 weeks", "give the antimalarial recommended for her gestation", "artemether-lumefantrine", "blood film"],
    ["a patient asking about the bitter taste of the antimalarial", "explain the taste and advise taking with food", "artemether-lumefantrine", "not applicable"],
    ["a patient with malaria treated but still febrile at 48 hours", "reassess for treatment failure or another cause", "not applicable", "blood film"],
    ["a child who spat out most of the antimalarial dose", "assess and repeat the dose as advised", "artemether-lumefantrine", "not applicable"],
    ["a patient taking antimalarials bought from a roadside seller", "teach the danger of fake and substandard medicines", "not applicable", "not applicable"],
    ["a patient with malaria and a history of allergy to a medicine", "check the allergy history before giving the dose", "not applicable", "not applicable"],
    ["a patient with malaria on antimalarials asking about a follow-up test", "explain when a repeat blood film is needed", "not applicable", "blood film"],
  ]],
  ["Pharmacology & Ghana STG", "antiretroviral therapy", [
    ["a patient missing antiretroviral doses to avoid clinic stigma", "plan adherence support and involve a treatment buddy", "tenofovir-lamivudine-dolutegravir", "viral load"],
    ["a patient with a rising viral load on antiretroviral therapy", "assess adherence before considering resistance", "antiretroviral therapy", "viral load"],
    ["a patient with antiretrovirals and no food at home", "refer for nutritional support to sustain adherence", "not applicable", "not applicable"],
    ["a patient asking whether antiretroviral therapy is lifelong", "explain that treatment is continuous and monitored", "antiretroviral therapy", "viral load"],
    ["a patient with antiretrovirals stored in a hot place", "teach correct storage away from heat", "antiretroviral therapy", "not applicable"],
    ["a patient afraid to collect antiretrovirals from the local clinic", "discuss alternative collection arrangements for privacy", "not applicable", "not applicable"],
    ["a patient with antiretroviral therapy and a new pregnancy", "continue therapy and monitor closely", "antiretroviral therapy", "viral load"],
    ["a patient on antiretroviral therapy with a new tuberculosis diagnosis", "coordinate both treatments and watch for interactions", "antituberculosis therapy", "not applicable"],
    ["a patient who stopped therapy because of side effects", "assess the effects and review the regimen", "antiretroviral therapy", "viral load"],
    ["a patient asking whether a cure is available", "explain honestly that treatment controls the virus", "antiretroviral therapy", "viral load"],
  ]],
  ["Pharmacology & Ghana STG", "quinine infusion", [
    ["tinnitus and sweating during a quinine infusion", "slow the infusion rate and monitor for cinchonism", "intravenous quinine", "blood glucose"],
    ["a patient on quinine with a falling blood glucose", "give intravenous dextrose and monitor closely", "intravenous dextrose", "blood glucose"],
    ["a quinine infusion running much faster than prescribed", "slow the rate to the prescribed speed", "intravenous quinine", "not applicable"],
    ["a patient on quinine with vomiting and abdominal pain", "slow the infusion and assess the patient", "intravenous quinine", "not applicable"],
    ["a patient switched from quinine to oral therapy", "confirm the patient can tolerate oral medicines", "oral antimalarial", "not applicable"],
    ["a quinine infusion with visible particles in the fluid", "stop the infusion and do not give the affected bag", "not applicable", "not applicable"],
    ["a patient on quinine asking why monitoring is frequent", "explain that quinine can affect the heart and glucose", "intravenous quinine", "ECG"],
    ["a pregnant patient with severe malaria needing therapy", "give the recommended therapy and monitor the fetus", "intravenous artesunate", "fetal heart rate"],
    ["a patient on quinine whose cannula site is swollen", "stop the infusion and resite the cannula", "not applicable", "not applicable"],
  ]],
  ["Pharmacology & Ghana STG", "gentamicin therapy", [
    ["reduced urine output with tinnitus on aminoglycoside therapy", "report for dose review and monitor renal function", "gentamicin", "serum creatinine"],
    ["a patient on gentamicin with unsteady gait and dizziness", "report the possible toxicity and review the medicine", "gentamicin", "not applicable"],
    ["a patient on gentamicin with no level monitoring", "request a gentamicin level before the next dose", "gentamicin", "gentamicin level"],
    ["a patient with kidney disease prescribed full-dose gentamicin", "review the dose with the prescriber", "gentamicin", "serum creatinine"],
    ["a patient on gentamicin asking why blood tests are repeated", "explain that the medicine can affect the kidneys and ears", "gentamicin", "serum creatinine"],
    ["a patient on gentamicin with a rash developing", "assess for an allergic reaction and report", "not applicable", "not applicable"],
    ["a patient on gentamicin with dehydration from vomiting", "correct the dehydration as it increases toxicity", "intravenous fluids", "not applicable"],
    ["a child prescribed gentamicin by weight", "check the dose calculation against the weight", "gentamicin", "weight record"],
    ["a patient on gentamicin with a worsening infection", "reassess the treatment and send cultures", "not applicable", "culture and sensitivity"],
    ["a patient on gentamicin asking how long treatment lasts", "explain that the course is kept as short as is safe", "gentamicin", "not applicable"],
  ]],
  ["Pharmacology & Ghana STG", "paracetamol overdose", [
    ["right upper quadrant pain after a deliberate paracetamol overdose", "administer prescribed N-acetylcysteine and monitor the liver", "N-acetylcysteine", "liver enzymes"],
    ["a patient who took an overdose four hours ago", "give the antidote and monitor closely", "N-acetylcysteine", "paracetamol level"],
    ["a patient who took an overdose and refuses treatment", "assess the risk and involve the mental health team", "N-acetylcysteine", "not applicable"],
    ["a patient who took an overdose with alcohol", "assess as higher risk and treat promptly", "N-acetylcysteine", "liver enzymes"],
    ["a patient who took an overdose asking about the antidote", "explain that it protects the liver if given early", "N-acetylcysteine", "not applicable"],
    ["a patient who took an overdose and is now drowsy", "assess the airway and refer for urgent review", "not applicable", "conscious level"],
    ["a patient who took an overdose with a plan for another attempt", "place on close observation and involve mental health", "not applicable", "risk assessment"],
    ["a patient who took an overdose and has vomiting", "give the antidote by the appropriate route", "N-acetylcysteine", "not applicable"],
    ["a family asking why the patient is being observed closely", "explain the risk of a further attempt", "not applicable", "not applicable"],
    ["a patient who took an overdose and is being discharged", "arrange follow-up and family support before discharge", "not applicable", "not applicable"],
  ]],
  ["Pharmacology & Ghana STG", "controlled medicines register", [
    ["a controlled drug register entry that does not balance", "report the discrepancy immediately and investigate", "pethidine", "controlled drug register"],
    ["a controlled drug given without a second nurse checking", "stop and follow the two-nurse checking procedure", "pethidine", "controlled drug register"],
    ["a controlled drug cupboard left unlocked", "lock the cupboard and report the breach", "not applicable", "not applicable"],
    ["a controlled drug wasted with no witness recorded", "ensure a witness signs for all wastage", "not applicable", "controlled drug register"],
    ["a controlled drug prescription with an unclear dose", "clarify the order before administering", "not applicable", "prescription chart"],
    ["a controlled drug request with no signature", "do not issue it and return it for completion", "not applicable", "not applicable"],
    ["a patient requesting more controlled medicine than prescribed", "assess the pain and involve the prescriber", "not applicable", "pain score"],
    ["a controlled drug count done only once a week", "follow the policy for regular counting", "not applicable", "controlled drug register"],
    ["a controlled drug key left with an unauthorised person", "retrieve the key and report the breach", "not applicable", "not applicable"],
    ["a controlled drug expired in the cupboard", "follow the policy for destruction and recording", "not applicable", "not applicable"],
  ]],

  // ── Community Health Nursing ────────────────────────────────────
  ["Community Health Nursing", "cholera outbreak response", [
    ["several households with acute watery diarrhoea after a funeral", "notify the disease control officer and start oral rehydration", "oral rehydration salts", "stool culture"],
    ["a cholera patient with severe dehydration and a weak pulse", "give rapid intravenous rehydration", "intravenous Ringer's lactate", "vital signs"],
    ["a cholera outbreak with families sharing a water source", "close or treat the source and educate the community", "not applicable", "water quality test"],
    ["a cholera patient being cared for without protective equipment", "use protective equipment and follow the precautions", "not applicable", "not applicable"],
    ["a cholera patient discharged with no health education", "teach hygiene and hand washing before discharge", "not applicable", "not applicable"],
    ["a cholera outbreak with food sellers still operating", "educate the vendors and involve the environmental health officer", "not applicable", "not applicable"],
    ["a child with cholera and vomiting unable to drink", "refer for intravenous rehydration", "intravenous fluids", "not applicable"],
    ["a cholera patient who has recovered but is still weak", "assess the nutrition and continue rehydration", "oral rehydration salts", "not applicable"],
    ["a community blaming cholera on witchcraft", "respect their belief while explaining the real cause", "not applicable", "not applicable"],
    ["a cholera outbreak with deaths at home not reported", "investigate the deaths and strengthen surveillance", "not applicable", "surveillance report"],
  ]],
  ["Community Health Nursing", "measles outbreak", [
    ["clusters of fever with rash in unvaccinated children", "report the suspected outbreak and plan mass vaccination", "measles vaccine", "serology"],
    ["a child with measles and mouth ulcers unable to eat", "give vitamin A and treat the mouth lesions", "vitamin A", "clinical assessment"],
    ["a child with measles and eye discharge", "clean the eyes and give prescribed treatment", "not applicable", "not applicable"],
    ["a child with measles developing fast breathing", "assess for pneumonia and refer urgently", "antibiotic", "oxygen saturation"],
    ["a child with measles whose caregiver used traditional remedies", "respect their belief and explain the need for treatment", "not applicable", "not applicable"],
    ["a community with low measles vaccination coverage", "plan catch-up vaccination and health education", "measles vaccine", "EPI card"],
    ["a child with measles and diarrhoea becoming dehydrated", "rehydrate and monitor closely", "oral rehydration salts", "not applicable"],
    ["a school with several children having fever and rash", "notify the disease control officer and investigate", "not applicable", "surveillance report"],
    ["a caregiver asking whether measles is dangerous", "explain the complications and the value of vaccination", "not applicable", "not applicable"],
    ["a child recovering from measles who is still weak", "assess nutrition and support recovery", "not applicable", "weight record"],
  ]],
  ["Community Health Nursing", "malnutrition prevention", [
    ["several under-five children with yellow-zone mid-upper arm circumference", "enrol the children in supplementary feeding and educate caregivers", "supplementary feed", "mid-upper arm circumference"],
    ["a child with red-zone mid-upper arm circumference and oedema", "refer urgently for therapeutic feeding", "therapeutic milk", "mid-upper arm circumference"],
    ["a caregiver diluting formula to make it last longer", "counsel on correct preparation and support the family", "not applicable", "not applicable"],
    ["a child with malnutrition and a poor appetite", "assess for infection and start therapeutic feeding", "therapeutic milk", "not applicable"],
    ["a caregiver feeding a child only maize porridge", "teach the addition of protein and vegetables", "not applicable", "growth chart"],
    ["a child with malnutrition whose mother is also malnourished", "support both the mother and the child", "not applicable", "not applicable"],
    ["a child with malnutrition who is not gaining weight on treatment", "review the feeding plan and screen for infection", "not applicable", "weight record"],
    ["a community with seasonal food shortages", "plan nutrition support ahead of the lean season", "not applicable", "not applicable"],
    ["a caregiver who believes a child should not eat eggs", "respect the belief and explain the nutritional value", "not applicable", "not applicable"],
    ["a child with malnutrition and a fever", "treat the infection as it worsens malnutrition", "antibiotic", "temperature"],
  ]],
  ["Community Health Nursing", "tuberculosis contact tracing", [
    ["a household contact of a smear-positive patient with a chronic cough", "screen the household contacts and collect sputum samples", "not applicable", "sputum AFB"],
    ["a tuberculosis patient who has stopped attending for treatment", "trace the patient and resume directly observed therapy", "antituberculosis therapy", "sputum AFB"],
    ["a child in a tuberculosis household with no screening", "screen the child and consider preventive therapy", "isoniazid preventive therapy", "not applicable"],
    ["a tuberculosis patient coughing in a crowded waiting area", "separate the patient and provide a surgical mask", "not applicable", "not applicable"],
    ["a tuberculosis patient who is pregnant", "treat with the recommended regimen and monitor", "antituberculosis therapy", "not applicable"],
    ["a tuberculosis patient with no improvement after treatment", "request drug sensitivity testing", "not applicable", "sputum culture"],
    ["a tuberculosis patient afraid of stigma at work", "counsel on confidentiality and treatment completion", "not applicable", "not applicable"],
    ["a tuberculosis patient with orange-red urine on therapy", "reassure that this is an expected effect", "rifampicin", "liver enzymes"],
    ["a tuberculosis patient with a poor appetite and weight loss", "assess nutrition and support the treatment", "not applicable", "weight record"],
    ["a community health worker afraid to visit a tuberculosis home", "educate and provide the correct protective measures", "not applicable", "not applicable"],
  ]],
  ["Community Health Nursing", "HIV testing services", [
    ["a patient who fears knowing their HIV status", "provide pre-test counselling and obtain informed consent", "not applicable", "HIV rapid test"],
    ["a patient with a positive HIV screening test", "confirm the result and link the patient to care", "antiretroviral therapy", "confirmatory test"],
    ["a patient who tested positive and disappeared", "trace the patient sensitively and support linkage to care", "antiretroviral therapy", "not applicable"],
    ["a patient whose partner refuses testing", "counsel the patient and offer partner notification support", "not applicable", "not applicable"],
    ["a patient testing negative but with ongoing risk", "teach prevention and schedule repeat testing", "not applicable", "not applicable"],
    ["a patient who tested positive and is pregnant", "start antiretroviral therapy and plan infant prophylaxis", "antiretroviral therapy", "viral load"],
    ["a patient asking for a test with no counselling available", "provide counselling before and after the test", "not applicable", "not applicable"],
    ["a community with high HIV stigma", "run anti-stigma education with community leaders", "not applicable", "not applicable"],
    ["a patient asking whether the test result will be shared", "explain the confidentiality policy clearly", "not applicable", "not applicable"],
    ["a health worker with a needle stick injury from an HIV patient", "start post-exposure prophylaxis within 72 hours", "post-exposure prophylaxis", "baseline HIV test"],
  ]],
  ["Community Health Nursing", "elderly care in the community", [
    ["an older person living alone with uncontrolled blood pressure", "plan a home visit schedule and teach medication adherence", "amlodipine", "blood pressure"],
    ["an older patient with pressure sores and no caregiver", "teach the family repositioning and arrange support", "not applicable", "not applicable"],
    ["an older patient taking several medicines with no review", "review the medicines for interactions", "not applicable", "not applicable"],
    ["an older patient who has fallen twice at home", "assess the home hazards and the vision", "not applicable", "fall risk score"],
    ["an older patient with poor vision unable to read a label", "teach the family to help with the medicines", "not applicable", "not applicable"],
    ["an older patient with no transportation to the clinic", "arrange a home visit or community transport", "not applicable", "not applicable"],
    ["an older patient who is confused and alone", "assess for a treatable cause and arrange support", "not applicable", "urinalysis"],
    ["an older patient with weight loss and a poor appetite", "assess the nutrition and screen for illness", "not applicable", "weight record"],
    ["an older patient whose family has stopped visiting", "involve the family and community support", "not applicable", "not applicable"],
    ["an older patient asking about pain in the joints", "assess the pain and advise on safe management", "analgesia", "not applicable"],
  ]],

  // ── Maternal & Newborn Care ─────────────────────────────────────
  ["Maternal & Newborn Care", "postpartum haemorrhage", [
    ["a boggy uterus with heavy bleeding after delivery", "massage the uterus and give the prescribed uterotonic", "oxytocin", "haemoglobin level"],
    ["blood loss over 500 mL within 24 hours of delivery", "call for help and start intravenous resuscitation", "intravenous fluids", "haemoglobin level"],
    ["a full bladder with a deviated uterus after delivery", "empty the bladder and reassess the uterus", "urinary catheter", "not applicable"],
    ["continuous oozing with no firm clot formation", "assess for coagulation problems and refer urgently", "blood products", "coagulation profile"],
    ["a uterus that will not contract after the third baby", "give a second uterotonic and prepare for transfer", "carboprost", "blood loss"],
    ["heavy bleeding with a firm contracted uterus", "assess for tears or retained tissue", "not applicable", "haemoglobin level"],
    ["a mother who is pale, sweaty and drowsy after delivery", "treat for shock and call for help", "intravenous fluids", "vital signs"],
    ["a retained placenta with ongoing bleeding", "refer for manual removal of the placenta", "intravenous fluids", "blood loss"],
    ["heavy bleeding returning on day ten after delivery", "assess for retained products and infection", "intravenous antibiotics", "haemoglobin level"],
    ["a mother discharged early with no postnatal visit planned", "arrange a postnatal visit and teach the danger signs", "not applicable", "not applicable"],
  ]],
  ["Maternal & Newborn Care", "pre-eclampsia and eclampsia", [
    ["a blood pressure of 165/115 mmHg with proteinuria and headache", "start magnesium sulfate as prescribed and institute seizure precautions", "magnesium sulfate", "urine protein"],
    ["convulsions in a pregnant woman at term", "protect from injury and give prescribed magnesium sulfate", "magnesium sulfate", "blood pressure"],
    ["absent knee reflexes on magnesium sulfate therapy", "stop the infusion and give calcium gluconate", "calcium gluconate", "reflex assessment"],
    ["a respiratory rate of 10 per minute on magnesium sulfate", "stop the infusion and give the antidote", "calcium gluconate", "respiratory rate"],
    ["epigastric pain with a rising blood pressure at 34 weeks", "assess for impending eclampsia and call for help", "magnesium sulfate", "blood pressure"],
    ["a woman with pre-eclampsia referred without any treatment", "stabilise with magnesium sulfate before referral", "magnesium sulfate", "referral note"],
    ["blurred vision with a blood pressure of 170/115 mmHg", "treat as severe pre-eclampsia and refer urgently", "magnesium sulfate", "blood pressure"],
    ["a woman with pre-eclampsia who has no fetal heart heard", "refer for urgent assessment of the fetus", "not applicable", "obstetric ultrasound"],
    ["a woman with pre-eclampsia asking why she needs admission", "explain the risk of seizures to her and the baby", "not applicable", "not applicable"],
    ["a woman with pre-eclampsia delivered and still hypertensive", "continue monitoring the blood pressure after delivery", "antihypertensive", "blood pressure"],
  ]],
  ["Maternal & Newborn Care", "neonatal sepsis", [
    ["a three-day-old baby feeding poorly with a low temperature", "refer urgently for parenteral antibiotics", "intravenous ampicillin", "blood culture"],
    ["a baby with a bulging fontanelle and fever", "refer urgently for lumbar puncture and antibiotics", "intravenous ceftriaxone", "cerebrospinal fluid"],
    ["a baby with an umbilical stump discharging pus", "clean the cord and start prescribed antibiotics", "intravenous antibiotics", "not applicable"],
    ["a baby with a temperature of 35.5 degrees and poor feeding", "warm the baby and assess for sepsis", "intravenous antibiotics", "blood culture"],
    ["a baby with grunting and a high temperature", "assess for sepsis and refer for treatment", "intravenous antibiotics", "blood culture"],
    ["a baby whose mother's membranes ruptured over 24 hours before delivery", "observe closely and assess for sepsis", "intravenous antibiotics", "not applicable"],
    ["a baby with jaundice and a fever", "assess for sepsis and refer urgently", "intravenous antibiotics", "serum bilirubin"],
    ["a baby with sepsis whose feeding has stopped", "refer for intravenous fluids and antibiotics", "intravenous fluids", "not applicable"],
    ["a mother using traditional remedies on the cord", "teach clean cord care and the risk of infection", "chlorhexidine gel", "not applicable"],
    ["a baby with sepsis discharged too early", "ensure the full antibiotic course is completed", "intravenous antibiotics", "not applicable"],
  ]],
  ["Maternal & Newborn Care", "neonatal jaundice", [
    ["yellow palms and soles on day two of life", "refer urgently for bilirubin measurement", "phototherapy", "serum bilirubin"],
    ["a lethargic jaundiced baby who is feeding poorly", "refer urgently and support feeding", "phototherapy", "serum bilirubin"],
    ["a baby with jaundice in the first 24 hours of life", "treat as pathological and refer immediately", "phototherapy", "serum bilirubin"],
    ["a baby with a rising bilirubin despite phototherapy", "prepare for exchange transfusion", "exchange transfusion", "serum bilirubin"],
    ["a baby under phototherapy with loose green stools", "reassure the mother and protect the eyes", "phototherapy", "not applicable"],
    ["a mother using traditional remedies for the jaundice", "explain the danger and refer for proper treatment", "phototherapy", "serum bilirubin"],
    ["a jaundiced baby whose mother has diabetes", "check the glucose and refer for assessment", "phototherapy", "blood glucose"],
    ["a jaundiced baby who is dehydrated", "support feeding and refer for assessment", "phototherapy", "not applicable"],
    ["a baby with jaundice and a fever", "assess for sepsis and refer urgently", "intravenous antibiotics", "blood culture"],
    ["a mother asking why the baby's eyes are covered", "explain that phototherapy can harm the eyes", "phototherapy", "not applicable"],
  ]],
  ["Maternal & Newborn Care", "neonatal resuscitation", [
    ["a newborn with gasping breathing at one minute", "start bag and mask ventilation within the golden minute", "oxygen", "Apgar score"],
    ["a newborn who is not breathing and floppy at birth", "call for help and start ventilation", "oxygen", "Apgar score"],
    ["a newborn whose heart rate is below 60 after ventilation", "start chest compressions with the ventilation", "adrenaline", "heart rate"],
    ["a newborn with a good heart rate improving on ventilation", "continue ventilation until breathing is established", "not applicable", "Apgar score"],
    ["a newborn delivered through thick meconium who is not breathing", "suction and begin resuscitation promptly", "not applicable", "Apgar score"],
    ["a resuscitated newborn who is still cold and floppy", "warm the baby and refer for continued care", "not applicable", "temperature"],
    ["a newborn resuscitated with no follow-up observation", "monitor closely for recurrent apnoea", "not applicable", "not applicable"],
    ["a mother asking why her baby needed resuscitation", "explain gently what happened and the outlook", "not applicable", "not applicable"],
    ["a newborn resuscitated in a facility that cannot care for it", "refer with a completed note and warmth", "not applicable", "referral note"],
    ["a newborn resuscitation attempted without proper equipment", "ensure the resuscitation area is always ready", "not applicable", "not applicable"],
  ]],
  ["Maternal & Newborn Care", "exclusive breastfeeding", [
    ["a mother giving water and herbs to her newborn", "counsel on exclusive breastfeeding for six months", "not applicable", "not applicable"],
    ["a mother who believes colostrum is dirty and discards it", "teach that colostrum protects the baby", "not applicable", "not applicable"],
    ["a baby taking only the nipple with a narrow mouth", "teach the mother correct attachment", "not applicable", "feeding assessment"],
    ["a mother with painful cracked nipples", "correct the positioning and attachment", "not applicable", "not applicable"],
    ["a mother returning to work who plans to stop feeding", "teach expression and storage to keep breastfeeding", "not applicable", "not applicable"],
    ["a baby with poor weight gain on breastfeeding", "assess attachment, frequency and refer for review", "not applicable", "infant weight"],
    ["a mother with engorgement and difficulty latching", "support frequent feeding and express before latching", "not applicable", "not applicable"],
    ["a family pressuring a mother to use formula", "counsel the family and support continued breastfeeding", "not applicable", "not applicable"],
    ["a mother with HIV asking how to feed her baby", "counsel according to the national infant feeding guidance", "antiretroviral therapy", "viral load"],
    ["a mother feeding a baby at only four-hour intervals", "teach feeding on demand at least eight times a day", "not applicable", "not applicable"],
  ]],

  // ── Child Health (Ghana) ────────────────────────────────────────
  ["Child Health (Ghana)", "severe acute malnutrition", [
    ["a child with mid-upper arm circumference in the red zone", "refer for severe acute malnutrition management", "therapeutic milk", "mid-upper arm circumference"],
    ["visible wasting with oedema of both feet in a child", "begin therapeutic feeding and treat infection", "F-75 therapeutic milk", "serum albumin"],
    ["a child with severe malnutrition and no appetite", "begin nasogastric feeding and treat infection", "F-75 therapeutic milk", "weight for height"],
    ["a child developing diarrhoea during refeeding", "slow the feed and assess for refeeding syndrome", "not applicable", "serum potassium"],
    ["a caregiver diluting therapeutic milk to make it last", "counsel on correct preparation and support the family", "therapeutic milk", "not applicable"],
    ["a child with malnutrition and a fever", "treat the infection as it worsens malnutrition", "antibiotic", "temperature"],
    ["a child with malnutrition discharged with no follow-up", "schedule follow-up and monitor the growth", "not applicable", "growth chart"],
    ["a child with malnutrition whose caregiver uses herbal remedies", "respect their belief and explain the nutritional need", "not applicable", "not applicable"],
    ["a child with malnutrition and a poor appetite test", "begin feeding carefully and monitor closely", "therapeutic milk", "not applicable"],
    ["a child recovering from malnutrition who is still underweight", "continue supplementation and monitor the growth", "not applicable", "growth chart"],
  ]],
  ["Child Health (Ghana)", "childhood pneumonia", [
    ["chest indrawing with a respiratory rate of 60 in a child", "give prescribed antibiotics and oxygen", "intravenous amoxicillin", "oxygen saturation"],
    ["a child who is unable to drink with fast breathing", "refer urgently for parenteral treatment", "intravenous antibiotics", "oxygen saturation"],
    ["grunting with nasal flaring in an infant", "assess the oxygen and refer for treatment", "oxygen", "oxygen saturation"],
    ["a child with fever and cough not drinking fluids", "encourage fluids and reassess the hydration", "not applicable", "temperature"],
    ["a cough not improving after three days of treatment", "reassess and review the antibiotic choice", "not applicable", "chest x-ray"],
    ["a child with pneumonia whose oxygen saturation is 86 percent", "give oxygen and refer for assessment", "oxygen", "oxygen saturation"],
    ["a child with pneumonia and cyanosis", "give oxygen urgently and refer", "oxygen", "oxygen saturation"],
    ["a child with pneumonia whose caregiver delays treatment", "counsel on the danger of delay in pneumonia", "not applicable", "not applicable"],
    ["a child with pneumonia and no immunisation record", "update the immunisation after treatment", "not applicable", "immunisation card"],
    ["a child with repeated pneumonia admissions", "assess for an underlying cause such as HIV", "not applicable", "HIV test"],
  ]],
  ["Child Health (Ghana)", "childhood diarrhoea", [
    ["sunken eyes with reduced skin elasticity in a child", "give oral rehydration solution over four hours", "oral rehydration salts", "not applicable"],
    ["a child with diarrhoea who is lethargic and cannot drink", "start intravenous rehydration urgently", "intravenous Ringer's lactate", "serum electrolytes"],
    ["a child with bloody diarrhoea and fever", "treat with the recommended antibiotic and rehydrate", "antibiotic", "stool culture"],
    ["a child with diarrhoea given only plain water at home", "teach the use of oral rehydration solution", "oral rehydration salts", "not applicable"],
    ["a child with diarrhoea and persistent vomiting", "give small frequent sips and refer if not tolerated", "oral rehydration salts", "not applicable"],
    ["a child with diarrhoea whose caregiver uses herbal concoctions", "explain the risk of delay and dehydration", "oral rehydration salts", "not applicable"],
    ["a child with diarrhoea and no wet nappy for eight hours", "assess the dehydration and refer", "intravenous fluids", "not applicable"],
    ["a child with diarrhoea recovering but still weak", "continue rehydration and feeding", "not applicable", "weight record"],
    ["a child with diarrhoea in a household with unsafe water", "teach safe water treatment and storage", "not applicable", "water quality test"],
    ["a child with repeated episodes of diarrhoea", "assess nutrition and screen for other causes", "not applicable", "not applicable"],
  ]],
  ["Child Health (Ghana)", "neonatal tetanus", [
    ["a two-week-old baby who cannot suck with muscle spasms", "keep the baby in a quiet dark room and refer urgently", "tetanus antitoxin", "clinical assessment"],
    ["a newborn with spasms triggered by touch and noise", "minimise stimulation and refer for treatment", "not applicable", "not applicable"],
    ["a mother with no tetanus immunisation during pregnancy", "counsel on the importance of tetanus immunisation", "tetanus toxoid", "immunisation card"],
    ["a newborn whose cord was cut with an unsterile blade", "assess for tetanus and refer urgently", "tetanus antitoxin", "not applicable"],
    ["a newborn with tetanus whose feeding has stopped", "refer for nasogastric feeding and treatment", "not applicable", "not applicable"],
    ["a community where births occur at home without skilled care", "promote skilled attendance and tetanus immunisation", "tetanus toxoid", "not applicable"],
    ["a newborn with tetanus in a facility without ventilator support", "refer urgently to a facility with capacity", "not applicable", "referral note"],
    ["a caregiver applying herbs to the newborn's cord", "teach clean, dry cord care", "chlorhexidine gel", "not applicable"],
    ["a newborn with tetanus who survives the acute illness", "support feeding and monitor development", "not applicable", "not applicable"],
    ["a mother asking how neonatal tetanus is prevented", "explain immunisation and clean delivery practices", "tetanus toxoid", "not applicable"],
  ]],
  ["Child Health (Ghana)", "childhood malaria", [
    ["a child with fever and a positive malaria test", "give the recommended antimalarial and monitor", "artemether-lumefantrine", "blood film"],
    ["a child with malaria who cannot take oral medicine", "refer for parenteral treatment", "intravenous artesunate", "not applicable"],
    ["a child with malaria and pallor with fast breathing", "transfuse as prescribed and treat the malaria", "packed red blood cells", "haemoglobin level"],
    ["a child with malaria and convulsions", "give prescribed anticonvulsant and antimalarial", "intravenous diazepam", "blood glucose"],
    ["a child with malaria whose caregiver delayed treatment", "counsel on the danger of delay in children", "not applicable", "not applicable"],
    ["a child with malaria in a household with no bed net", "provide a treated net and teach its use", "insecticide-treated net", "not applicable"],
    ["a child treated for malaria who is still febrile", "reassess and check for another cause", "not applicable", "blood film"],
    ["a child with malaria and a poor appetite", "encourage feeding during recovery", "not applicable", "weight record"],
    ["a child with repeated malaria episodes", "assess prevention and consider screening the household", "not applicable", "not applicable"],
    ["a child with malaria whose caregiver used herbal medicine first", "respect their belief and explain the need for tested treatment", "antimalarial", "blood film"],
  ]],

  // ── Mental Health Nursing ───────────────────────────────────────
  ["Mental Health Nursing", "acute psychosis", [
    ["a patient hearing voices and refusing to eat", "provide a calm environment and give prescribed antipsychotics", "haloperidol", "vital signs"],
    ["a patient with acute psychosis who is aggressive", "attempt verbal de-escalation before any restraint", "intramuscular haloperidol", "vital signs"],
    ["a patient with psychosis whose family stopped the medicine", "educate the family and restart the treatment", "antipsychotic", "not applicable"],
    ["a patient with psychosis who is not sleeping at all", "reduce stimulation and give prescribed medicine", "antipsychotic", "not applicable"],
    ["a patient with psychosis and a stiff neck with upward gaze", "give the prescribed anticholinergic and report", "biperiden", "not applicable"],
    ["a patient with psychosis who is wandering away from home", "assess the risk and involve the family in safety", "not applicable", "not applicable"],
    ["a patient with psychosis brought to the facility chained", "remove the restraints and treat the patient with dignity", "not applicable", "not applicable"],
    ["a patient with psychosis who is fearful of the medicine", "explain the treatment and build trust", "antipsychotic", "not applicable"],
    ["a patient with psychosis who has no family support", "arrange community follow-up and support", "not applicable", "not applicable"],
    ["a patient with psychosis who is a danger to others", "assess the risk and involve the mental health team", "not applicable", "risk assessment"],
  ]],
  ["Mental Health Nursing", "epilepsy in the community", [
    ["a patient having a generalised seizure in the market", "protect from injury, position on the side and time the seizure", "diazepam", "not applicable"],
    ["a patient with epilepsy who stopped the medicine for a traditional remedy", "respect their belief while restarting prescribed therapy", "carbamazepine", "not applicable"],
    ["a child with epilepsy excluded from school", "educate the school and support inclusion", "not applicable", "not applicable"],
    ["a patient with epilepsy injured during a seizure at home", "assess the injury and review the seizure control", "not applicable", "not applicable"],
    ["a patient with epilepsy who has never had treatment", "refer for assessment and start prescribed therapy", "anticonvulsant", "not applicable"],
    ["a patient with epilepsy whose seizures are increasing", "review the adherence and the medicine dose", "anticonvulsant", "not applicable"],
    ["a family believing epilepsy is contagious", "educate the family that epilepsy is not contagious", "not applicable", "not applicable"],
    ["a patient with epilepsy asking about driving and work", "explain the safety restrictions honestly", "not applicable", "not applicable"],
    ["a pregnant patient with epilepsy on anticonvulsants", "review the medicine and monitor the pregnancy", "anticonvulsant", "not applicable"],
    ["a patient with epilepsy with no medicine available locally", "arrange a supply and follow-up plan", "anticonvulsant", "not applicable"],
  ]],
  ["Mental Health Nursing", "severe depression", [
    ["a patient with severe depression not eating or sleeping", "assess the risk and refer for treatment", "antidepressant", "risk assessment"],
    ["a patient with depression who is withdrawn from the family", "involve the family and provide support", "not applicable", "not applicable"],
    ["a patient with depression asking whether treatment works", "explain that depression is treatable", "antidepressant", "not applicable"],
    ["a patient with depression and a chronic physical illness", "treat both conditions together", "not applicable", "not applicable"],
    ["a patient with depression who stopped the medicine after a week", "explain that antidepressants take several weeks", "antidepressant", "not applicable"],
    ["a patient with depression and strong religious beliefs", "respect their faith while offering treatment", "not applicable", "not applicable"],
    ["a patient with depression unable to work", "assess the function and refer for support", "not applicable", "not applicable"],
    ["a patient with depression whose family blames them", "educate the family and reduce the blame", "not applicable", "not applicable"],
    ["a patient with depression and poor appetite with weight loss", "assess the nutrition alongside the mood", "not applicable", "weight record"],
    ["a patient with depression asking about counselling", "refer for psychological therapy alongside medicine", "not applicable", "not applicable"],
  ]],
  ["Mental Health Nursing", "substance use disorder", [
    ["a young man with tremors and confusion after stopping alcohol", "institute seizure precautions and give prescribed benzodiazepines", "diazepam", "withdrawal assessment"],
    ["a patient with substance use and no family support", "arrange community and peer support services", "not applicable", "not applicable"],
    ["a patient using substances to cope with grief", "address both the grief and the substance use", "not applicable", "not applicable"],
    ["a patient with a relapse after a period of abstinence", "explore the triggers and restart support without blame", "not applicable", "not applicable"],
    ["a patient asking whether recovery is possible", "offer hope with realistic information about recovery", "not applicable", "not applicable"],
    ["a patient with substance use denying any problem", "use a non-confrontational approach and build trust", "not applicable", "not applicable"],
    ["a patient with substance use and a damaged liver", "assess the physical effects and refer for care", "not applicable", "liver enzymes"],
    ["a patient with substance use who is homeless", "refer for social support alongside treatment", "not applicable", "not applicable"],
    ["a community with rising substance use among the youth", "run community education and prevention programmes", "not applicable", "not applicable"],
    ["a patient with substance use asking about treatment options", "explain the available treatment and support services", "not applicable", "not applicable"],
  ]],

  // ── Communicable Diseases (Ghana) ───────────────────────────────
  ["Communicable Diseases (Ghana)", "Lassa fever suspicion", [
    ["fever with bleeding gums unresponsive to antimalarials", "isolate the patient and notify the disease control officer immediately", "ribavirin", "polymerase chain reaction"],
    ["a suspected haemorrhagic fever case managed in an open ward", "isolate immediately with full protective equipment", "not applicable", "not applicable"],
    ["a patient with suspected Lassa fever and no contact tracing", "trace and monitor all the contacts", "not applicable", "not applicable"],
    ["a health worker exposed to a suspected Lassa fever patient", "monitor the worker and follow the exposure protocol", "not applicable", "not applicable"],
    ["a patient with suspected Lassa fever whose samples are delayed", "continue isolation and escalate the sample collection", "not applicable", "not applicable"],
    ["a community with a suspected haemorrhagic fever death", "investigate and educate the community on prevention", "not applicable", "surveillance report"],
    ["a patient with suspected Lassa fever referred without precautions", "isolate before transfer and inform the receiving unit", "not applicable", "referral note"],
    ["a patient with suspected Lassa fever whose family is at home", "educate and monitor the family members", "not applicable", "not applicable"],
    ["a patient with suspected Lassa fever asking about survival", "communicate honestly while providing supportive care", "not applicable", "not applicable"],
    ["a facility with no isolation capacity for a suspected case", "refer urgently and notify the district team", "not applicable", "referral note"],
  ]],
  ["Communicable Diseases (Ghana)", "meningococcal meningitis", [
    ["fever with neck stiffness and a non-blanching rash", "isolate, notify and give prescribed antibiotics immediately", "intravenous ceftriaxone", "cerebrospinal fluid analysis"],
    ["a child with meningitis and a bulging fontanelle", "refer urgently for lumbar puncture and antibiotics", "intravenous ceftriaxone", "cerebrospinal fluid"],
    ["a patient with meningitis and a convulsion", "protect from injury and give prescribed treatment", "intravenous diazepam", "not applicable"],
    ["a patient with meningitis in a crowded ward", "isolate the patient to protect the others", "not applicable", "not applicable"],
    ["household contacts of a meningitis patient", "provide prophylaxis to close contacts as prescribed", "prophylactic antibiotic", "not applicable"],
    ["a patient with meningitis who is drowsy and vomiting", "refer urgently and monitor the conscious level", "intravenous fluids", "conscious level"],
    ["a community with several meningitis cases in the dry season", "report the outbreak and plan vaccination", "meningitis vaccine", "surveillance report"],
    ["a patient treated for meningitis with hearing loss", "refer for audiological assessment", "not applicable", "hearing assessment"],
    ["a patient with meningitis whose treatment was delayed", "assess for complications and continue treatment", "intravenous antibiotics", "not applicable"],
    ["a caregiver asking whether meningitis is contagious", "explain the transmission and the need for prophylaxis", "not applicable", "not applicable"],
  ]],
  ["Communicable Diseases (Ghana)", "hepatitis B", [
    ["a patient with hepatitis B sharing razors at home", "educate on prevention and screen and vaccinate household contacts", "hepatitis B vaccine", "hepatitis B surface antigen"],
    ["a pregnant woman with a positive hepatitis B test", "plan newborn immunoprophylaxis at birth", "hepatitis B immunoglobulin and vaccine", "hepatitis B surface antigen"],
    ["a patient with hepatitis B and a swollen abdomen", "refer for assessment of chronic liver disease", "not applicable", "liver enzymes"],
    ["a health worker with a needle stick injury from a hepatitis B patient", "check the immunisation status and follow the protocol", "hepatitis B immunoglobulin", "baseline screening"],
    ["a patient with hepatitis B asking about treatment", "refer for assessment of chronic hepatitis B", "antiviral therapy", "liver enzymes"],
    ["a community with high hepatitis B prevalence", "promote vaccination and safe practices", "hepatitis B vaccine", "not applicable"],
    ["a patient with hepatitis B who shares toothbrushes", "teach the household not to share personal items", "not applicable", "not applicable"],
    ["a patient with hepatitis B and alcohol use", "counsel strongly on stopping alcohol", "not applicable", "liver enzymes"],
    ["a newborn of a hepatitis B mother not given prophylaxis", "give the vaccine and immunoglobulin immediately", "hepatitis B immunoglobulin", "not applicable"],
    ["a patient with hepatitis B asking about the vaccine", "explain that vaccination protects those not yet infected", "hepatitis B vaccine", "not applicable"],
  ]],
  ["Communicable Diseases (Ghana)", "buruli ulcer", [
    ["a painless swelling progressing to an ulcer in a riverine community", "refer early for surgical and antibiotic management", "rifampicin and streptomycin", "clinical assessment"],
    ["a buruli ulcer with limited joint movement nearby", "refer early to prevent permanent disability", "not applicable", "not applicable"],
    ["a buruli ulcer treated with herbs for months", "explain the need for early medical treatment", "antibiotic therapy", "not applicable"],
    ["a child with buruli ulcer whose family is far from a facility", "arrange transport and support for treatment", "not applicable", "not applicable"],
    ["a buruli ulcer patient with a large ulcer needing surgery", "refer for surgical management and skin grafting", "not applicable", "not applicable"],
    ["a buruli ulcer patient stigmatised in the community", "educate the community that it is treatable", "not applicable", "not applicable"],
    ["a buruli ulcer patient whose wound is not healing", "review the treatment and the nutrition", "not applicable", "not applicable"],
    ["a community near a river with several buruli ulcer cases", "report the cluster and educate on early presentation", "not applicable", "surveillance report"],
    ["a buruli ulcer patient who has completed treatment", "monitor for recurrence and disability", "not applicable", "not applicable"],
    ["a buruli ulcer patient with a wound needing daily dressing", "teach the family dressing technique for home care", "not applicable", "not applicable"],
  ]],

  // ── Professional Practice & NMC Ghana Code ──────────────────────
  ["Professional Practice & NMC Ghana Code", "professional accountability", [
    ["a colleague collecting money from a patient for free services", "report the conduct to the appropriate authority", "not applicable", "incident report"],
    ["a student nurse asked to perform a procedure beyond their competence", "decline and inform the supervising registered nurse", "not applicable", "competency record"],
    ["a nurse giving a medicine without checking the prescription", "stop and follow the rights of administration", "not applicable", "prescription chart"],
    ["a nurse arriving late and leaving patients unattended", "report on time and ensure a proper handover", "not applicable", "handover record"],
    ["a newly posted nurse left to manage a ward alone", "provide supervision and support", "not applicable", "supervision record"],
    ["a nurse guessing a drug dose rather than asking", "ask for help rather than risk a patient's safety", "not applicable", "not applicable"],
    ["a nurse performing a procedure only a doctor may do", "stop and refer the task to the appropriate professional", "not applicable", "not applicable"],
    ["a nurse's registration not renewed before practice", "renew the registration before continuing to practise", "not applicable", "registration record"],
    ["a nurse delegating a task and never following up", "always follow up on every delegated task", "not applicable", "not applicable"],
    ["a nurse who made an error and fears reporting it", "assess the patient, report honestly and learn from it", "not applicable", "incident report"],
  ]],
  ["Professional Practice & NMC Ghana Code", "confidentiality and consent", [
    ["a nurse discussing a patient's HIV status in the corridor", "stop the discussion and remind the colleague about confidentiality", "not applicable", "not applicable"],
    ["a relative asking for a patient's test results by telephone", "verify identity and consent before disclosing information", "not applicable", "not applicable"],
    ["a patient being prepared for surgery who does not understand the operation", "pause and ask the clinician to re-explain before signing", "not applicable", "consent form"],
    ["a nurse posting a patient's photograph online", "remove it and follow the confidentiality policy", "not applicable", "not applicable"],
    ["patient records left open on a desk in a public area", "secure the records and follow the confidentiality policy", "not applicable", "not applicable"],
    ["a student performing a procedure without the patient's agreement", "obtain consent and explain the student's role", "not applicable", "consent form"],
    ["a patient whose treatment is decided by relatives against her wish", "respect the patient's own informed decision", "not applicable", "not applicable"],
    ["a patient asking whether their information will be shared", "explain the confidentiality policy clearly", "not applicable", "not applicable"],
    ["a nurse sharing patient details on social media", "remove it and follow the confidentiality policy", "not applicable", "not applicable"],
    ["a patient refusing treatment and the family insisting", "respect the patient's right to refuse and inform the provider", "not applicable", "not applicable"],
  ]],
  ["Professional Practice & NMC Ghana Code", "documentation standards", [
    ["an entry in the nurses' notes without the date, time or signature", "complete the record properly and follow facility policy", "not applicable", "nurses' notes"],
    ["a delivery register entry completed hours later from memory", "document contemporaneously, accurately and legibly", "not applicable", "delivery register"],
    ["a record with a crossed-out error and no signature", "follow the policy for correcting an entry", "not applicable", "not applicable"],
    ["care given but not documented at all", "document the care as soon as possible", "not applicable", "not applicable"],
    ["a record with a personal opinion about the patient", "record objective observations instead", "not applicable", "not applicable"],
    ["a partograph with missing fetal heart recordings", "correct the practice and document all observations", "not applicable", "partograph"],
    ["a patient's property lost with no record", "record and safeguard patient property", "not applicable", "property record"],
    ["a monthly report compiled from memory at month end", "record each patient contact immediately and accurately", "not applicable", "facility register"],
    ["a note using abbreviations nobody understands", "use only approved abbreviations and write clearly", "not applicable", "not applicable"],
    ["an emergency managed with no record of the drugs given", "document times, drugs and responses accurately", "not applicable", "not applicable"],
  ]],
  ["Professional Practice & NMC Ghana Code", "cultural competence", [
    ["a patient refusing care from a male nurse for religious reasons", "respect the preference and arrange an alternative where possible", "not applicable", "care plan"],
    ["a family insisting on a traditional practice that endangers the baby", "respect their beliefs while explaining the risk to the baby", "not applicable", "care plan"],
    ["a patient's prayer time ignored during ward care", "accommodate the patient's religious practice", "not applicable", "not applicable"],
    ["a patient who does not speak the local language", "arrange a professional interpreter rather than using a relative", "not applicable", "not applicable"],
    ["a community attributing illness to spiritual causes", "respect their belief while explaining the medical need", "not applicable", "not applicable"],
    ["a patient requesting a special diet for religious reasons", "accommodate the request where it is clinically safe", "not applicable", "not applicable"],
    ["a nurse making fun of a patient's traditional dress", "stop the behaviour and treat the patient with respect", "not applicable", "not applicable"],
    ["a family wanting a traditional healer to see the patient", "allow it where safe while continuing medical care", "not applicable", "not applicable"],
    ["a patient declining a blood transfusion on religious grounds", "respect the refusal and plan alternative care", "not applicable", "not applicable"],
    ["a community health talk given without considering local customs", "plan the talk with the community's customs in mind", "not applicable", "not applicable"],
  ]],
  ["Professional Practice & NMC Ghana Code", "continuing professional development", [
    ["a nurse who has not attended any in-service training this year", "plan and attend approved continuing professional development sessions", "not applicable", "CPD portfolio"],
    ["a midwife who has not updated emergency skills", "attend approved refresher training on emergencies", "not applicable", "CPD portfolio"],
    ["a nurse with a portfolio with no evidence of training", "attend approved training and keep the portfolio current", "not applicable", "CPD portfolio"],
    ["a nurse unaware of the renewal requirements", "find out the requirements and comply before the deadline", "not applicable", "registration record"],
    ["a nurse using outdated practice learned years ago", "update the knowledge through approved training", "not applicable", "not applicable"],
    ["a nurse who cannot access training due to remote posting", "explore online or district-based approved training", "not applicable", "not applicable"],
    ["a nurse asking why CPD is necessary", "explain that it maintains safe, current practice", "not applicable", "not applicable"],
    ["a nurse whose certificate expired last month", "renew it before continuing to practise", "not applicable", "registration record"],
    ["a nurse attending unapproved training and counting it as CPD", "confirm the training is approved before counting it", "not applicable", "CPD portfolio"],
    ["a nurse mentoring a student with no guidance on how", "seek guidance on supervision and mentoring", "not applicable", "not applicable"],
  ]],

  // ── Emergency & Critical Care ───────────────────────────────────
  ["Emergency & Critical Care", "anaphylaxis", [
    ["sudden facial swelling with difficulty breathing after an injection", "give intramuscular adrenaline immediately", "adrenaline 1:1000", "vital signs"],
    ["a patient with a widespread rash, wheeze and hypotension", "give adrenaline and start intravenous fluids", "adrenaline 1:1000", "blood pressure"],
    ["a patient with anaphylaxis whose airway is swelling", "prepare for advanced airway support", "adrenaline", "not applicable"],
    ["a patient with anaphylaxis who received only an antihistamine", "give adrenaline as the first-line treatment", "adrenaline 1:1000", "vital signs"],
    ["a patient with anaphylaxis stabilised and ready for discharge", "teach the patient to avoid the trigger and carry adrenaline", "adrenaline autoinjector", "not applicable"],
    ["a patient with anaphylaxis from a bee sting", "remove the sting and give intramuscular adrenaline", "adrenaline 1:1000", "vital signs"],
    ["a patient with anaphylaxis whose family is panicked", "reassure the family while treating the patient", "not applicable", "not applicable"],
    ["a patient with anaphylaxis and no intravenous access", "give intramuscular adrenaline without delay", "adrenaline 1:1000", "not applicable"],
    ["a patient with anaphylaxis whose observations are not recorded", "monitor closely and document the response", "not applicable", "vital signs"],
    ["a patient with a mild rash only after a medicine", "observe closely as it may progress to anaphylaxis", "not applicable", "not applicable"],
  ]],
  ["Emergency & Critical Care", "hypovolaemic shock", [
    ["a fast weak pulse with cold clammy skin after a road accident", "control the bleeding and give rapid intravenous fluids", "intravenous crystalloids", "haemoglobin level"],
    ["a patient in shock with no obvious bleeding", "assess for internal bleeding and refer urgently", "intravenous fluids", "not applicable"],
    ["a patient in shock with a blood pressure of 78/48 mmHg", "resuscitate and identify the source of the loss", "intravenous fluids and blood", "blood pressure"],
    ["a patient in shock whose urine output is very low", "insert a catheter and monitor the output closely", "urinary catheter", "urine output"],
    ["a patient in shock referred without any fluids given", "stabilise before transfer and send a referral note", "intravenous fluids", "referral note"],
    ["a patient in shock from a ruptured ectopic pregnancy", "resuscitate and arrange emergency surgery", "intravenous fluids and blood", "haemoglobin level"],
    ["a patient in shock whose blood is not available locally", "refer urgently and arrange blood at the receiving unit", "not applicable", "not applicable"],
    ["a patient in shock kept warm and observed closely", "continue resuscitation and reassess frequently", "intravenous fluids", "vital signs"],
    ["a patient in shock with cold peripheries and mottled skin", "recognise the shock and act immediately", "intravenous fluids", "capillary refill"],
    ["a patient in shock whose family is distressed", "brief the family honestly while treating the patient", "not applicable", "not applicable"],
  ]],
  ["Emergency & Critical Care", "status epilepticus", [
    ["a seizure lasting more than five minutes", "protect the airway and give prescribed anticonvulsant", "intravenous diazepam", "blood glucose"],
    ["repeated seizures without regaining consciousness", "treat as status epilepticus and call for help", "intravenous diazepam", "not applicable"],
    ["a seizure in a patient with an unknown glucose", "check the glucose immediately during the event", "intravenous dextrose", "blood glucose"],
    ["a seizing patient with cyanosis", "position on the side and protect the airway", "not applicable", "oxygen saturation"],
    ["a seizing patient whose airway is obstructed", "suction and maintain the airway", "not applicable", "not applicable"],
    ["a seizing patient with a fever and stiff neck", "treat as an infection and refer urgently", "intravenous antibiotics", "not applicable"],
    ["a seizing patient restrained by relatives holding the limbs", "stop the restraint and protect from injury properly", "not applicable", "not applicable"],
    ["a seizing patient with no intravenous access", "give the medicine by the alternative route available", "rectal or buccal diazepam", "not applicable"],
    ["a seizing patient who recovers but remains confused", "monitor closely and reassess the cause", "not applicable", "conscious level"],
    ["a seizing patient referred with no record of the treatment given", "document the times and medicines before transfer", "not applicable", "referral note"],
  ]],
  ["Emergency & Critical Care", "major burns", [
    ["burns over 30 percent of the body surface with blistering", "calculate the fluid needs and insert a urinary catheter", "intravenous fluids", "urine output"],
    ["a burn patient with singed nasal hairs and a hoarse voice", "assess the airway urgently for inhalation injury", "oxygen", "not applicable"],
    ["a burn patient whose wounds were covered with toothpaste at home", "clean the wounds and apply the correct dressing", "not applicable", "not applicable"],
    ["a burn patient with a circumferential burn on the limb", "assess the circulation and refer for possible escharotomy", "not applicable", "not applicable"],
    ["a burn patient with a fever and foul-smelling wounds", "assess for infection and start prescribed antibiotics", "intravenous antibiotics", "wound swab"],
    ["a burn patient with no tetanus immunisation", "give tetanus prophylaxis after cleaning the wound", "tetanus toxoid", "not applicable"],
    ["a burn patient with a low urine output despite fluids", "increase the fluid rate and reassess", "intravenous fluids", "urine output"],
    ["a burn patient who is hypothermic on admission", "warm the patient while continuing resuscitation", "not applicable", "temperature"],
    ["a burn patient in severe pain during dressing", "give adequate analgesia before the procedure", "analgesia", "pain score"],
    ["a burn patient referred with no fluid given", "start fluids before and during transfer", "intravenous fluids", "referral note"],
  ]],
  ["Emergency & Critical Care", "hypoglycaemic coma", [
    ["an unconscious diabetic patient with a blood glucose of 2.2 mmol/L", "give intravenous dextrose and monitor the response", "intravenous 50 percent dextrose", "blood glucose"],
    ["an unconscious patient with a low glucose and no intravenous access", "give glucagon while arranging access", "glucagon", "blood glucose"],
    ["a patient treated for hypoglycaemia who remains unconscious", "repeat the glucose and refer urgently", "intravenous dextrose", "blood glucose"],
    ["a patient with recurrent hypoglycaemia on insulin", "review the insulin doses and the meal pattern", "insulin", "blood glucose"],
    ["a patient with hypoglycaemia who is now awake and refusing admission", "assess the risk and explain the need for observation", "not applicable", "not applicable"],
    ["a patient with hypoglycaemia who is a child and vomiting", "refer for urgent assessment and treatment", "intravenous dextrose", "not applicable"],
    ["a patient with hypoglycaemia and alcohol intake", "treat the glucose and observe for withdrawal", "intravenous dextrose", "not applicable"],
    ["a patient with hypoglycaemia whose family gave water by mouth", "explain the aspiration risk with an unconscious patient", "not applicable", "not applicable"],
    ["a patient with hypoglycaemia with no follow-up appointment", "arrange follow-up and review the treatment", "not applicable", "not applicable"],
    ["a patient with hypoglycaemia whose observations were not recorded", "monitor and document the glucose and the response", "not applicable", "blood glucose"],
  ]],
];
