/**
 * Compact Midwifery clinical dataset (Ghana NMC Midwifery licensing exam).
 * Format: [category, condition, [ [finding, priorityAction, keyDrug, keyLab], ... ]]
 */
export type MidFact = [finding: string, action: string, drug: string, lab: string];

export const MIDWIFERY_DATA: [category: string, condition: string, facts: MidFact[]][] = [
  ["Antenatal Care", "anaemia in pregnancy", [
    ["pallor with a haemoglobin of 8 g/dL at 30 weeks", "give prescribed iron and folate and recheck", "ferrous sulphate", "haemoglobin level"],
    ["breathlessness with pallor at 34 weeks", "assess for severe anaemia and refer", "packed red blood cells", "haemoglobin level"],
    ["a woman taking iron tablets with strong tea", "teach her to separate the tea from the dose", "ferrous sulphate", "haemoglobin level"],
    ["dizziness on standing at an antenatal visit", "check the haemoglobin and blood pressure", "ferrous sulphate", "blood pressure"],
    ["a poor diet with no animal protein", "counsel on iron-rich local foods", "not applicable", "haemoglobin level"],
    ["tiredness limiting her daily activity", "assess the haemoglobin and plan treatment", "ferrous sulphate", "haemoglobin level"],
  ]],
  ["Antenatal Care", "hypertension in pregnancy", [
    ["a blood pressure of 150/100 mmHg at 28 weeks", "monitor closely and assess for proteinuria", "not applicable", "urine protein"],
    ["a blood pressure of 165/112 mmHg with a headache", "start prescribed magnesium sulfate and refer", "magnesium sulfate", "blood pressure"],
    ["swelling of the face and hands in late pregnancy", "assess for pre-eclampsia and refer urgently", "magnesium sulfate", "urine protein"],
    ["a rising blood pressure over two visits", "increase the visit frequency and review", "not applicable", "blood pressure"],
    ["blurred vision with a high reading", "treat as severe pre-eclampsia and refer", "magnesium sulfate", "blood pressure"],
  ]],
  ["Antenatal Care", "malaria in pregnancy", [
    ["fever with chills and a positive blood film at 20 weeks", "give the recommended antimalarial for her gestation", "artemether-lumefantrine", "blood film"],
    ["a woman who has had only one preventive dose by 32 weeks", "give the remaining doses under observation", "sulfadoxine-pyrimethamine", "antenatal card"],
    ["pallor after repeated malaria episodes", "treat the anaemia and prevent further malaria", "ferrous sulphate", "haemoglobin level"],
    ["a woman sleeping without a treated net", "provide a net and teach its correct use", "insecticide-treated net", "not applicable"],
    ["fever with drowsiness and dark urine in pregnancy", "refer urgently for parenteral treatment", "intravenous artesunate", "blood glucose"],
    ["vomiting after an antimalarial dose", "assess tolerance and repeat if within 30 minutes", "artemether-lumefantrine", "blood film"],
  ]],
  ["Antenatal Care", "reduced fetal movement", [
    ["a woman reporting no fetal movement for 12 hours", "ask her to attend immediately for assessment", "not applicable", "cardiotocograph"],
    ["a fetal heart rate of 100 beats per minute", "reposition the woman and refer urgently", "not applicable", "fetal heart rate"],
    ["reduced movements with a small-for-dates abdomen", "refer for ultrasound growth assessment", "not applicable", "obstetric ultrasound"],
    ["a woman anxious about movement patterns at 34 weeks", "teach her to count movements and when to report", "not applicable", "not applicable"],
    ["a positive drug or alcohol history with reduced movement", "counsel sensitively and refer for support", "not applicable", "not applicable"],
  ]],
  ["Antenatal Care", "HIV in pregnancy", [
    ["a newly positive HIV test at booking", "start lifelong antiretroviral therapy and plan infant prophylaxis", "tenofovir-lamivudine-dolutegravir", "viral load"],
    ["a woman afraid to disclose her result to her partner", "offer confidential counselling and support", "not applicable", "not applicable"],
    ["a low viral load late in pregnancy on therapy", "continue therapy and plan a safe delivery", "antiretroviral therapy", "viral load"],
    ["a woman defaulting antiretroviral therapy", "trace her and restart treatment with support", "antiretroviral therapy", "viral load"],
    ["a request to formula feed instead of breastfeeding", "counsel on the national infant feeding guidance", "not applicable", "not applicable"],
  ]],
  ["Normal Labour & Delivery", "normal labour progress", [
    ["cervical dilation crossing the alert line on the partograph", "review the cause and refer if there is no progress", "not applicable", "partograph"],
    ["contractions lasting 20 seconds every 15 minutes", "assess progress and support the woman", "not applicable", "partograph"],
    ["a woman lying flat on her back in established labour", "encourage an upright or left lateral position", "not applicable", "partograph"],
    ["a full bladder palpated in active labour", "encourage her to pass urine to aid progress", "not applicable", "urine output"],
    ["membranes ruptured for 12 hours with no fever", "monitor the fetal heart and the mother's temperature", "not applicable", "temperature"],
    ["the urge to bear down before full dilation", "discourage pushing and assess the cervix", "not applicable", "vaginal examination"],
  ]],
  ["Normal Labour & Delivery", "fetal distress in labour", [
    ["a fetal heart rate of 170 beats per minute", "reposition the woman and assess the cause", "not applicable", "fetal heart rate"],
    ["meconium-stained liquor with a normal heart rate", "monitor the fetus closely and prepare for resuscitation", "not applicable", "liquor assessment"],
    ["late decelerations on the fetal heart trace", "stop any oxytocin and reposition the woman", "not applicable", "fetal heart rate"],
    ["a fetal heart rate not heard for 20 minutes", "use a doppler or refer for urgent assessment", "not applicable", "cardiotocograph"],
    ["thick meconium with a slow fetal heart rate", "prepare for emergency delivery and resuscitation", "not applicable", "fetal heart rate"],
  ]],
  ["Normal Labour & Delivery", "third stage of labour", [
    ["a slow trickle of blood after the baby is born", "give the prescribed uterotonic and check the uterus", "oxytocin", "blood loss"],
    ["the placenta not delivered 40 minutes after the baby", "refer for manual removal of the placenta", "intravenous fluids", "blood loss"],
    ["a soft boggy uterus after the third stage", "massage the uterus and give a uterotonic", "oxytocin", "blood loss"],
    ["a cord that stops pulsating after delivery", "clamp and cut the cord then deliver the placenta", "oxytocin", "not applicable"],
    ["heavy bleeding with clots after the placenta", "assess for tears and retained products", "intravenous fluids", "haemoglobin level"],
  ]],
  ["Normal Labour & Delivery", "immediate newborn care", [
    ["a newborn with a good cry but cold feet", "dry and warm the baby with skin-to-skin contact", "not applicable", "temperature"],
    ["a baby not breathing well at one minute of life", "start bag and mask ventilation within the golden minute", "oxygen", "Apgar score"],
    ["a baby whose cord is cut with a dirty blade", "assess for infection and teach clean cord care", "chlorhexidine gel", "not applicable"],
    ["a newborn not fed within the first hour", "support early breastfeeding within one hour of birth", "not applicable", "not applicable"],
    ["a baby with only two cord vessels seen", "document the finding and refer the baby for review", "not applicable", "newborn examination"],
    ["a newborn given glucose water instead of the breast", "stop the practice and support breastfeeding", "not applicable", "not applicable"],
  ]],
  ["Obstetric Emergencies", "postpartum haemorrhage", [
    ["blood loss over 500 mL within 24 hours of delivery", "call for help and give the prescribed uterotonic", "oxytocin", "haemoglobin level"],
    ["a torn perineum with active bleeding after delivery", "apply pressure and arrange immediate repair", "not applicable", "haemoglobin level"],
    ["continuous oozing with no firm clot forming", "assess for a clotting problem and refer urgently", "blood products", "coagulation profile"],
    ["a rising pulse with a falling blood pressure after delivery", "treat for shock and give intravenous fluids", "intravenous fluids", "vital signs"],
    ["a retained placenta with ongoing bleeding", "refer for manual removal of the placenta", "intravenous fluids", "blood loss"],
    ["heavy bleeding with a firm contracted uterus", "assess for tears or retained tissue", "not applicable", "haemoglobin level"],
  ]],
  ["Obstetric Emergencies", "eclampsia", [
    ["a convulsing woman in the labour ward at term", "protect from injury and give magnesium sulfate", "magnesium sulfate", "blood pressure"],
    ["a fit followed by drowsiness and a high blood pressure", "position on the side and continue magnesium therapy", "magnesium sulfate", "blood pressure"],
    ["a respiratory rate of 10 on magnesium sulfate therapy", "stop the infusion and give calcium gluconate", "calcium gluconate", "respiratory rate"],
    ["absent knee reflexes on magnesium sulfate therapy", "withhold the next dose and assess the level", "calcium gluconate", "reflex assessment"],
    ["a urine output below 25 mL per hour on magnesium therapy", "reduce the dose and monitor renal function", "not applicable", "urine output"],
  ]],
  ["Obstetric Emergencies", "shoulder dystocia", [
    ["the head delivered but the shoulders not following", "call for help and flex the mother's hips", "not applicable", "delivery record"],
    ["the anterior shoulder trapped behind the pubic bone", "apply suprapubic pressure with the hips flexed", "not applicable", "delivery record"],
    ["a delay between the head and body over one minute", "call for emergency help and use the manoeuvres", "not applicable", "not applicable"],
    ["a large baby with a difficult delivery of the head", "anticipate shoulder dystocia and prepare for help", "not applicable", "not applicable"],
    ["a baby born flat and limp after a difficult delivery", "resuscitate the newborn and check for injury", "not applicable", "Apgar score"],
  ]],
  ["Obstetric Emergencies", "cord prolapse", [
    ["a pulsating cord felt at the introitus after rupture", "elevate the presenting part and call for help", "not applicable", "fetal heart rate"],
    ["a cord seen at the vulva with a slowing fetal heart", "position knee-to-chest and prepare for delivery", "not applicable", "fetal heart rate"],
    ["a cord prolapse in a facility that cannot operate", "stabilise and arrange an immediate emergency referral", "not applicable", "referral note"],
    ["a cord prolapse with the mother lying flat on her back", "reposition her and relieve pressure on the cord", "not applicable", "fetal heart rate"],
    ["a cord prolapse during a vaginal examination", "do not remove the hand and call for help", "not applicable", "fetal heart rate"],
  ]],
  ["Obstetric Emergencies", "uterine rupture", [
    ["severe abdominal pain with loss of the fetal heart rate", "resuscitate and prepare for immediate surgery", "intravenous fluids and blood", "haemoglobin level"],
    ["a scar dehiscence with abdominal tenderness in labour", "stop labour and refer for emergency surgery", "intravenous fluids", "partograph"],
    ["a woman with a previous caesarean and sudden pain", "assess the fetal heart and refer urgently", "not applicable", "fetal heart rate"],
    ["vaginal bleeding with a loss of contractions in labour", "assess for rupture and prepare for laparotomy", "intravenous fluids and blood", "haemoglobin level"],
    ["a rising pulse with abdominal distension in labour", "assess for rupture and call for help", "intravenous fluids", "vital signs"],
  ]],
  ["Puerperium & Postnatal Care", "puerperal sepsis", [
    ["fever with foul-smelling lochia on day four", "start prescribed antibiotics and monitor for shock", "intravenous antibiotics", "full blood count"],
    ["lower abdominal pain with a high temperature", "assess for sepsis and refer for treatment", "intravenous antibiotics", "full blood count"],
    ["a mother with a fast pulse and confusion after delivery", "treat as sepsis and call for help", "intravenous fluids", "vital signs"],
    ["a caesarean wound with pus and redness", "take a swab and give prescribed antibiotics", "intravenous antibiotics", "wound swab"],
    ["a mother with a foul discharge and pelvic pain", "assess for retained products and refer", "not applicable", "ultrasound"],
    ["a mother discharged without postnatal education", "teach the danger signs and when to return", "not applicable", "not applicable"],
  ]],
  ["Puerperium & Postnatal Care", "postpartum depression", [
    ["a mother tearful and refusing to care for the baby", "screen her and involve the family in support", "sertraline", "screening score"],
    ["a mother saying she cannot bond with her baby", "assess her mood and refer for support", "not applicable", "screening score"],
    ["a mother with thoughts of harming herself after delivery", "assess the risk urgently and keep her safe", "not applicable", "risk assessment"],
    ["a mother with insomnia and agitation beyond two weeks", "refer for mental health review", "not applicable", "screening score"],
    ["a mother hiding her low mood from the family", "offer confidential support and counselling", "not applicable", "not applicable"],
    ["a mother with no support at home after delivery", "arrange community follow-up and family education", "not applicable", "not applicable"],
  ]],
  ["Puerperium & Postnatal Care", "breast problems postpartum", [
    ["a red painful swollen breast with fever", "support continued feeding and give antibiotics", "cloxacillin", "not applicable"],
    ["a fluctuant painful lump in the breast", "refer for drainage and feed from the other side", "intravenous antibiotics", "not applicable"],
    ["cracked bleeding nipples with pain on feeding", "correct the positioning and attachment", "not applicable", "not applicable"],
    ["hard painful breasts with difficulty latching", "support frequent feeding and express before latching", "not applicable", "not applicable"],
    ["a blocked duct with a palpable lump", "encourage feeding on the affected side and warmth", "not applicable", "not applicable"],
    ["a mother stopping feeding because of pain", "support her to continue with correct technique", "not applicable", "not applicable"],
  ]],
  ["Newborn Care", "neonatal hypothermia", [
    ["a newborn with cold feet and a temperature of 35.8 degrees", "warm the baby with skin-to-skin contact and a cap", "not applicable", "temperature"],
    ["a wet newborn left on a cold surface at delivery", "dry the baby immediately and keep it warm", "not applicable", "temperature"],
    ["a baby bathed soon after birth in a cold room", "delay the bath and keep the baby warm", "not applicable", "temperature"],
    ["a low birth weight baby with cold extremities", "use kangaroo mother care for warmth", "not applicable", "temperature"],
    ["a baby separated from the mother for observations", "reunite the baby for warmth and breastfeeding", "not applicable", "not applicable"],
    ["a baby in a cold labour ward with no cap", "put a cap on the baby and cover the head", "not applicable", "temperature"],
  ]],
  ["Newborn Care", "neonatal jaundice", [
    ["yellow palms and soles on the second day", "refer urgently for bilirubin measurement", "phototherapy", "serum bilirubin"],
    ["a jaundiced baby who is sleepy and feeding poorly", "refer urgently and support feeding", "phototherapy", "serum bilirubin"],
    ["jaundice appearing in the first 24 hours of life", "treat as pathological and refer immediately", "phototherapy", "serum bilirubin"],
    ["a baby under phototherapy with loose green stools", "reassure the mother and protect the baby's eyes", "phototherapy", "not applicable"],
    ["a baby with a rising bilirubin despite phototherapy", "prepare for exchange transfusion", "exchange transfusion", "serum bilirubin"],
    ["a mother using herbs to treat the baby's jaundice", "explain the danger and refer for proper treatment", "phototherapy", "serum bilirubin"],
  ]],
  ["Newborn Care", "low birth weight baby", [
    ["a baby weighing 1.7 kg who is feeding slowly", "support kangaroo mother care and supervised feeding", "expressed breast milk", "daily weight"],
    ["a preterm baby unable to suck effectively", "feed by nasogastric tube with expressed breast milk", "expressed breast milk", "daily weight"],
    ["a low birth weight baby with a low body temperature", "warm with kangaroo care and monitor the temperature", "not applicable", "temperature"],
    ["a baby losing more than ten percent of birth weight", "assess feeding and refer for review", "expressed breast milk", "daily weight"],
    ["a mother of twins unable to feed both babies", "support a feeding plan and involve the family", "expressed breast milk", "infant weight"],
    ["a small baby discharged with no follow-up plan", "arrange community follow-up and growth monitoring", "not applicable", "growth chart"],
  ]],
  ["Newborn Care", "newborn feeding problems", [
    ["a newborn fed only twice in twelve hours of life", "support feeding at least eight times in 24 hours", "not applicable", "not applicable"],
    ["a baby taking only the nipple with a narrow mouth", "teach the mother correct attachment", "not applicable", "not applicable"],
    ["a mother giving water and herbs to her newborn", "counsel on exclusive breastfeeding for six months", "not applicable", "not applicable"],
    ["a baby with a cleft palate unable to latch", "teach alternative feeding positions and refer", "expressed breast milk", "infant weight"],
    ["a mother discarding the first yellow milk", "teach that colostrum protects the baby", "not applicable", "not applicable"],
    ["a baby not passing meconium within 24 hours", "assess for obstruction and refer", "not applicable", "abdominal examination"],
  ]],
  ["Family Planning", "contraceptive counselling", [
    ["a woman over 35 who smokes requesting combined pills", "explain the risks and offer a progestogen-only method", "progestogen-only pill", "blood pressure"],
    ["a client given a method with no counselling at all", "provide full counselling and document informed choice", "not applicable", "consent form"],
    ["a woman with sickle cell disease seeking contraception", "counsel on methods safe for her condition", "not applicable", "haemoglobin level"],
    ["a mother under six weeks postpartum given combined pills", "switch to a method that does not affect milk supply", "progestogen-only pill", "not applicable"],
    ["a couple requesting permanent contraception after one child", "counsel thoroughly about permanence before consent", "not applicable", "consent form"],
    ["a teenager afraid to ask for contraception", "provide confidential and non-judgemental counselling", "not applicable", "not applicable"],
  ]],
  ["Family Planning", "contraceptive side effects", [
    ["prolonged irregular bleeding after a depot injection", "reassure, review and counsel on expected effects", "depot medroxyprogesterone", "haemoglobin level"],
    ["severe pelvic pain after an intrauterine device insertion", "assess for perforation or infection and refer", "not applicable", "pelvic examination"],
    ["a client stopping a method because of bleeding", "counsel on side effects before starting the method", "not applicable", "not applicable"],
    ["a client arriving two weeks late for a repeat injection", "exclude pregnancy before repeating the injection", "depot medroxyprogesterone", "pregnancy test"],
    ["a client who felt the device come out on its own", "assess for pregnancy and counsel on replacement", "not applicable", "pregnancy test"],
    ["a client with a severe headache on combined pills", "assess the blood pressure and review the method", "not applicable", "blood pressure"],
  ]],
  ["Gynaecology & Women's Health", "ectopic pregnancy", [
    ["severe one-sided pain with a positive pregnancy test and fainting", "resuscitate and refer for emergency surgery", "intravenous fluids and blood", "pregnancy test"],
    ["shoulder tip pain with collapse in early pregnancy", "treat for a ruptured ectopic and call for help", "intravenous fluids and blood", "haemoglobin level"],
    ["light bleeding with one-sided pain at six weeks", "refer for urgent ultrasound assessment", "not applicable", "obstetric ultrasound"],
    ["a woman with a previous ectopic and new pain", "assess urgently and refer for review", "not applicable", "pregnancy test"],
    ["a woman collapsing at home in early pregnancy", "treat for shock and arrange emergency transfer", "intravenous fluids", "vital signs"],
  ]],
  ["Gynaecology & Women's Health", "miscarriage", [
    ["heavy bleeding with cramps and an open cervix", "resuscitate and refer for evacuation", "intravenous fluids", "haemoglobin level"],
    ["heavy bleeding and fever after an unsafe abortion", "treat infection and refer for surgical review", "intravenous antibiotics", "full blood count"],
    ["a mother grieving a miscarriage and blaming herself", "counsel her sensitively and support the family", "not applicable", "not applicable"],
    ["light spotting at eight weeks with a closed cervix", "arrange an ultrasound and advise rest", "not applicable", "obstetric ultrasound"],
    ["a woman with repeated miscarriages asking why", "counsel and refer both partners for assessment", "not applicable", "not applicable"],
  ]],
  ["Gynaecology & Women's Health", "pelvic inflammatory disease", [
    ["lower abdominal pain with fever and a vaginal discharge", "treat both partners using the syndromic approach", "ceftriaxone and doxycycline", "syndromic assessment"],
    ["a client with pelvic pain and a new sexual partner", "treat, counsel on partner treatment and prevention", "ceftriaxone", "not applicable"],
    ["a woman with pelvic pain becoming septic", "refer urgently for intravenous therapy", "intravenous antibiotics", "vital signs"],
    ["a client with recurring pelvic inflammatory disease", "counsel on prevention and screen the partner", "not applicable", "not applicable"],
    ["a woman with pelvic pain and a missed period", "exclude an ectopic pregnancy urgently", "not applicable", "pregnancy test"],
    ["a client with a discharge afraid of a HIV test", "offer pre-test counselling and screening", "not applicable", "HIV rapid test"],
  ]],
];
