/** Topic seeds for the Midwifery licensing examination question bank. */
export type MidwiferyTopic = {
  name: string;
  finding: string;
  action: string;
  drug: string;
  lab: string;
};

export const MIDWIFERY_CATEGORIES: {
  category: string;
  clientNeed: string;
  topics: MidwiferyTopic[];
}[] = [
  {
    category: "Antenatal Care",
    clientNeed: "Midwifery Practice",
    topics: [
      { name: "booking history taking", finding: "a woman who cannot remember her last menstrual period", action: "establish the gestational age using an early ultrasound", drug: "not applicable", lab: "obstetric ultrasound" },
      { name: "anaemia in pregnancy", finding: "pallor with a haemoglobin below 9 g/dL at 30 weeks", action: "give prescribed iron and folate and reassess the haemoglobin", drug: "ferrous sulphate and folic acid", lab: "haemoglobin level" },
      { name: "malaria prophylaxis in pregnancy", finding: "a pregnant woman who has not taken intermittent preventive treatment", action: "administer the scheduled sulfadoxine-pyrimethamine dose", drug: "sulfadoxine-pyrimethamine", lab: "blood film" },
      { name: "tetanus immunisation in pregnancy", finding: "a woman with no previous tetanus immunisation", action: "give the first tetanus toxoid dose and plan the schedule", drug: "tetanus toxoid", lab: "immunisation card" },
      { name: "syphilis screening in pregnancy", finding: "a positive rapid syphilis test at booking", action: "treat the woman and screen her partner", drug: "benzathine penicillin", lab: "rapid syphilis test" },
      { name: "urinary tract infection in pregnancy", finding: "burning on passing urine with frequency at 22 weeks", action: "collect a midstream specimen and give prescribed antibiotics", drug: "nitrofurantoin", lab: "urinalysis" },
      { name: "hyperemesis gravidarum", finding: "persistent vomiting with ketones in the urine and weight loss", action: "admit, rehydrate and give prescribed antiemetics", drug: "intravenous fluids and ondansetron", lab: "urine ketones" },
      { name: "fetal movement counting", finding: "a woman reporting reduced fetal movement at 36 weeks", action: "ask her to attend immediately for fetal heart assessment", drug: "not applicable", lab: "cardiotocograph" },
      { name: "abdominal examination in pregnancy", finding: "a fundal height smaller than the gestational age", action: "refer for ultrasound to assess fetal growth", drug: "not applicable", lab: "obstetric ultrasound" },
      { name: "danger signs in pregnancy education", finding: "a woman who does not know the pregnancy danger signs", action: "teach the danger signs and when to seek help", drug: "not applicable", lab: "antenatal card" },
      { name: "rhesus negative pregnancy", finding: "a rhesus negative woman with a sensitising event", action: "administer anti-D immunoglobulin as prescribed", drug: "anti-D immunoglobulin", lab: "Kleihauer test" },
      { name: "gestational diabetes screening", finding: "persistent glycosuria with a big-for-dates fetus", action: "refer for an oral glucose tolerance test", drug: "insulin", lab: "oral glucose tolerance test" },
    ],
  },
  {
    category: "Normal Labour & Delivery",
    clientNeed: "Intrapartum Care",
    topics: [
      { name: "the partograph", finding: "cervical dilation crossing to the right of the alert line", action: "review the cause and refer if there is no progress", drug: "not applicable", lab: "partograph" },
      { name: "fetal heart monitoring", finding: "a fetal heart rate above 160 beats per minute for a prolonged period", action: "reposition the woman and assess for fetal distress", drug: "not applicable", lab: "fetal heart rate chart" },
      { name: "meconium-stained liquor", finding: "green-stained amniotic fluid at the onset of labour", action: "monitor the fetus closely and prepare for resuscitation", drug: "not applicable", lab: "liquor assessment" },
      { name: "active management of the third stage", finding: "a slow trickle of blood after delivery of the baby", action: "give the prescribed uterotonic and deliver the placenta by controlled cord traction", drug: "oxytocin", lab: "blood loss estimation" },
      { name: "episiotomy and perineal tear repair", finding: "a second-degree perineal tear after delivery", action: "arrange repair with adequate analgesia and asepsis", drug: "lignocaine", lab: "wound assessment" },
      { name: "immediate newborn care", finding: "a newborn with a good cry but cold extremities", action: "dry and warm the baby with immediate skin-to-skin contact", drug: "not applicable", lab: "temperature" },
      { name: " cord care", finding: "a family applying herbs to the umbilical stump", action: "teach clean, dry cord care and the danger of infection", drug: "chlorhexidine gel", lab: "cord assessment" },
      { name: "assessing labour progress", finding: "membranes ruptured for many hours with no progress", action: "assess for obstruction and refer if there is no progress", drug: "not applicable", lab: "partograph" },
      { name: "pain relief in labour", finding: "a woman in severe pain requesting help in established labour", action: "offer support, positioning and prescribed analgesia", drug: "pentazocine", lab: "vital signs" },
      { name: "delivery of the placenta", finding: "the placenta not delivered 40 minutes after the baby", action: "assess for retained placenta and refer for manual removal", drug: "intravenous fluids", lab: "blood loss" },
      { name: "vesicovaginal examination during labour", finding: "a cervix that is 6 cm dilated with the head not engaged", action: "assess caput and moulding and refer if obstructed", drug: "not applicable", lab: "vaginal examination" },
      { name: "preparing the delivery room", finding: "no sterile delivery pack ready in an imminent delivery", action: "prepare a sterile field quickly while reassuring the woman", drug: "not applicable", lab: "delivery register" },
    ],
  },
  {
    category: "Obstetric Emergencies",
    clientNeed: "Emergency Midwifery Care",
    topics: [
      { name: "primary postpartum haemorrhage", finding: "more than 500 mL of blood loss within 24 hours of delivery", action: "call for help, massage the uterus and give uterotonics", drug: "oxytocin and ergometrine", lab: "haemoglobin level" },
      { name: "secondary postpartum haemorrhage", finding: "heavy bleeding with foul-smelling lochia at day ten", action: "treat infection and refer for retained products assessment", drug: "intravenous antibiotics", lab: "haemoglobin level" },
      { name: "eclamptic fit", finding: "a convulsing pregnant woman in the labour ward", action: "protect from injury, position on the side and give magnesium sulfate", drug: "magnesium sulfate", lab: "blood pressure" },
      { name: "shoulder dystocia", finding: "the head delivered but the shoulders not following", action: "call for help and perform the manoeuvres for shoulder dystocia", drug: "not applicable", lab: "delivery record" },
      { name: "cord prolapse", finding: "a pulsating cord felt at the introitus after membrane rupture", action: "elevate the presenting part and prepare for emergency delivery", drug: "not applicable", lab: "fetal heart rate" },
      { name: "uterine rupture", finding: "severe abdominal pain with loss of fetal heart sounds in a previous caesarean", action: "resuscitate and prepare for immediate laparotomy", drug: "intravenous fluids and blood", lab: "haemoglobin level" },
      { name: "retained placenta", finding: "a placenta retained for over one hour with bleeding", action: "refer for manual removal of the placenta", drug: "intravenous fluids", lab: "blood loss" },
      { name: "placenta praevia", finding: "painless bright red bleeding in the third trimester", action: "avoid vaginal examination and refer immediately", drug: "intravenous fluids", lab: "obstetric ultrasound" },
      { name: "abruptio placentae", finding: "a tense tender uterus with dark bleeding and fetal distress", action: "prepare for emergency delivery and monitor clotting", drug: "intravenous fluids and blood", lab: "coagulation profile" },
      { name: "obstructed labour", finding: "a moulded head with no dilation for many hours and an exhausted mother", action: "resuscitate and refer for emergency caesarean section", drug: "intravenous fluids and antibiotics", lab: "partograph" },
      { name: "inversion of the uterus", finding: "a mass at the introitus with severe shock after delivery", action: "call for help and do not attempt to replace it yourself", drug: "intravenous fluids", lab: "vital signs" },
      { name: "sepsis after delivery", finding: "fever with a foul-smelling discharge and abdominal pain", action: "start prescribed antibiotics and monitor for septic shock", drug: "intravenous clindamycin and gentamicin", lab: "full blood count" },
    ],
  },
  {
    category: "Puerperium & Postnatal Care",
    clientNeed: "Postnatal Care",
    topics: [
      { name: "normal involution of the uterus", finding: "a uterus not contracting well on the third postnatal day", action: "assess for retained products and massage the uterus", drug: "oxytocin", lab: "uterine assessment" },
      { name: "postnatal depression", finding: "a mother who is tearful and refuses to breastfeed on day five", action: "screen her, provide support and involve the family", drug: "sertraline", lab: "screening score" },
      { name: "puerperal sepsis", finding: "fever with lower abdominal pain and foul lochia", action: "start prescribed antibiotics and monitor for septic shock", drug: "intravenous antibiotics", lab: "full blood count" },
      { name: "breast engorgement", finding: "painful hard breasts with difficulty latching the baby", action: "support frequent feeding and express before latching", drug: "not applicable", lab: "not applicable" },
      { name: "cracked nipples", finding: "bleeding nipples with pain during feeding", action: "correct the positioning and attachment of the baby", drug: "not applicable", lab: "not applicable" },
      { name: "postnatal family planning counselling", finding: "a mother asking when she can start a contraceptive method", action: "counsel on options and respect her informed choice", drug: "progestogen-only pill", lab: "not applicable" },
      { name: "postnatal wound infection", finding: "a caesarean wound with redness and purulent discharge", action: "take a swab and give prescribed antibiotics", drug: "intravenous antibiotics", lab: "wound swab" },
      { name: "perineal wound care", finding: "a swollen painful perineal wound with sutures", action: "provide hygiene, analgesia and review the wound", drug: "analgesia", lab: "wound assessment" },
      { name: "venous thromboembolism after delivery", finding: "a painful swollen calf with breathlessness postnatally", action: "refer urgently for assessment and start prophylaxis as prescribed", drug: "low molecular weight heparin", lab: "Doppler ultrasound" },
      { name: "postnatal visit schedule", finding: "a mother and baby who have not been seen since discharge", action: "trace the family and complete the postnatal visits", drug: "not applicable", lab: "postnatal register" },
      { name: "resumption of menstruation and fertility", finding: "a mother believing she cannot conceive while breastfeeding", action: "explain that breastfeeding is not a reliable contraceptive", drug: "not applicable", lab: "not applicable" },
      { name: "newborn danger signs teaching", finding: "a mother who cannot name any newborn danger signs", action: "teach the danger signs and when to return to the facility", drug: "not applicable", lab: "child health record" },
    ],
  },
  {
    category: "Newborn Care",
    clientNeed: "Neonatal Care",
    topics: [
      { name: "neonatal resuscitation", finding: "a newborn with gasping breathing at one minute", action: "start bag and mask ventilation within the golden minute", drug: "oxygen", lab: "Apgar score" },
      { name: "hypothermia in a newborn", finding: "a baby with cold feet and a temperature below 36.5 degrees", action: "warm the baby using skin-to-skin contact and a cap", drug: "not applicable", lab: "temperature" },
      { name: "neonatal sepsis", finding: "a baby who is feeding poorly with a low temperature", action: "refer urgently for parenteral antibiotics", drug: "intravenous ampicillin and gentamicin", lab: "blood culture" },
      { name: "neonatal jaundice", finding: "yellow palms and soles with a lethargic baby", action: "refer for phototherapy and bilirubin measurement", drug: "phototherapy", lab: "serum bilirubin" },
      { name: "low birth weight care", finding: "a baby weighing 1.8 kg who is feeding slowly", action: "support kangaroo mother care and supervised feeding", drug: "expressed breast milk", lab: "daily weight" },
      { name: "neonatal hypoglycaemia", finding: "a jittery baby with a low blood glucose", action: "feed the baby and recheck the glucose urgently", drug: "expressed breast milk or dextrose", lab: "blood glucose" },
      { name: "Bcg and birth immunisation", finding: "a baby discharged without immunisation", action: "give BCG and oral polio vaccine and complete the card", drug: "BCG and oral polio vaccine", lab: "immunisation card" },
      { name: "neonatal convulsions", finding: "repetitive twitching of a newborn's limbs", action: "check the blood glucose and refer urgently", drug: "intravenous dextrose or anticonvulsant", lab: "blood glucose" },
      { name: "congenital abnormalities recognition", finding: "a newborn with an obvious neural tube defect on the back", action: "cover with a sterile dressing and refer for surgery", drug: "not applicable", lab: "clinical assessment" },
      { name: "preterm baby feeding", finding: "a preterm baby unable to suck effectively", action: "feed by nasogastric tube with expressed breast milk", drug: "expressed breast milk", lab: "daily weight" },
      { name: "necrotising enterocolitis", finding: "abdominal distension with blood in the stool of a preterm baby", action: "stop feeds and refer urgently for review", drug: "intravenous antibiotics", lab: "abdominal x-ray" },
      { name: "newborn screening and examination", finding: "a baby not examined for hip and heart problems before discharge", action: "complete a full newborn examination before discharge", drug: "not applicable", lab: "newborn examination" },
    ],
  },
  {
    category: "Breastfeeding & Infant Feeding",
    clientNeed: "Infant and Young Child Feeding",
    topics: [
      { name: "correct attachment for breastfeeding", finding: "a baby taking only the nipple with a wide open mouth", action: "help the mother reposition for correct attachment", drug: "not applicable", lab: "feeding assessment" },
      { name: "exclusive breastfeeding", finding: "a mother giving water and glucose to her newborn", action: "counsel her on exclusive breastfeeding for six months", drug: "not applicable", lab: "infant weight" },
      { name: "insufficient milk concerns", finding: "a mother worried that her baby is not getting enough milk", action: "assess feeding frequency and the baby's weight and urine output", drug: "not applicable", lab: "infant weight" },
      { name: "expressing and storing breast milk", finding: "a mother returning to work who needs to express", action: "teach safe expression and storage of breast milk", drug: "not applicable", lab: "not applicable" },
      { name: "mastitis", finding: "a red painful swollen breast with fever", action: "support continued feeding and give prescribed antibiotics", drug: "cloxacillin", lab: "not applicable" },
      { name: "breast abscess", finding: "a fluctuant painful lump in the breast with fever", action: "refer for drainage and support feeding from the other breast", drug: "intravenous antibiotics", lab: "clinical assessment" },
      { name: "feeding a baby with a cleft lip or palate", finding: "a newborn with a cleft palate unable to latch", action: "teach alternative feeding positions and refer for surgery", drug: "expressed breast milk", lab: "infant weight" },
      { name: "HIV and infant feeding", finding: "an HIV-positive mother asking how to feed her baby safely", action: "counsel her according to national guidelines on exclusive breastfeeding with antiretroviral therapy", drug: "antiretroviral therapy", lab: "viral load" },
      { name: "complementary feeding introduction", finding: "a mother introducing cereal at two months", action: "explain exclusive breastfeeding until six months", drug: "not applicable", lab: "growth chart" },
      { name: "baby-friendly hospital practices", finding: "glucose water given to a healthy newborn in the ward", action: "stop the practice and support immediate breastfeeding", drug: "not applicable", lab: "feeding record" },
      { name: "poor weight gain in a breastfed baby", finding: "a baby below birth weight at two weeks", action: "assess attachment, frequency and refer for review", drug: "not applicable", lab: "infant weight" },
      { name: "relactation support", finding: "a mother who stopped breastfeeding and wants to restart", action: "support relactation with frequent skin-to-skin and suckling", drug: "not applicable", lab: "infant weight" },
    ],
  },
  {
    category: "Family Planning",
    clientNeed: "Reproductive Health Services",
    topics: [
      { name: "intrauterine contraceptive device insertion", finding: "severe pelvic pain after an intrauterine device insertion", action: "assess for perforation or infection and refer if needed", drug: "not applicable", lab: "pelvic examination" },
      { name: "combined oral contraceptive counselling", finding: "a woman over 35 who smokes requesting combined pills", action: "explain the risks and offer a progestogen-only method", drug: "progestogen-only pill", lab: "blood pressure" },
      { name: "implanon insertion and removal", finding: "a patient requesting implant removal after two years", action: "counsel and arrange removal with informed consent", drug: "etonogestrel implant", lab: "not applicable" },
      { name: "injectable contraception side effects", finding: "prolonged irregular bleeding after a depot injection", action: "reassure, review and counsel on the expected effects", drug: "depot medroxyprogesterone", lab: "haemoglobin level" },
      { name: "emergency contraception", finding: "a woman presenting within 72 hours of unprotected intercourse", action: "counsel and give emergency contraception as prescribed", drug: "levonorgestrel", lab: "not applicable" },
      { name: "postpartum intrauterine device", finding: "a woman wanting immediate contraception after delivery", action: "counsel on timing, benefits and complications", drug: "intrauterine contraceptive device", lab: "not applicable" },
      { name: "condom promotion and dual protection", finding: "a patient using only hormonal contraception with a new partner", action: "counsel on dual protection against sexually transmitted infections", drug: "condoms", lab: "not applicable" },
      { name: "voluntary sterilisation counselling", finding: "a couple requesting permanent contraception", action: "provide thorough counselling and obtain informed written consent", drug: "not applicable", lab: "consent form" },
      { name: "contraceptive failure and pregnancy", finding: "a pregnant woman who had an intrauterine device in place", action: "refer for assessment of the device location", drug: "not applicable", lab: "obstetric ultrasound" },
      { name: "contraception after an abortion", finding: "a woman wanting to avoid another unintended pregnancy", action: "counsel and provide a method before discharge", drug: "chosen method", lab: "not applicable" },
      { name: "missed injectable appointment", finding: "a patient arriving two weeks late for a repeat injection", action: "assess for pregnancy before repeating the injection", drug: "depot medroxyprogesterone", lab: "pregnancy test" },
      { name: "lactational amenorrhoea method", finding: "a mother asking about the breastfeeding method", action: "explain the strict criteria required for it to work", drug: "not applicable", lab: "not applicable" },
    ],
  },
  {
    category: "Malaria & Infections in Pregnancy",
    clientNeed: "Midwifery Practice",
    topics: [
      { name: "malaria in the first trimester", finding: "fever with a positive blood film at nine weeks", action: "treat with the recommended first-trimester antimalarial", drug: "quinine", lab: "blood film" },
      { name: "malaria in the second and third trimester", finding: "fever with a positive test at 32 weeks", action: "give the recommended antimalarial and monitor the fetus", drug: "artemether-lumefantrine", lab: "blood film" },
      { name: "severe malaria in pregnancy", finding: "fever with confusion and dark urine in a pregnant woman", action: "refer urgently for parenteral therapy and glucose monitoring", drug: "intravenous artesunate", lab: "blood glucose" },
      { name: "anaemia from malaria in pregnancy", finding: "pallor with a haemoglobin of 7 g/dL at 28 weeks", action: "treat the malaria and give iron and folate therapy", drug: "ferrous sulphate and folic acid", lab: "haemoglobin level" },
      { name: "HIV in pregnancy and PMTCT", finding: "a newly positive HIV test at antenatal clinic", action: "start lifelong antiretroviral therapy and plan infant prophylaxis", drug: "tenofovir-lamivudine-dolutegravir", lab: "viral load" },
      { name: "syphilis in pregnancy", finding: "a positive syphilis screen with no treatment given", action: "treat with benzathine penicillin and screen the partner", drug: "benzathine penicillin", lab: "rapid syphilis test" },
      { name: "tuberculosis in pregnancy", finding: "a chronic cough with weight loss in a pregnant woman", action: "screen for tuberculosis and start prescribed treatment", drug: "rifampicin-based therapy", lab: "sputum AFB" },
      { name: "hepatitis B in pregnancy", finding: "a positive hepatitis B surface antigen at booking", action: "plan newborn immunoprophylaxis at birth", drug: "hepatitis B immunoglobulin and vaccine", lab: "hepatitis B surface antigen" },
      { name: "insecticide-treated net use in pregnancy", finding: "a pregnant woman sleeping without a treated net", action: "provide a treated net and teach its correct use", drug: "insecticide-treated net", lab: "not applicable" },
      { name: "genital tract infection in pregnancy", finding: "an abnormal vaginal discharge with itching", action: "assess, treat according to guidelines and screen the partner", drug: "metronidazole", lab: "high vaginal swab" },
      { name: "pyelonephritis in pregnancy", finding: "fever with loin pain and vomiting in pregnancy", action: "admit for intravenous antibiotics and monitor the fetus", drug: "intravenous ceftriaxone", lab: "urine culture" },
    ],
  },
  {
    category: "Midwifery Professional Practice",
    clientNeed: "Professional Midwifery Practice",
    topics: [
      { name: "respectful maternity care", finding: "a woman shouted at and left alone during labour", action: "stop the practice and provide supportive, dignified care", drug: "not applicable", lab: "not applicable" },
      { name: "informed consent before a procedure", finding: "a woman taken to theatre without understanding the operation", action: "ensure consent is properly obtained before the procedure", drug: "not applicable", lab: "consent form" },
      { name: "confidentiality of maternity records", finding: "a neighbour asking about a patient's HIV result", action: "decline to disclose any information without consent", drug: "not applicable", lab: "not applicable" },
      { name: "prompt referral of obstetric emergencies", finding: "a midwife managing a breech delivery alone at a CHPS compound", action: "call for help and refer according to the emergency plan", drug: "not applicable", lab: "referral note" },
      { name: "accurate partograph documentation", finding: "a partograph with missing fetal heart recordings", action: "correct the practice and document all observations", drug: "not applicable", lab: "partograph" },
      { name: "reporting maternal deaths", finding: "a maternal death not reported within the required period", action: "report immediately and participate in the death review", drug: "not applicable", lab: "maternal death audit" },
      { name: "continuing professional development for midwives", finding: "a midwife who has not updated emergency skills", action: "attend approved refresher training on emergencies", drug: "not applicable", lab: "CPD portfolio" },
      { name: "supervision of student midwives", finding: "a student left to conduct a delivery alone", action: "supervise directly and take responsibility for the care", drug: "not applicable", lab: "competency record" },
      { name: "cultural practices around childbirth", finding: "a family insisting on a traditional practice that endangers the baby", action: "respect their beliefs while explaining the risk to the baby", drug: "not applicable", lab: "care plan" },
      { name: "handling complaints in the maternity unit", finding: "a husband angry about a delay in seeing the midwife", action: "listen, apologise and explain what is being done", drug: "not applicable", lab: "complaint register" },
      { name: "record keeping and legal responsibility", finding: "a delivery register entry completed hours later with recalled details", action: "document contemporaneously, accurately and legibly", drug: "not applicable", lab: "delivery register" },
      { name: "professional boundaries with patients", finding: "a midwife accepting money to prioritise a patient in labour", action: "refuse the payment and report the conduct", drug: "not applicable", lab: "not applicable" },
    ],
  },
  {
    category: "Gynaecology & Women's Health",
    clientNeed: "Women's Health Care",
    topics: [
      { name: "ectopic pregnancy", finding: "severe one-sided abdominal pain with a positive pregnancy test and fainting", action: "resuscitate and refer for emergency surgical review", drug: "intravenous fluids and blood", lab: "pregnancy test" },
      { name: "miscarriage and incomplete abortion", finding: "heavy bleeding with cramps and an open cervix", action: "resuscitate and refer for evacuation of retained products", drug: "intravenous fluids", lab: "haemoglobin level" },
      { name: "septic abortion", finding: "fever with foul discharge after an unsafe abortion", action: "resuscitate, treat infection and refer for surgical review", drug: "intravenous antibiotics", lab: "full blood count" },
      { name: "fibroids", finding: "heavy painful periods with a palpable abdominal mass", action: "refer for gynaecological assessment", drug: "tranexamic acid", lab: "haemoglobin level" },
      { name: "pelvic inflammatory disease", finding: "lower abdominal pain with fever and vaginal discharge", action: "treat both partners according to the syndromic approach", drug: "ceftriaxone, doxycycline and metronidazole", lab: "syndromic assessment" },
      { name: "cervical cancer screening", finding: "a woman over 30 who has never been screened", action: "offer human papillomavirus or visual inspection screening", drug: "not applicable", lab: "cervical screening result" },
      { name: "cervical cancer warning signs", finding: "bleeding after intercourse in a woman over 40", action: "refer urgently for gynaecological assessment", drug: "not applicable", lab: "cervical biopsy" },
      { name: "menstrual disorder assessment", finding: "cycles lasting twice as long as usual with clots", action: "assess for anaemia and refer for review", drug: "not applicable", lab: "haemoglobin level" },
      { name: "menopause counselling", finding: "hot flushes and disturbed sleep in a woman over 50", action: "counsel on menopause and assess cardiovascular and bone health", drug: "hormone therapy if indicated", lab: "not applicable" },
      { name: "vesicovaginal fistula", finding: "continuous leakage of urine after prolonged obstructed labour", action: "refer for specialist fistula repair and provide support", drug: "not applicable", lab: "clinical assessment" },
      { name: "domestic and gender-based violence", finding: "a woman with repeated unexplained injuries and a controlling partner", action: "see her alone, assess safety and offer support services", drug: "not applicable", lab: "risk assessment" },
      { name: "infertility counselling", finding: "a couple distressed after two years of trying to conceive", action: "counsel and refer both partners for assessment", drug: "not applicable", lab: "semen analysis" },
    ],
  },


  {
    category: "Antenatal Care",
    clientNeed: "Midwifery Practice",
    topics: [
      { name: "assessment of fetal presentation and lie", finding: "a transverse lie with the shoulder presenting at term", action: "refer for assessment of mode of delivery", drug: "not applicable", lab: "obstetric ultrasound" },
      { name: "measurement of the symphysis-fundal height", finding: "a fundal height four centimetres larger than the gestational age", action: "refer for ultrasound to exclude twins and polyhydramnios", drug: "not applicable", lab: "obstetric ultrasound" },
      { name: "leopold's manoeuvres", finding: "an unclear presentation on abdominal palpation at 36 weeks", action: "confirm the presentation with an ultrasound scan", drug: "not applicable", lab: "obstetric ultrasound" },
      { name: "advice on diet in pregnancy", finding: "a woman eating one meal a day with poor weight gain", action: "counsel on frequent protein-rich meals and refer for support", drug: "not applicable", lab: "weight chart" },
      { name: "management of leg cramps in pregnancy", finding: "painful calf cramps at night in the third trimester", action: "reassure and teach calf stretching and calcium-rich foods", drug: "calcium supplement", lab: "not applicable" },
      { name: "heartburn in pregnancy", finding: "burning chest discomfort after meals in late pregnancy", action: "advise small frequent meals and sitting upright after eating", drug: "antacid", lab: "not applicable" },
      { name: "constipation in pregnancy", finding: "hard stools with straining in a pregnant woman", action: "advise fluids, fibre and gentle activity", drug: "lactulose", lab: "not applicable" },
      { name: "anaemia prevention counselling", finding: "a woman taking iron with tea immediately after the dose", action: "explain that tea reduces iron absorption and separate the timing", drug: "ferrous sulphate", lab: "haemoglobin level" },
      { name: "testing for HIV at the first visit", finding: "a woman declining an HIV test at booking", action: "counsel her again and respect her decision", drug: "antiretroviral therapy", lab: "HIV rapid test" },
      { name: "screening for anaemia at each visit", finding: "pale conjunctiva at a routine antenatal visit", action: "check the haemoglobin and treat as prescribed", drug: "ferrous sulphate", lab: "haemoglobin level" },
      { name: "immunisation schedule in pregnancy", finding: "a woman at 28 weeks who has not completed tetanus immunisation", action: "give the due tetanus toxoid dose and update the card", drug: "tetanus toxoid", lab: "immunisation card" },
      { name: "birth preparedness and complication readiness", finding: "a woman with no plan for transport or blood donors", action: "help her develop a birth preparedness plan", drug: "not applicable", lab: "antenatal card" },
      { name: "recognition of twin pregnancy", finding: "three fetal parts palpated with two fetal heart rates heard", action: "refer for ultrasound and specialist antenatal care", drug: "not applicable", lab: "obstetric ultrasound" },
      { name: "polyhydramnios", finding: "a tense over-distended uterus with difficulty palpating fetal parts", action: "refer for ultrasound to exclude anomalies", drug: "not applicable", lab: "obstetric ultrasound" },
      { name: "varicose veins in pregnancy", finding: "painful swollen leg veins in late pregnancy", action: "advise rest with elevation and graduated support", drug: "not applicable", lab: "not applicable" },
    ],
  },
  {
    category: "Normal Labour & Delivery",
    clientNeed: "Intrapartum Care",
    topics: [
      { name: "the true versus false labour assessment", finding: "irregular contractions with no cervical change over two hours", action: "reassure the woman and advise when to return", drug: "not applicable", lab: "cervical assessment" },
      { name: "the first stage of labour care", finding: "a woman in established labour who is lying flat on her back", action: "encourage an upright or left lateral position", drug: "not applicable", lab: "partograph" },
      { name: "fluid and nutrition in labour", finding: "a woman in labour who has not drunk water for many hours", action: "offer oral fluids and monitor hydration", drug: "intravenous fluids if indicated", lab: "vital signs" },
      { name: "bladder care in labour", finding: "a full bladder palpated in a woman in established labour", action: "encourage her to pass urine to aid progress", drug: "not applicable", lab: "urine output" },
      { name: "recording the fetal heart in labour", finding: "a fetal heart rate recorded only once in four hours", action: "monitor the fetal heart every 30 minutes in the active phase", drug: "not applicable", lab: "fetal heart rate chart" },
      { name: "the second stage of labour", finding: "a woman with the urge to push at full dilation", action: "support pushing with the contraction and protect the perineum", drug: "not applicable", lab: "partograph" },
      { name: "delivery of the baby's head", finding: "rapid delivery of the head with risk of a perineal tear", action: "support the perineum and control the delivery of the head", drug: "not applicable", lab: "perineal assessment" },
      { name: "checking the umbilical cord at birth", finding: "two vessels seen instead of three on the cord", action: "document the finding and refer the baby for review", drug: "not applicable", lab: "newborn examination" },
      { name: "estimating blood loss after delivery", finding: "a swab weighing method used to estimate blood loss", action: "record the estimated loss accurately and act on heavy loss", drug: "not applicable", lab: "blood loss estimation" },
      { name: "the fourth stage of labour observation", finding: "a woman left unobserved in the first hour after delivery", action: "check the uterus and bleeding every 15 minutes", drug: "not applicable", lab: "vital signs" },
      { name: "cleanliness and asepsis at delivery", finding: "a delivery performed without hand hygiene or sterile gloves", action: "stop and follow the aseptic technique", drug: "not applicable", lab: "not applicable" },
      { name: "welcoming and supporting the labouring woman", finding: "a woman left alone and unattended during contractions", action: "stay with her and provide continuous support", drug: "not applicable", lab: "not applicable" },
      { name: "assessing moulding and caput", finding: "increasing moulding with poor progress in labour", action: "assess for obstruction and refer urgently", drug: "not applicable", lab: "vaginal examination" },
      { name: "recognising the second stage", finding: "an urge to bear down with full cervical dilation", action: "transfer the woman to the delivery room", drug: "not applicable", lab: "partograph" },
      { name: " newborn thermal protection at birth", finding: "a wet newborn left on a cold surface", action: "dry the baby immediately and place skin-to-skin", drug: "not applicable", lab: "temperature" },
    ],
  },
  {
    category: "Obstetric Emergencies",
    clientNeed: "Emergency Midwifery Care",
    topics: [
      { name: "amniotic fluid embolism", finding: "sudden collapse with cyanosis and convulsions during labour", action: "call for emergency help and support airway and circulation", drug: "oxygen and intravenous fluids", lab: "coagulation profile" },
      { name: "acute uterine inversion recognition", finding: "a dark red mass seen at the vagina with profound shock", action: "call for senior help and treat the shock without forcing replacement", drug: "intravenous fluids", lab: "vital signs" },
      { name: "management of a torn perineum with bleeding", finding: "active spurting bleeding from a perineal tear", action: "apply pressure and arrange immediate repair", drug: "not applicable", lab: "haemoglobin level" },
      { name: "HELLP syndrome", finding: "right upper quadrant pain with vomiting in a pre-eclamptic woman", action: "refer urgently for specialist review and blood tests", drug: "magnesium sulfate", lab: "liver enzymes and platelets" },
      { name: "disseminated intravascular coagulation", finding: "bleeding from the gums and venepuncture sites after placental abruption", action: "refer urgently and prepare blood products", drug: "blood products", lab: "coagulation profile" },
      { name: "management of a dead fetus in utero", finding: "no fetal heart heard with decreasing pregnancy symptoms", action: "confirm with ultrasound and counsel the woman sensitively", drug: "not applicable", lab: "obstetric ultrasound" },
      { name: "ruptured ectopic pregnancy recognition", finding: "shoulder tip pain with collapse and a positive pregnancy test", action: "treat for shock and arrange immediate surgery", drug: "intravenous fluids and blood", lab: "haemoglobin level" },
      { name: "anaphylaxis in the labour ward", finding: "facial swelling with wheeze after a medicine is given", action: "stop the medicine and give intramuscular adrenaline", drug: "adrenaline 1:1000", lab: "vital signs" },
      { name: "management of cord around the neck", finding: "the cord wrapped tightly around the baby's neck at delivery", action: "loosen it over the head or clamp and cut before the body delivers", drug: "not applicable", lab: "not applicable" },
      { name: "suprapubic pressure for shoulder dystocia", finding: "the anterior shoulder trapped behind the pubic bone", action: "apply suprapubic pressure with the mother's hips flexed", drug: "not applicable", lab: "delivery record" },
      { name: "shock index and early recognition", finding: "a rising pulse with a falling blood pressure after delivery", action: "treat for haemorrhagic shock and call for help", drug: "intravenous fluids and blood", lab: "haemoglobin level" },
      { name: "emergency referral communication", finding: "an unstable woman referred without a written note or phone call", action: "stabilise, document and telephone the receiving unit", drug: "not applicable", lab: "referral note" },
      { name: "caring for a woman after a stillbirth", finding: "a grieving mother refusing to see her stillborn baby", action: "give her time, choice and sensitive psychological support", drug: "not applicable", lab: "not applicable" },
      { name: "magnesium sulfate toxicity monitoring", finding: "reduced respiratory rate with absent knee reflexes on therapy", action: "stop the infusion and give calcium gluconate", drug: "calcium gluconate", lab: "respiratory rate" },
      { name: "uterine atony after a big baby", finding: "a soft poorly contracted uterus after delivering a large baby", action: "massage the uterus and give the prescribed uterotonic", drug: "oxytocin", lab: "blood loss" },
    ],
  },
  {
    category: "Puerperium & Postnatal Care",
    clientNeed: "Postnatal Care",
    topics: [
      { name: "assessing the lochia after delivery", finding: "large clots with a foul-smelling red lochia on day four", action: "assess for retained products and start treatment for infection", drug: "intravenous antibiotics", lab: "haemoglobin level" },
      { name: "postnatal bladder function", finding: "the mother has not passed urine for eight hours after delivery", action: "assess the bladder and catheterise if she cannot void", drug: "not applicable", lab: "urine output" },
      { name: "postnatal nutrition counselling", finding: "a breastfeeding mother skipping meals to feed her baby", action: "counsel her to eat and drink adequately to make milk", drug: "not applicable", lab: "haemoglobin level" },
      { name: "postnatal exercise and pelvic floor", finding: "stress incontinence on coughing after delivery", action: "teach pelvic floor exercises", drug: "not applicable", lab: "not applicable" },
      { name: "recognising postpartum psychosis", finding: "confusion with hallucinations and refusal to sleep after delivery", action: "refer urgently for psychiatric review and keep the baby safe", drug: "antipsychotic medicine", lab: "risk assessment" },
      { name: "baby blues versus depression", finding: "mild tearfulness on day three with normal care of the baby", action: "reassure and review her at the next visit", drug: "not applicable", lab: "not applicable" },
      { name: "resumption of sexual activity advice", finding: "a mother asking when intercourse is safe after delivery", action: "advise waiting until bleeding has stopped and the wound has healed", drug: "not applicable", lab: "not applicable" },
      { name: "contraception in the postnatal period", finding: "a mother at six weeks wanting a long-acting method", action: "counsel, exclude pregnancy and provide the method", drug: "levonorgestrel implant", lab: "pregnancy test" },
      { name: "postnatal examination of the mother", finding: "a mother not examined at the six-week visit", action: "complete a full postnatal examination including blood pressure", drug: "not applicable", lab: "blood pressure" },
      { name: "treating perineal pain after delivery", finding: "persistent perineal pain with swelling on day two", action: "assess the wound and give prescribed analgesia", drug: "paracetamol", lab: "wound assessment" },
      { name: "supporting a mother of twins", finding: "a mother overwhelmed feeding two newborn babies", action: "support her with a feeding plan and family assistance", drug: "not applicable", lab: "infant weight" },
      { name: "anaemia in the puerperium", finding: "pallor with tiredness and dizziness after a postpartum bleed", action: "check the haemoglobin and treat as prescribed", drug: "ferrous sulphate", lab: "haemoglobin level" },
      { name: "documenting the postnatal record", finding: "a postnatal record with no record of the baby's feeding", action: "complete the feeding and maternal observations", drug: "not applicable", lab: "postnatal record" },
      { name: "counselling on danger signs after delivery", finding: "a mother discharged without being taught danger signs", action: "teach the danger signs and when to return immediately", drug: "not applicable", lab: "not applicable" },
      { name: "supporting exclusive breastfeeding at home", finding: "a mother giving formula because of pressure from relatives", action: "counsel the family and support continued breastfeeding", drug: "not applicable", lab: "infant weight" },
    ],
  },
  {
    category: "Newborn Care",
    clientNeed: "Neonatal Care",
    topics: [
      { name: "the Apgar score at one and five minutes", finding: "a baby scored without assessing the heart rate properly", action: "assess all five signs correctly at one and five minutes", drug: "not applicable", lab: "Apgar score" },
      { name: "newborn feeding cues", finding: "a baby rooting and sucking on a hand soon after birth", action: "support early breastfeeding on demand", drug: "not applicable", lab: "not applicable" },
      { name: "cord infection warning signs", finding: "a red discharging umbilical stump with a feverish baby", action: "refer urgently for antibiotics", drug: "intravenous antibiotics", lab: "blood culture" },
      { name: "newborn weight monitoring", finding: "a baby losing more than ten percent of birth weight", action: "assess feeding and refer for review", drug: "expressed breast milk", lab: "daily weight" },
      { name: "neonatal temperature regulation", finding: "a baby with cold hands and feet in a hot room", action: "keep the baby warm with skin-to-skin contact and a cap", drug: "not applicable", lab: "temperature" },
      { name: "care of the preterm baby's skin", finding: "frequent rubbing of a very preterm baby's fragile skin", action: "handle minimally and protect the skin barrier", drug: "not applicable", lab: "not applicable" },
      { name: "recognising neonatal respiratory distress", finding: "chest indrawing with grunting and a fast respiratory rate", action: "refer urgently for oxygen and assessment", drug: "oxygen", lab: "oxygen saturation" },
      { name: "safe sleep advice for a newborn", finding: "a baby sleeping on its front on a soft pillow", action: "teach the family to place the baby on the back", drug: "not applicable", lab: "not applicable" },
      { name: "newborn eye care", finding: "sticky red eyes with discharge on day two", action: "clean the eyes and give prescribed treatment", drug: "erythromycin eye ointment", lab: "not applicable" },
      { name: "jaundice assessment in the newborn", finding: "yellow skin appearing within the first 24 hours", action: "refer urgently as this is a pathological jaundice", drug: "phototherapy", lab: "serum bilirubin" },
      { name: "newborn hearing and red reflex", finding: "no red reflex seen in one eye at examination", action: "refer the baby for ophthalmic review", drug: "not applicable", lab: "newborn examination" },
      { name: "immunisation site care", finding: "a hot swollen thigh after BCG vaccination", action: "assess and reassure as a small reaction is expected", drug: "not applicable", lab: "not applicable" },
      { name: "feeding the baby with a low blood glucose", finding: "a baby with a blood glucose below 2.5 mmol/L who is floppy", action: "feed urgently and refer if the glucose stays low", drug: "expressed breast milk or dextrose", lab: "blood glucose" },
      { name: "newborn stool patterns", finding: "a baby who has not passed meconium within 24 hours", action: "assess for obstruction and refer", drug: "not applicable", lab: "abdominal examination" },
      { name: "transporting a sick newborn", finding: "a sick baby referred without warmth or a referral note", action: "keep the baby warm and send a completed referral note", drug: "not applicable", lab: "referral note" },
    ],
  },
  {
    category: "Breastfeeding & Infant Feeding",
    clientNeed: "Infant and Young Child Feeding",
    topics: [
      { name: "the let-down reflex", finding: "a mother feeling tingling before the milk flows", action: "reassure her that this is a normal reflex", drug: "not applicable", lab: "not applicable" },
      { name: "feeding frequency in the early days", finding: "a newborn fed only twice since birth twelve hours ago", action: "support feeding at least eight times in 24 hours", drug: "not applicable", lab: "not applicable" },
      { name: "using a supplement at the breast", finding: "a mother needing to supplement while keeping the baby at the breast", action: "teach supplementation with a cup or a supply line", drug: "expressed breast milk", lab: "infant weight" },
      { name: "expressing by hand", finding: "a mother with engorgement who cannot afford a pump", action: "teach hand expression of breast milk", drug: "not applicable", lab: "not applicable" },
      { name: "storing expressed breast milk safely", finding: "expressed milk left at room temperature for a whole day", action: "discard the milk and teach safe storage times", drug: "not applicable", lab: "not applicable" },
      { name: "cup feeding a small baby", finding: "a preterm baby unable to breastfeed but able to swallow", action: "feed with a cup rather than a bottle teat", drug: "expressed breast milk", lab: "infant weight" },
      { name: "returning to work while breastfeeding", finding: "a mother planning to stop breastfeeding on returning to work", action: "teach expression and storage to keep breastfeeding", drug: "not applicable", lab: "not applicable" },
      { name: "tongue tie and poor feeding", finding: "a baby unable to latch with a tight tongue tie", action: "refer for assessment of the tongue tie", drug: "not applicable", lab: "feeding assessment" },
      { name: "feeding during maternal illness", finding: "a mother with fever stopping breastfeeding", action: "encourage continued feeding with correct hygiene", drug: "not applicable", lab: "not applicable" },
      { name: "medicines and breastfeeding", finding: "a mother told to discard milk while on an antibiotic", action: "check the compatibility of the medicine with breastfeeding", drug: "prescribed antibiotic", lab: "not applicable" },
      { name: "growth monitoring and feeding", finding: "a baby crossing downwards on the growth chart", action: "assess feeding and refer for nutritional review", drug: "not applicable", lab: "growth chart" },
      { name: "complementary food quality", finding: "a six-month-old given only thin maize porridge", action: "teach thick enriched complementary foods", drug: "not applicable", lab: "growth chart" },
      { name: "responsive feeding practices", finding: "a baby force-fed by a caregiver at every meal", action: "teach the caregiver to feed in response to the baby's cues", drug: "not applicable", lab: "growth chart" },
      { name: "weaning problems", finding: "a baby refusing all solids at seven months", action: "assess technique and encourage patience with variety", drug: "not applicable", lab: "growth chart" },
      { name: "colostrum value counselling", finding: "a family discarding the first yellow milk", action: "teach them that colostrum protects the baby", drug: "not applicable", lab: "not applicable" },
    ],
  },
  {
    category: "Family Planning",
    clientNeed: "Reproductive Health Services",
    topics: [
      { name: "assessing suitability for a method", finding: "a woman with severe hypertension requesting combined pills", action: "explain the risks and offer a safer alternative method", drug: "progestogen-only pill", lab: "blood pressure" },
      { name: "infection prevention at family planning clinics", finding: "instruments reused without sterilisation between patients", action: "stop the practice and reprocess the instruments", drug: "not applicable", lab: "sterilisation record" },
      { name: "documenting informed choice", finding: "a patient given a method without any counselling", action: "provide full counselling and document informed choice", drug: "not applicable", lab: "consent form" },
      { name: "managing missed combined pills", finding: "a patient who missed three active pills in a row", action: "advise on the missed-pill rules and use a backup method", drug: "combined oral contraceptive", lab: "not applicable" },
      { name: "implant removal difficulty", finding: "an implant that cannot be palpated at removal", action: "refer to a trained provider rather than probing blindly", drug: "not applicable", lab: "not applicable" },
      { name: "intrauterine device expulsion", finding: "a patient who felt the device come out on its own", action: "assess for pregnancy and counsel on replacement", drug: "not applicable", lab: "pregnancy test" },
      { name: "counelling adolescents confidentially", finding: "a teenager afraid to ask for contraception", action: "provide confidential, non-judgemental counselling", drug: "not applicable", lab: "not applicable" },
      { name: "male involvement in family planning", finding: "a husband refusing to allow his wife to use contraception", action: "invite him for counselling and explain the benefits", drug: "not applicable", lab: "not applicable" },
      { name: "return to fertility after methods", finding: "a woman planning pregnancy after stopping a method", action: "counsel her on the expected return to fertility", drug: "not applicable", lab: "not applicable" },
      { name: "warning signs with a method", finding: "severe lower abdominal pain with a missed period on a device", action: "exclude ectopic pregnancy urgently", drug: "not applicable", lab: "pregnancy test" },
      { name: "lactation and combined methods", finding: "a mother under six weeks postpartum given combined pills", action: "switch her to a method that does not affect milk supply", drug: "progestogen-only pill", lab: "not applicable" },
      { name: "stock and supply management", finding: "a family planning clinic with no condoms in stock", action: "report the stock-out and arrange an emergency supply", drug: "condoms", lab: "stock record" },
      { name: "counselling on side effects", finding: "a patient stopping a method because of bleeding without advice", action: "counsel on expected effects before starting a method", drug: "not applicable", lab: "not applicable" },
      { name: "sterilisation consent and regret", finding: "a young patient requesting sterilisation after a single child", action: "counsel thoroughly about permanence before consenting", drug: "not applicable", lab: "consent form" },
      { name: "contraception for women with medical conditions", finding: "a woman with sickle cell disease seeking contraception", action: "counsel on methods that are safe for her condition", drug: "not applicable", lab: "haemoglobin level" },
    ],
  },
  {
    category: "Malaria & Infections in Pregnancy",
    clientNeed: "Midwifery Practice",
    topics: [
      { name: "diagnosing malaria in pregnancy", finding: "fever with chills and sweating in a pregnant woman", action: "test with a rapid diagnostic test or blood film", drug: "not applicable", lab: "rapid diagnostic test" },
      { name: "anaemia screening frequency in pregnancy", finding: "a woman with no haemoglobin checked after booking", action: "check the haemoglobin at every scheduled visit", drug: "ferrous sulphate", lab: "haemoglobin level" },
      { name: "treating uncomplicated malaria safely", finding: "a pregnant woman at 20 weeks with uncomplicated malaria", action: "give the recommended antimalarial for her gestation", drug: "artemether-lumefantrine", lab: "blood film" },
      { name: "the effect of malaria on the baby", finding: "a small-for-dates baby with a mother who had repeated malaria", action: "monitor fetal growth and prevent further malaria", drug: "insecticide-treated net", lab: "obstetric ultrasound" },
      { name: "preventive education for malaria", finding: "a community with low use of treated nets in pregnancy", action: "run health education on net use and net repair", drug: "insecticide-treated net", lab: "not applicable" },
      { name: "recognising severe malaria warning signs", finding: "a pregnant woman with malaria who is drowsy and passing dark urine", action: "refer urgently for parenteral treatment", drug: "intravenous artesunate", lab: "blood glucose" },
      { name: "intermittent preventive treatment schedule", finding: "a woman who received only one dose by 36 weeks", action: "give the outstanding doses under direct observation", drug: "sulfadoxine-pyrimethamine", lab: "antenatal card" },
      { name: "HIV and malaria co-infection", finding: "an HIV-positive pregnant woman with recurrent malaria", action: "manage both conditions and ensure adherence to therapy", drug: "antiretroviral therapy", lab: "viral load" },
      { name: "fever management in pregnancy", finding: "a high fever in a pregnant woman being cooled with cold water", action: "use tepid sponging and prescribed antipyretics safely", drug: "paracetamol", lab: "temperature" },
      { name: "counselling on malaria medicine safety", finding: "a mother worried that malaria medicine will harm her baby", action: "explain the safety and the danger of untreated malaria", drug: "recommended antimalarial", lab: "not applicable" },
      { name: "following up a treated infection", finding: "a woman treated for malaria with no follow-up test", action: "review her to confirm the fever and anaemia have resolved", drug: "not applicable", lab: "blood film" },
      { name: "documenting infection in pregnancy", finding: "no record of a malaria diagnosis in the antenatal card", action: "record the diagnosis, treatment and follow-up plan", drug: "not applicable", lab: "antenatal card" },
      { name: "preventing congenital infection", finding: "a mother with an untreated infection near delivery", action: "coordinate care to protect the newborn at delivery", drug: "not applicable", lab: "not applicable" },
      { name: "water and sanitation to reduce infection", finding: "a household using unprotected well water", action: "teach safe water handling and refer for a protected source", drug: "not applicable", lab: "water quality test" },
      { name: "screening for anaemia after malaria", finding: "a woman treated for malaria with persistent pallor", action: "recheck the haemoglobin and treat the anaemia", drug: "ferrous sulphate", lab: "haemoglobin level" },
    ],
  },
];
