/** Topic seeds for the Ghana NMC Licensing Examination in Midwifery. */
export type MidwiferyTopic = {
  name: string;
  finding: string;
  action: string;
  drug: string;
  lab: string;
};

export const MIDWIFERY_CATEGORIES: {
  category: string;
  clientNeed: string;
  topics: MidwiferyTopic[];
}[] = [
  {
    category: "Antenatal Care",
    clientNeed: "Midwifery Practice",
    topics: [
      { name: "booking history taking", finding: "a woman who cannot remember her last menstrual period", action: "establish the gestational age using an early ultrasound", drug: "not applicable", lab: "obstetric ultrasound" },
      { name: "anaemia in pregnancy", finding: "pallor with a haemoglobin below 9 g/dL at 30 weeks", action: "give prescribed iron and folate and reassess the haemoglobin", drug: "ferrous sulphate and folic acid", lab: "haemoglobin level" },
      { name: "malaria prophylaxis in pregnancy", finding: "a pregnant woman who has not taken intermittent preventive treatment", action: "administer the scheduled sulfadoxine-pyrimethamine dose", drug: "sulfadoxine-pyrimethamine", lab: "blood film" },
      { name: "tetanus immunisation in pregnancy", finding: "a woman with no previous tetanus immunisation", action: "give the first tetanus toxoid dose and plan the schedule", drug: "tetanus toxoid", lab: "immunisation card" },
      { name: "syphilis screening in pregnancy", finding: "a positive rapid syphilis test at booking", action: "treat the woman and screen her partner", drug: "benzathine penicillin", lab: "rapid syphilis test" },
      { name: "urinary tract infection in pregnancy", finding: "burning on passing urine with frequency at 22 weeks", action: "collect a midstream specimen and give prescribed antibiotics", drug: "nitrofurantoin", lab: "urinalysis" },
      { name: "hyperemesis gravidarum", finding: "persistent vomiting with ketones in the urine and weight loss", action: "admit, rehydrate and give prescribed antiemetics", drug: "intravenous fluids and ondansetron", lab: "urine ketones" },
      { name: "fetal movement counting", finding: "a woman reporting reduced fetal movement at 36 weeks", action: "ask her to attend immediately for fetal heart assessment", drug: "not applicable", lab: "cardiotocograph" },
      { name: "abdominal examination in pregnancy", finding: "a fundal height smaller than the gestational age", action: "refer for ultrasound to assess fetal growth", drug: "not applicable", lab: "obstetric ultrasound" },
      { name: "danger signs in pregnancy education", finding: "a woman who does not know the pregnancy danger signs", action: "teach the danger signs and when to seek help", drug: "not applicable", lab: "antenatal card" },
      { name: "rhesus negative pregnancy", finding: "a rhesus negative woman with a sensitising event", action: "administer anti-D immunoglobulin as prescribed", drug: "anti-D immunoglobulin", lab: "Kleihauer test" },
      { name: "gestational diabetes screening", finding: "persistent glycosuria with a big-for-dates fetus", action: "refer for an oral glucose tolerance test", drug: "insulin", lab: "oral glucose tolerance test" },
    ],
  },
  {
    category: "Normal Labour & Delivery",
    clientNeed: "Intrapartum Care",
    topics: [
      { name: "the partograph", finding: "cervical dilation crossing to the right of the alert line", action: "review the cause and refer if there is no progress", drug: "not applicable", lab: "partograph" },
      { name: "fetal heart monitoring", finding: "a fetal heart rate above 160 beats per minute for a prolonged period", action: "reposition the woman and assess for fetal distress", drug: "not applicable", lab: "fetal heart rate chart" },
      { name: "meconium-stained liquor", finding: "green-stained amniotic fluid at the onset of labour", action: "monitor the fetus closely and prepare for resuscitation", drug: "not applicable", lab: "liquor assessment" },
      { name: "active management of the third stage", finding: "a slow trickle of blood after delivery of the baby", action: "give the prescribed uterotonic and deliver the placenta by controlled cord traction", drug: "oxytocin", lab: "blood loss estimation" },
      { name: "episiotomy and perineal tear repair", finding: "a second-degree perineal tear after delivery", action: "arrange repair with adequate analgesia and asepsis", drug: "lignocaine", lab: "wound assessment" },
      { name: "immediate newborn care", finding: "a newborn with a good cry but cold extremities", action: "dry and warm the baby with immediate skin-to-skin contact", drug: "not applicable", lab: "temperature" },
      { name: " cord care", finding: "a family applying herbs to the umbilical stump", action: "teach clean, dry cord care and the danger of infection", drug: "chlorhexidine gel", lab: "cord assessment" },
      { name: "assessing labour progress", finding: "membranes ruptured for many hours with no progress", action: "assess for obstruction and refer if there is no progress", drug: "not applicable", lab: "partograph" },
      { name: "pain relief in labour", finding: "a woman in severe pain requesting help in established labour", action: "offer support, positioning and prescribed analgesia", drug: "pentazocine", lab: "vital signs" },
      { name: "delivery of the placenta", finding: "the placenta not delivered 40 minutes after the baby", action: "assess for retained placenta and refer for manual removal", drug: "intravenous fluids", lab: "blood loss" },
      { name: "vesicovaginal examination during labour", finding: "a cervix that is 6 cm dilated with the head not engaged", action: "assess caput and moulding and refer if obstructed", drug: "not applicable", lab: "vaginal examination" },
      { name: "preparing the delivery room", finding: "no sterile delivery pack ready in an imminent delivery", action: "prepare a sterile field quickly while reassuring the woman", drug: "not applicable", lab: "delivery register" },
    ],
  },
  {
    category: "Obstetric Emergencies",
    clientNeed: "Emergency Midwifery Care",
    topics: [
      { name: "primary postpartum haemorrhage", finding: "more than 500 mL of blood loss within 24 hours of delivery", action: "call for help, massage the uterus and give uterotonics", drug: "oxytocin and ergometrine", lab: "haemoglobin level" },
      { name: "secondary postpartum haemorrhage", finding: "heavy bleeding with foul-smelling lochia at day ten", action: "treat infection and refer for retained products assessment", drug: "intravenous antibiotics", lab: "haemoglobin level" },
      { name: "eclamptic fit", finding: "a convulsing pregnant woman in the labour ward", action: "protect from injury, position on the side and give magnesium sulfate", drug: "magnesium sulfate", lab: "blood pressure" },
      { name: "shoulder dystocia", finding: "the head delivered but the shoulders not following", action: "call for help and perform the manoeuvres for shoulder dystocia", drug: "not applicable", lab: "delivery record" },
      { name: "cord prolapse", finding: "a pulsating cord felt at the introitus after membrane rupture", action: "elevate the presenting part and prepare for emergency delivery", drug: "not applicable", lab: "fetal heart rate" },
      { name: "uterine rupture", finding: "severe abdominal pain with loss of fetal heart sounds in a previous caesarean", action: "resuscitate and prepare for immediate laparotomy", drug: "intravenous fluids and blood", lab: "haemoglobin level" },
      { name: "retained placenta", finding: "a placenta retained for over one hour with bleeding", action: "refer for manual removal of the placenta", drug: "intravenous fluids", lab: "blood loss" },
      { name: "placenta praevia", finding: "painless bright red bleeding in the third trimester", action: "avoid vaginal examination and refer immediately", drug: "intravenous fluids", lab: "obstetric ultrasound" },
      { name: "abruptio placentae", finding: "a tense tender uterus with dark bleeding and fetal distress", action: "prepare for emergency delivery and monitor clotting", drug: "intravenous fluids and blood", lab: "coagulation profile" },
      { name: "obstructed labour", finding: "a moulded head with no dilation for many hours and an exhausted mother", action: "resuscitate and refer for emergency caesarean section", drug: "intravenous fluids and antibiotics", lab: "partograph" },
      { name: "inversion of the uterus", finding: "a mass at the introitus with severe shock after delivery", action: "call for help and do not attempt to replace it yourself", drug: "intravenous fluids", lab: "vital signs" },
      { name: "sepsis after delivery", finding: "fever with a foul-smelling discharge and abdominal pain", action: "start prescribed antibiotics and monitor for septic shock", drug: "intravenous clindamycin and gentamicin", lab: "full blood count" },
    ],
  },
  {
    category: "Puerperium & Postnatal Care",
    clientNeed: "Postnatal Care",
    topics: [
      { name: "normal involution of the uterus", finding: "a uterus not contracting well on the third postnatal day", action: "assess for retained products and massage the uterus", drug: "oxytocin", lab: "uterine assessment" },
      { name: "postnatal depression", finding: "a mother who is tearful and refuses to breastfeed on day five", action: "screen her, provide support and involve the family", drug: "sertraline", lab: "screening score" },
      { name: "puerperal sepsis", finding: "fever with lower abdominal pain and foul lochia", action: "start prescribed antibiotics and monitor for septic shock", drug: "intravenous antibiotics", lab: "full blood count" },
      { name: "breast engorgement", finding: "painful hard breasts with difficulty latching the baby", action: "support frequent feeding and express before latching", drug: "not applicable", lab: "not applicable" },
      { name: "cracked nipples", finding: "bleeding nipples with pain during feeding", action: "correct the positioning and attachment of the baby", drug: "not applicable", lab: "not applicable" },
      { name: "postnatal family planning counselling", finding: "a mother asking when she can start a contraceptive method", action: "counsel on options and respect her informed choice", drug: "progestogen-only pill", lab: "not applicable" },
      { name: "postnatal wound infection", finding: "a caesarean wound with redness and purulent discharge", action: "take a swab and give prescribed antibiotics", drug: "intravenous antibiotics", lab: "wound swab" },
      { name: "perineal wound care", finding: "a swollen painful perineal wound with sutures", action: "provide hygiene, analgesia and review the wound", drug: "analgesia", lab: "wound assessment" },
      { name: "venous thromboembolism after delivery", finding: "a painful swollen calf with breathlessness postnatally", action: "refer urgently for assessment and start prophylaxis as prescribed", drug: "low molecular weight heparin", lab: "Doppler ultrasound" },
      { name: "postnatal visit schedule", finding: "a mother and baby who have not been seen since discharge", action: "trace the family and complete the postnatal visits", drug: "not applicable", lab: "postnatal register" },
      { name: "resumption of menstruation and fertility", finding: "a mother believing she cannot conceive while breastfeeding", action: "explain that breastfeeding is not a reliable contraceptive", drug: "not applicable", lab: "not applicable" },
      { name: "newborn danger signs teaching", finding: "a mother who cannot name any newborn danger signs", action: "teach the danger signs and when to return to the facility", drug: "not applicable", lab: "child health record" },
    ],
  },
  {
    category: "Newborn Care",
    clientNeed: "Neonatal Care",
    topics: [
      { name: "neonatal resuscitation", finding: "a newborn with gasping breathing at one minute", action: "start bag and mask ventilation within the golden minute", drug: "oxygen", lab: "Apgar score" },
      { name: "hypothermia in a newborn", finding: "a baby with cold feet and a temperature below 36.5 degrees", action: "warm the baby using skin-to-skin contact and a cap", drug: "not applicable", lab: "temperature" },
      { name: "neonatal sepsis", finding: "a baby who is feeding poorly with a low temperature", action: "refer urgently for parenteral antibiotics", drug: "intravenous ampicillin and gentamicin", lab: "blood culture" },
      { name: "neonatal jaundice", finding: "yellow palms and soles with a lethargic baby", action: "refer for phototherapy and bilirubin measurement", drug: "phototherapy", lab: "serum bilirubin" },
      { name: "low birth weight care", finding: "a baby weighing 1.8 kg who is feeding slowly", action: "support kangaroo mother care and supervised feeding", drug: "expressed breast milk", lab: "daily weight" },
      { name: "neonatal hypoglycaemia", finding: "a jittery baby with a low blood glucose", action: "feed the baby and recheck the glucose urgently", drug: "expressed breast milk or dextrose", lab: "blood glucose" },
      { name: "Bcg and birth immunisation", finding: "a baby discharged without immunisation", action: "give BCG and oral polio vaccine and complete the card", drug: "BCG and oral polio vaccine", lab: "immunisation card" },
      { name: "neonatal convulsions", finding: "repetitive twitching of a newborn's limbs", action: "check the blood glucose and refer urgently", drug: "intravenous dextrose or anticonvulsant", lab: "blood glucose" },
      { name: "congenital abnormalities recognition", finding: "a newborn with an obvious neural tube defect on the back", action: "cover with a sterile dressing and refer for surgery", drug: "not applicable", lab: "clinical assessment" },
      { name: "preterm baby feeding", finding: "a preterm baby unable to suck effectively", action: "feed by nasogastric tube with expressed breast milk", drug: "expressed breast milk", lab: "daily weight" },
      { name: "necrotising enterocolitis", finding: "abdominal distension with blood in the stool of a preterm baby", action: "stop feeds and refer urgently for review", drug: "intravenous antibiotics", lab: "abdominal x-ray" },
      { name: "newborn screening and examination", finding: "a baby not examined for hip and heart problems before discharge", action: "complete a full newborn examination before discharge", drug: "not applicable", lab: "newborn examination" },
    ],
  },
  {
    category: "Breastfeeding & Infant Feeding",
    clientNeed: "Infant and Young Child Feeding",
    topics: [
      { name: "correct attachment for breastfeeding", finding: "a baby taking only the nipple with a wide open mouth", action: "help the mother reposition for correct attachment", drug: "not applicable", lab: "feeding assessment" },
      { name: "exclusive breastfeeding", finding: "a mother giving water and glucose to her newborn", action: "counsel her on exclusive breastfeeding for six months", drug: "not applicable", lab: "infant weight" },
      { name: "insufficient milk concerns", finding: "a mother worried that her baby is not getting enough milk", action: "assess feeding frequency and the baby's weight and urine output", drug: "not applicable", lab: "infant weight" },
      { name: "expressing and storing breast milk", finding: "a mother returning to work who needs to express", action: "teach safe expression and storage of breast milk", drug: "not applicable", lab: "not applicable" },
      { name: "mastitis", finding: "a red painful swollen breast with fever", action: "support continued feeding and give prescribed antibiotics", drug: "cloxacillin", lab: "not applicable" },
      { name: "breast abscess", finding: "a fluctuant painful lump in the breast with fever", action: "refer for drainage and support feeding from the other breast", drug: "intravenous antibiotics", lab: "clinical assessment" },
      { name: "feeding a baby with a cleft lip or palate", finding: "a newborn with a cleft palate unable to latch", action: "teach alternative feeding positions and refer for surgery", drug: "expressed breast milk", lab: "infant weight" },
      { name: "HIV and infant feeding", finding: "an HIV-positive mother asking how to feed her baby safely", action: "counsel her according to national guidelines on exclusive breastfeeding with antiretroviral therapy", drug: "antiretroviral therapy", lab: "viral load" },
      { name: "complementary feeding introduction", finding: "a mother introducing cereal at two months", action: "explain exclusive breastfeeding until six months", drug: "not applicable", lab: "growth chart" },
      { name: "baby-friendly hospital practices", finding: "glucose water given to a healthy newborn in the ward", action: "stop the practice and support immediate breastfeeding", drug: "not applicable", lab: "feeding record" },
      { name: "poor weight gain in a breastfed baby", finding: "a baby below birth weight at two weeks", action: "assess attachment, frequency and refer for review", drug: "not applicable", lab: "infant weight" },
      { name: "relactation support", finding: "a mother who stopped breastfeeding and wants to restart", action: "support relactation with frequent skin-to-skin and suckling", drug: "not applicable", lab: "infant weight" },
    ],
  },
  {
    category: "Family Planning",
    clientNeed: "Reproductive Health Services",
    topics: [
      { name: "intrauterine contraceptive device insertion", finding: "severe pelvic pain after an intrauterine device insertion", action: "assess for perforation or infection and refer if needed", drug: "not applicable", lab: "pelvic examination" },
      { name: "combined oral contraceptive counselling", finding: "a woman over 35 who smokes requesting combined pills", action: "explain the risks and offer a progestogen-only method", drug: "progestogen-only pill", lab: "blood pressure" },
      { name: "implanon insertion and removal", finding: "a patient requesting implant removal after two years", action: "counsel and arrange removal with informed consent", drug: "etonogestrel implant", lab: "not applicable" },
      { name: "injectable contraception side effects", finding: "prolonged irregular bleeding after a depot injection", action: "reassure, review and counsel on the expected effects", drug: "depot medroxyprogesterone", lab: "haemoglobin level" },
      { name: "emergency contraception", finding: "a woman presenting within 72 hours of unprotected intercourse", action: "counsel and give emergency contraception as prescribed", drug: "levonorgestrel", lab: "not applicable" },
      { name: "postpartum intrauterine device", finding: "a woman wanting immediate contraception after delivery", action: "counsel on timing, benefits and complications", drug: "intrauterine contraceptive device", lab: "not applicable" },
      { name: "condom promotion and dual protection", finding: "a patient using only hormonal contraception with a new partner", action: "counsel on dual protection against sexually transmitted infections", drug: "condoms", lab: "not applicable" },
      { name: "voluntary sterilisation counselling", finding: "a couple requesting permanent contraception", action: "provide thorough counselling and obtain informed written consent", drug: "not applicable", lab: "consent form" },
      { name: "contraceptive failure and pregnancy", finding: "a pregnant woman who had an intrauterine device in place", action: "refer for assessment of the device location", drug: "not applicable", lab: "obstetric ultrasound" },
      { name: "contraception after an abortion", finding: "a woman wanting to avoid another unintended pregnancy", action: "counsel and provide a method before discharge", drug: "chosen method", lab: "not applicable" },
      { name: "missed injectable appointment", finding: "a patient arriving two weeks late for a repeat injection", action: "assess for pregnancy before repeating the injection", drug: "depot medroxyprogesterone", lab: "pregnancy test" },
      { name: "lactational amenorrhoea method", finding: "a mother asking about the breastfeeding method", action: "explain the strict criteria required for it to work", drug: "not applicable", lab: "not applicable" },
    ],
  },
  {
    category: "Malaria & Infections in Pregnancy",
    clientNeed: "Midwifery Practice",
    topics: [
      { name: "malaria in the first trimester", finding: "fever with a positive blood film at nine weeks", action: "treat with the recommended first-trimester antimalarial", drug: "quinine", lab: "blood film" },
      { name: "malaria in the second and third trimester", finding: "fever with a positive test at 32 weeks", action: "give the recommended antimalarial and monitor the fetus", drug: "artemether-lumefantrine", lab: "blood film" },
      { name: "severe malaria in pregnancy", finding: "fever with confusion and dark urine in a pregnant woman", action: "refer urgently for parenteral therapy and glucose monitoring", drug: "intravenous artesunate", lab: "blood glucose" },
      { name: "anaemia from malaria in pregnancy", finding: "pallor with a haemoglobin of 7 g/dL at 28 weeks", action: "treat the malaria and give iron and folate therapy", drug: "ferrous sulphate and folic acid", lab: "haemoglobin level" },
      { name: "HIV in pregnancy and PMTCT", finding: "a newly positive HIV test at antenatal clinic", action: "start lifelong antiretroviral therapy and plan infant prophylaxis", drug: "tenofovir-lamivudine-dolutegravir", lab: "viral load" },
      { name: "syphilis in pregnancy", finding: "a positive syphilis screen with no treatment given", action: "treat with benzathine penicillin and screen the partner", drug: "benzathine penicillin", lab: "rapid syphilis test" },
      { name: "tuberculosis in pregnancy", finding: "a chronic cough with weight loss in a pregnant woman", action: "screen for tuberculosis and start prescribed treatment", drug: "rifampicin-based therapy", lab: "sputum AFB" },
      { name: "urinary tract infection in pregnancy", finding: "frequency with suprapubic pain and fever", action: "collect a specimen and give prescribed antibiotics", drug: "nitrofurantoin", lab: "urinalysis" },
      { name: "hepatitis B in pregnancy", finding: "a positive hepatitis B surface antigen at booking", action: "plan newborn immunoprophylaxis at birth", drug: "hepatitis B immunoglobulin and vaccine", lab: "hepatitis B surface antigen" },
      { name: "insecticide-treated net use in pregnancy", finding: "a pregnant woman sleeping without a treated net", action: "provide a treated net and teach its correct use", drug: "insecticide-treated net", lab: "not applicable" },
      { name: "genital tract infection in pregnancy", finding: "an abnormal vaginal discharge with itching", action: "assess, treat according to guidelines and screen the partner", drug: "metronidazole", lab: "high vaginal swab" },
      { name: "pyelonephritis in pregnancy", finding: "fever with loin pain and vomiting in pregnancy", action: "admit for intravenous antibiotics and monitor the fetus", drug: "intravenous ceftriaxone", lab: "urine culture" },
    ],
  },
  {
    category: "Midwifery Professional Practice",
    clientNeed: "Professional Midwifery Practice",
    topics: [
      { name: "respectful maternity care", finding: "a woman shouted at and left alone during labour", action: "stop the practice and provide supportive, dignified care", drug: "not applicable", lab: "not applicable" },
      { name: "informed consent before a procedure", finding: "a woman taken to theatre without understanding the operation", action: "ensure consent is properly obtained before the procedure", drug: "not applicable", lab: "consent form" },
      { name: "confidentiality of maternity records", finding: "a neighbour asking about a patient's HIV result", action: "decline to disclose any information without consent", drug: "not applicable", lab: "not applicable" },
      { name: "prompt referral of obstetric emergencies", finding: "a midwife managing a breech delivery alone at a CHPS compound", action: "call for help and refer according to the emergency plan", drug: "not applicable", lab: "referral note" },
      { name: "accurate partograph documentation", finding: "a partograph with missing fetal heart recordings", action: "correct the practice and document all observations", drug: "not applicable", lab: "partograph" },
      { name: "reporting maternal deaths", finding: "a maternal death not reported within the required period", action: "report immediately and participate in the death review", drug: "not applicable", lab: "maternal death audit" },
      { name: "continuing professional development for midwives", finding: "a midwife who has not updated emergency skills", action: "attend approved refresher training on emergencies", drug: "not applicable", lab: "CPD portfolio" },
      { name: "supervision of student midwives", finding: "a student left to conduct a delivery alone", action: "supervise directly and take responsibility for the care", drug: "not applicable", lab: "competency record" },
      { name: "cultural practices around childbirth", finding: "a family insisting on a traditional practice that endangers the baby", action: "respect their beliefs while explaining the risk to the baby", drug: "not applicable", lab: "care plan" },
      { name: "handling complaints in the maternity unit", finding: "a husband angry about a delay in seeing the midwife", action: "listen, apologise and explain what is being done", drug: "not applicable", lab: "complaint register" },
      { name: "record keeping and legal responsibility", finding: "a delivery register entry completed hours later with recalled details", action: "document contemporaneously, accurately and legibly", drug: "not applicable", lab: "delivery register" },
      { name: "professional boundaries with patients", finding: "a midwife accepting money to prioritise a patient in labour", action: "refuse the payment and report the conduct", drug: "not applicable", lab: "not applicable" },
    ],
  },
  {
    category: "Gynaecology & Women's Health",
    clientNeed: "Women's Health Care",
    topics: [
      { name: "ectopic pregnancy", finding: "severe one-sided abdominal pain with a positive pregnancy test and fainting", action: "resuscitate and refer for emergency surgical review", drug: "intravenous fluids and blood", lab: "pregnancy test" },
      { name: "miscarriage and incomplete abortion", finding: "heavy bleeding with cramps and an open cervix", action: "resuscitate and refer for evacuation of retained products", drug: "intravenous fluids", lab: "haemoglobin level" },
      { name: "septic abortion", finding: "fever with foul discharge after an unsafe abortion", action: "resuscitate, treat infection and refer for surgical review", drug: "intravenous antibiotics", lab: "full blood count" },
      { name: "fibroids", finding: "heavy painful periods with a palpable abdominal mass", action: "refer for gynaecological assessment", drug: "tranexamic acid", lab: "haemoglobin level" },
      { name: "pelvic inflammatory disease", finding: "lower abdominal pain with fever and vaginal discharge", action: "treat both partners according to the syndromic approach", drug: "ceftriaxone, doxycycline and metronidazole", lab: "syndromic assessment" },
      { name: "cervical cancer screening", finding: "a woman over 30 who has never been screened", action: "offer human papillomavirus or visual inspection screening", drug: "not applicable", lab: "cervical screening result" },
      { name: "cervical cancer warning signs", finding: "bleeding after intercourse in a woman over 40", action: "refer urgently for gynaecological assessment", drug: "not applicable", lab: "cervical biopsy" },
      { name: "menstrual disorder assessment", finding: "cycles lasting twice as long as usual with clots", action: "assess for anaemia and refer for review", drug: "not applicable", lab: "haemoglobin level" },
      { name: "menopause counselling", finding: "hot flushes and disturbed sleep in a woman over 50", action: "counsel on menopause and assess cardiovascular and bone health", drug: "hormone therapy if indicated", lab: "not applicable" },
      { name: "vesicovaginal fistula", finding: "continuous leakage of urine after prolonged obstructed labour", action: "refer for specialist fistula repair and provide support", drug: "not applicable", lab: "clinical assessment" },
      { name: "domestic and gender-based violence", finding: "a woman with repeated unexplained injuries and a controlling partner", action: "see her alone, assess safety and offer support services", drug: "not applicable", lab: "risk assessment" },
      { name: "infertility counselling", finding: "a couple distressed after two years of trying to conceive", action: "counsel and refer both partners for assessment", drug: "not applicable", lab: "semen analysis" },
    ],
  },
];
