/** Topic seeds for the NMC (UK) Test of Competence question bank. */
export type NmcTopic = {
  name: string;
  finding: string;
  action: string;
  drug: string;
  lab: string;
};

export const NMC_CATEGORIES: {
  category: string;
  clientNeed: string;
  topics: NmcTopic[];
}[] = [
  {
    category: "The NMC Code & Accountability",
    clientNeed: "Professional Values",
    topics: [
      { name: "the four pillars of the NMC Code", finding: "a colleague sharing patient details in a public corridor", action: "challenge the behaviour and report it to the nurse in charge", drug: "not applicable", lab: "the NMC Code" },
      { name: "duty of candour", finding: "a medication error that reached the patient", action: "tell the patient, apologise and complete a Datix incident form", drug: "not applicable", lab: "incident report" },
      { name: "revalidation requirements", finding: "a nurse due to revalidate in three months", action: "confirm 450 practice hours, 35 CPD hours and five reflective accounts", drug: "not applicable", lab: "revalidation portfolio" },
      { name: "delegation and accountability", finding: "a task delegated to an unregistered healthcare assistant", action: "confirm the person is competent and remain accountable for the delegation", drug: "not applicable", lab: "competency record" },
      { name: "raising concerns and whistleblowing", finding: "persistent unsafe staffing on the ward", action: "escalate in writing through the line manager and use the local speaking-up guardian", drug: "not applicable", lab: "escalation policy" },
      { name: "professional boundaries", finding: "a patient asking the nurse to be a social media friend", action: "politely decline and explain professional boundaries", drug: "not applicable", lab: "the NMC Code" },
      { name: "record keeping standards", finding: "an entry made without a date, time or signature", action: "complete the record contemporaneously, signed, dated and timed", drug: "not applicable", lab: "nursing records" },
      { name: "fitness to practise", finding: "a nurse suspected of attending work under the influence of alcohol", action: "remove them from patient care and inform the manager immediately", drug: "not applicable", lab: "occupational health referral" },
      { name: "informed consent", finding: "a patient who cannot explain the planned procedure", action: "stop and ask the clinician to revisit the consent discussion", drug: "not applicable", lab: "consent form" },
      { name: "equality and cultural competence", finding: "a patient requesting a same-sex nurse for personal care", action: "accommodate the request wherever it is reasonably practicable", drug: "not applicable", lab: "care plan" },
      { name: "confidentiality and GDPR", finding: "a relative telephoning to ask for test results", action: "verify identity and consent before disclosing any information", drug: "not applicable", lab: "information governance policy" },
      { name: "preceptorship for new registrants", finding: "a newly registered nurse asked to work unsupervised", action: "arrange appropriate supervision and support", drug: "not applicable", lab: "preceptorship record" },
    ],
  },
  {
    category: "Numeracy & Drug Calculations",
    clientNeed: "Safe Medicines Management",
    topics: [
      { name: "tablet dosage calculation", finding: "a prescription for 750 micrograms when 250 microgram tablets are stocked", action: "administer three tablets after a second-nurse check", drug: "digoxin", lab: "prescription chart" },
      { name: "liquid medicine calculation", finding: "a prescription for 120 mg of a 250 mg/5 mL suspension", action: "measure 2.4 mL using an oral syringe", drug: "paracetamol suspension", lab: "prescription chart" },
      { name: "intravenous infusion rate", finding: "1000 mL to be given over 8 hours", action: "set the pump to 125 mL per hour", drug: "sodium chloride 0.9%", lab: "fluid balance chart" },
      { name: "drops per minute calculation", finding: "500 mL over 4 hours with a 20 drops/mL giving set", action: "run the infusion at approximately 42 drops per minute", drug: "compound sodium lactate", lab: "fluid balance chart" },
      { name: "weight-based dosing", finding: "a prescription of 15 mg/kg for a 68 kg adult", action: "calculate and administer 1020 mg", drug: "paracetamol", lab: "documented body weight" },
      { name: "unit conversion", finding: "a prescription written in grams but stock labelled in milligrams", action: "convert accurately before drawing up the dose", drug: "amoxicillin", lab: "drug label" },
      { name: "percentage strength solutions", finding: "a 0.9% sodium chloride bag", action: "recognise this contains 9 g of sodium chloride per litre", drug: "sodium chloride 0.9%", lab: "infusion label" },
      { name: "insulin measurement", finding: "a prescription for 14 units of insulin", action: "draw up with an insulin syringe only and complete a second check", drug: "insulin", lab: "blood glucose" },
      { name: "controlled drug administration", finding: "a prescription for a Schedule 2 controlled drug", action: "check and sign the CD register with a second registered nurse", drug: "morphine sulfate", lab: "controlled drug register" },
      { name: "paediatric dose checking", finding: "a calculated dose that exceeds the BNF for Children maximum", action: "withhold the dose and contact the prescriber", drug: "ibuprofen", lab: "BNF for Children" },
      { name: "the six rights of administration", finding: "an unlabelled syringe left at the bedside", action: "discard it and prepare a fresh, labelled dose", drug: "not applicable", lab: "prescription chart" },
      { name: "titrated infusions", finding: "a syringe driver programmed at the wrong rate", action: "stop the infusion, recalculate and escalate as an incident", drug: "noradrenaline", lab: "infusion device settings" },
    ],
  },
  {
    category: "Safeguarding & Consent (UK)",
    clientNeed: "Safeguarding",
    topics: [
      { name: "the Mental Capacity Act 2005", finding: "a patient refusing treatment who understands the consequences", action: "respect the decision as capacity is assumed unless proven otherwise", drug: "not applicable", lab: "capacity assessment" },
      { name: "Deprivation of Liberty Safeguards", finding: "a confused patient repeatedly prevented from leaving the ward", action: "request an urgent DoLS authorisation", drug: "not applicable", lab: "DoLS documentation" },
      { name: "safeguarding adults at risk", finding: "unexplained bruising on a care home resident", action: "raise a safeguarding alert to the local authority", drug: "not applicable", lab: "body map" },
      { name: "safeguarding children", finding: "a child with injuries inconsistent with the given history", action: "inform the safeguarding lead and follow local child protection procedures", drug: "not applicable", lab: "child protection plan" },
      { name: "Gillick competence", finding: "a 15-year-old requesting contraception without parental knowledge", action: "assess Gillick competence and document the decision", drug: "not applicable", lab: "Fraser guidelines" },
      { name: "best interests decisions", finding: "an unconscious patient with no advance decision", action: "act in the patient's best interests and consult those close to them", drug: "not applicable", lab: "best interests checklist" },
      { name: "advance decisions to refuse treatment", finding: "a valid written advance decision refusing transfusion", action: "respect the advance decision and inform the clinical team", drug: "not applicable", lab: "advance decision document" },
      { name: "domestic abuse recognition", finding: "a patient whose partner answers all questions for them", action: "create an opportunity to see the patient alone", drug: "not applicable", lab: "risk assessment" },
      { name: "female genital mutilation duty", finding: "FGM identified in a girl under 18", action: "report to the police as a mandatory duty", drug: "not applicable", lab: "mandatory reporting record" },
      { name: "PREVENT and radicalisation", finding: "concerns a patient is being radicalised", action: "raise a PREVENT referral through the safeguarding lead", drug: "not applicable", lab: "PREVENT referral" },
      { name: "restraint and least restrictive practice", finding: "a patient at risk of falls being physically held", action: "use the least restrictive option and document the rationale", drug: "not applicable", lab: "restraint record" },
      { name: "modern slavery indicators", finding: "a patient with no identity documents controlled by another adult", action: "refer through the National Referral Mechanism", drug: "not applicable", lab: "NRM referral" },
    ],
  },
  {
    category: "Infection Prevention (UK)",
    clientNeed: "Infection Prevention and Control",
    topics: [
      { name: "the five moments for hand hygiene", finding: "a nurse moving between patients without decontaminating hands", action: "perform hand hygiene before and after every patient contact", drug: "alcohol handrub", lab: "audit score" },
      { name: "Clostridioides difficile management", finding: "type 7 stool on the Bristol Stool Chart with recent antibiotics", action: "isolate the patient, send a specimen and use soap and water", drug: "oral vancomycin", lab: "C. difficile toxin" },
      { name: "MRSA screening and decolonisation", finding: "a positive MRSA nasal screen on admission", action: "commence decolonisation and apply contact precautions", drug: "mupirocin nasal ointment", lab: "MRSA screen" },
      { name: "aseptic non-touch technique", finding: "a key part touched during a dressing change", action: "discard the contaminated item and restart with a sterile field", drug: "not applicable", lab: "ANTT audit" },
      { name: "sepsis six", finding: "a NEWS2 score of 7 with suspected infection", action: "escalate immediately and deliver the Sepsis Six within one hour", drug: "broad-spectrum antibiotics", lab: "serum lactate" },
      { name: "catheter associated urinary tract infection", finding: "a catheter in place for 14 days without review", action: "assess ongoing need and remove the catheter as soon as possible", drug: "not applicable", lab: "urinalysis" },
      { name: "personal protective equipment", finding: "an aerosol generating procedure planned", action: "wear an FFP3 respirator with eye protection", drug: "not applicable", lab: "fit-test record" },
      { name: "sharps management", finding: "a sharps bin filled beyond the marked line", action: "close and replace the bin immediately", drug: "not applicable", lab: "waste policy" },
      { name: "tuberculosis precautions", finding: "a patient with a chronic cough and night sweats", action: "isolate in a negative-pressure room and send sputum samples", drug: "rifampicin", lab: "sputum AFB" },
      { name: "norovirus outbreak management", finding: "several patients with vomiting on the same bay", action: "close the bay and inform infection prevention and control", drug: "oral rehydration solution", lab: "stool sample" },
      { name: "antimicrobial stewardship", finding: "intravenous antibiotics continued beyond 48 hours without review", action: "prompt the team to review for IV to oral switch", drug: "co-amoxiclav", lab: "inflammatory markers" },
      { name: "waste segregation", finding: "a used dressing placed in the domestic waste stream", action: "dispose of it in the orange clinical waste bag", drug: "not applicable", lab: "waste policy" },
    ],
  },
  {
    category: "Adult Nursing (UK)",
    clientNeed: "Adult Field Practice",
    topics: [
      { name: "NEWS2 escalation", finding: "a total NEWS2 score of 6", action: "request an urgent review by a clinician with core competencies in acute illness", drug: "oxygen", lab: "NEWS2 chart" },
      { name: "acute chest pain", finding: "central crushing pain radiating to the jaw", action: "obtain a 12-lead ECG within 10 minutes and follow the ACS pathway", drug: "glyceryl trinitrate", lab: "troponin" },
      { name: "heart failure management", finding: "a 2 kg weight gain over two days with worsening breathlessness", action: "sit the patient upright, record daily weights and escalate", drug: "furosemide", lab: "BNP" },
      { name: "COPD oxygen targets", finding: "an oxygen saturation of 96% in a patient at risk of hypercapnia", action: "titrate oxygen to a target saturation of 88 to 92%", drug: "controlled oxygen", lab: "arterial blood gases" },
      { name: "acute kidney injury", finding: "a rising creatinine with a urine output below 0.5 mL/kg/hr", action: "review nephrotoxic drugs and complete a fluid balance chart", drug: "not applicable", lab: "serum creatinine" },
      { name: "stroke recognition", finding: "a positive FAST assessment", action: "activate the stroke pathway and keep the patient nil by mouth", drug: "alteplase", lab: "CT head" },
      { name: "venous thromboembolism prophylaxis", finding: "no VTE risk assessment completed within 14 hours of admission", action: "complete the assessment and escalate for prophylaxis", drug: "enoxaparin", lab: "VTE risk assessment" },
      { name: "pressure ulcer prevention", finding: "a Waterlow score indicating very high risk", action: "implement SSKIN, reposition regularly and provide a pressure-relieving mattress", drug: "barrier cream", lab: "Waterlow score" },
      { name: "falls prevention", finding: "an older patient with delirium attempting to mobilise alone", action: "complete a multifactorial falls assessment and increase observation", drug: "not applicable", lab: "falls risk assessment" },
      { name: "malnutrition screening", finding: "a MUST score of 2", action: "refer to the dietitian and start a food record chart", drug: "oral nutritional supplement", lab: "MUST score" },
      { name: "diabetes management", finding: "a capillary blood glucose of 3.1 mmol/L", action: "treat hypoglycaemia with 15 to 20 g of fast-acting carbohydrate and recheck", drug: "glucose gel", lab: "capillary blood glucose" },
      { name: "end of life care", finding: "a patient in the last days of life with noisy secretions", action: "reposition and follow the individualised care plan with anticipatory medicines", drug: "hyoscine butylbromide", lab: "care plan" },
    ],
  },
  {
    category: "Mental Health Nursing (UK)",
    clientNeed: "Mental Health Field Practice",
    topics: [
      { name: "the Mental Health Act 1983", finding: "a patient detained under Section 2 asking to leave", action: "explain their rights and inform the nurse in charge", drug: "not applicable", lab: "detention paperwork" },
      { name: "Section 5(4) nurse holding power", finding: "an informal patient at immediate risk attempting to leave", action: "apply the six-hour nurse holding power and arrange urgent review", drug: "not applicable", lab: "Section 5(4) form" },
      { name: "suicide risk assessment", finding: "a patient with a clear plan and access to means", action: "remove the means and commence enhanced observation", drug: "not applicable", lab: "risk assessment" },
      { name: "therapeutic communication", finding: "a distressed patient expressing hopelessness", action: "listen actively, avoid false reassurance and explore their feelings", drug: "not applicable", lab: "care plan" },
      { name: "rapid tranquillisation", finding: "escalating aggression despite de-escalation attempts", action: "follow NICE guidance and monitor physical observations afterwards", drug: "lorazepam", lab: "physical observations" },
      { name: "lithium monitoring", finding: "coarse tremor, vomiting and confusion", action: "withhold the dose and obtain an urgent lithium level", drug: "lithium carbonate", lab: "serum lithium" },
      { name: "clozapine monitoring", finding: "a sore throat and fever in a patient on clozapine", action: "arrange an urgent full blood count for neutropenia", drug: "clozapine", lab: "neutrophil count" },
      { name: "eating disorder care", finding: "a very low BMI with electrolyte disturbance", action: "monitor closely for refeeding syndrome", drug: "thiamine", lab: "serum phosphate" },
      { name: "dementia and delirium", finding: "acute confusion of new onset in an older adult", action: "screen for reversible causes such as infection or pain", drug: "not applicable", lab: "4AT score" },
      { name: "alcohol withdrawal", finding: "tremor, sweating and agitation 24 hours after admission", action: "commence a withdrawal regimen and monitor with CIWA", drug: "chlordiazepoxide", lab: "CIWA score" },
      { name: "least restrictive practice", finding: "a patient in seclusion without documented review", action: "ensure reviews occur at the required intervals and document them", drug: "not applicable", lab: "seclusion record" },
      { name: "care programme approach", finding: "a patient being discharged with complex needs", action: "arrange a CPA meeting and a seven-day follow-up", drug: "not applicable", lab: "CPA documentation" },
    ],
  },
  {
    category: "Midwifery & Maternal Care (UK)",
    clientNeed: "Midwifery Practice",
    topics: [
      { name: "pre-eclampsia", finding: "a blood pressure of 162/112 mmHg with proteinuria", action: "escalate urgently and prepare for magnesium sulfate", drug: "labetalol", lab: "urine protein:creatinine ratio" },
      { name: "postpartum haemorrhage", finding: "blood loss exceeding 500 mL with a boggy uterus", action: "call for help, rub up a contraction and empty the bladder", drug: "oxytocin", lab: "full blood count" },
      { name: "gestational diabetes", finding: "a raised glucose tolerance test result", action: "refer to the joint diabetes and antenatal clinic", drug: "metformin", lab: "oral glucose tolerance test" },
      { name: "reduced fetal movements", finding: "a woman reporting no movements for 12 hours", action: "advise immediate attendance for assessment and CTG", drug: "not applicable", lab: "cardiotocograph" },
      { name: "sepsis in pregnancy", finding: "pyrexia with tachycardia in the postnatal period", action: "escalate immediately using the maternal sepsis pathway", drug: "intravenous antibiotics", lab: "serum lactate" },
      { name: "venous thromboembolism in pregnancy", finding: "unilateral calf pain and swelling postnatally", action: "escalate for urgent assessment and imaging", drug: "enoxaparin", lab: "Doppler ultrasound" },
      { name: "neonatal observation", finding: "a newborn who is grunting with intercostal recession", action: "escalate to the neonatal team immediately", drug: "oxygen", lab: "NEWTT chart" },
      { name: "infant feeding support", finding: "poor latch with sore, cracked nipples", action: "observe a full feed and correct positioning and attachment", drug: "not applicable", lab: "feeding assessment" },
      { name: "perinatal mental health", finding: "persistent low mood at six weeks postnatal", action: "screen with a validated tool and refer to perinatal mental health", drug: "sertraline", lab: "EPDS score" },
      { name: "anti-D prophylaxis", finding: "a rhesus negative woman after a sensitising event", action: "administer anti-D immunoglobulin within 72 hours", drug: "anti-D immunoglobulin", lab: "Kleihauer test" },
      { name: "birth plan and choice", finding: "a woman requesting a birth option against clinical advice", action: "provide balanced information and respect her informed decision", drug: "not applicable", lab: "birth plan" },
      { name: "newborn screening", finding: "a blood spot test not taken by day five", action: "arrange the newborn blood spot screening without delay", drug: "not applicable", lab: "newborn blood spot" },
    ],
  },
  {
    category: "Child & Young Person Nursing (UK)",
    clientNeed: "Children's Field Practice",
    topics: [
      { name: "the paediatric early warning score", finding: "a rising PEWS with increased work of breathing", action: "escalate urgently to the paediatric team", drug: "oxygen", lab: "PEWS chart" },
      { name: "bronchiolitis", finding: "an infant with nasal flaring and poor feeding", action: "assess hydration, suction the nares and monitor saturations", drug: "not applicable", lab: "oxygen saturation" },
      { name: "croup", finding: "a barking cough with stridor at rest", action: "keep the child calm and give oral dexamethasone as prescribed", drug: "dexamethasone", lab: "respiratory assessment" },
      { name: "paediatric sepsis", finding: "a non-blanching rash with fever", action: "escalate immediately as suspected meningococcal sepsis", drug: "ceftriaxone", lab: "blood cultures" },
      { name: "childhood asthma", finding: "inability to complete sentences in one breath", action: "give burst therapy via spacer and escalate", drug: "salbutamol", lab: "peak expiratory flow" },
      { name: "paediatric dehydration", finding: "reduced wet nappies with a sunken fontanelle", action: "commence oral rehydration and monitor fluid balance", drug: "oral rehydration solution", lab: "fluid balance chart" },
      { name: "type 1 diabetes in children", finding: "polyuria, polydipsia and weight loss", action: "check blood glucose and ketones and refer urgently", drug: "insulin", lab: "blood ketones" },
      { name: "immunisation schedule", finding: "a child overdue for routine vaccinations", action: "signpost to the practice nurse to catch up the schedule", drug: "routine vaccines", lab: "red book record" },
      { name: "play and developmental care", finding: "a preschool child frightened before a procedure", action: "use play preparation and involve the play specialist", drug: "not applicable", lab: "developmental assessment" },
      { name: "child protection", finding: "a delayed presentation with an inconsistent explanation", action: "inform the safeguarding lead and document factually", drug: "not applicable", lab: "safeguarding referral" },
      { name: "transition to adult services", finding: "a 16-year-old with a long-term condition", action: "begin planned transition with the young person involved", drug: "not applicable", lab: "transition plan" },
      { name: "paediatric pain assessment", finding: "a non-verbal child who is grimacing and withdrawn", action: "use an age-appropriate observational pain tool", drug: "paracetamol", lab: "FLACC score" },
    ],
  },
  {
    category: "OSCE Skills & Stations",
    clientNeed: "Practical Competence",
    topics: [
      { name: "the OSCE assessment station", finding: "an incomplete A to E assessment", action: "work systematically through airway, breathing, circulation, disability and exposure", drug: "not applicable", lab: "A to E assessment" },
      { name: "aseptic wound dressing station", finding: "a sterile field breached during the procedure", action: "stop, discard the contaminated items and restart", drug: "not applicable", lab: "ANTT checklist" },
      { name: "intramuscular injection station", finding: "an injection site chosen without landmarking", action: "identify the ventrogluteal site correctly before administering", drug: "prescribed injection", lab: "prescription chart" },
      { name: "in-hospital resuscitation station", finding: "an unresponsive patient who is not breathing normally", action: "call the resuscitation team and start chest compressions at 30:2", drug: "adrenaline", lab: "Resuscitation Council UK algorithm" },
      { name: "catheterisation station", finding: "the catheter tip touching a non-sterile surface", action: "discard the catheter and use a new sterile one", drug: "sterile lubricant", lab: "catheter care bundle" },
      { name: "medicines administration station", finding: "a prescription missing the patient's allergy status", action: "clarify with the prescriber before administering anything", drug: "not applicable", lab: "prescription chart" },
      { name: "fluid balance station", finding: "an incomplete intake and output record", action: "document all input and output accurately and calculate the balance", drug: "not applicable", lab: "fluid balance chart" },
      { name: "peak flow and inhaler technique station", finding: "a patient using a metered dose inhaler incorrectly", action: "demonstrate correct technique with a spacer and check understanding", drug: "salbutamol", lab: "peak flow reading" },
      { name: "nasogastric tube station", finding: "an aspirate pH above 5.5", action: "do not use the tube and arrange confirmation by x-ray", drug: "not applicable", lab: "gastric aspirate pH" },
      { name: "evidence-based practice station", finding: "a question about the source of best practice guidance", action: "refer to current NICE guidance and local policy", drug: "not applicable", lab: "NICE guidance" },
      { name: "professional values station", finding: "a simulated patient becoming distressed", action: "respond with compassion, maintain dignity and offer support", drug: "not applicable", lab: "the NMC Code" },
      { name: "handover and SBAR station", finding: "a disorganised verbal handover", action: "structure the handover using situation, background, assessment and recommendation", drug: "not applicable", lab: "SBAR tool" },
    ],
  },
  {
    category: "Care Planning: APIE",
    clientNeed: "Nursing Process",
    topics: [
      { name: "the APIE framework", finding: "a care plan written without any assessment data", action: "assess first, then plan, implement and evaluate", drug: "not applicable", lab: "care plan" },
      { name: "holistic assessment", finding: "an assessment covering only physical needs", action: "include psychological, social and spiritual needs", drug: "not applicable", lab: "holistic assessment tool" },
      { name: "Roper Logan Tierney model", finding: "an assessment of activities of daily living", action: "assess each activity of living against usual and current ability", drug: "not applicable", lab: "activities of living assessment" },
      { name: "setting SMART goals", finding: "a goal recorded as 'improve mobility'", action: "rewrite it as specific, measurable, achievable, realistic and timed", drug: "not applicable", lab: "care plan" },
      { name: "person-centred care planning", finding: "a plan written without the patient's involvement", action: "involve the patient and record their preferences", drug: "not applicable", lab: "care plan" },
      { name: "evaluating care", finding: "an intervention in place for a week with no review", action: "evaluate against the stated outcome and revise the plan", drug: "not applicable", lab: "evaluation record" },
      { name: "discharge planning", finding: "a patient living alone with new mobility needs", action: "arrange a multidisciplinary discharge assessment and equipment", drug: "not applicable", lab: "discharge checklist" },
      { name: "multidisciplinary working", finding: "complex needs beyond the nurse's scope", action: "refer to the appropriate member of the multidisciplinary team", drug: "not applicable", lab: "referral record" },
      { name: "risk assessment documentation", finding: "risk assessments not updated after a change in condition", action: "reassess and update all relevant risk assessments", drug: "not applicable", lab: "risk assessment" },
      { name: "communication needs", finding: "a patient with limited English", action: "arrange a professional interpreter rather than using a relative", drug: "not applicable", lab: "communication plan" },
      { name: "self-management support", finding: "a patient unsure how to manage their condition at home", action: "provide tailored education and check understanding using teach-back", drug: "not applicable", lab: "education record" },
      { name: "reflective practice", finding: "a challenging clinical incident", action: "reflect using a recognised model and record it for revalidation", drug: "not applicable", lab: "reflective account" },
    ],
  },
];
