/**
 * Question Bank for All Nurses - clinical dataset.
 * Format: [category, topic, [[finding, priorityAction, keyDrug, keyLab], ...]]
 */
export type Fact = [finding: string, action: string, drug: string, lab: string];

export const NURSING_DATA: [category: string, topic: string, facts: Fact[]][] = [
  ["Cardiovascular Nursing", "heart failure", [
    ["crackles in the lower lung fields", "sit the client upright and restrict sodium and fluid", "furosemide", "B-type natriuretic peptide"],
    ["a weight gain of 1.5 kg in 24 hours", "record a daily weight and notify the provider", "furosemide", "daily weight record"],
    ["orthopnoea needing three pillows to sleep", "elevate the head of the bed and assess oxygenation", "oxygen therapy", "oxygen saturation"],
    ["bilateral pitting ankle oedema", "elevate the legs and assess the skin for breakdown", "spironolactone", "serum potassium"],
    ["a new third heart sound on auscultation", "assess for fluid overload and report the finding", "furosemide", "B-type natriuretic peptide"],
    ["a dry hacking cough worse at night", "assess for pulmonary congestion and report it", "an ACE inhibitor", "chest x-ray"],
    ["fatigue on climbing one flight of stairs", "pace activity with rest periods and assess tolerance", "not applicable", "exercise tolerance"],
    ["a reduced urine output with abdominal distension", "monitor the intake and output and assess the abdomen", "not applicable", "fluid balance chart"],
    ["distended neck veins with a rapid irregular pulse", "assess the rhythm and report the findings", "not applicable", "ECG"],
    ["a client anxious about their failing heart", "explain the condition and involve the family", "not applicable", "not applicable"],
  ]],
  ["Cardiovascular Nursing", "myocardial infarction", [
    ["crushing substernal chest pressure radiating to the jaw", "obtain a 12-lead ECG and give chewable aspirin", "aspirin", "troponin I"],
    ["ST elevation in leads II, III and aVF", "activate the catheterisation team immediately", "alteplase", "ECG"],
    ["a blood pressure of 86/50 mmHg with pale clammy skin", "treat for cardiogenic shock and call for help", "intravenous fluids", "mean arterial pressure"],
    ["nausea and diaphoresis with epigastric discomfort", "record an ECG rather than assuming indigestion", "morphine", "troponin I"],
    ["a systolic pressure of 82 mmHg after nitroglycerin", "stop the nitroglycerin and give intravenous fluids", "intravenous fluids", "blood pressure"],
    ["a heart rate of 42 beats per minute after infarction", "assess for heart block and prepare for pacing", "atropine", "ECG"],
    ["a new pansystolic murmur after infarction", "assess for papillary muscle rupture and escalate", "not applicable", "echocardiogram"],
    ["anxiety with a feeling of impending death", "stay with the client and give prescribed oxygen", "oxygen", "oxygen saturation"],
    ["a raised temperature 24 hours after infarction", "explain this is a normal inflammatory response", "not applicable", "temperature"],
    ["a client who smoked for 20 years before the event", "counsel strongly on stopping smoking", "not applicable", "not applicable"],
  ]],
  ["Cardiovascular Nursing", "atrial fibrillation", [
    ["an irregularly irregular pulse of 140 beats per minute", "assess the client and anticipate anticoagulation", "diltiazem", "ECG"],
    ["sudden weakness on one side of the body", "treat as a stroke and obtain an urgent CT scan", "not applicable", "CT of the head"],
    ["an INR of 5.2 on warfarin therapy", "hold the warfarin and report the result", "vitamin K", "INR"],
    ["a left atrial thrombus seen on echocardiogram", "anticipate anticoagulation before any rhythm attempt", "apixaban", "echocardiogram"],
    ["slurred speech and facial droop at home", "activate the stroke pathway immediately", "not applicable", "glucose and CT"],
    ["palpitations with light-headedness on standing", "sit the client down and record an ECG", "not applicable", "ECG"],
    ["an apical-radial pulse deficit of 20 beats", "count both pulses with two nurses for one full minute", "not applicable", "apical radial pulse"],
    ["a client asking why anticoagulants are needed", "explain that the irregular rhythm can form clots", "anticoagulant", "not applicable"],
    ["an irregular pulse after heavy alcohol intake", "assess for alcohol induced atrial fibrillation", "not applicable", "ECG"],
    ["a raised thyroid hormone with atrial fibrillation", "assess for thyrotoxicosis as a reversible cause", "not applicable", "thyroid function tests"],
  ]],
  ["Cardiovascular Nursing", "cardiac arrest", [
    ["an unresponsive client with no normal breathing", "start chest compressions at a rate of 30 to 2", "adrenaline", "rhythm strip"],
    ["a shockable rhythm on the defibrillator monitor", "deliver the shock and resume compressions immediately", "defibrillation", "rhythm strip"],
    ["a return of spontaneous circulation after arrest", "begin targeted temperature management and monitoring", "not applicable", "arterial blood gases"],
    ["no intravenous access during an arrest", "start compressions and secure access as soon as possible", "intraosseous access", "not applicable"],
    ["a client found collapsed and unattended", "check responsiveness and call the resuscitation team", "not applicable", "not applicable"],
    ["a heart rate below 60 with hypotension after arrest", "prepare for transcutaneous pacing", "atropine", "ECG"],
    ["a client regaining consciousness after resuscitation", "reassure the client and explain what happened", "not applicable", "not applicable"],
    ["a resuscitation trolley left unstocked after use", "restock the trolley and record the check", "not applicable", "trolley checklist"],
    ["a relative distressed during a resuscitation attempt", "assign a staff member to stay with and inform the relative", "not applicable", "not applicable"],
    ["a certified death after a prolonged resuscitation", "care for the body with dignity and support the family", "not applicable", "not applicable"],
  ]],
  ["Cardiovascular Nursing", "deep vein thrombosis", [
    ["a unilateral swollen painful calf", "do not massage the limb and anticipate anticoagulation", "low molecular weight heparin", "Doppler ultrasound"],
    ["sudden breathlessness in a client with a swollen calf", "assess for pulmonary embolism and call for help", "oxygen", "D-dimer"],
    ["a warm red leg with visible distended veins", "elevate the leg and apply prescribed compression", "compression stockings", "not applicable"],
    ["a client on bed rest with no leg movement", "encourage ankle exercises to promote venous return", "not applicable", "not applicable"],
    ["bleeding gums on anticoagulant therapy", "report the bleeding and check the coagulation results", "not applicable", "coagulation profile"],
    ["a client asking why compression stockings are needed", "explain that they improve venous return", "compression stockings", "not applicable"],
    ["a client discharged after a deep vein thrombosis", "teach the signs of recurrence and of bleeding", "anticoagulant", "not applicable"],
    ["a long flight planned by a client with previous thrombosis", "advise on hydration, movement and compression", "not applicable", "not applicable"],
    ["a rising pulse with chest pain in an anticoagulated client", "assess for pulmonary embolism urgently", "not applicable", "D-dimer"],
    ["a deep vein thrombosis with a raised temperature", "assess for infection as a contributing cause", "antibiotic", "white blood cell count"],
  ]],
  ["Cardiovascular Nursing", "hypertensive emergency", [
    ["a blood pressure of 224/132 mmHg with blurred vision", "lower the pressure gradually with intravenous therapy", "nicardipine", "blood pressure"],
    ["chest pain with a blood pressure of 200/120 mmHg", "assess for aortic dissection and monitor both arms", "intravenous antihypertensive", "chest CT"],
    ["papilloedema with a severe headache", "reduce the pressure slowly to avoid cerebral hypoperfusion", "labetalol", "neurological assessment"],
    ["a seizure in a severely hypertensive client", "protect from injury and give prescribed antihypertensives", "labetalol", "blood pressure"],
    ["rebound hypertension after stopping medication", "teach the client never to stop treatment abruptly", "clonidine", "blood pressure"],
    ["a hypertensive client who stopped taking medicines", "explain the risk of stroke and restart treatment", "antihypertensive", "blood pressure"],
    ["a hypertensive client with a poor diet high in salt", "counsel on reducing dietary salt intake", "not applicable", "blood pressure"],
    ["a hypertensive client with no home monitoring", "teach home blood pressure monitoring", "not applicable", "blood pressure"],
    ["a hypertensive client with a target organ damage", "refer for specialist assessment", "not applicable", "not applicable"],
    ["a hypertensive client anxious about lifelong medicine", "explain the benefits and address the concerns", "not applicable", "not applicable"],
  ]],
  ["Respiratory Nursing", "asthma", [
    ["a silent chest with severe respiratory distress", "call the emergency team and prepare for ventilation", "nebulised salbutamol", "peak expiratory flow"],
    ["wheezing with an oxygen saturation of 88 percent", "give prescribed nebulised bronchodilator and oxygen", "salbutamol", "oxygen saturation"],
    ["a peak flow reading in the red zone", "give the rescue inhaler and reassess urgently", "prednisolone", "peak expiratory flow"],
    ["night-time wakening with wheeze three times a week", "review inhaler technique and preventer adherence", "beclomethasone", "peak expiratory flow"],
    ["tracheal tug with accessory muscle use", "position upright and prepare emergency treatment", "oxygen", "arterial blood gases"],
    ["a reliever inhaler used more than four times daily", "review the preventer inhaler and the technique", "beclomethasone", "not applicable"],
    ["wheezing after exposure to cold air or dust", "teach trigger identification and avoidance", "not applicable", "not applicable"],
    ["a child unable to complete a sentence in one breath", "give burst therapy and refer urgently", "salbutamol", "oxygen saturation"],
    ["a client with asthma asking about exercise", "explain exercise is beneficial with pre-treatment", "not applicable", "not applicable"],
    ["an inhaler used without a spacer", "teach correct use of the spacer for better delivery", "spacer", "not applicable"],
  ]],
  ["Respiratory Nursing", "pneumothorax", [
    ["absent breath sounds with tracheal deviation", "prepare for immediate needle decompression", "oxygen", "chest x-ray"],
    ["sudden pleuritic pain after a chest drain fell out", "cover the site and call for urgent help", "oxygen", "chest x-ray"],
    ["subcutaneous emphysema around a chest drain", "assess the drain system for an air leak", "not applicable", "chest x-ray"],
    ["continuous bubbling in the water seal chamber", "check the tubing for a disconnect or a leak", "not applicable", "chest x-ray"],
    ["a chest drain that has stopped swinging", "assess for blockage or a fully expanded lung", "not applicable", "chest x-ray"],
    ["sudden sharp pain after a rib fracture", "assess for a pneumothorax and monitor closely", "oxygen", "chest x-ray"],
    ["a client with a chest drain asking about mobilising", "keep the drain below chest level and support tubing", "not applicable", "not applicable"],
    ["a chest drain accidentally clamped during transfer", "unclamp it and assess the client immediately", "not applicable", "oxygen saturation"],
    ["a small pneumothorax under observation", "monitor the breathing and repeat the imaging", "not applicable", "chest x-ray"],
    ["a chest drain removed with the site now leaking air", "apply an occlusive dressing and inform the team", "not applicable", "not applicable"],
  ]],
  ["Respiratory Nursing", "pulmonary embolism", [
    ["sudden dyspnoea with sharp chest pain and tachycardia", "sit the client up, give oxygen and call for help", "heparin", "D-dimer"],
    ["haemoptysis with pleuritic pain after surgery", "assess for embolism and anticipate anticoagulation", "enoxaparin", "CT pulmonary angiogram"],
    ["a swollen painful calf with sudden breathlessness", "treat as an embolism and do not massage the leg", "heparin", "Doppler ultrasound"],
    ["hypotension with distended neck veins after surgery", "assess for a massive embolism and call for help", "thrombolysis", "ECG"],
    ["an oxygen saturation of 85 percent on room air", "give high-flow oxygen and prepare for imaging", "oxygen", "arterial blood gases"],
    ["a client on oral contraceptives with sudden breathlessness", "assess for embolism as a recognised risk", "not applicable", "D-dimer"],
    ["a recovering embolism client asking about activity", "advise gradual return with prescribed anticoagulation", "anticoagulant", "not applicable"],
    ["an embolism with a raised heart rate", "monitor the rhythm and the oxygen continuously", "not applicable", "ECG"],
    ["an embolism client who is anxious and frightened", "stay with the client and explain the treatment", "not applicable", "not applicable"],
    ["a client starting anticoagulation after an embolism", "teach the signs of bleeding and the follow-up plan", "anticoagulant", "not applicable"],
  ]],
  ["Respiratory Nursing", "pneumonia", [
    ["crackles with a productive rust-coloured sputum", "encourage deep breathing and give prescribed antibiotics", "amoxicillin", "chest x-ray"],
    ["a fever of 39.2 degrees with tachypnoea", "give prescribed antibiotics and monitor the temperature", "ceftriaxone", "white blood cell count"],
    ["an oxygen saturation of 89 percent with confusion", "give oxygen and assess for sepsis", "oxygen", "arterial blood gases"],
    ["poor cough effort in a frail older client", "assist with clearing secretions and monitor aspiration risk", "not applicable", "oxygen saturation"],
    ["pleuritic pain on deep breathing", "encourage splinting with deep breathing and analgesia", "analgesia", "chest x-ray"],
    ["pneumonia with a poor fluid intake", "encourage fluids to loosen the secretions", "not applicable", "not applicable"],
    ["pneumonia with a rising respiratory rate", "assess for sepsis and escalate urgently", "not applicable", "respiratory rate"],
    ["a recovering pneumonia client who is weak", "plan graded activity and nutrition support", "not applicable", "not applicable"],
    ["pneumonia in a crowded ward", "apply respiratory precautions to protect others", "not applicable", "not applicable"],
    ["a pneumonia client asking about the vaccine", "explain vaccination reduces the risk", "vaccine", "not applicable"],
  ]],
  ["Respiratory Nursing", "chronic obstructive pulmonary disease", [
    ["an oxygen saturation of 86 percent on room air", "give controlled oxygen to a target of 88 to 92 percent", "controlled oxygen", "arterial blood gases"],
    ["drowsiness with a rising carbon dioxide level", "assess for carbon dioxide retention and adjust oxygen", "not applicable", "arterial blood gases"],
    ["increasing dyspnoea with green sputum", "give prescribed nebulisers and antibiotics", "salbutamol", "sputum culture"],
    ["a barrel-shaped chest with pursed-lip breathing", "position upright and teach pursed-lip breathing", "not applicable", "spirometry"],
    ["a productive morning cough with weight loss", "assess nutrition and refer for respiratory review", "bronchodilator", "chest x-ray"],
    ["a COPD client who continues to smoke", "offer support and treatment to stop smoking", "not applicable", "not applicable"],
    ["a COPD client losing weight and muscle bulk", "refer for nutrition support with small frequent meals", "nutritional supplement", "weight record"],
    ["a COPD client with a raised carbon dioxide level", "avoid high-flow oxygen that may worsen retention", "controlled oxygen", "arterial blood gases"],
    ["a COPD client asking about the flu vaccine", "explain vaccination reduces exacerbations", "influenza vaccine", "not applicable"],
    ["a COPD client anxious about breathlessness", "teach breathing control and pacing of activity", "not applicable", "not applicable"],
  ]],
  ["Respiratory Nursing", "tuberculosis", [
    ["a cough for six weeks with night sweats and weight loss", "isolate the client and collect sputum samples", "rifampicin", "sputum AFB"],
    ["haemoptysis with a positive sputum smear", "start airborne precautions and prescribed therapy", "isoniazid", "sputum culture"],
    ["orange-red urine on anti-tuberculosis therapy", "reassure the client that this is an expected effect", "rifampicin", "liver enzymes"],
    ["refusal to continue treatment after two months", "arrange directly observed therapy and adherence support", "pyrazinamide", "sputum AFB"],
    ["a household contact with a chronic cough", "screen all household contacts for tuberculosis", "not applicable", "sputum AFB"],
    ["tuberculosis with a raised liver enzyme", "monitor the liver function and report", "not applicable", "liver enzymes"],
    ["tuberculosis in a pregnant client", "continue the recommended regimen with monitoring", "antituberculosis therapy", "not applicable"],
    ["a tuberculosis client asking about the duration", "explain treatment usually lasts at least six months", "antituberculosis therapy", "not applicable"],
    ["a nurse caring for a tuberculosis client without a mask", "wear the correct respirator to protect yourself", "not applicable", "not applicable"],
    ["tuberculosis with a poor appetite", "assess nutrition as weight loss is a key feature", "not applicable", "weight record"],
  ]],
  ["Endocrine Nursing", "diabetic ketoacidosis", [
    ["a blood glucose of 26 mmol/L with Kussmaul breathing", "start intravenous fluids and an insulin infusion", "intravenous insulin", "serum ketones"],
    ["fruity breath with vomiting and abdominal pain", "check the glucose and ketones immediately", "intravenous insulin", "serum ketones"],
    ["a glucose falling to 12 mmol/L on an insulin infusion", "add dextrose to the intravenous fluids", "intravenous dextrose", "blood glucose"],
    ["a potassium of 3.1 mmol/L during treatment", "replace potassium before continuing the insulin infusion", "potassium chloride", "serum potassium"],
    ["dehydration with a capillary refill of three seconds", "give rapid intravenous crystalloid resuscitation", "intravenous crystalloid", "vital signs"],
    ["ketoacidosis with a drowsy client", "protect the airway and refer for urgent care", "not applicable", "conscious level"],
    ["ketoacidosis with a client asking why they are thirsty", "explain the high glucose is causing fluid loss", "not applicable", "not applicable"],
    ["a newly diagnosed client with ketoacidosis", "plan education on diabetes and insulin before discharge", "insulin", "not applicable"],
    ["ketoacidosis with a normal glucose but ketones", "continue treatment until the ketones clear", "intravenous insulin", "serum ketones"],
    ["ketoacidosis with a mild infection", "treat the infection as it precipitated the episode", "antibiotic", "white blood cell count"],
  ]],
  ["Endocrine Nursing", "hypoglycaemia", [
    ["a blood glucose of 2.8 mmol/L with sweating and confusion", "give 15 grams of fast-acting carbohydrate", "oral glucose gel", "blood glucose"],
    ["an unconscious client with a glucose of 2.2 mmol/L", "give intravenous dextrose and never oral fluid", "intravenous dextrose", "blood glucose"],
    ["a glucose of 3.0 mmol/L before a meal in a client on insulin", "treat before the meal and reassess", "fast-acting carbohydrate", "blood glucose"],
    ["repeated night-time hypoglycaemia", "review the evening insulin dose with the provider", "insulin", "blood glucose"],
    ["a client who cannot swallow with a low glucose", "give glucagon or intravenous dextrose", "glucagon", "blood glucose"],
    ["hypoglycaemia with an aggressive confused client", "treat the glucose while keeping the client safe", "oral glucose gel", "blood glucose"],
    ["hypoglycaemia after more exercise than usual", "teach adjustment of food and insulin for activity", "not applicable", "blood glucose"],
    ["hypoglycaemia with no warning symptoms", "discuss impaired awareness with the provider", "not applicable", "blood glucose"],
    ["hypoglycaemia after skipping a meal", "teach the importance of meals with insulin", "not applicable", "not applicable"],
    ["hypoglycaemia that has recovered", "give a complex carbohydrate snack to prevent recurrence", "not applicable", "blood glucose"],
  ]],
  ["Endocrine Nursing", "hyperthyroidism", [
    ["a heart rate of 150 with fever and agitation", "assess for thyroid storm and call for help", "propranolol", "thyroid function tests"],
    ["exophthalmos with a visible neck swelling", "protect the eyes and refer for endocrine review", "carbimazole", "thyroid function tests"],
    ["weight loss with a good appetite and tremor", "assess thyroid function and provide a high-calorie diet", "carbimazole", "thyroid function tests"],
    ["a thyroidectomy client with a tingling face", "check the calcium level for post-operative hypocalcaemia", "calcium gluconate", "serum calcium"],
    ["a hoarse voice after thyroid surgery", "assess the airway and report possible nerve injury", "not applicable", "serum calcium"],
    ["hyperthyroidism with diarrhoea and heat intolerance", "explain these are features of the overactive thyroid", "not applicable", "not applicable"],
    ["antithyroid medicine with a sore throat and fever", "check the white cell count for agranulocytosis", "not applicable", "white blood cell count"],
    ["hyperthyroidism in a pregnant client", "refer for specialist monitoring of mother and fetus", "not applicable", "thyroid function tests"],
    ["hyperthyroidism with anxiety about radioiodine", "explain the treatment and the precautions needed", "radioactive iodine", "not applicable"],
    ["hyperthyroidism with a rapid weight loss", "monitor the weight and provide a high-calorie diet", "not applicable", "weight record"],
  ]],
  ["Endocrine Nursing", "hypothyroidism", [
    ["cold intolerance with a heart rate of 48", "assess thyroid function and warm the client", "levothyroxine", "thyroid stimulating hormone"],
    ["lethargy with dry skin and constipation", "give prescribed levothyroxine on an empty stomach", "levothyroxine", "thyroid stimulating hormone"],
    ["a swollen face with a hoarse voice and slow speech", "assess for severe hypothyroidism and report", "levothyroxine", "thyroid function tests"],
    ["bradycardia with hypothermia and confusion", "treat as myxoedema coma and call for help", "intravenous levothyroxine", "thyroid function tests"],
    ["weight gain with heavy menstrual bleeding", "check thyroid function and monitor the cycle", "levothyroxine", "thyroid function tests"],
    ["levothyroxine taken with breakfast", "teach taking it on an empty stomach for absorption", "levothyroxine", "thyroid function tests"],
    ["a rising thyroid stimulating hormone on treatment", "anticipate a dose increase", "levothyroxine", "thyroid stimulating hormone"],
    ["hypothyroidism with a raised cholesterol", "assess thyroid replacement adequacy", "levothyroxine", "lipid profile"],
    ["hypothyroidism in a pregnant client", "increase the monitoring as requirements rise", "levothyroxine", "thyroid function tests"],
    ["a client asking about the duration of treatment", "explain treatment is usually lifelong", "levothyroxine", "not applicable"],
  ]],
  ["Endocrine Nursing", "Addison disease", [
    ["hypotension with hyperpigmented skin creases", "give prescribed hydrocortisone and monitor the pressure", "hydrocortisone", "serum cortisol"],
    ["vomiting with a sodium of 122 mmol/L", "give intravenous fluids and hydrocortisone", "hydrocortisone", "serum sodium"],
    ["collapse after abruptly stopping steroids", "treat as an Addisonian crisis immediately", "intravenous hydrocortisone", "serum cortisol"],
    ["a potassium of 6.2 mmol/L with weakness", "assess the heart rhythm and treat the hyperkalaemia", "intravenous calcium", "ECG"],
    ["a craving for salty food with weight loss", "assess adrenal function and consider salt replacement", "fludrocortisone", "serum sodium"],
    ["a client on steroids acutely unwell with infection", "increase the steroid dose as prescribed", "hydrocortisone", "not applicable"],
    ["a client wearing a medical alert band", "support the client to keep the band with them", "not applicable", "not applicable"],
    ["a client asking about sick day rules", "teach how to increase the dose during illness", "hydrocortisone", "not applicable"],
    ["Addison disease with a low blood sugar", "treat the glucose and give the steroid dose", "intravenous dextrose", "blood glucose"],
    ["a client anxious about the future", "provide clear information and long-term support", "not applicable", "not applicable"],
  ]],
  ["Renal Nursing", "acute kidney injury", [
    ["a urine output of 0.3 mL/kg/hr for six hours", "assess fluid status and review nephrotoxic medicines", "not applicable", "serum creatinine"],
    ["a creatinine rising from 80 to 320 micromol/L", "report the trend and stop nephrotoxic medicines", "not applicable", "serum creatinine"],
    ["hyperkalaemia with peaked T waves", "give intravenous calcium and prepare for dialysis", "intravenous calcium gluconate", "ECG"],
    ["a distended bladder with no urine output", "perform a bladder scan and catheterise if indicated", "urinary catheter", "bladder scan volume"],
    ["fluid overload with pulmonary oedema", "restrict fluids and prepare for dialysis", "not applicable", "chest x-ray"],
    ["acute kidney injury after severe diarrhoea", "restore the circulating volume with fluids", "intravenous fluids", "blood pressure"],
    ["acute kidney injury on a non-steroidal anti-inflammatory", "stop the medicine and monitor the kidneys", "not applicable", "serum creatinine"],
    ["acute kidney injury with a rising potassium", "repeat the potassium and start treatment", "intravenous calcium", "serum potassium"],
    ["acute kidney injury and a client asking about recovery", "explain that many causes are reversible", "not applicable", "serum creatinine"],
    ["acute kidney injury with a poor urine output at night", "monitor the fluid balance hourly", "not applicable", "fluid balance chart"],
  ]],
  ["Renal Nursing", "chronic kidney disease", [
    ["a haemoglobin of 8 g/dL with fatigue", "assess erythropoietin therapy and iron status", "erythropoietin", "haemoglobin level"],
    ["pruritus with a phosphate of 2.4 mmol/L", "give phosphate binders with meals", "calcium acetate", "serum phosphate"],
    ["a potassium of 6.4 mmol/L with muscle weakness", "restrict potassium and give calcium gluconate", "intravenous calcium", "ECG"],
    ["metabolic acidosis with deep rapid breathing", "assess the bicarbonate level and report", "sodium bicarbonate", "serum bicarbonate"],
    ["kidney disease with a high blood pressure", "monitor the pressure and give prescribed antihypertensives", "antihypertensive", "blood pressure"],
    ["kidney disease with oedema of the legs", "restrict fluid as prescribed and monitor the weight", "not applicable", "daily weight"],
    ["kidney disease with a herbal preparation in use", "advise on the risk of further kidney damage", "not applicable", "serum creatinine"],
    ["a client asking about dialysis", "explain the types of dialysis and prepare the client", "not applicable", "not applicable"],
    ["kidney disease with bone pain", "assess the calcium and phosphate balance", "vitamin D analogue", "serum calcium"],
    ["a client anxious about the future", "provide clear information and long-term support", "not applicable", "not applicable"],
  ]],
  ["Renal Nursing", "dialysis care", [
    ["hypotension developing during a dialysis session", "reduce the ultrafiltration rate and position flat", "not applicable", "blood pressure"],
    ["a fistula site with no thrill on palpation", "report immediately as the access may be blocked", "not applicable", "not applicable"],
    ["redness and swelling at the fistula site", "assess for infection and notify the team", "antibiotic", "not applicable"],
    ["muscle cramps during a dialysis session", "slow the fluid removal and reassure the client", "not applicable", "not applicable"],
    ["a client who missed a dialysis session", "assess the fluid and potassium status urgently", "not applicable", "serum potassium"],
    ["dialysis with a poor appetite", "refer to the dietitian for a renal diet plan", "not applicable", "serum albumin"],
    ["a catheter exit site with pus", "take a swab and start prescribed antibiotics", "antibiotic", "catheter swab"],
    ["a client asking why weight is taken before dialysis", "explain it guides how much fluid to remove", "not applicable", "weight record"],
    ["dialysis with a low blood pressure at home", "teach the client to report dizziness and fainting", "not applicable", "blood pressure"],
    ["a client anxious about the dialysis machine", "explain each step and stay with the client", "not applicable", "not applicable"],
  ]],
  ["Renal Nursing", "urinary tract infection", [
    ["burning on passing urine with frequency", "encourage fluids and give prescribed antibiotics", "antibiotic", "urinalysis"],
    ["a urinary catheter in place for fourteen days", "assess the need and remove it as soon as possible", "not applicable", "not applicable"],
    ["cloudy smelly urine with a raised temperature", "collect a specimen and start prescribed antibiotics", "antibiotic", "urine culture"],
    ["a urinary infection with a new confusion", "assess for a systemic infection and escalate", "not applicable", "not applicable"],
    ["a drainage bag resting on the floor", "reposition the bag below bladder level and off the floor", "not applicable", "not applicable"],
    ["recurring urinary infections", "teach hygiene, fluids and complete the antibiotic course", "not applicable", "not applicable"],
    ["a urinary infection with loin pain", "assess for kidney involvement and refer", "not applicable", "not applicable"],
    ["a urinary infection and questions about prevention", "teach fluids, hygiene and regular voiding", "not applicable", "not applicable"],
    ["a urinary infection with no improvement", "send a culture and review the antibiotic", "not applicable", "urine culture"],
    ["a catheter with no clinical indication", "discuss removal with the team to reduce infection", "not applicable", "not applicable"],
  ]],
  ["Neurological Nursing", "stroke", [
    ["facial droop with slurred speech for one hour", "activate the stroke pathway and check the glucose", "alteplase", "CT of the head"],
    ["a Glasgow Coma Scale score falling from 15 to 9", "protect the airway and call for urgent imaging", "not applicable", "CT of the head"],
    ["dysphagia detected on a swallow screen", "keep the client nil by mouth and refer to speech therapy", "not applicable", "swallow assessment"],
    ["a blood pressure of 200/110 mmHg before thrombolysis", "report the pressure before giving thrombolysis", "alteplase", "blood pressure"],
    ["neglect of the affected side after a right-sided stroke", "approach from the unaffected side and teach scanning", "not applicable", "not applicable"],
    ["a stroke client who cannot swallow safely", "insert a nasogastric tube as prescribed for feeding", "nasogastric tube", "not applicable"],
    ["a stroke client with a pressure area on the hip", "reposition regularly and offload the pressure", "not applicable", "not applicable"],
    ["a stroke client who is tearful and withdrawn", "recognise post-stroke depression and refer", "not applicable", "not applicable"],
    ["a stroke client asking about recovery", "explain rehabilitation and involve the family", "not applicable", "not applicable"],
    ["a stroke client with a spastic hand", "support the arm and begin passive range of movement", "not applicable", "not applicable"],
  ]],
  ["Neurological Nursing", "raised intracranial pressure", [
    ["a widening pulse pressure with bradycardia", "elevate the head of the bed and call for help", "mannitol", "intracranial pressure"],
    ["vomiting with a worsening headache at dawn", "assess neurological status and notify the provider", "mannitol", "CT of the head"],
    ["unequal pupils with a deteriorating conscious level", "prepare for emergency imaging and intervention", "mannitol", "pupil assessment"],
    ["a client coughing against a closed ventilator circuit", "check the circuit and reduce the stimulation", "sedation", "intracranial pressure"],
    ["seizure activity after a head injury", "protect from injury and give prescribed anticonvulsant", "phenytoin", "EEG"],
    ["raised pressure with a low sodium", "assess the sodium as it worsens cerebral oedema", "not applicable", "serum sodium"],
    ["raised pressure in an over-sedated client", "assess the conscious level before the sedation", "not applicable", "conscious level"],
    ["raised pressure in a client nursed flat", "elevate the head of the bed to thirty degrees", "not applicable", "not applicable"],
    ["raised pressure with constipation", "prevent straining which raises the pressure", "laxative", "not applicable"],
    ["raised pressure with a distressed family", "explain the situation honestly and support them", "not applicable", "not applicable"],
  ]],
  ["Neurological Nursing", "epilepsy", [
    ["a generalised seizure lasting more than five minutes", "protect from injury and give prescribed anticonvulsant", "intravenous lorazepam", "blood glucose"],
    ["a seizure in a client with an unknown glucose", "check the glucose immediately during the event", "intravenous dextrose", "blood glucose"],
    ["cyanosis with tonic-clonic movements", "position on the side and protect the airway", "not applicable", "oxygen saturation"],
    ["a drowsy client after a seizure", "reassess the airway, glucose and neurological status", "not applicable", "blood glucose"],
    ["repeated seizures without regaining consciousness", "treat as status epilepticus and call for help", "intravenous lorazepam", "EEG"],
    ["epilepsy with stopped medicine", "teach the importance of continuing treatment", "anticonvulsant", "not applicable"],
    ["epilepsy with an injury during a seizure", "assess the injury and review the seizure control", "not applicable", "not applicable"],
    ["epilepsy with questions about pregnancy", "refer for pre-conception counselling on medicines", "not applicable", "not applicable"],
    ["epilepsy with feelings of stigma", "provide education to reduce stigma and support", "not applicable", "not applicable"],
    ["epilepsy with gum hypertrophy on phenytoin", "teach oral hygiene and dental review", "phenytoin", "not applicable"],
  ]],
  ["Neurological Nursing", "head injury", [
    ["clear fluid draining from the nose after trauma", "do not suction and test the fluid for glucose", "not applicable", "CT of the head"],
    ["a deteriorating conscious level with vomiting", "prepare for urgent imaging and neurosurgical review", "not applicable", "CT of the head"],
    ["a black eye with a battle sign behind the ear", "assess for a base of skull fracture", "not applicable", "CT of the head"],
    ["a pupil becoming fixed and dilated", "call for emergency help and reduce the pressure", "mannitol", "pupil assessment"],
    ["restlessness after a head injury in an older client", "assess for a bleed rather than assuming agitation", "not applicable", "CT of the head"],
    ["a head injury with a seizure", "protect from injury and give prescribed anticonvulsant", "phenytoin", "EEG"],
    ["a head injury with a clear fluid leak from the ear", "cover loosely and do not pack the ear", "not applicable", "not applicable"],
    ["a head injury with repeated questions about the event", "reassure and reorientate with short simple explanations", "not applicable", "not applicable"],
    ["a head injury discharged with no advice", "teach the warning signs and when to return", "not applicable", "not applicable"],
    ["a head injury with a rising blood pressure and slow pulse", "recognise raised pressure and escalate", "not applicable", "vital signs"],
  ]],
  ["Neurological Nursing", "spinal cord injury", [
    ["a pounding headache with a blood pressure of 210/110 mmHg", "sit the client upright and check for bladder distention", "not applicable", "blood pressure"],
    ["a spinal injury with a loss of sensation below the chest", "assess the level and prevent pressure areas", "not applicable", "not applicable"],
    ["a spinal injury with no bowel movement", "establish a bowel management programme", "not applicable", "not applicable"],
    ["a spinal injury with a weak cough", "suction and support the breathing", "not applicable", "oxygen saturation"],
    ["a spinal injury moved without a board", "use a spinal board and log roll the client", "not applicable", "not applicable"],
    ["a spinal injury with cool pale legs", "assess the circulation and prevent pressure areas", "not applicable", "not applicable"],
    ["a spinal injury and questions about walking again", "communicate honestly and support the client", "not applicable", "not applicable"],
    ["a spinal injury with a catheter and a fever", "assess for a urinary infection", "antibiotic", "urinalysis"],
    ["a spinal injury with no sweating above the level", "monitor the temperature and keep the client comfortable", "not applicable", "temperature"],
    ["a spinal injury being transferred to a chair", "use a planned transfer with enough staff", "not applicable", "not applicable"],
  ]],
  ["Gastrointestinal Nursing", "upper gastrointestinal bleed", [
    ["coffee-ground vomiting with a pulse of 118", "insert large-bore access and crossmatch blood", "intravenous fluids", "haemoglobin level"],
    ["black tarry stools with dizziness", "assess for shock and prepare for transfusion", "packed red blood cells", "haemoglobin level"],
    ["a haemoglobin falling from 12 to 7 g/dL", "transfuse as prescribed and monitor for rebleeding", "packed red blood cells", "haemoglobin level"],
    ["vomiting blood after frequent NSAID use", "stop the NSAID and give prescribed acid suppression", "omeprazole", "endoscopy"],
    ["abdominal distension with absent bowel sounds after a bleed", "assess for perforation and keep nil by mouth", "not applicable", "abdominal x-ray"],
    ["a gastrointestinal bleed with an anxious thirsty client", "reassure the client and keep nil by mouth", "not applicable", "not applicable"],
    ["a gastrointestinal bleed with a rising pulse rate", "assess for continuing blood loss and escalate", "not applicable", "vital signs"],
    ["a gastrointestinal bleed needing urgent endoscopy", "prepare the client and explain the procedure", "not applicable", "endoscopy"],
    ["a gastrointestinal bleed in a chronic alcohol user", "assess the liver and consider varices", "not applicable", "liver function tests"],
    ["a gastrointestinal bleed discharged with no follow-up", "arrange endoscopy follow-up and teaching", "not applicable", "not applicable"],
  ]],
  ["Gastrointestinal Nursing", "intestinal obstruction", [
    ["vomiting with a distended abdomen and no flatus", "insert a nasogastric tube and keep nil by mouth", "nasogastric tube", "abdominal x-ray"],
    ["colicky pain with visible bowel loops", "assess for strangulation and notify the surgeon", "intravenous fluids", "abdominal x-ray"],
    ["a rising pulse with localised pain and tenderness", "assess for strangulation and prepare for surgery", "intravenous fluids", "white blood cell count"],
    ["feculent vomiting with a distended abdomen", "assess for a distal obstruction and decompress", "nasogastric tube", "abdominal x-ray"],
    ["dehydration after prolonged vomiting", "replace fluids and monitor the electrolytes", "intravenous fluids", "serum electrolytes"],
    ["an obstruction with a hernia that cannot be reduced", "do not force it and refer for urgent surgery", "not applicable", "not applicable"],
    ["an obstruction with questions about surgery", "explain the likely operation and the recovery", "not applicable", "not applicable"],
    ["an obstruction with a tender irreducible lump", "escalate as this may be strangulated", "not applicable", "not applicable"],
    ["an obstruction with a nasogastric tube in place", "check the tube position and the drainage", "not applicable", "gastric aspirate pH"],
    ["an obstruction with a low potassium", "replace the potassium as prescribed", "potassium chloride", "serum potassium"],
  ]],
  ["Gastrointestinal Nursing", "liver cirrhosis", [
    ["flapping tremor with drowsiness in liver disease", "give prescribed lactulose and assess consciousness", "lactulose", "serum ammonia"],
    ["a distended abdomen with shifting dullness", "monitor weight and girth and restrict sodium", "spironolactone", "serum sodium"],
    ["haematemesis with known varices", "prepare for emergency endoscopy and blood transfusion", "terlipressin", "haemoglobin level"],
    ["a low albumin with oedema and ascites", "restrict sodium and assess the nutritional needs", "albumin infusion", "serum albumin"],
    ["pruritus with a deeply jaundiced client", "assess bilirubin and provide skin care", "not applicable", "serum bilirubin"],
    ["cirrhosis with continued alcohol use", "assess honestly and arrange support for cessation", "not applicable", "not applicable"],
    ["cirrhosis with a fever and abdominal pain", "assess for spontaneous bacterial peritonitis", "intravenous antibiotics", "not applicable"],
    ["cirrhosis with easy bruising", "assess the clotting and monitor for bleeding", "not applicable", "coagulation profile"],
    ["cirrhosis with confusion and agitation at night", "assess the encephalopathy and keep the client safe", "lactulose", "conscious level"],
    ["cirrhosis with questions about the prognosis", "communicate honestly and involve the family", "not applicable", "not applicable"],
  ]],
  ["Gastrointestinal Nursing", "acute pancreatitis", [
    ["severe epigastric pain radiating to the back", "keep nil by mouth and give intravenous fluids", "intravenous fluids", "serum lipase"],
    ["a serum lipase three times the upper limit", "confirm the diagnosis and keep nil by mouth", "not applicable", "serum lipase"],
    ["a falling calcium with bruising on the flanks", "report the severity and monitor closely", "intravenous calcium", "serum calcium"],
    ["a rising respiratory rate 48 hours after admission", "assess for acute respiratory distress syndrome", "oxygen", "arterial blood gases"],
    ["severe pain requiring strong analgesia", "give prescribed analgesia and assess the response", "pethidine", "pain score"],
    ["pancreatitis with heavy alcohol use", "arrange support to stop alcohol completely", "not applicable", "not applicable"],
    ["pancreatitis with a fever and tenderness", "assess for infection and necrosis", "antibiotic", "white blood cell count"],
    ["pancreatitis with a low urine output", "monitor the fluids and the kidney function", "not applicable", "urine output"],
    ["pancreatitis with a high blood glucose", "monitor the glucose as the pancreas is inflamed", "insulin", "blood glucose"],
    ["pancreatitis starting oral fluids again", "introduce fluids gradually and monitor for pain", "not applicable", "not applicable"],
  ]],
  ["Gastrointestinal Nursing", "stoma care", [
    ["a stoma that looks dark and dusky", "report immediately as the blood supply may be affected", "not applicable", "not applicable"],
    ["skin excoriation around the stoma bag", "fit the appliance properly and use a barrier product", "barrier product", "not applicable"],
    ["a stoma bag that keeps leaking", "re-measure the stoma and change the appliance size", "not applicable", "not applicable"],
    ["a client refusing to look at the stoma", "allow time and offer support before teaching", "not applicable", "not applicable"],
    ["questions about a normal stoma appearance", "explain that a healthy stoma is moist and pink", "not applicable", "not applicable"],
    ["no output from the stoma for twelve hours", "assess for obstruction and notify the surgeon", "not applicable", "not applicable"],
    ["a stoma with a poor fluid intake", "encourage fluids as output can be high", "not applicable", "not applicable"],
    ["a stoma client asking about returning to work", "explain normal activity is possible with support", "not applicable", "not applicable"],
    ["a stoma client embarrassed in social situations", "offer peer support and practical advice", "not applicable", "not applicable"],
    ["a stoma that has become retracted", "refer to the stoma nurse for appliance advice", "not applicable", "not applicable"],
  ]],
  ["Maternal & Child Health", "postpartum haemorrhage", [
    ["a boggy uterus with heavy bleeding after delivery", "massage the uterus and give the prescribed uterotonic", "oxytocin", "haemoglobin level"],
    ["blood loss over 500 mL within 24 hours of delivery", "call for help and start intravenous resuscitation", "intravenous fluids", "haemoglobin level"],
    ["a full bladder with a deviated uterus after delivery", "empty the bladder and reassess the uterus", "urinary catheter", "not applicable"],
    ["continuous oozing with no firm clot formation", "assess for coagulation problems and refer urgently", "blood products", "coagulation profile"],
    ["a uterus that will not contract after the third baby", "give a second uterotonic and prepare for transfer", "carboprost", "blood loss"],
    ["a mother pale, sweaty and drowsy after delivery", "treat for shock and call for help", "intravenous fluids", "vital signs"],
    ["a retained placenta with ongoing bleeding", "refer for manual removal of the placenta", "intravenous fluids", "blood loss"],
    ["heavy bleeding returning on day ten after delivery", "assess for retained products and infection", "intravenous antibiotics", "haemoglobin level"],
    ["early discharge with no postnatal visit planned", "arrange a postnatal visit and teach the danger signs", "not applicable", "not applicable"],
    ["heavy bleeding and questions about future pregnancy", "counsel on the risk in future deliveries", "not applicable", "not applicable"],
  ]],
  ["Maternal & Child Health", "pre-eclampsia", [
    ["a blood pressure of 165/112 mmHg with proteinuria and headache", "start prescribed magnesium sulfate and institute precautions", "magnesium sulfate", "urine protein"],
    ["absent knee reflexes on magnesium sulfate therapy", "stop the infusion and give calcium gluconate", "calcium gluconate", "reflex assessment"],
    ["a respiratory rate of 10 per minute on magnesium sulfate", "stop the infusion and give the antidote", "calcium gluconate", "respiratory rate"],
    ["epigastric pain with a rising blood pressure at 34 weeks", "assess for impending eclampsia and call for help", "magnesium sulfate", "blood pressure"],
    ["blurred vision with a blood pressure of 170/115 mmHg", "treat as severe pre-eclampsia and refer urgently", "magnesium sulfate", "blood pressure"],
    ["pre-eclampsia referred without any treatment", "stabilise with magnesium sulfate before referral", "magnesium sulfate", "referral note"],
    ["pre-eclampsia with questions about admission", "explain the risk of seizures to her and the baby", "not applicable", "not applicable"],
    ["pre-eclampsia with a reduced fetal movement", "monitor the fetus and refer for assessment", "not applicable", "fetal heart rate"],
    ["pre-eclampsia now delivered", "continue monitoring the blood pressure afterwards", "antihypertensive", "blood pressure"],
    ["pre-eclampsia with a poor urine output", "monitor the kidneys and the fluid balance", "not applicable", "urine output"],
  ]],
  ["Maternal & Child Health", "newborn jaundice", [
    ["yellow palms and soles on day two of life", "refer urgently for bilirubin measurement", "phototherapy", "serum bilirubin"],
    ["a lethargic jaundiced baby who is feeding poorly", "refer urgently and support feeding", "phototherapy", "serum bilirubin"],
    ["jaundice in the first 24 hours of life", "treat as pathological and refer immediately", "phototherapy", "serum bilirubin"],
    ["a rising bilirubin despite phototherapy", "prepare for exchange transfusion", "exchange transfusion", "serum bilirubin"],
    ["phototherapy with loose green stools", "reassure the mother and protect the eyes", "phototherapy", "not applicable"],
    ["traditional remedies used for jaundice", "explain the danger and refer for proper treatment", "phototherapy", "serum bilirubin"],
    ["jaundice in a baby of a diabetic mother", "check the glucose and refer for assessment", "phototherapy", "blood glucose"],
    ["a jaundiced baby who is dehydrated", "support feeding and refer for assessment", "phototherapy", "not applicable"],
    ["jaundice with a fever", "assess for sepsis and refer urgently", "intravenous antibiotics", "blood culture"],
    ["questions about why the baby's eyes are covered", "explain that phototherapy can harm the eyes", "phototherapy", "not applicable"],
  ]],
  ["Maternal & Child Health", "neonatal sepsis", [
    ["a three-day-old baby feeding poorly with a low temperature", "refer urgently for parenteral antibiotics", "intravenous ampicillin", "blood culture"],
    ["a baby with a bulging fontanelle and fever", "refer urgently for lumbar puncture and antibiotics", "intravenous ceftriaxone", "cerebrospinal fluid"],
    ["an umbilical stump discharging pus", "clean the cord and start prescribed antibiotics", "intravenous antibiotics", "not applicable"],
    ["a temperature of 35.5 degrees with poor feeding", "warm the baby and assess for sepsis", "intravenous antibiotics", "blood culture"],
    ["grunting with a high temperature", "assess for sepsis and refer for treatment", "intravenous antibiotics", "blood culture"],
    ["membranes ruptured over 24 hours before birth", "observe closely and assess for sepsis", "intravenous antibiotics", "not applicable"],
    ["jaundice with a fever", "assess for sepsis and refer urgently", "intravenous antibiotics", "serum bilirubin"],
    ["sepsis with feeding that has stopped", "refer for intravenous fluids and antibiotics", "intravenous fluids", "not applicable"],
    ["traditional remedies used on the cord", "teach clean cord care and the risk of infection", "chlorhexidine gel", "not applicable"],
    ["sepsis discharged too early", "ensure the full antibiotic course is completed", "intravenous antibiotics", "not applicable"],
  ]],
  ["Maternal & Child Health", "severe acute malnutrition", [
    ["a mid-upper arm circumference in the red zone", "refer for therapeutic feeding and treat infection", "therapeutic milk", "mid-upper arm circumference"],
    ["visible wasting with oedema of both feet", "begin therapeutic feeding and treat infection", "F-75 therapeutic milk", "serum albumin"],
    ["severe malnutrition with no appetite", "begin nasogastric feeding and treat infection", "F-75 therapeutic milk", "weight for height"],
    ["diarrhoea developing during refeeding", "slow the feed and assess for refeeding syndrome", "not applicable", "serum potassium"],
    ["therapeutic milk diluted to make it last", "counsel on correct preparation and support the family", "therapeutic milk", "not applicable"],
    ["malnutrition with a fever", "treat the infection as it worsens malnutrition", "antibiotic", "temperature"],
    ["malnutrition discharged with no follow-up", "schedule follow-up and monitor the growth", "not applicable", "growth chart"],
    ["herbal remedies used for malnutrition", "respect their belief and explain the nutritional need", "not applicable", "not applicable"],
    ["malnutrition with a poor appetite test", "begin feeding carefully and monitor closely", "therapeutic milk", "not applicable"],
    ["recovered malnutrition with continued low weight", "continue supplementation and monitor the growth", "not applicable", "growth chart"],
  ]],
  ["Maternal & Child Health", "childhood pneumonia", [
    ["chest indrawing with a respiratory rate of 60", "give prescribed antibiotics and oxygen", "intravenous amoxicillin", "oxygen saturation"],
    ["a child unable to drink with fast breathing", "refer urgently for parenteral treatment", "intravenous antibiotics", "oxygen saturation"],
    ["grunting with nasal flaring in an infant", "assess the oxygen and refer for treatment", "oxygen", "oxygen saturation"],
    ["fever and cough with poor fluid intake", "encourage fluids and reassess the hydration", "not applicable", "temperature"],
    ["a cough not improving after three days of treatment", "reassess and review the antibiotic choice", "not applicable", "chest x-ray"],
    ["pneumonia with an oxygen saturation of 86 percent", "give oxygen and refer for assessment", "oxygen", "oxygen saturation"],
    ["pneumonia with cyanosis", "give oxygen urgently and refer", "oxygen", "oxygen saturation"],
    ["pneumonia with delayed treatment by the caregiver", "counsel on the danger of delay in pneumonia", "not applicable", "not applicable"],
    ["pneumonia with no immunisation record", "update the immunisation after treatment", "not applicable", "immunisation card"],
    ["repeated pneumonia admissions", "assess for an underlying cause such as HIV", "not applicable", "HIV test"],
  ]],
  ["Maternal & Child Health", "breastfeeding support", [
    ["a baby taking only the nipple with a narrow mouth", "teach the mother correct attachment", "not applicable", "feeding assessment"],
    ["water and herbs given to a newborn", "counsel on exclusive breastfeeding for six months", "not applicable", "not applicable"],
    ["colostrum believed to be dirty and discarded", "teach that colostrum protects the baby", "not applicable", "not applicable"],
    ["painful cracked nipples while feeding", "correct the positioning and attachment", "not applicable", "not applicable"],
    ["engorgement with difficulty latching", "support frequent feeding and express before latching", "not applicable", "not applicable"],
    ["poor weight gain on breastfeeding", "assess attachment, frequency and refer for review", "not applicable", "infant weight"],
    ["a family pressuring the mother to use formula", "counsel the family and support continued breastfeeding", "not applicable", "not applicable"],
    ["HIV and questions about infant feeding", "counsel according to the national infant feeding guidance", "antiretroviral therapy", "viral load"],
    ["a mother returning to work and planning to stop", "teach expression and storage to keep breastfeeding", "not applicable", "not applicable"],
    ["feeding at only four-hour intervals", "teach feeding on demand at least eight times a day", "not applicable", "not applicable"],
  ]],
  ["Mental Health Nursing", "suicidal ideation", [
    ["a client saying life is not worth living with a plan", "initiate one-to-one observation and remove means", "not applicable", "risk assessment"],
    ["a client giving away possessions and writing a note", "assess the risk urgently and keep the client safe", "not applicable", "risk assessment"],
    ["suicidal ideas asked about in front of many people", "assess risk privately and sensitively", "not applicable", "risk assessment"],
    ["a client refusing to discuss suicidal thoughts", "assess directly and document the findings", "not applicable", "risk assessment"],
    ["a client discharged after a suicide attempt", "arrange follow-up and involve the family safely", "not applicable", "risk assessment"],
    ["access to medicines at home with low mood", "teach the family to remove means of self-harm", "not applicable", "risk assessment"],
    ["sudden calm after a period of despair", "increase observation as this may signal a decision", "not applicable", "risk assessment"],
    ["a previous attempt with current low mood", "assess the risk and agree a safety plan", "not applicable", "risk assessment"],
    ["fear of disclosing thoughts of self-harm", "provide a confidential and non-judgemental space", "not applicable", "not applicable"],
    ["a family unsure how to support a suicidal relative", "teach the family warning signs and support options", "not applicable", "not applicable"],
  ]],
  ["Mental Health Nursing", "acute psychosis", [
    ["voices commanding the client to harm others", "ask directly about the voices and assess safety", "haloperidol", "not applicable"],
    ["food refused because it is believed to be poisoned", "offer sealed alternatives and build trust", "not applicable", "not applicable"],
    ["a disorganised client unable to meet basic needs", "assist with hygiene and provide a calm environment", "antipsychotic", "not applicable"],
    ["an aggressive client escalating on the ward", "use verbal de-escalation before any restraint", "not applicable", "not applicable"],
    ["rigid muscles with a fever on antipsychotics", "treat as neuroleptic malignant syndrome and refer urgently", "not applicable", "serum creatine kinase"],
    ["withdrawal and sleeplessness before a relapse", "recognise the early signs and act quickly", "not applicable", "not applicable"],
    ["a client bathed in public view on the ward", "protect the client's privacy and dignity", "not applicable", "not applicable"],
    ["a family blaming the client for the illness", "educate the family and reduce the blame", "not applicable", "not applicable"],
    ["psychosis with alcohol dependence", "address both problems together in the care plan", "not applicable", "not applicable"],
    ["medicine stopped because of stigma at work", "plan adherence support and involve a trusted person", "antipsychotic", "not applicable"],
  ]],
  ["Mental Health Nursing", "alcohol withdrawal", [
    ["tremor and sweating 48 hours after the last drink", "institute seizure precautions and give benzodiazepines", "diazepam", "withdrawal score"],
    ["visual hallucinations two days after stopping alcohol", "assess the withdrawal score and give treatment", "diazepam", "withdrawal score"],
    ["a seizure during alcohol withdrawal", "protect from injury and give prescribed benzodiazepine", "diazepam", "not applicable"],
    ["thiamine deficiency with confusion", "give thiamine before any glucose infusion", "thiamine", "not applicable"],
    ["a wish to stop drinking for good", "arrange counselling and relapse prevention support", "not applicable", "not applicable"],
    ["denial of alcohol use despite the signs", "use a non-confrontational approach and build trust", "not applicable", "not applicable"],
    ["substance use with no family support", "arrange community and peer support services", "not applicable", "not applicable"],
    ["substances used to cope with grief", "address both the grief and the substance use", "not applicable", "not applicable"],
    ["questions about whether recovery is possible", "offer hope with realistic information about recovery", "not applicable", "not applicable"],
    ["relapse after a period of abstinence", "explore the triggers and restart support without blame", "not applicable", "not applicable"],
  ]],
  ["Mental Health Nursing", "severe anxiety", [
    ["hyperventilation with a sense of impending doom", "stay with the client and teach slow breathing", "not applicable", "oxygen saturation"],
    ["inability to speak during a panic attack", "remain calm, use short sentences and stay present", "not applicable", "not applicable"],
    ["chest pain with a normal ECG during an anxious episode", "assess fully before attributing it to anxiety", "not applicable", "ECG"],
    ["avoidance of all social situations for months", "refer for psychological therapy and support", "not applicable", "not applicable"],
    ["alcohol used to control anxiety", "assess for dependence and offer support", "not applicable", "not applicable"],
    ["palpitations with fear of dying and no physical cause", "stay with the client and teach slow breathing", "not applicable", "not applicable"],
    ["refusal to leave the ward after a panic attack", "support gradual re-exposure and reassurance", "not applicable", "not applicable"],
    ["disturbed sleep from persistent worry", "teach relaxation techniques and refer for review", "not applicable", "not applicable"],
    ["embarrassment about being anxious", "normalise the experience and reduce the stigma", "not applicable", "not applicable"],
    ["questions about whether anxiety is a real illness", "explain that anxiety is genuine and treatable", "not applicable", "not applicable"],
  ]],
  ["Mental Health Nursing", "epilepsy in the community", [
    ["a generalised seizure in the market", "protect from injury, position on the side and time the seizure", "diazepam", "not applicable"],
    ["medicine stopped for a traditional remedy", "respect their belief while restarting prescribed therapy", "carbamazepine", "not applicable"],
    ["a child with epilepsy excluded from school", "educate the school and support inclusion", "not applicable", "not applicable"],
    ["an injury during a seizure at home", "assess the injury and review the seizure control", "not applicable", "not applicable"],
    ["epilepsy with no previous treatment", "refer for assessment and start prescribed therapy", "anticonvulsant", "not applicable"],
    ["epilepsy with increasing seizures", "review the adherence and the medicine dose", "anticonvulsant", "not applicable"],
    ["a family believing epilepsy is contagious", "educate the family that epilepsy is not contagious", "not applicable", "not applicable"],
    ["questions about driving and work with epilepsy", "explain the safety restrictions honestly", "not applicable", "not applicable"],
    ["epilepsy in a pregnant client on anticonvulsants", "review the medicine and monitor the pregnancy", "anticonvulsant", "not applicable"],
    ["epilepsy with no medicine available locally", "arrange a supply and follow-up plan", "anticonvulsant", "not applicable"],
  ]],
  ["Infection Prevention", "sepsis", [
    ["a fever of 39 degrees with a blood pressure of 84/50", "give oxygen, cultures and antibiotics within one hour", "intravenous antibiotics", "serum lactate"],
    ["confusion with a respiratory rate of 28 and fever", "treat as sepsis and follow the one-hour bundle", "intravenous antibiotics", "serum lactate"],
    ["a lactate of 4.5 mmol/L with hypotension", "give fluids and vasopressors as prescribed", "noradrenaline", "serum lactate"],
    ["a urinary catheter with a new fever", "remove the catheter if not needed and send cultures", "intravenous antibiotics", "urine culture"],
    ["mottled skin with a capillary refill of four seconds", "assess for shock and give rapid fluids", "intravenous fluids", "serum lactate"],
    ["sepsis with delayed antibiotics", "escalate as delay increases mortality", "intravenous antibiotics", "not applicable"],
    ["sepsis with a poor urine output", "monitor the kidneys and the fluid resuscitation", "not applicable", "urine output"],
    ["recovery from sepsis with ongoing weakness", "plan rehabilitation and nutrition support", "not applicable", "not applicable"],
    ["a family asking how sepsis developed", "explain the infection and the treatment clearly", "not applicable", "not applicable"],
    ["sepsis discharged with no follow-up", "arrange follow-up and review the recovery", "not applicable", "not applicable"],
  ]],
  ["Infection Prevention", "surgical site infection", [
    ["redness and purulent discharge on day five", "take a swab and start prescribed antibiotics", "intravenous antibiotics", "wound swab"],
    ["a wound breaking open with serosanguinous discharge", "cover with a sterile dressing and notify the surgeon", "not applicable", "wound swab"],
    ["a fever with a tender inflamed wound after surgery", "assess the wound and report the findings", "intravenous antibiotics", "white blood cell count"],
    ["a wound treated without any hand hygiene", "stop the procedure and perform hand hygiene", "not applicable", "not applicable"],
    ["a slow-healing wound in a diabetic client", "optimise glucose control and assess nutrition", "insulin", "random blood glucose"],
    ["necrotic tissue in the wound base", "assess for debridement and choose the dressing", "not applicable", "not applicable"],
    ["a dressing soaked through", "change the dressing and monitor the drainage", "not applicable", "not applicable"],
    ["a wound with spreading redness", "mark the edge and escalate urgently", "not applicable", "not applicable"],
    ["questions about when stitches come out", "explain the usual removal time for the wound", "not applicable", "not applicable"],
    ["discharge with no dressing advice", "teach the family dressing and warning signs", "not applicable", "not applicable"],
  ]],
  ["Infection Prevention", "Clostridioides difficile", [
    ["watery diarrhoea after a course of antibiotics", "collect a stool specimen and start the specific therapy", "oral vancomycin", "stool test"],
    ["diarrhoea on a proton pump inhibitor", "review the medicine and follow infection precautions", "not applicable", "stool test"],
    ["C. difficile with alcohol hand rub in use", "switch to soap and water hand washing", "not applicable", "not applicable"],
    ["C. difficile in a shared ward", "isolate the client and use dedicated equipment", "not applicable", "not applicable"],
    ["recurrent diarrhoea after completing treatment", "report the recurrence for review", "not applicable", "stool test"],
    ["C. difficile with severe dehydration", "rehydrate and monitor the electrolytes", "intravenous fluids", "serum electrolytes"],
    ["C. difficile with abdominal pain and distension", "assess for complications and escalate", "not applicable", "abdominal x-ray"],
    ["questions about how C. difficile was caught", "explain the link with antibiotic use", "not applicable", "not applicable"],
    ["a family worried about C. difficile", "teach the family hand washing and precautions", "not applicable", "not applicable"],
    ["C. difficile discharged to a care home", "inform the receiving facility of the precautions", "not applicable", "not applicable"],
  ]],
  ["Infection Prevention", "blood transfusion safety", [
    ["back pain and fever ten minutes into a transfusion", "stop the transfusion and keep the line open with saline", "0.9 percent sodium chloride", "urinalysis"],
    ["a temperature rise of 1.5 degrees during transfusion", "stop the transfusion and assess the client", "not applicable", "vital signs"],
    ["dark urine with loin pain during a transfusion", "stop immediately and return the unit to the laboratory", "not applicable", "urinalysis"],
    ["a falling oxygen saturation during transfusion", "stop the transfusion and assess for fluid overload", "not applicable", "oxygen saturation"],
    ["transfusion without proper identification checks", "stop and repeat the two-person identification check", "not applicable", "not applicable"],
    ["a unit left out of the fridge before transfusion", "do not transfuse the unit and report it", "not applicable", "not applicable"],
    ["transfusion with no observations recorded", "record observations before, during and after", "not applicable", "vital signs"],
    ["questions about close monitoring during transfusion", "explain that reactions need quick action", "not applicable", "not applicable"],
    ["refusal of transfusion on religious grounds", "respect the refusal and plan alternative care", "not applicable", "not applicable"],
    ["anaemia and questions about alternatives to transfusion", "discuss the options with the clinical team", "not applicable", "haemoglobin level"],
  ]],
  ["Infection Prevention", "standard precautions", [
    ["hand hygiene skipped between two client contacts", "perform hand hygiene between every client contact", "not applicable", "not applicable"],
    ["the same syringe used for several clients", "use a new sterile syringe for every injection", "not applicable", "not applicable"],
    ["soiled linen carried uncovered through a corridor", "transport and process the linen safely", "not applicable", "not applicable"],
    ["sharps mixed with general waste in a bin", "segregate the waste into the correct colour-coded bins", "not applicable", "waste audit"],
    ["equipment shared without decontamination", "decontaminate and sterilise before reuse", "chlorine solution", "sterilisation record"],
    ["no gloves during a procedure with blood spillage", "use protective equipment and follow the exposure protocol", "post-exposure prophylaxis", "baseline screening"],
    ["a needle stick injury with no report", "wash, report and start post-exposure prophylaxis", "post-exposure prophylaxis", "baseline HIV test"],
    ["disposable masks reused to save supplies", "report the shortage and follow the safety standard", "not applicable", "not applicable"],
    ["an airborne infection in an open ward", "isolate the client and use the correct respirator", "not applicable", "not applicable"],
    ["a visitor with an infectious illness on the ward", "advise the visitor to postpone the visit", "not applicable", "not applicable"],
  ]],
  ["Fundamentals of Nursing", "medication safety", [
    ["an unclear verbal order for a high-alert medicine", "read back and clarify the order before giving", "not applicable", "not applicable"],
    ["a medicine about to be given without checking allergies", "stop and verify the allergy status first", "not applicable", "not applicable"],
    ["two clients with similar names on the same ward", "verify identity with two identifiers before any medicine", "not applicable", "not applicable"],
    ["a dose calculation the nurse is unsure about", "ask a second nurse or the pharmacist to verify", "not applicable", "not applicable"],
    ["a medicine label that is illegible", "do not give it and obtain a clear prescription", "not applicable", "not applicable"],
    ["a medicine given late without documentation", "document the delay and the reason for it", "not applicable", "not applicable"],
    ["a client asking what a medicine is for", "explain the purpose before administering it", "not applicable", "not applicable"],
    ["a client refusing a prescribed medicine", "explore the reason and inform the prescriber", "not applicable", "not applicable"],
    ["a crushed medicine given down a tube without checking", "confirm the medicine may be crushed first", "not applicable", "not applicable"],
    ["a medicine prepared and left unattended", "discard it and prepare a fresh dose", "not applicable", "not applicable"],
  ]],
  ["Fundamentals of Nursing", "fluid balance", [
    ["a urine output of 20 mL per hour for four hours", "report the oliguria and assess fluid status", "not applicable", "urine output"],
    ["a fluid balance showing a negative balance of 2 litres", "assess for dehydration and report the trend", "not applicable", "fluid balance chart"],
    ["an intake of 5 litres with only 800 mL output", "assess for retention and notify the provider", "not applicable", "fluid balance chart"],
    ["a client unable to drink after surgery", "start intravenous fluids as prescribed", "intravenous fluids", "serum electrolytes"],
    ["oedema with a positive fluid balance", "assess for overload and restrict fluids as prescribed", "not applicable", "daily weight"],
    ["a fluid balance chart with gaps", "complete the chart accurately every shift", "not applicable", "not applicable"],
    ["diarrhoea with a poor fluid intake", "assess for dehydration and increase fluids", "not applicable", "not applicable"],
    ["intravenous fluids with swollen legs", "assess for overload and report", "not applicable", "not applicable"],
    ["questions about why intake is measured", "explain that fluid balance guides treatment", "not applicable", "not applicable"],
    ["a poor intake in a confused client", "offer fluids regularly and supervise the intake", "not applicable", "not applicable"],
  ]],
  ["Fundamentals of Nursing", "pressure area care", [
    ["non-blanchable redness over the sacrum", "reposition every two hours and offload the area", "barrier cream", "Braden score"],
    ["a Braden score of 12 on admission", "start a pressure-relieving mattress and turn chart", "not applicable", "Braden score"],
    ["incontinence with broken skin", "clean, dry and apply a barrier product promptly", "barrier cream", "not applicable"],
    ["one position maintained for four hours", "reposition immediately and document the turning schedule", "not applicable", "not applicable"],
    ["a stage two pressure injury developing in hospital", "document, report and review the prevention plan", "not applicable", "wound assessment"],
    ["a pressure injury with a poor appetite", "refer to the dietitian for protein support", "protein supplement", "serum albumin"],
    ["a reddened bony prominence being massaged", "stop massaging as it damages the tissue further", "not applicable", "not applicable"],
    ["a pressure injury with heavy exudate", "choose an absorbent dressing and monitor", "not applicable", "not applicable"],
    ["questions about whether a pressure injury heals", "explain the healing process and the care plan", "not applicable", "not applicable"],
    ["discharge with a pressure injury risk", "teach the family repositioning and skin checks", "not applicable", "not applicable"],
  ]],
  ["Fundamentals of Nursing", "pain management", [
    ["pain scored 8 out of 10 an hour after analgesia", "reassess and escalate rather than repeating blindly", "not applicable", "pain score"],
    ["grimacing while denying pain", "use a behavioural pain scale and reassess", "not applicable", "pain score"],
    ["analgesia refused for fear of addiction", "explain the benefits and address the concern", "not applicable", "not applicable"],
    ["pain disturbing sleep every night", "review the analgesia timing and the plan", "not applicable", "pain score"],
    ["pain with constipation on opioids", "prescribe and give a regular laxative", "laxative", "not applicable"],
    ["pain with a respiratory rate of 8", "withhold the opioid and assess the airway", "naloxone", "respiratory rate"],
    ["pain during a move without analgesia", "give analgesia before the procedure or transfer", "analgesia", "not applicable"],
    ["poor understanding of the pain scale", "explain the scale and reassess consistently", "not applicable", "pain score"],
    ["pain expressed in a culturally different way", "assess using an appropriate and respectful method", "not applicable", "not applicable"],
    ["pain discharged with no plan", "teach the analgesia schedule and the follow-up", "not applicable", "not applicable"],
  ]],
  ["Fundamentals of Nursing", "documentation and handover", [
    ["a note written two hours after the event", "document the time of writing and the actual event time", "not applicable", "not applicable"],
    ["a crossed-out error with no signature", "follow the policy for correcting an entry", "not applicable", "not applicable"],
    ["a client record left open on a public computer", "log out and secure the record immediately", "not applicable", "not applicable"],
    ["a personal opinion recorded about the client", "record objective observations instead", "not applicable", "not applicable"],
    ["care given but not documented", "document the care as soon as possible", "not applicable", "not applicable"],
    ["a handover with no structured format", "use a structured tool and cover all clients", "not applicable", "not applicable"],
    ["a handover missing the outstanding tasks", "list and confirm all outstanding tasks", "not applicable", "not applicable"],
    ["a handover given in a busy open corridor", "move to a private area to protect confidentiality", "not applicable", "not applicable"],
    ["abbreviations nobody understands", "use only approved abbreviations and write clearly", "not applicable", "not applicable"],
    ["a chart accessed by an unauthorised person", "report the breach and follow the policy", "not applicable", "not applicable"],
  ]],
  ["Fundamentals of Nursing", "nutrition and elimination", [
    ["a serum albumin of 24 g/L with a poor intake", "refer to the dietitian for supplementation", "protein supplement", "serum albumin"],
    ["less than half of every meal eaten", "assess the intake and involve the dietitian", "protein supplement", "weight record"],
    ["unintentional weight loss of five percent in a month", "assess nutrition and monitor the weight weekly", "not applicable", "weight record"],
    ["dysphagia with coughing on thin fluids", "keep nil by mouth and refer for a swallow assessment", "not applicable", "swallow assessment"],
    ["a nasogastric tube with an unclear aspirate", "confirm tube position before feeding", "not applicable", "gastric aspirate pH"],
    ["no bowel movement for four days with distension", "assess the bowel sounds and consider a laxative", "laxative", "not applicable"],
    ["constipation with a poor fluid intake", "increase fluids and fibre as tolerated", "not applicable", "not applicable"],
    ["a catheter with no drainage", "check the tubing for kinks and the bag position", "not applicable", "not applicable"],
    ["incontinence with broken skin", "clean, dry and apply a barrier product promptly", "barrier cream", "not applicable"],
    ["questions about a normal bowel pattern", "explain the normal range and when to seek help", "not applicable", "not applicable"],
  ]],
];
