/**
 * Past NMC examination questions - Surgical Nursing paper (part 2).
 * Curated from verified past licensing examination papers.
 */

import type { PastQuestion } from "./past-paper-medical";

export const PAST_PAPER_SURGICAL_2: PastQuestion[] = [
  {
    stem: "Mrs. Ramatu Abdulai is a 65 year old woman with diagnosed genitourinary cancer. She is to undergo radiation therapy. This therapy is the treatment of choice for ...",
    options: [
      "Ovarian cancer",
      "Uterine carcinoma",
      "Squamous cell carcinoma of the cervix",
    ],
    correctIndex: 2,
    rationale: "Squamous cell carcinoma of the cervix is radiosensitive, thus radiation therapy is the most effective treatment option for it.",
    category: "Maternal & Child Health",
    verified: true,
  },
  {
    stem: "Mrs. Rita Akoto was rushed to the emergency unit with the complaint of an ankle sprain. Her condition could be classified under the following grades EXCEPT;",
    options: [
      "Grade 2 (moderate)",
      "Grade 4 (chronic)",
      "Grade 3 (severe)",
    ],
    correctIndex: 1,
    rationale: "Ankle sprains are classified based on the severity of the injury, which is typically graded 1 to 3. There is no such classification as Grade 4 for an ankle sprain. Grade 1 is mild.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "Mrs. Selina Klagono, a 30-year-old seamstress is admitted to your ward for laminectomy. Prior to the surgery, the surgeon requested a lumbar puncture to be done. During the lumbar puncture procedure, what would be your role as a Nurse to prevent her from experiencing post-lumbar puncture headache?",
    options: [
      "Instruct her to lie prone just after surgery",
      "Instruct her to sit up",
      "Instruct her to lie flat / supine for 1 to 2 hours",
    ],
    correctIndex: 2,
    rationale: "Post-lumbar puncture headache is caused by leakage of cerebrospinal fluid (CSF) from the puncture site, leading to a decrease in CSF pressure. The American Academy of Neurology recommends lying flat for 1 to 2 hours.",
    category: "Neurological Nursing",
    verified: true,
  },
  {
    stem: "Mrs. Takyi-Benson reported to the OPD with the complaint of lesions on the skin. Which of the following are noted to cause skin lesions? I. Mycobacterium ulcerans II. Mycobacterium tuberculosis III. Mycobacterium leprae IV. Mycobacterium aureus",
    options: [
      "I and III",
      "I, II and IV",
      "I, III and IV",
    ],
    correctIndex: 0,
    rationale: "Mycobacterium aureus is not a species of Mycobacterium, and M. tuberculosis is not typically known to cause primary skin lesions. On the flip side, M. ulcerans and M. leprae cause Buruli ulcer and leprosy respectively, both of which present with skin lesions.",
    category: "Infection Prevention",
    verified: true,
  },
  {
    stem: "Mrs. Theresa Oppong has been booked for laparotomy. As part of your preparations, you are to educate Mrs. Oppong on the various peri-operative phases that she is expected to go through. Which of the following statements describes the pre-operative phase?",
    options: [
      "Begins at the consulting room when the decision for surgery is made until transfer to the operating table",
      "Begins with admission of the patient to the anaesthesia care unit",
      "Involves the immediate preparation on the day of surgery until discharge",
    ],
    correctIndex: 0,
    rationale: "The pre-operative phase begins when the decision for surgical intervention is made and ends when the patient is transferred onto the operating room table.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "Mrs. Winfred Hajdo, aged 45 years has returned from the theatre after a successful laparotomy. Surgical wound healing typically occurs in how many phases?",
    options: [
      "Four",
      "Two",
      "Three",
    ],
    correctIndex: 0,
    rationale: "Surgical wound healing typically occurs in four phases: haemostasis, inflammatory phase, proliferative phase, and remodelling/maturation phase.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "Ms. Akua Busan, aged 45, reported at the OPD with a history of irregular circular skin lesions that were dull pink in colour with elevated margins. She was diagnosed with malignant melanoma. Which diagnostic investigation provides information on the level of invasion and thickness?",
    options: [
      "Excision biopsy",
      "A thorough history",
      "Physical examination",
    ],
    correctIndex: 0,
    rationale: "Excision biopsy provides information on the level of invasion and thickness of the lesion by removing the entire lesion with a margin of healthy tissue for microscopic depth evaluation (Breslow depth / Clark level).",
    category: "Infection Prevention",
    verified: true,
  },
  {
    stem: "Ms. Amina Zinabu, 21 years old, was admitted to the gynaecological ward with severe dysmenorrhoea. What would be your focus of care for Ms. Zinabu? I. Alleviation of pain II. Endurance of the pain III. Identification of underlying cause IV. Re-establishment of functional capacity",
    options: [
      "I, III and IV",
      "I and III",
      "II, III and IV",
    ],
    correctIndex: 0,
    rationale: "Interventions aim to provide pain relief, address the root cause, and promote recovery of functional capacity. Forcing pain endurance is not appropriate.",
    category: "Maternal & Child Health",
    verified: true,
  },
  {
    stem: "Ms. Cynthia had appendectomy a week ago. Her wound has healed with a thin scar tissue formation. How would you describe this type of wound healing?",
    options: [
      "Fourth intention",
      "Secondary intention",
      "Primary intention",
    ],
    correctIndex: 2,
    rationale: "In primary intention, the edges of the clean surgical wound are brought together and closed with sutures or staples, resulting in minimal scar tissue formation.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "Ms. Docia Adomako, a 26 year old university student, has been diagnosed with peritonitis and scheduled for surgery. The MAIN objective for a surgical intervention includes:",
    options: [
      "Resection and anastomosis of the intestine",
      "Removal of the infected content and correcting the cause",
      "Resection of the intestine alone",
    ],
    correctIndex: 1,
    rationale: "Peritonitis is an inflammation of the peritoneum usually caused by infection; the infected material must be removed and the underlying source corrected to prevent further sepsis.",
    category: "Gastrointestinal Nursing",
    verified: true,
  },
  {
    stem: "Ms. Dora Muri, aged 22 years, has undergone appendectomy and is brought back to the ward. What should the Nurse do to ensure that the patient's wound is free from infection?",
    options: [
      "Use adequate sterile dressing technique during wound dressing",
      "Take trolley to patient's bedside without disinfection",
      "Clean wound with non-sterile tap water",
    ],
    correctIndex: 0,
    rationale: "Maintaining strict asepsis and using sterile dressing materials protects the surgical wound from environmental pathogens and cross-infection.",
    category: "Infection Prevention",
    verified: true,
  },
  {
    stem: "Elorm Agboja, a 25 year old student, was rushed to the emergency unit with severe abdominal pain after falling from a height. Patient was pale and dizzy, BP 80/50 mmHg, with left upper quadrant tenderness and abdominal distension. A provisional diagnosis of splenic rupture was made. Which diagnostic investigation would confirm splenic rupture?",
    options: [
      "Abdominal paracentesis",
      "Abdominal X-ray",
      "Abdominal ultrasound scan (FAST)",
    ],
    correctIndex: 2,
    rationale: "Focused abdominal ultrasound (FAST) can quickly and accurately detect free fluid or blood in the peritoneal cavity, which is a key sign of splenic rupture.",
    category: "Gastrointestinal Nursing",
    verified: true,
  },
  {
    stem: "Ms. Gyanfua Afrani, a 20 year old student, presented with pain and a boil in the groin for 5 days. The MOST common causative agent for boils (furuncles) is:",
    options: [
      "Streptococcus aureus",
      "Staphylococcus aureus",
      "Pseudomonas aeruginosa",
    ],
    correctIndex: 1,
    rationale: "Staphylococcus aureus is the primary causative bacterium for furuncles (boils) and skin abscesses.",
    category: "Infection Prevention",
    verified: true,
  },
  {
    stem: "Mr. Sampson Adu-Mensah, 42 years old, was involved in an RTA. X-ray shows fracture of the nose. What would be the immediate nursing care?",
    options: [
      "Apply direct pressure to the nasal bridge",
      "Splint the nose with gauze",
      "Apply ice packs and keep the head elevated",
    ],
    correctIndex: 2,
    rationale: "Elevating the head reduces blood flow and venous pressure while cold application produces vasoconstriction to minimise swelling, bleeding, and pain.",
    category: "Respiratory Nursing",
    verified: true,
  },
  {
    stem: "Ms. Isabella France, a 38-year-old woman, reported passage of faeces draining through the vagina. The Gynaecologist is likely to diagnose:",
    options: [
      "Anal fissure",
      "Rectovaginal fistula",
      "Perineal tear",
    ],
    correctIndex: 1,
    rationale: "Passage of flatus or faeces through the vagina is the hallmark sign of a rectovaginal fistula.",
    category: "Maternal & Child Health",
    verified: true,
  },
  {
    stem: "Ms. Joyce Adansnsa, aged 55 years, has painless blurred vision with opacity of the eye lens. Diagnosed with cataract and booked for surgery. An early post-operative complication is:",
    options: [
      "Fungal blepharitis",
      "Retrobulbar infiltration",
      "Bacterial endophthalmitis",
    ],
    correctIndex: 2,
    rationale: "Bacterial endophthalmitis is a devastating early intraocular infection following cataract surgery requiring immediate emergency intervention.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "Ms. Kakraba Forson has intermittent bleeding per vagina, diagnosed with uterine myoma, and booked for total hysterectomy. This procedure involves removal of the:",
    options: [
      "Uterus and cervix",
      "Uterus, cervix and fallopian tubes",
      "Uterus, cervix, fallopian tubes and ovaries",
    ],
    correctIndex: 0,
    rationale: "Total hysterectomy involves surgical removal of the uterus and the cervix. Salpingo-oophorectomy removes the adnexa.",
    category: "Maternal & Child Health",
    verified: true,
  },
  {
    stem: "Ms. Lovia Danquah, aged 38, is admitted with pelvic inflammatory disease (PID). To promote home-based care and prevent recurrence, the Nurse educates her to:",
    options: [
      "Use barrier protection (condoms) during sexual intercourse",
      "Have a gynaecological examination every week",
      "Perform vaginal douching weekly",
    ],
    correctIndex: 0,
    rationale: "Barrier contraception prevents transmission of sexually transmitted pathogens (gonorrhoea, chlamydia) that trigger recurrent PID. Douching is harmful.",
    category: "Maternal & Child Health",
    verified: true,
  },
  {
    stem: "Ms. Mabel Owari, a 21 year old student, has undergone tonsillectomy. What would be your immediate post-operative positioning?",
    options: [
      "On the back with head flat",
      "Prone or side-lying with head turned to the side",
      "High-Fowler's with neck flexed",
    ],
    correctIndex: 1,
    rationale: "Placing the patient prone or lateral with the head turned allows blood and secretions to drain naturally from the mouth, preventing aspiration.",
    category: "Respiratory Nursing",
    verified: true,
  },
  {
    stem: "Ms. Mercy Adams, 23 years old, has been booked for elective lower extremity amputation of the right leg. Which condition is the MOST frequent cause for lower limb amputation overall?",
    options: [
      "Electrical burns",
      "Malignant tumours",
      "Peripheral vascular disease secondary to diabetes mellitus",
    ],
    correctIndex: 2,
    rationale: "Diabetes mellitus and associated severe peripheral vascular disease and neuropathy are the leading causes of non-traumatic lower extremity amputations.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "Ms. Sabina Pentsil is scheduled to undergo right leg amputation under general anaesthesia. Which of the following statements BEST describe informed consent? I. A legal document required before invasive surgery II. A manual that guides the surgical process III. An operative permit IV. Protects the client, surgical team, and healthcare facility",
    options: [
      "I, III and IV",
      "I, II and III",
      "II and IV",
    ],
    correctIndex: 0,
    rationale: "Informed consent is an operative permit and legal document that ensures patient autonomy and protects all parties by confirming risks, benefits, and alternatives were explained.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "Ms. Vivian Saabo, 21 years old, was admitted with severe lower abdominal pain and fever, diagnosed with pelvic appendicitis. Which presentation is MOST consistent with pelvic appendicitis?",
    options: [
      "Rectal tenesmus, loose stools, and urinary frequency/irritation",
      "Pain on extension of the right thigh only",
      "Right upper quadrant flank tenderness",
    ],
    correctIndex: 0,
    rationale: "Because the inflamed appendix lies adjacent to the rectum and bladder in the pelvis, it causes symptoms of rectal irritation (diarrhoea/tenesmus) and bladder irritation (dysuria/frequency).",
    category: "Gastrointestinal Nursing",
    verified: true,
  },
  {
    stem: "Ms. Yvonne Atubam, aged 58 years, reported with a suspected breast mass. The following diagnostic tests may be ordered to confirm EXCEPT:",
    options: [
      "Percutaneous core needle biopsy",
      "Excisional biopsy",
      "Percussion of the breast",
    ],
    correctIndex: 2,
    rationale: "Percussion provides no diagnostic utility in breast tissue pathology and cannot distinguish benign from malignant breast lesions.",
    category: "Maternal & Child Health",
    verified: true,
  },
  {
    stem: "Multiple non-inflamed sac-like herniations of the intestinal mucosa through the muscular layer of the bowel is termed:",
    options: [
      "Diverticular disease",
      "Diverticulum",
      "Diverticulosis",
    ],
    correctIndex: 2,
    rationale: "Diverticulosis describes the presence of multiple uninflamed outpouchings (diverticula) in the colon. When inflamed, it is diverticulitis.",
    category: "Gastrointestinal Nursing",
    verified: true,
  },
  {
    stem: "Mustapha Ogee, a 60-year-old farmer, underwent ORIF for a hip fracture. A few hours later he becomes suddenly confused, tachypnoeic, and dyspnoeic. Which complications may explain these clinical manifestations? I. Deep vein thrombosis II. Pulmonary embolism III. Fat embolism syndrome IV. Compartment syndrome",
    options: [
      "I, II and III",
      "I, II and IV",
      "II and III",
    ],
    correctIndex: 0,
    rationale: "Sudden dyspnoea, tachypnoea, and acute confusion in a post-op long-bone/hip fracture patient strongly suggest pulmonary embolism or fat embolism syndrome.",
    category: "Cardiovascular Nursing",
    verified: true,
  },
  {
    stem: "Naa Awula Dodoo, 38 years, diagnosed with uterine fibroids, complains of backache, pelvic pressure, bloating, and constipation. The Nurse explains these symptoms result from:",
    options: [
      "Pressure effect of the enlarging fibroids on surrounding pelvic organs",
      "Direct effect of the fibroids on gastric acid secretion",
      "Venous pooling in the upper extremities",
    ],
    correctIndex: 0,
    rationale: "Enlarging intramural or subserosal fibroids compress the rectum (constipation), bladder (frequency), and lumbosacral nerves (backache).",
    category: "Maternal & Child Health",
    verified: true,
  },
  {
    stem: "Mr. Akaizi, 52 years old, underwent total hip replacement surgery. On day 2 he complains of severe unilateral calf pain and swelling. Which medication should the nurse ensure is ordered for venous thromboembolism prophylaxis?",
    options: [
      "Rocephin",
      "Unfractionated or low-molecular-weight heparin",
      "Morphine sulphate",
    ],
    correctIndex: 1,
    rationale: "Anticoagulation (heparin / LMWH) is essential for prophylaxis and treatment of deep vein thrombosis following major orthopaedic joint surgery.",
    category: "Cardiovascular Nursing",
    verified: true,
  },
  {
    stem: "Nurse Aba is assessing pain in an 82-year-old retired banker who had open-heart surgery. When assessing pain in the elderly, the nurse must consider that:",
    options: [
      "Elderly patients do not feel pain",
      "Sensory perception may be altered and atypical presentations can occur",
      "Elderly patients always over-report mild pain",
    ],
    correctIndex: 1,
    rationale: "Physiological aging decreases sensory transmission and may alter cognitive perception, meaning pain may present atypically (e.g. confusion, restlessness) rather than standard complaint.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "Nurse Abaka is performing assessment on a victim of an RTA. The nurse suspects multiple bilateral leg fractures. Which initial assessment of the extremities is MOST crucial?",
    options: [
      "Neurovascular assessment (pulses, capillary refill, sensation, temperature)",
      "Testing weight-bearing ability immediately",
      "Checking range of motion against resistance",
    ],
    correctIndex: 0,
    rationale: "Assessing distal neurovascular integrity (pulses, sensation, colour, temperature) is critical before moving or splinting fractured limbs to identify vascular compromise.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "Nurse Abeeku is caring for a patient with a feeding gastrostomy. Which of the following is a classic mechanical complication?",
    options: [
      "Inadvertent tube displacement or dislodgement",
      "Immediate wound evisceration",
      "Complete small bowel obstruction",
    ],
    correctIndex: 0,
    rationale: "Accidental tube dislodgement before the tract has matured is a serious complication that can allow feeding formula to leak into the peritoneal cavity.",
    category: "Gastrointestinal Nursing",
    verified: true,
  },
  {
    stem: "Nurse Aminatu is preparing a patient for paracentesis abdominis. Before the trocar needle is inserted, the nurse MUST instruct the patient to:",
    options: [
      "Empty the urinary bladder completely",
      "Drink two litres of water",
      "Maintain a strict Trendelenburg position",
    ],
    correctIndex: 0,
    rationale: "Emptying the bladder immediately prior to paracentesis prevents accidental trocar puncture of a distended bladder.",
    category: "Gastrointestinal Nursing",
    verified: true,
  },
  {
    stem: "Nurse Comfort is interviewing a client about his medical history. Which existing condition should alert the nurse to an increased risk of colorectal cancer?",
    options: [
      "Adenomatous polyps of the colon",
      "External haemorrhoids",
      "Irritable bowel syndrome without bleeding",
    ],
    correctIndex: 0,
    rationale: "Adenomatous colorectal polyps are pre-cancerous lesions that can transform into invasive adenocarcinoma over time.",
    category: "Gastrointestinal Nursing",
    verified: true,
  },
  {
    stem: "Which statement made by a circulating nurse indicates a need for further teaching regarding circulating roles during surgery?",
    options: [
      "\"I must ensure strict aseptic practices are maintained in the theatre.\"",
      "\"It is solely the anaesthetist's responsibility to verify signed surgical consent.\"",
      "\"I coordinate the needs of the sterile team and manage environmental controls.\"",
    ],
    correctIndex: 1,
    rationale: "The operating surgeon carries the primary legal responsibility to verify informed surgical consent, supported by the nursing team during the pre-op check.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "Nurse Kankai is teaching student nurses on orthopaedic cast application. Which of the following is NOT a recognized type of rigid plaster/fibre cast?",
    options: [
      "Full cylinder cast",
      "Half cast (split slab is a splint/backslab, not a finished circular cast)",
      "Short arm cast",
    ],
    correctIndex: 1,
    rationale: "Circular casts are complete tubular structures (short/long arm or leg); a half-slab is an open splint or backslab used prior to swelling reduction.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "Nurse Kobo is planning care for a 35 year old patient with oesophageal stricture. Which nursing diagnosis demands highest PRIORITY?",
    options: [
      "Risk for aspiration related to impaired swallowing",
      "Deficient knowledge regarding soft foods",
      "Activity intolerance related to fatigue",
    ],
    correctIndex: 0,
    rationale: "Airway and pulmonary protection are paramount; food or liquid regurgitated into the trachea can cause fatal aspiration or chemical pneumonitis.",
    category: "Gastrointestinal Nursing",
    verified: true,
  },
  {
    stem: "Nurse Kwame is suctioning an adult patient with a tracheostomy tube. Each suction catheter pass MUST NOT exceed:",
    options: [
      "10 to 15 seconds",
      "30 seconds",
      "45 seconds",
    ],
    correctIndex: 0,
    rationale: "Prolonged tracheal suctioning beyond 10–15 seconds induces severe alveolar hypoxia, mucosal trauma, and vagal-mediated bradycardia.",
    category: "Respiratory Nursing",
    verified: true,
  },
  {
    stem: "On the 3rd postoperative day after laparotomy, a patient complains of sudden severe pain, tenderness, and warmth in the right calf. The nurse should immediately:",
    options: [
      "Encourage the patient to walk vigorously to dissolve the clot",
      "Massage the calf muscle with warm liniment",
      "Elevate the affected leg, instruct bed rest, avoid massage, and notify the physician",
    ],
    correctIndex: 2,
    rationale: "Never massage a suspected DVT due to the high risk of dislodging an embolus to the lungs. Elevate, rest, and alert the surgeon.",
    category: "Cardiovascular Nursing",
    verified: true,
  },
  {
    stem: "Which congenital heart defect is classically cyanotic due to right-to-left shunting?",
    options: [
      "Tetralogy of Fallot",
      "Atrial septal defect (ASD)",
      "Patent ductus arteriosus (PDA)",
    ],
    correctIndex: 0,
    rationale: "Tetralogy of Fallot involves severe pulmonary stenosis and a large VSD causing deoxygenated blood to bypass the lungs into the systemic circulation (cyanosis).",
    category: "Cardiovascular Nursing",
    verified: true,
  },
  {
    stem: "What is the primary purpose of an underwater-seal chest drainage system?",
    options: [
      "To allow air and fluid to exit the pleural space while preventing atmospheric air from re-entering",
      "To irrigate the pleural cavity with antibiotic solution",
      "To maintain positive pressure within the thoracic cage",
    ],
    correctIndex: 0,
    rationale: "The water seal acts as a one-way valve: positive intrapleural pressure pushes air and fluid out through the water, but atmospheric air cannot be sucked back in.",
    category: "Respiratory Nursing",
    verified: true,
  },
  {
    stem: "The MOST appropriate position for a client undergoing rigid or flexible sigmoidoscopy is:",
    options: [
      "Sims' left lateral position",
      "Supine position with legs flat",
      "Trendelenburg position",
    ],
    correctIndex: 0,
    rationale: "Left lateral Sims' position aligns the anatomical curve of the sigmoid colon with the rectum, facilitating scope insertion with minimal discomfort.",
    category: "Gastrointestinal Nursing",
    verified: true,
  },
  {
    stem: "What is the MOST serious immediate post-operative complication to monitor for following tonsillectomy?",
    options: [
      "Haemorrhage (frequent swallowing)",
      "Constipation",
      "Mild dehydration",
    ],
    correctIndex: 0,
    rationale: "Tonsillar beds are highly vascular; frequent swallowing is the classic early warning sign of active post-tonsillectomy haemorrhage trickling down the pharynx.",
    category: "Respiratory Nursing",
    verified: true,
  },
  {
    stem: "Normal intraocular pressure (IOP) measured by tonometry in a healthy adult is:",
    options: [
      "10 to 21 mmHg",
      "25 to 35 mmHg",
      "40 to 50 mmHg",
    ],
    correctIndex: 0,
    rationale: "Normal physiological IOP ranges from 10 to 21 mmHg. Values consistently above 21 mmHg warrant investigation for ocular hypertension or glaucoma.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "A patient who had abdominal surgery develops wound dehiscence with evisceration (organs protruding). The nurse's immediate action is to:",
    options: [
      "Cover the protruding viscera with sterile gauze moistened with normal saline",
      "Attempt to push the protruding organs back inside the abdominal cavity",
      "Place the patient prone to apply pressure to the wound",
    ],
    correctIndex: 0,
    rationale: "Protruding organs must be kept sterile and moist with saline-soaked dressings to prevent tissue drying, necrosis, and bacterial contamination while surgical repair is organized. Never attempt manual reinsertion.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "When teaching a patient with a new colostomy how to perform irrigation, the nurse instructs that the fluid container should hang:",
    options: [
      "45 to 50 cm (18 to 20 inches) above the stoma level",
      "At least 2 metres high to maximize pressure",
      "Below the patient's hip level",
    ],
    correctIndex: 0,
    rationale: "Hanging the irrigation reservoir 45 cm (18 inches) above the stoma provides a gentle hydrostatic pressure gradient without causing bowel cramping or perforation.",
    category: "Gastrointestinal Nursing",
    verified: true,
  },
  {
    stem: "Following a total thyroidectomy, which emergency equipment MUST be kept at the patient's bedside?",
    options: [
      "Emergency tracheostomy tray, suction equipment, and IV calcium gluconate",
      "Defibrillator pads only",
      "Blood transfusion tubing only",
    ],
    correctIndex: 0,
    rationale: "Tracheal compression from haematoma or laryngeal oedema can cause sudden airway obstruction, and accidental parathyroid removal triggers acute hypocalcaemic tetany requiring IV calcium gluconate.",
    category: "Endocrine Nursing",
    verified: true,
  },
  {
    stem: "In Wallace's Rule of Nines for adult burn estimation, what percentage is assigned to the entire anterior trunk (chest and abdomen)?",
    options: [
      "18%",
      "9%",
      "36%",
    ],
    correctIndex: 0,
    rationale: "In an adult, the anterior trunk (chest + abdomen) is 18%, posterior trunk is 18%, each entire leg is 18%, each entire arm is 9%, head is 9%, and perineum is 1%.",
    category: "Fundamentals of Nursing",
    verified: true,
  },
  {
    stem: "Following a right modified radical mastectomy, the nurse should ensure that:",
    options: [
      "No blood pressure measurements, venipunctures, or injections are performed on the right arm",
      "The right arm is kept strictly dependent below the waist",
      "A tight compression tourniquet is kept on the right forearm",
    ],
    correctIndex: 0,
    rationale: "Axillary lymph node dissection impairs lymphatic drainage; invasive procedures or constriction on the operative arm increase the risk of chronic lymphedema and serious infection.",
    category: "Maternal & Child Health",
    verified: true,
  },
];
