/**
 * Past NMC examination questions - Medical Nursing paper (part 3).
 */

import type { PastQuestion } from "./past-paper-medical";

export const PAST_PAPER_MEDICAL_3: PastQuestion[] = [
  {
    stem: "Nurse Agnes Ofori inserted a small-bored nasogastric feeding tube prior to feeding a client. The BEST way to confirm the correct placement of the tube is by?",
    options: [
      "X-ray of the stomach",
      "Observing the client for coughing",
      "Pushing fluid to check patency",
      "Auscultating over the epigastrium",
    ],
    correctIndex: 0,
    rationale: "X-ray of the stomach can confirm that the tip of the tube is in the stomach and not in the lungs or oesophagus. Other methods such as observing for coughing or pushing air are not as reliable.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Nurse Akorful is caring for a client diagnosed with peptic ulcer disease. Which observations should the nurse report immediately to the physician?",
    options: [
      "Hypotension, board-like rigidity of the abdomen, tachycardia and restlessness",
      "Hypotension, thirst, board-like rigidity, tachycardia and restlessness",
      "Hypotension, board-like rigidity, tachycardia, restlessness and diarrhoea",
      "Thirst, diarrhoea and restlessness",
    ],
    correctIndex: 0,
    rationale: "Hypotension may indicate haemorrhagic shock, while board-like rigidity of the abdomen is a sign of perforation. Both are medical emergencies requiring prompt attention. Tachycardia and restlessness are also urgent findings.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Nurse Ampiah is assessing a 48-year-old diagnosed with hypoparathyroidism. The nurse observes spasm of the facial muscles on tapping the facial nerve. This sign is known as?",
    options: [
      "Chvostek's sign",
      "Murphy's sign",
      "Trousseau's sign",
      "Kernig's sign",
    ],
    correctIndex: 0,
    rationale: "Chvostek's sign is a clinical sign used to assess facial nerve irritability and is seen in clients with hypoparathyroidism. It is elicited by tapping on the facial nerve, causing contraction of the facial muscles.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "Nurse Budu is initiating peritoneal dialysis for a client with renal failure. During instillation of the dialysate the client reports abdominal pain. Which intervention is MOST appropriate?",
    options: [
      "Stop the dialysis immediately and report to the physician",
      "Explain that pain will subside after a few exchanges",
      "Ask if the client is constipated and administer a mild laxative",
      "Slow the instillation rate and continue",
    ],
    correctIndex: 0,
    rationale: "Abdominal pain during peritoneal dialysis could indicate peritonitis or bowel perforation, which are serious complications that require immediate medical attention.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Nurse Ella Nsono is performing abdominal examination for a client suspected of having appendicitis. During deep palpation, the nurse should expect intense pain in the?",
    options: [
      "Right iliac region",
      "Right lumbar region",
      "Right hypochondriac region",
      "Left iliac region",
    ],
    correctIndex: 0,
    rationale: "The right iliac region is the location of the appendix and deep palpation in this area could elicit pain if the appendix is inflamed.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Nurse Frimpong is preparing a client for bronchoscopy. Which necessary information does the client need?",
    options: [
      "Informed consent is necessary, and sedation will be used during the procedure",
      "A light meal may be taken in the morning, and a cleaning enema may be required",
      "No preparation is needed as it is a simple procedure",
      "The client will need to be admitted for three days",
    ],
    correctIndex: 0,
    rationale: "Informed consent is necessary for any invasive procedure, and sedation is commonly used to help reduce anxiety and discomfort during the procedure.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "Nurse Irene Adu is assigned to care for a client with cholelithiasis. She observes the client's stools to be grey in colour. The nurse understands the change in stool is due to?",
    options: [
      "Decreased bile in stool",
      "Decreased liver function",
      "Poor bile secretion",
      "Increased bilirubin",
    ],
    correctIndex: 0,
    rationale: "In cholelithiasis gallstones can obstruct the bile ducts, leading to decreased bile flow into the intestines and a resulting decrease in the amount of bile pigments in the stool, causing grey-coloured stool.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Nurse Linda Jaja was giving a health talk on priapism as a complication of sickle cell disease. She mentioned priapism is BEST managed by?",
    options: [
      "Emptying the bladder at the onset of the attack, and seeking medical attention if the condition goes beyond three hours",
      "Taking a warm bath and seeking medical attention if it goes beyond three hours",
      "Emptying the bladder and taking a warm bath only",
      "Applying ice packs and waiting for resolution",
    ],
    correctIndex: 0,
    rationale: "Emptying the bladder at the onset of the attack can help relieve pressure on the blood vessels, while seeking medical attention if the condition goes beyond three hours is important to prevent long-term damage to the penis.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Nurse Mercy Ashong was asked to prepare a trolley for pericardiocentesis. To which client's bedside will the nurse send the prepared trolley?",
    options: [
      "A client diagnosed with cardiac tamponade",
      "A client diagnosed with constrictive pericarditis",
      "A client diagnosed with myocardial infarction",
      "A client diagnosed with endocarditis",
    ],
    correctIndex: 0,
    rationale: "Pericardiocentesis is a procedure in which a needle is inserted through the chest to remove excess fluid from the sac surrounding the heart, and this is the treatment of choice for cardiac tamponade to relieve pressure on the heart.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Nurse Mpuni is caring for a client who has undergone oesophagogastroduodenoscopy. Which aspect of care should the nurse place the highest priority on?",
    options: [
      "Assessing for the return of the gag reflex",
      "Administering warm gargles to soothe the throat",
      "Monitoring the temperature",
      "Offering oral fluids immediately",
    ],
    correctIndex: 0,
    rationale: "Oesophagogastroduodenoscopy requires the client to be under sedation, which can lead to a temporary loss of the gag reflex. Assessing for its return is the highest priority to prevent aspiration.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "The nurse is caring for a client after a bronchoscopy and biopsy. Which finding, if noted, should be reported immediately to the physician?",
    options: [
      "Bronchospasm",
      "Dry cough",
      "Haematuria",
      "Mild sore throat",
    ],
    correctIndex: 0,
    rationale: "Bronchospasm is a sudden constriction of the smooth muscle in the walls of the bronchi, causing difficulty in breathing and can be life-threatening. It is a potential complication of bronchoscopy and biopsy.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "The nurse completed the admission process for a client diagnosed with pulmonary oedema. Which signs is the nurse expected to find?",
    options: [
      "Persistent cough, breathing better in a sitting up position, and increased heart rate",
      "Persistent cough, increased urine output and decreased heart rate",
      "Increased urine output, breathing better lying flat, and decreased heart rate",
      "Decreased cough, breathing worse sitting up, and normal heart rate",
    ],
    correctIndex: 0,
    rationale: "A persistent cough is a common symptom of pulmonary oedema as the lungs become congested with fluid. Breathing is easier in a sitting up position which alleviates pressure on the lungs, and the heart rate increases in response to the reduced oxygen supply.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "The nurse was asked to administer calcium gluconate to a client. This medicine MUST be administered slowly because it can?",
    options: [
      "Cause cardiac arrest when given rapidly",
      "Impair consciousness level when given rapidly",
      "Increase parathyroid hormone secretion rapidly",
      "Cause severe hypotension",
    ],
    correctIndex: 0,
    rationale: "Calcium gluconate is used to treat low blood calcium levels or protect the heart from certain medicines or toxins. When given too quickly it can cause hypercalcaemia, which can lead to dangerous cardiac arrhythmias and cardiac arrest.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "The nurse is performing an abdominal examination for a client suspected of having appendicitis. Light palpation can identify the following EXCEPT?",
    options: [
      "Hypersensitivity",
      "Abscesses",
      "Muscular resistance",
      "Guarding",
    ],
    correctIndex: 0,
    rationale: "Light palpation can identify certain abdominal conditions such as abscesses and muscular resistance, but it cannot identify hypersensitivity, which is a sensory response to touch or pressure and not a physical finding identifiable through palpation.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A nursing care plan is prepared for nursing clients to achieve which one of the following goals?",
    options: [
      "Promote continuity of care from nurses on all shifts",
      "Change the nursing actions to improve the client's response",
      "Determine how far the client has tolerated the care given",
      "Reduce the workload of the nursing staff",
    ],
    correctIndex: 0,
    rationale: "The primary goal of a nursing care plan is to promote continuity of care from nurses on all shifts, ensuring that every nurse understands the plan and can deliver consistent, individualised care.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A nursing diagnosis for a client diagnosed with chronic renal failure who has developed disseminated intravascular coagulation (DIC) would be?",
    options: [
      "Altered tissue perfusion related to blocked microcirculation",
      "Altered renal function related to less performance",
      "Decreased cardiac output related to fluid overload",
      "Impaired gas exchange related to pulmonary oedema",
    ],
    correctIndex: 0,
    rationale: "The most appropriate nursing diagnosis directly addresses the issue of renal perfusion in DIC and highlights the blocked microcirculation and impaired renal function.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "On the female medical ward a client with hyperthyroidism develops myxoedema after treatment. The KEY sign associated with myxoedema is?",
    options: [
      "Weight gain",
      "Irritability",
      "Heat intolerance",
      "Exophthalmos",
    ],
    correctIndex: 0,
    rationale: "The key sign associated with myxoedema is weight gain, as clients with myxoedema tend to have a significant increase in body weight due to fluid retention in the subcutaneous tissues.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "On the medical ward a client with coronary thrombosis complains of pain and asks for pain relief. The pain associated with coronary thrombosis is caused primarily by?",
    options: [
      "Ischaemia of the heart muscles",
      "Blocking of the coronary veins",
      "Arterial spasm",
      "Pericardial inflammation",
    ],
    correctIndex: 0,
    rationale: "Ischaemia of the heart muscles is the correct answer, as the pain is caused by insufficient blood flow to the heart muscles, resulting in tissue damage and the release of pain-inducing substances.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "On the medical ward a client diagnosed with herpes zoster complains of severe pains in the affected area. Which nerve is affected?",
    options: [
      "Sensory nerve",
      "Motor nerve",
      "Mixed nerve",
      "Autonomic nerve",
    ],
    correctIndex: 0,
    rationale: "Herpes zoster, also known as shingles, is caused by reactivation of the varicella-zoster virus, which affects the nerve roots and causes a painful rash. The nerve affected is most likely a sensory nerve.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "On the medical ward a client diagnosed with liver cirrhosis is booked for paracentesis abdominis. In preparing this client for the procedure you will explain that the needle would be inserted?",
    options: [
      "2 to 4 cm above the umbilicus",
      "Between the 4th and 5th intercostal space",
      "Mid-line halfway between the umbilicus and symphysis pubis",
      "In the left iliac fossa",
    ],
    correctIndex: 0,
    rationale: "Paracentesis abdominis involves inserting a needle into the peritoneal cavity to remove excess fluid from the abdominal cavity. The needle is typically inserted 2 to 4 cm above the umbilicus, taking care to avoid important blood vessels and organs.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "One of the complications of haemolytic streptococcal infection is?",
    options: [
      "Rheumatic heart disease",
      "Cerebrospinal meningitis",
      "Rheumatoid arthritis",
      "Nephrotic syndrome",
    ],
    correctIndex: 0,
    rationale: "Haemolytic streptococcal infection is known to produce antigens that can cross-react with heart tissue, leading to the development of rheumatic heart disease as a post-streptococcal complication.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "One of the major causes of chronic ill health in the tropics is malaria. Which are among the chronic complications of malaria?",
    options: [
      "Chronic anaemia and failure to thrive",
      "Nephrotic syndrome only",
      "Failure to thrive and nephrotic syndrome only",
      "Chronic anaemia and nephrotic syndrome only",
    ],
    correctIndex: 0,
    rationale: "Repeated episodes of malaria can cause chronic blood loss leading to chronic anaemia, and result in reduced appetite, growth delays and developmental problems, contributing to failure to thrive particularly in children and other vulnerable populations.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "Opanin Antokuo, 75 years, a chain smoker and known diabetic, reported with purulent cough, chest pain, difficulty in breathing, loss of appetite and weight loss. Pleural effusion was diagnosed and he is scheduled for underwater seal drainage after chest tube insertion. Which nursing action is appropriate before the procedure?",
    options: [
      "Maintain nil per os for the client",
      "Assess the area of insertion for lesions",
      "Teach the client to remain still and hold breath as the tube is inserted",
      "Encourage oral fluids to clear the lungs",
    ],
    correctIndex: 0,
    rationale: "The most appropriate nursing action before the procedure is to maintain nil per os for the client to minimise the risk of aspiration during the procedure.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "Opanyin Daniel Sey reported with history of weight loss, weakness and increased urinary output. A provisional diagnosis of diabetes mellitus was made. What differentiates diabetes mellitus from diabetes insipidus? The client may experience increased?",
    options: [
      "Hunger",
      "Fatigue",
      "Thirst",
      "Urination",
    ],
    correctIndex: 0,
    rationale: "Both diabetes mellitus and diabetes insipidus can cause increased thirst and frequent urination, but the presence of increased hunger is more commonly associated with diabetes mellitus.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "Osmoreceptors involved in the regulation of thirst are located in which part of the brain?",
    options: [
      "Hypothalamus",
      "Cerebellum",
      "Thalamus",
      "Medulla oblongata",
    ],
    correctIndex: 0,
    rationale: "The hypothalamus plays a crucial role in regulating thirst and maintaining fluid and electrolyte concentration balance in the blood, signalling the need for hydration.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "Osteomalacia is common in women of childbearing age. Choose the BEST way to prevent this disease from occurring?",
    options: [
      "Daily intake of 400 IU of vitamin D",
      "Frequent intake of iodized salt",
      "Daily intake of ascorbic acid",
      "Increased protein intake",
    ],
    correctIndex: 0,
    rationale: "A daily intake of 400 IU of vitamin D helps in the absorption of calcium, a mineral essential for strong bones, and prevents osteomalacia.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Clients diagnosed with renal failure may have sodium and water restricted in their diets because they contribute to?",
    options: [
      "Hypertension",
      "Uraemia",
      "Hyperlipidaemia",
      "Metabolic acidosis",
    ],
    correctIndex: 0,
    rationale: "Excessive intake of sodium and water can cause an increase in blood volume, leading to an increase in blood pressure, which can contribute to the development of hypertension.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Plans to assist in the rehabilitation of a client after a cerebrovascular accident include?",
    options: [
      "Encourage any attempts to assist in care activities",
      "Accept that independent existence is impossible",
      "Keep working on skills until they are perfected",
      "Discourage the client from attempting self-care",
    ],
    correctIndex: 0,
    rationale: "Encouraging the client to participate in their own care helps promote independence and helps them regain their functional abilities after a cerebrovascular accident.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "The recommended dietary regimen in the management of a client with acute renal failure is high carbohydrate and?",
    options: [
      "Low potassium",
      "High protein",
      "High potassium",
      "High fat",
    ],
    correctIndex: 0,
    rationale: "High protein intake can increase the workload on the kidneys, while high potassium intake can be harmful in the presence of renal impairment. Carbohydrates may be included to provide energy, but the primary focus is on limiting protein and potassium intake.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Risk factors associated with cerebrovascular accident include?",
    options: [
      "Hypertension, polycythaemia and pre-existing cardiovascular disease",
      "Epstein-Barr virus, hypertension and polycythaemia",
      "Epstein-Barr virus, polycythaemia and pre-existing cardiovascular disease",
      "Epstein-Barr virus, hypertension and pre-existing cardiovascular disease",
    ],
    correctIndex: 0,
    rationale: "Epstein-Barr virus is not considered a risk factor for strokes because it primarily affects the immune system and causes infections such as mononucleosis, and is not directly related to the development of cerebrovascular accidents.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "Sasu, 36 years, complains of progressive headache and dizziness on rising in the morning with rising blood glucose. How would you manage this condition?",
    options: [
      "Change the acting time of intermediate insulin from dinner time to bedtime",
      "Increase the dose of intermediate acting insulin at dinner",
      "Increase the dose of intermediate or long acting insulin before the evening meal",
      "Stop the evening insulin dose completely",
    ],
    correctIndex: 0,
    rationale: "The client's symptoms suggest nocturnal hypoglycaemia causing a compensatory rise in blood glucose in the morning. Changing the intermediate-acting insulin to bedtime can help prevent nocturnal hypoglycaemia and subsequent morning hyperglycaemia.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "Severe acute malnutrition is usually manifested by wasting and/or oedema. Which are major contributory factors?",
    options: [
      "Nutritional deficiency and recurrent infections",
      "Recurrent infections and severe anaemia only",
      "Severe anaemia only",
      "Nutritional deficiency and severe anaemia only",
    ],
    correctIndex: 0,
    rationale: "Nutritional deficiency and recurrent infections lead to wasting and/or oedema in severe acute malnutrition by causing a breakdown in the body's ability to absorb and utilise nutrients, as well as making it more susceptible to disease and infections.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Significant nursing assessment data relevant to renal function should include information about?",
    options: [
      "Voiding disorders, presence of diabetes mellitus and presence of hypertension",
      "Client's occupation, presence of diabetes and voiding disorders",
      "Presence of diabetes, hypertension and client's occupation",
      "Voiding disorders, client's occupation and presence of hypertension",
    ],
    correctIndex: 0,
    rationale: "Voiding disorders, diabetes mellitus and hypertension are directly related to renal function and can impact the kidneys' ability to function properly.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Sintim, a 20-year-old known epileptic admitted with malaria just had a generalised seizure. What nursing care would you give after the seizure?",
    options: [
      "Use calm persuasion and gentle restraint, and re-orientate the client to the environment",
      "Keep the client on the back for six hours and protect the head with a pad",
      "Use calm persuasion, re-orientate and protect the head with a pad",
      "Re-orientate the client, keep on the back for six hours and protect the head",
    ],
    correctIndex: 0,
    rationale: "After a seizure it is important to use calm persuasion and gentle restraint to prevent harm to the client, and re-orientate the client to the environment since seizures can affect consciousness and cause confusion and disorientation.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "Sister Phillips, a nurse tutor, was teaching her students on the various birth defects. She described the formation of tetralogy of Fallot as including?",
    options: [
      "Overriding of the aorta, pulmonary stenosis, right ventricular hypertrophy and ventricular septal defect",
      "Overriding of the aorta, right ventricular hypertrophy and ventricular septal defect",
      "Pulmonary stenosis, right ventricular hypertrophy and ventricular septal defect",
      "Overriding of the aorta, pulmonary stenosis and ventricular septal defect",
    ],
    correctIndex: 0,
    rationale: "Tetralogy of Fallot is a congenital heart defect characterised by four distinct structural abnormalities: overriding of the aorta, pulmonary stenosis, right ventricular hypertrophy and ventricular septal defect.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Sodium restriction is an effective therapeutic tool in the treatment of heart failure because it?",
    options: [
      "Allows excess fluids in the tissue to be excreted",
      "Helps to control food intake and body weight",
      "Aids the weakened heart muscles to contract and improve cardiac output",
      "Prevents further damage to the heart valves",
    ],
    correctIndex: 0,
    rationale: "Sodium restriction helps to reduce fluid build-up in the body, which reduces the workload on the heart and improves cardiac function.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Solo Mills, a known diabetic and smoker, reported with purulent cough, chest pain and difficulty in breathing with weight loss. Pleural effusion was diagnosed and he is scheduled for underwater seal drainage after chest tube insertion. He requested to visit the washroom after chest tube insertion. Which action would the nurse perform first?",
    options: [
      "Clamp the tube at the connection to the bottle and assist the client to the washroom",
      "Clamp and disconnect the tube from the drainage bottle",
      "Disconnect the tube and assist the client to the washroom",
      "Ask the client to use a bedpan instead",
    ],
    correctIndex: 0,
    rationale: "Clamping the tube at the connection to the bottle helps prevent loss of suction or air from entering the pleural cavity and maintains proper drainage of the pleural effusion.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "A student nurse is giving a presentation on intravenous fluids. Which statement about isotonic fluids is appropriate?",
    options: [
      "Provides equal amounts of water and electrolytes",
      "Provides more water than electrolytes",
      "Provides more electrolytes than water",
      "Provides neither water nor electrolytes",
    ],
    correctIndex: 0,
    rationale: "Isotonic fluids are designed to maintain the balance of electrolytes and fluids in the body, and they contain the same concentration of electrolytes as normal body fluids.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Students on clinical placement inquire about the types of psoriasis. The following are types of psoriasis EXCEPT?",
    options: [
      "Reverse",
      "Plaque",
      "Nail",
      "Guttate",
    ],
    correctIndex: 0,
    rationale: "Psoriasis is a chronic skin condition characterised by the formation of scaly, itchy and red patches on the skin. Types include plaque, nail, guttate, pustular and inverse psoriasis. However, reverse is not a type of psoriasis.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Syndromic management of sexually transmitted infections has both advantages and disadvantages. The following are among the disadvantages EXCEPT?",
    options: [
      "Treatment is given at the first visit",
      "May lead to problems with partner notification",
      "Only symptomatic STIs are treated",
      "Does not identify the specific causative organism",
    ],
    correctIndex: 0,
    rationale: "The advantage of syndromic management is that treatment is given at the first visit to quickly relieve symptoms and reduce the risk of complications and transmission. The disadvantages include problems with partner notification and only treating symptomatic infections.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "The amount of blood pumped by the ventricle of the heart in one contraction is known as?",
    options: [
      "Stroke volume",
      "Cardiac output",
      "Tidal volume",
      "Ejection fraction",
    ],
    correctIndex: 0,
    rationale: "Stroke volume is the amount of blood pumped by the left ventricle in one contraction. Cardiac output is the amount of blood pumped per minute, calculated by multiplying stroke volume by heart rate.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "The assessment of an unconscious client demands the use of the Glasgow Coma Scale. Which of these would be used by the physician to test for sensation of pain?",
    options: [
      "Pin",
      "Cold water",
      "Cotton wisp or fine brush",
      "Tuning fork",
    ],
    correctIndex: 0,
    rationale: "The Glasgow Coma Scale is a neurological scale used to assess the level of consciousness in clients who have suffered a brain injury. In the assessment, a pin is commonly used to test the client's response to pain.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "The body's tendency to maintain a state of physiologic balance in the presence of changing conditions is referred to as?",
    options: [
      "Homeostasis",
      "Haemostasis",
      "Homoeothermic",
      "Metabolism",
    ],
    correctIndex: 0,
    rationale: "Homeostasis refers to the body's ability to maintain a stable internal environment in response to changes in the external environment.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "The charge nurse during tutorials discussed predisposing factors of atherosclerosis. Which is included?",
    options: [
      "Hypertension",
      "Low serum cholesterol",
      "Regular exercise",
      "High fibre diet",
    ],
    correctIndex: 0,
    rationale: "Predisposing factors of atherosclerosis include hypertension, obesity, smoking, diabetes and high levels of serum cholesterol.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "The charge nurse is giving tutorials to nurses on a client with a history of Crohn's disease. Which explanation refers to this condition?",
    options: [
      "An inflammatory bowel disease characterised by transmural inflammatory lesions throughout the gastrointestinal tract",
      "A gastrointestinal syndrome without identifiable organic cause",
      "A small bowel disorder characterised by inflammation and atrophy of villi on exposure to dietary gluten",
      "An autoimmune disorder causing destruction of the gastric mucosa",
    ],
    correctIndex: 0,
    rationale: "Crohn's disease is an inflammatory bowel disease characterised by transmural inflammatory lesions affecting the entire gastrointestinal tract, which is a characteristic feature of the disease.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "The clinical preceptor on the ward asked a first-year student to explain what myocardial infarction is. She describes myocardial infarction as?",
    options: [
      "Interruption of blood supply to cardiac muscles",
      "Irregular heart rhythm due to low blood pressure",
      "Intense pain in the chest on inspiration, relieved by rest",
      "Inflammation of the pericardial sac",
    ],
    correctIndex: 0,
    rationale: "Myocardial infarction, or a heart attack, results from the interruption of blood flow to the heart muscle due to a blockage in one or more of the coronary arteries, causing potentially life-threatening damage.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "The difference between the apical pulse and the radial pulse of a client is?",
    options: [
      "Pulse deficit",
      "Bradycardia",
      "Rhythm deficit",
      "Tachycardia",
    ],
    correctIndex: 0,
    rationale: "Pulse deficit occurs when the radial pulse is less than the apical pulse, indicating that not all heartbeats are reaching the peripheral arteries, which can be a sign of underlying cardiac arrhythmias or other conditions.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "The following are among the general observations that should be noted in the initial examination of a newly admitted client EXCEPT?",
    options: [
      "Body mass index",
      "Vital signs",
      "Nutritional status",
      "Level of consciousness",
    ],
    correctIndex: 0,
    rationale: "Body mass index is a measurement of a person's weight in relation to their height, and while it is important in evaluating overall health, it is not considered a general observation during a client's admission to a ward.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "The following are among the roles of the nurse in genetic counselling?",
    options: [
      "Coordinate genetic related health care with relevant community sources, gather relevant data about the family, and provide information",
      "Gather relevant data about the family, offer support only at the end, and provide information",
      "Coordinate genetic related health care and offer support only at the end",
      "Provide information only and refer elsewhere for the rest",
    ],
    correctIndex: 0,
    rationale: "The nurse's roles in genetic counselling include coordinating genetic related health care, gathering relevant family data and providing information to help the client and family understand the genetic status and make informed decisions.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "The following are the typical first symptoms of myasthenia gravis EXCEPT?",
    options: [
      "Ascending symmetrical weakness",
      "Weakness of eyelids and extraocular muscles",
      "Generalised weakness of limbs",
      "Diplopia and ptosis",
    ],
    correctIndex: 0,
    rationale: "Myasthenia gravis is a neuromuscular disorder causing muscle weakness and fatigue. The typical first symptoms include weakness of the eyelids and extraocular muscles. Ascending symmetrical weakness is not a typical first symptom.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "The following nursing diagnoses can be used for obesity EXCEPT?",
    options: [
      "Imbalanced nutrition, less than body requirements",
      "Risk for imbalanced nutrition, more than body requirements",
      "Anxiety related to change in lifestyle",
      "Activity intolerance",
    ],
    correctIndex: 0,
    rationale: "Obesity is characterised by excessive accumulation of body fat resulting from consuming more calories than the body burns. Imbalanced nutrition less than body requirements is an incorrect diagnosis for obesity.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "The following options are among the clinical manifestations of metabolic acidosis EXCEPT?",
    options: [
      "Increased blood pressure",
      "Confusion",
      "Drowsiness",
      "Deep rapid breathing",
    ],
    correctIndex: 0,
    rationale: "Increased blood pressure is not a manifestation of metabolic acidosis because it is a typical clinical sign of metabolic alkalosis, not acidosis.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "The laboratory investigation for a client revealed the causative organism for gastric ulcer disease. Which organism is responsible for gastric ulcers?",
    options: [
      "Helicobacter pylori",
      "Escherichia coli",
      "Ascaris lumbricoides",
      "Salmonella typhi",
    ],
    correctIndex: 0,
    rationale: "Helicobacter pylori is a type of bacterium that can infect the stomach lining, leading to inflammation, gastritis and peptic ulcers. It is estimated that up to 80 percent of gastric and duodenal ulcers are caused by H. pylori infection.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Laboratory investigations of a client indicated the body is making use of amino acids for gluconeogenesis. This process has an increase of which by-product?",
    options: [
      "Ammonia",
      "Fatty acids",
      "Ketone bodies",
      "Lactic acid",
    ],
    correctIndex: 0,
    rationale: "During gluconeogenesis the body breaks down amino acids from protein to produce glucose, which results in the release of ammonia as a by-product that can be toxic and needs to be converted to urea and eliminated by the kidneys.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "The laboratory results of a client revealed enteritis. Assessment revealed she had been consuming unpasteurised milk every day. Which organism could be the cause?",
    options: [
      "Salmonella",
      "Candida",
      "Helicobacter pylori",
      "Giardia lamblia",
    ],
    correctIndex: 0,
    rationale: "The most likely causative organism in this scenario is Salmonella, a bacterial species commonly associated with foodborne illness and enteritis that can be found in the gastrointestinal tracts of animals such as cows, and can contaminate milk and other dairy products.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A laboratory test result on a specimen taken from a 39-year-old woman indicated the presence of HPV. Which will be MOST likely diagnosed?",
    options: [
      "Genital warts",
      "Herpes",
      "Gonorrhoea",
      "Syphilis",
    ],
    correctIndex: 0,
    rationale: "A positive result for HPV suggests genital warts, as HPV is a common sexually transmitted infection that can cause the development of small, fleshy growths in the genital or anal area.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "The laboratory test that the nurse should refer to for the diagnosis of rheumatoid arthritis is?",
    options: [
      "Antinuclear antibody",
      "Bone marrow biopsy",
      "Alkaline phosphatase",
      "Erythrocyte sedimentation rate",
    ],
    correctIndex: 0,
    rationale: "Rheumatoid arthritis is an autoimmune disorder in which the body's immune system mistakenly attacks its own joint tissues, resulting in joint inflammation and damage. The antinuclear antibody test is a blood test that detects the presence of autoantibodies against components of the cell nucleus.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "The main function of adipose tissue metabolism is?",
    options: [
      "Storing triglycerides for energy reserve",
      "Regulating cholesterol production",
      "Releasing glucose for energy",
      "Producing insulin",
    ],
    correctIndex: 0,
    rationale: "Adipose tissue serves as a storage depot for triglycerides, which are used as a source of energy when needed. It does not regulate cholesterol production or release glucose for energy.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "The major reason a person has been infected with tuberculosis and needs to determine whether a person has been infected with the tuberculosis bacillus is termed?",
    options: [
      "Mantoux test",
      "Koch's test",
      "Brudzinski's test",
      "Heaf test",
    ],
    correctIndex: 0,
    rationale: "The Mantoux, also known as the tuberculin skin test, is a simple and non-invasive diagnostic tool that involves injecting a small amount of purified protein derivative of the tuberculosis bacillus into the skin to determine whether a person has been infected.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "The MOST therapeutic diet for a client with hepatic cirrhosis would be?",
    options: [
      "Low sodium, protein to tolerate, moderately high calorie",
      "Low protein, low carbohydrates, high fat",
      "High carbohydrate, low saturated fats, low calories",
      "High protein, high sodium, low fat",
    ],
    correctIndex: 0,
    rationale: "This diet helps to maintain a balance of nutrients and energy while reducing the workload on the damaged liver and managing electrolyte imbalances.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "The nurse asked a client to close the eyes and identify mild aromas such as coffee, vanilla, peanut butter, chocolate or orange. Which cranial nerve is the nurse assessing?",
    options: [
      "Olfactory",
      "Hypoglossal",
      "Auditory",
      "Facial",
    ],
    correctIndex: 0,
    rationale: "The nurse is assessing the function of the olfactory nerve, cranial nerve I, which is responsible for the sense of smell, by having the client close their eyes and identify different aromas.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "The nurse has been instructed to administer 160 mg of aspirin to a client with angina pectoris. The action of this drug is to?",
    options: [
      "Prevent coagulation",
      "Improve circulation",
      "Increase oxygenation",
      "Reduce pain",
    ],
    correctIndex: 0,
    rationale: "Aspirin is used to treat angina pectoris by preventing blood clotting through blocking the production of prostaglandins, which play a role in the clotting process, helping to maintain an adequate blood supply to the heart.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "The nurse is assessing a client, 58 years, with the diagnosis of diabetes insipidus. Inspection for which of the following is critical in the assessment?",
    options: [
      "Skin turgor",
      "Sleeping pattern",
      "Breathing pattern",
      "Bowel pattern",
    ],
    correctIndex: 0,
    rationale: "The nurse is looking for skin turgor as it is a critical sign for assessing fluid balance and dehydration in clients with diabetes insipidus.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "The nurse educating a chain smoker encouraged him to cease from this habit to prevent emphysema. The nurse describes this disease condition as?",
    options: [
      "Gaseous distention of the alveoli",
      "Severe infection of the lungs",
      "Over distention of the bronchioles",
      "Narrowing of the bronchi",
    ],
    correctIndex: 0,
    rationale: "Emphysema is caused by gaseous distention of the alveoli, leading to destruction of their walls and a reduction in lung elasticity and surface area for gas exchange, resulting in difficulty breathing and decreased oxygen exchange.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "The nurse is assessing a client with mild to moderate dehydration secondary to food poisoning. Which symptoms would confirm the diagnosis?",
    options: [
      "Increased pulse rate and decreased urine output",
      "Decreased pulse rate and decreased urine output",
      "Decreased pulse rate and increased urine output",
      "Normal pulse rate with increased urine output",
    ],
    correctIndex: 0,
    rationale: "These symptoms indicate that the body is conserving fluid and compensating for fluid loss, which are common responses to dehydration.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "The nurse is assessing a client with a stroke. Which finding would suggest that the client has a haemorrhagic stroke?",
    options: [
      "Presence of ptosis and facial droop",
      "Impaired speech",
      "Hoarseness of voice",
      "Loss of memory",
    ],
    correctIndex: 0,
    rationale: "Ptosis and facial droop suggest a haemorrhagic stroke, as these specific symptoms are indicative of bleeding in the brain and are not commonly seen in other types of stroke such as ischaemic strokes.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "The nurse is educating a group of female teenagers on genital warts. One of the common causes of genital warts is?",
    options: [
      "Human papillomavirus",
      "Candida albicans",
      "Treponema pallidum",
      "Herpes simplex virus",
    ],
    correctIndex: 0,
    rationale: "Genital warts are a sexually transmitted infection caused by the human papillomavirus, and the virus is spread through sexual contact with an infected partner.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "The nurse is planning care for a client diagnosed with acute viral hepatitis. Which nursing diagnosis would require prompt intervention?",
    options: [
      "Risk for impaired liver function related to viral infection",
      "Risk for injury related to fatigue",
      "Activity intolerance related to fatigue",
      "Imbalanced nutrition less than body requirements",
    ],
    correctIndex: 0,
    rationale: "The viral infection can cause inflammation and injury to liver cells, leading to decreased liver function and potentially severe health consequences if not properly managed.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "The nurse is preparing a client for an intravenous pyelogram (IVP). Which action by the nurse is essential?",
    options: [
      "Withhold the client's metformin medication on the day of the test and 48 hours after",
      "Empty the bladder the morning before the procedure",
      "Administer laxatives the morning before the procedure to empty the bowels",
      "Encourage the client to drink plenty of water before the test",
    ],
    correctIndex: 0,
    rationale: "The administration of an intravenous pyelogram requires the use of a contrast medium, which can cause an increased risk of lactic acidosis in clients who are taking metformin.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "The nurse is setting goals and planning nursing care for excess fluid volume related to heart failure. Which is the MOST appropriate nursing order?",
    options: [
      "Restrict fluid intake",
      "Serve oral diuretics",
      "Restrict sodium intake",
      "Encourage increased activity",
    ],
    correctIndex: 0,
    rationale: "Excess fluid volume is a common problem in clients with heart failure and the most appropriate nursing order is to restrict fluid intake to help reduce the volume of fluid in the body and prevent complications such as pulmonary oedema and shortness of breath.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "The nurse is teaching a client who is a vegetarian on her diet. In order to prevent anaemia she should supplement her diet with vitamin?",
    options: [
      "B12",
      "B3",
      "B5",
      "B6",
    ],
    correctIndex: 0,
    rationale: "A vegetarian diet may lack sufficient amounts of vitamin B12, which is primarily found in animal products, leading to megaloblastic anaemia. Therefore vitamin B12 supplementation is important.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "The nurse is teaching a client with type I diabetes about measures to take to prevent long-term complications of the disease. The nurse should include which of the following?",
    options: [
      "Avoid wearing insulated boots in cold weather",
      "Wear knee-high nylons instead of panty hose",
      "Wear slippers when hanging out around the house",
      "Walk barefoot indoors to improve circulation",
    ],
    correctIndex: 0,
    rationale: "Wearing insulated boots in cold weather may cause the feet to sweat, which increases the risk of developing blisters and foot injuries that can lead to long-term complications in diabetic clients.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "The nurse's primary goal in preparing a client for a diagnostic test is to?",
    options: [
      "Enhance client compliance and cooperation",
      "Clarify any misconceptions and anxieties in the client",
      "Provide basic teaching about the indications for the test",
      "Ensure the test is completed as quickly as possible",
    ],
    correctIndex: 0,
    rationale: "The primary goal is to enhance client compliance and cooperation, clarify any misconceptions and anxieties the client may have, and provide basic information about the indications for and process of the test.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "The nursing diagnoses below are relevant for clients suffering from hypercalcaemia EXCEPT?",
    options: [
      "Fluid volume deficit related to diarrhoea",
      "Activity intolerance related to neuromuscular weakness",
      "Decreased cardiac output related to dysrhythmias",
      "Risk for injury related to bone fractures",
    ],
    correctIndex: 0,
    rationale: "Hypercalcaemia is characterised by elevated levels of calcium in the blood and primarily affects bone metabolism, causing soft tissue calcification and decreased muscle strength, not diarrhoea.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "The client who is unable to complete a bath because of right-sided weakness has a nursing diagnosis label of?",
    options: [
      "Self-care deficit",
      "Knowledge deficient",
      "Powerlessness",
      "Activity intolerance",
    ],
    correctIndex: 0,
    rationale: "Self-care deficit is defined as an impaired ability to perform or complete activities of daily living independently. Bathing is an essential activity of daily living, and a client unable to complete it due to physical limitations has a self-care deficit.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "The physician is managing a client with pulmonary embolism on the ward where you work. The MOST appropriate action of the nurse would be to administer?",
    options: [
      "Intranasal oxygen",
      "IV fluids",
      "Oral aspirin",
      "Intravenous antibiotics",
    ],
    correctIndex: 0,
    rationale: "Administering intranasal oxygen will improve oxygenation and help relieve hypoxaemia, which is an abnormally low level of oxygen in the arterial blood.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "The reason for administering diuretics to clients with congestive cardiac failure is to?",
    options: [
      "Decrease fluid retention",
      "Maintain fluid retention",
      "Increase fluid retention",
      "Increase cardiac output directly",
    ],
    correctIndex: 0,
    rationale: "Diuretics help to increase urine output and reduce the volume of fluid in the body, which can help alleviate symptoms of congestive cardiac failure such as oedema and shortness of breath.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "The reason why clients with leukaemia are nursed in protective isolation is because?",
    options: [
      "Their immune system cannot react to microbial infection",
      "To increase their resistance to microorganisms",
      "To prevent transmission of infections via fomites",
      "They are contagious to other clients",
    ],
    correctIndex: 0,
    rationale: "Leukaemia is a type of cancer that affects the white blood cells and bone marrow, impairing the immune system's ability to fight infections. Clients with leukaemia are nursed in protective isolation to prevent exposure to harmful microorganisms.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "The risk factors for developing coronary artery disease could be classified as modifiable and non-modifiable factors. Which are the non-modifiable risk factors?",
    options: [
      "Family history of CAD and increasing age",
      "Increasing age and obesity",
      "Obesity and hypertension",
      "Hypertension and family history",
    ],
    correctIndex: 0,
    rationale: "Non-modifiable factors are risk factors that cannot be changed or influenced, such as increasing age and family history. Modifiable factors such as obesity and hypertension can be managed through lifestyle changes.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "The success of tuberculosis control programmes depends critically on the quality of diagnostic services. Which investigations are carried out to confirm the diagnosis and monitor treatment?",
    options: [
      "Acid-fast bacilli test, polymerase chain reaction and tuberculin skin test",
      "Acid-fast bacilli test and tuberculin skin test only",
      "Acid-fast bacilli test and polymerase chain reaction only",
      "Polymerase chain reaction and chest x-ray only",
    ],
    correctIndex: 0,
    rationale: "All three of these tests are important in the diagnosis and monitoring of tuberculosis, and their combination provides the best results in detecting and managing the disease.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "The superficial veins begin on the hand and consist of the?",
    options: [
      "Median vein",
      "Axillary vein",
      "Brachial vein",
      "Subclavian vein",
    ],
    correctIndex: 0,
    rationale: "The median vein, located in the middle of the antecubital fossa, is formed by the confluence of the cephalic and basilic veins, along with the radial and ulnar veins which begin on the dorsum of the hand.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "There are numerous risk factors associated with the long-term development of arteriosclerosis and atherosclerosis, which are direct precursors of cardiovascular disease. Non-modifiable risk factors include age, gender and?",
    options: [
      "Ethnicity of the client",
      "Complete obstruction of the vessel",
      "Constriction of the lumen of the vessels",
      "High cholesterol level",
    ],
    correctIndex: 0,
    rationale: "These risk factors are non-modifiable because they are inherent characteristics that cannot be changed, such as age and gender, or culturally determined, such as ethnicity.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "To assess the effectiveness of vasodilators administered for the management of hypertension, the nurse should take the client's pulse and blood pressure?",
    options: [
      "After a resting position is maintained for five minutes",
      "Immediately after the client gets out of bed",
      "Prior to administering the medicine",
      "Immediately after administering the medicine",
    ],
    correctIndex: 0,
    rationale: "After a resting position is maintained for five minutes, the client's pulse and blood pressure would be in a stable state and provide an accurate reflection of the effectiveness of the vasodilators in managing hypertension.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "To help a client obtain maximum benefits after postural drainage, the nurse should?",
    options: [
      "Encourage the client to cough deeply",
      "Encourage the client to rest for 30 minutes",
      "Place the client in a sitting up position",
      "Offer the client a warm drink",
    ],
    correctIndex: 0,
    rationale: "Postural drainage is a technique used to help mobilise secretions in the lungs and airways. It involves positioning the client in different positions to promote drainage of mucus. After postural drainage, coughing is essential to expel the loosened secretions from the lungs.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "To identify a motor abnormality during nervous system assessment, the nurse instructs the client to do which of the following?",
    options: [
      "Flex the wrist",
      "Throw a ball",
      "Swing the arm",
      "Close the eyes",
    ],
    correctIndex: 0,
    rationale: "Assessing wrist flexion helps determine how well the corticospinal tract works, which is important for voluntary movement control. This test can reveal abnormalities in the part of the brain responsible for movement control.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "To make a definitive diagnosis of sickle cell disease, the diagnostic result is based on?",
    options: [
      "Haemoglobin electrophoresis",
      "Full blood count",
      "Bone marrow aspiration",
      "Peripheral blood film",
    ],
    correctIndex: 0,
    rationale: "The definitive diagnosis of sickle cell disease is based on the results of haemoglobin electrophoresis, which identifies the presence of abnormal haemoglobin, specifically haemoglobin S. Full blood count and bone marrow aspiration may provide additional information but are not definitive.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "To prevent hepatic coma in a client with severe hepatitis, it may become necessary to eliminate?",
    options: [
      "Protein from the diet",
      "Carbohydrate from the diet",
      "Fats from the diet",
      "Fluid from the diet",
    ],
    correctIndex: 0,
    rationale: "When the liver is severely compromised, it cannot process protein effectively, leading to an accumulation of toxic by-products in the body which can cause hepatic encephalopathy or coma.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "To prevent a client with chronic obstructive pulmonary disease who is bedridden from developing hypostatic pneumonia, the nurse would employ all the following measures EXCEPT?",
    options: [
      "Encourage the client to drink warm water",
      "Encourage effective coughing",
      "Serve prescribed expectorants",
      "Reposition the client regularly",
    ],
    correctIndex: 0,
    rationale: "Warm water is not proven to prevent hypostatic pneumonia and may even increase the risk of aspiration pneumonia in clients with dysphagia, while effective coughing and prescribed expectorants are effective measures that promote airway clearance and mobilise respiratory secretions.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "To prevent orthostatic hypotension in a client on methyldopa (Aldomet), the client should be taught to?",
    options: [
      "Sit on the edge of the bed a short time before getting up",
      "Avoid tasks that require high energy expenditure",
      "Lie down for 30 minutes after taking the medication",
      "Reduce the dose of medication",
    ],
    correctIndex: 0,
    rationale: "Orthostatic hypotension can occur as a side effect of methyldopa, and sitting on the edge of the bed before getting up allows the client's blood pressure to adjust, reducing the risk of hypotension.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "To reduce the symptoms of sprue, the client should be advised to avoid foods made from?",
    options: [
      "Wheat",
      "Broad beans",
      "Maize",
      "Rice",
    ],
    correctIndex: 0,
    rationale: "Sprue, also known as coeliac disease, is an autoimmune disorder in which the immune system reacts abnormally to gluten, a protein found in wheat, barley and rye. This immune reaction damages the lining of the small intestine and can lead to abdominal bloating, diarrhoea and weight loss.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A 68-year-old retired banker is admitted with prostatitis. Complications of inappropriate care of this condition could include?",
    options: [
      "Epididymitis, pyelonephritis, urinary retention and septicaemia",
      "Epididymitis and pyelonephritis only",
      "Pyelonephritis and urinary retention only",
      "Epididymitis and septicaemia only",
    ],
    correctIndex: 0,
    rationale: "All the listed complications can occur as a result of inappropriate care of prostatitis, which can lead to spread of infection to other parts of the urinary system, inflammation, blockage of the urethra, and even spread of bacteria into the bloodstream causing sepsis.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Urinary retention with overflow is evidenced by?",
    options: [
      "Continual incontinence",
      "Oliguria and oedema",
      "Frequent voiding of large amounts",
      "Complete absence of urine",
    ],
    correctIndex: 0,
    rationale: "Overflow urinary retention occurs when the bladder cannot empty completely, leading to continuous dribbling of urine despite frequent attempts to empty it.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Vitamin C is required for the formation of fibrous collagen in connective tissues and bones. Lack of vitamin C leads to scurvy which is characterised by the following EXCEPT?",
    options: [
      "Deformity of ribs, spine, pelvis and limbs",
      "Aching in bones, joints and muscles",
      "Petechiae on the limbs and trunk",
      "Bleeding gums",
    ],
    correctIndex: 0,
    rationale: "Scurvy is a condition caused by deficiency of vitamin C which affects the formation of collagen in skin and bones, leading to symptoms such as aching in bones and joints and petechiae, but not deformity of the skeleton.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "What explanation would the nurse give to a client inquiring about the reason for taking a urine specimen for culture and sensitivity test?",
    options: [
      "It helps with evaluation of abnormalities in urine, determines the presence of bacteria and identifies the antimicrobial therapy best for identified microbes",
      "It helps with evaluation of abnormalities, determines bacteria and estimates specific gravity of urine",
      "It determines bacteria, identifies therapy and estimates specific gravity",
      "It estimates specific gravity and evaluates abnormalities in urine",
    ],
    correctIndex: 0,
    rationale: "A urine culture and sensitivity test is done to evaluate urine abnormalities, determine the presence of bacterial infections and identify the most appropriate antibiotic therapy. It does not estimate the specific gravity of urine.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "What instruction would you give to a client preparing to undergo urea breath testing to evaluate peptic ulcer disease?",
    options: [
      "You may not eat or drink after midnight the night before the test",
      "You will need to have intravenous fluids started before the test",
      "You will be given a sedative so you will need someone to drive you home",
      "You should take your antacid before coming for the test",
    ],
    correctIndex: 0,
    rationale: "The urea breath test requires the client not to eat or drink before the test to ensure an accurate evaluation of peptic ulcer disease by measuring the amount of urea in the breath after it is broken down by the bacterium Helicobacter pylori.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "What is the major pathological effect when the hookworm migrates through the lungs?",
    options: [
      "Anaemia",
      "Diarrhoea",
      "Bronchitis",
      "Pneumonitis",
    ],
    correctIndex: 0,
    rationale: "The migration of hookworms can cause irritation and inflammation of the airways but this is usually not severe enough to result in bronchitis. Hookworms feed on the host's blood, leading to blood loss and a reduction in red blood cells and haemoglobin levels, causing anaemia which can have significant impacts on the host's health and well-being.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
];