/**
 * Past NMC examination questions — Medical Nursing paper.
 *
 * Transcribed from a real past paper supplied by the operator. Answers are
 * derived from the rationales printed in the paper, not from an official
 * answer key, so each is flagged `verified: false` for review.
 */

export type PastQuestion = {
  stem: string;
  options: string[];
  correctIndex: number;
  rationale: string;
  category: string;
  verified: boolean;
};

export const PAST_PAPER_MEDICAL: PastQuestion[] = [
  {
    stem: "Which condition is characterised by a slow progressive inflammatory disease with the potential of affecting multiple organs, presenting with dementia, psychosis, paresis, stroke or meningitis?",
    options: ["Tertiary syphilis", "Cerebral malaria", "Tetanus", "Meningococcal meningitis"],
    correctIndex: 0,
    rationale: "Tertiary syphilis is a slow progressive inflammatory disease that can affect multiple organs and cause dementia, psychosis, paresis, stroke and meningitis. These are features of the late stage of syphilis infection.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "Which body fluid compartment makes up about 40% of the total body weight?",
    options: ["Extracellular fluid", "Intestinal fluid", "Intracellular fluid", "Transcellular fluid"],
    correctIndex: 0,
    rationale: "Extracellular fluid accounts for approximately 40% of total body water and includes interstitial fluid, plasma and other specialised fluids. Intracellular fluid makes up the larger remaining share.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A 12-year-old girl is brought to the emergency unit with a history of seizure and fever. On assessment the nurse discovers an infected ulcer on the right leg. Which is the most likely diagnosis?",
    options: ["Epilepsy", "Meningitis", "Tetanus", "Cerebral palsy"],
    correctIndex: 2,
    rationale: "Tetanus is suggested by the infected ulcer, which can serve as an entry point for Clostridium tetani, causing muscle stiffness, spasms and seizures.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A 13-year-old girl presents with swollen gums, pain on brushing and halitosis. Her gums are red and puffy with bad breath. Which interventions are MOST appropriate to relieve her pain and halitosis?",
    options: [
      "Mouth washing with tap water or normal saline, avoiding alcohol based mouthwashes, and educating on tooth brushing",
      "Discouraging mouthwashing entirely and advising liberal fluid intake only",
      "Advising alcohol based mouthwashes and a low protein diet",
      "Withholding all oral care until the pain settles",
    ],
    correctIndex: 0,
    rationale: "Saline mouthwashes, avoiding alcohol based preparations that irritate the gums, and correct tooth brushing relieve pain and halitosis. Alcohol based mouthwashes worsen gum irritation.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A 15-year-old with nephrotic syndrome is on furosemide. Which electrolyte is most likely to be depleted?",
    options: ["Potassium", "Calcium", "Phosphate", "Magnesium"],
    correctIndex: 0,
    rationale: "Furosemide is a loop diuretic that causes loss of electrolytes, particularly potassium, through increased urine output.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A 16-year-old boy is brought in because of changes in his physical appearance. On assessment the nurse notes clubbing of the fingers. He is likely to be diagnosed with?",
    options: ["Bronchitis", "Congenital heart disease", "Anaemia", "Peptic ulcer disease"],
    correctIndex: 1,
    rationale: "Clubbing of the fingers is caused by enlargement of the fingertips and rounding of the nail base from increased tissue growth and altered blood flow, and is a common sign of congenital heart disease.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A 17-year-old girl attends the dental clinic with sore throat, halitosis and difficulty swallowing. Her throat is red and the tonsils inflamed. A diagnosis of Vincent's angina is made. Which is the appropriate management?",
    options: [
      "Penicillin with saline or salt water mouthwashes",
      "Penicillin, amoxicillin and hydrogen peroxide mouthwashes",
      "Penicillin, tetracycline and hydrogen peroxide mouthwashes",
      "Tetracycline alone with no oral care",
    ],
    correctIndex: 0,
    rationale: "Vincent's angina is a bacterial infection of the oral cavity caused by anaerobic organisms including Borrelia vincentii. Treatment is penicillin or another antibiotic effective against anaerobes, with saline or salt water mouthwashes to relieve symptoms and promote healing.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A 19-year-old male is diagnosed with hypertrophic cardiomyopathy. Which statement is true about this condition?",
    options: [
      "The patient should be restricted from intense physical activity",
      "Treatment includes reduction of intravascular volume",
      "The mechanism of sudden death is usually complete AV block",
      "The condition resolves without treatment",
    ],
    correctIndex: 0,
    rationale: "In hypertrophic cardiomyopathy the heart muscle becomes abnormally thick, making it harder to pump blood. The main concern is sudden cardiac death during exercise or intense physical activity, so activity is restricted.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A 19-year-old male reports with generalised fatigue and frequent sinus infections. He has never seen a physician, self-medicates with antibiotics, and has mild anaemia with Hb 9 g/dL. Sickle cell anaemia is confirmed. What is the MOST important care?",
    options: [
      "Rehydration and relief of pain",
      "Antibiotic administration and relief of pain",
      "Blood transfusion and relief of pain",
      "Iron supplementation and relief of pain",
    ],
    correctIndex: 0,
    rationale: "Sickle cell anaemia is a genetic blood disorder causing abnormal haemoglobin, sickling of red cells, vessel blockage and severe pain. Rehydration and pain relief are the priority in management.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Which are the typical symptoms of myasthenia gravis?",
    options: [
      "Weakness of the eyelids and extraocular muscles",
      "Slowed nerve conduction",
      "Ascending symmetrical weakness",
      "Loss of vibration sense in the feet",
    ],
    correctIndex: 0,
    rationale: "Myasthenia gravis is an autoimmune neuromuscular disorder affecting transmission of nerve impulses to muscles, causing weakness and fatigue. It often begins with weakness of the muscles controlling eye movement and eyelid function, causing ptosis and diplopia.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "A 21-year-old female is rushed to the medical emergency with diarrhoea, abdominal pain, nausea and vomiting starting six hours after eating noodles and vegetables. Coeliac disease is diagnosed. What is the appropriate nursing care?",
    options: [
      "Monitor fluid intake and output, vital signs, and provide supportive care",
      "Encourage liberal fluid intake and serve prescribed medications only",
      "Ensure strict maintenance of nil per os and serve medications",
      "Encourage intake of wheat based foods to settle the stomach",
    ],
    correctIndex: 0,
    rationale: "Coeliac disease is an autoimmune disorder that damages the small intestinal lining when gluten is ingested, causing diarrhoea, abdominal pain, nausea and vomiting. The priority is monitoring fluid and electrolyte balance to prevent dehydration, alongside supportive care.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A 23-year-old patient is admitted with hepatitis D. In caring for this patient the MOST important nursing intervention is to provide bed rest, and to?",
    options: [
      "Manage pruritus and weight, and prevent transmission",
      "Prevent transmission and manage weight only",
      "Manage pruritus and weight only",
      "Encourage a high protein diet and early mobilisation",
    ],
    correctIndex: 0,
    rationale: "Hepatitis D is a viral infection affecting the liver, transmitted through exposure to infected blood or body fluids. Managing symptoms, including pruritus, and preventing the spread of the virus are essential to recovery.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A 24-year-old female has recently started warfarin after an unprovoked deep vein thrombosis. Which can decrease the effectiveness of warfarin?",
    options: [
      "Oral contraceptives containing oestrogen",
      "Omeprazole",
      "Vitamin E",
      "Vitamin K supplement",
    ],
    correctIndex: 0,
    rationale: "Oral contraceptives containing oestrogen can decrease the effectiveness of warfarin by increasing the production of clotting factors in the liver and reducing the clearance of warfarin, leading to an increased risk of blood clots.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A 24-year-old man presents with headaches described as severe unilateral throbbing pain aggravated by movement, associated with nausea and sensitivity to light. Physical examination is completely normal. What is the MOST likely diagnosis?",
    options: ["Migraine", "Tension headache", "Cluster headache", "Subarachnoid haemorrhage"],
    correctIndex: 0,
    rationale: "Severe unilateral throbbing pain associated with nausea and sensitivity to light is a classic presentation of migraine headache.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "A 24-year-old female has a two-day history of dizziness. On sitting up this morning the room spun for about a minute, and she has had recurrent episodes with nausea while driving. She has no headache, tinnitus, vision change, weakness or gait abnormality, and vital signs are normal. What is the possible cause?",
    options: [
      "Benign paroxysmal positional vertigo",
      "Vestibular neuritis",
      "Cerebellar infarction",
      "Meniere's disease",
    ],
    correctIndex: 0,
    rationale: "Benign paroxysmal positional vertigo is a common cause of recurrent brief episodes of vertigo triggered by changes in head position, such as rolling over in bed or rising from lying or sitting, and is not associated with other neurological symptoms.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "A 15-year-old obese patient is being managed for gastro-oesophageal reflux disease and is concerned about possible complications. What is the appropriate nursing diagnosis?",
    options: [
      "Deficient knowledge related to lack of information regarding the condition",
      "Risk for aspiration related to lack of information regarding the disease process",
      "Acute pain related to irritated oesophageal mucosa",
      "Imbalanced nutrition less than body requirements",
    ],
    correctIndex: 0,
    rationale: "Because the patient is concerned about possible complications of gastro-oesophageal reflux disease, she requires education about the condition, its management and potential complications to promote self-care and prevent complications.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A 26-year-old man sustained a cut to the left ankle while weeding his backyard two weeks ago and has a provisional diagnosis of tetanus. Which of the following is NOT a clinical feature of tetanus?",
    options: ["Low pulse rate", "Lockjaw", "Low-grade fever", "Muscle spasm"],
    correctIndex: 0,
    rationale: "Tetanus is a life-threatening infection caused by Clostridium tetani affecting the nervous system, presenting with muscle stiffness, spasm, fever, sweating, rapid heart rate, raised blood pressure and difficulty swallowing and breathing. A low pulse rate is not a feature.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A 26-year-old female with no past medical history presents with low-grade fever, dysuria and flank pain, and is diagnosed with pyelonephritis. What is the most likely causative pathogen?",
    options: ["Escherichia coli", "Klebsiella pneumoniae", "Staphylococcus saprophyticus", "Pseudomonas aeruginosa"],
    correctIndex: 0,
    rationale: "Escherichia coli is the most common causative organism in community-acquired urinary tract infection and pyelonephritis in a young healthy female with dysuria and flank pain.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A 26-year-old man reports a painless penile lesion of several weeks with recent groin swelling. There is a single non-tender penile ulcer with bilateral non-tender inguinal lymph nodes. Rapid plasma reagin test is negative. What is the most likely diagnosis?",
    options: ["Primary syphilis", "Granuloma inguinale", "Herpes simplex virus", "Lymphogranuloma venereum"],
    correctIndex: 0,
    rationale: "Primary syphilis presents with a painless ulcer at the site of infection, and bilateral non-tender inguinal lymphadenopathy is common, which helps differentiate it from other causes of genital ulcers. A negative RPR does not rule out syphilis.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A 28-year-old female complains of vaginal discharge with burning, irritation and pruritus. She is sexually active with one partner. The vulva is erythematous and oedematous with thick white adherent discharge, and there is no cervical motion or uterine tenderness. What is the MOST common infectious cause of vulvovaginal pruritus?",
    options: ["Candidiasis", "Bacterial vaginosis", "Gonorrhoea", "Trichomoniasis"],
    correctIndex: 0,
    rationale: "Candidiasis is the most common infectious cause of vulvovaginal pruritus. It is a fungal infection from overgrowth of Candida yeast, normally present in the vagina, causing itching, burning and thick white discharge.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A 29-year-old male with a history of asthma complains of difficulty in breathing. Breath sounds are diminished on one side. Which initial investigation confirms the diagnosis?",
    options: ["Chest radiograph", "Echocardiogram", "Helical computed tomography", "Peak flow measurement"],
    correctIndex: 0,
    rationale: "A chest radiograph is the best initial investigation to confirm pneumothorax, as it visualises air in the pleural space and allows prompt diagnosis and treatment.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "A 30-year-old female with iron deficiency anaemia presents with double vision worse in the evening and difficulty swallowing food over the past month. Myasthenia gravis is diagnosed. Which medication will be used to treat her?",
    options: ["Pyridostigmine", "Sinemet", "Fibrinolytics", "Neostigmine with atropine"],
    correctIndex: 0,
    rationale: "Myasthenia gravis is an autoimmune disorder affecting the neuromuscular junction, causing muscle weakness and fatigue. Pyridostigmine is the drug of choice because it increases acetylcholine concentration at the neuromuscular junction, improving transmission and reducing weakness.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "A 30-year-old businessman is rushed to the emergency unit after sudden loss of consciousness and is to be catheterised for a urine specimen. Which measures would the nurse take to prevent infection?",
    options: [
      "Avoid unnecessary handling of the catheter, empty the collection bag at least every eight hours, and use a pre-assembled sterile closed drainage system",
      "Ensure routine irrigation of the indwelling catheter and empty the bag every eight hours",
      "Empty the collection bag every eight hours and use an open drainage system",
      "Irrigate the catheter daily and change it every shift",
    ],
    correctIndex: 0,
    rationale: "Routine irrigation of an indwelling catheter is not recommended as it increases infection risk. The catheter should only be irrigated when necessary, using sterile technique. Avoiding unnecessary handling, regular bag emptying and a closed sterile system all reduce infection.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A 30-year-old man is admitted with glomerulonephritis. Which reading indicates high blood pressure?",
    options: [
      "Diastolic pressure of 95 mmHg",
      "Pulse deficit of 10 per minute",
      "Systolic pressure of 30 mmHg",
      "Respiratory rate of 22 per minute",
    ],
    correctIndex: 0,
    rationale: "Diastolic pressure is the bottom number of a blood pressure reading. A diastolic pressure of 90 mmHg or higher is considered high blood pressure.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A 32-year-old woman has read about Graves' disease online and is afraid she has it. Which feature is specific to Graves' disease?",
    options: ["Ophthalmopathy", "Heat intolerance", "Fine tremor", "Weight loss"],
    correctIndex: 0,
    rationale: "Ophthalmopathy is specific to Graves' disease, an autoimmune disorder causing hyperthyroidism, characterised by eye disease such as exophthalmos, dryness, irritation and in severe cases double vision or vision loss.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "A 34-year-old female wakes with unilateral facial paralysis. She has flattening of the forehead and nasolabial fold on the affected side, difficulty closing the eyelid and tingling on that side. Which cranial nerve is responsible?",
    options: ["CN VII (facial nerve)", "CN V (trigeminal nerve)", "CN IV (trochlear nerve)", "CN III (oculomotor nerve)"],
    correctIndex: 0,
    rationale: "The symptoms indicate facial nerve palsy. The facial nerve innervates the muscles of facial expression, and damage causes facial paralysis, flattening of the forehead and nasolabial fold, and difficulty closing the eyelid.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "A 39-year-old female with severe hypertension on a beta-blocker and thiazide diuretic also has type 2 diabetes on an oral hypoglycaemic agent. Urinalysis shows microscopic proteinuria but the blood pressure will not settle. What is the MOST appropriate treatment to add?",
    options: [
      "An ACE inhibitor",
      "Discontinuation of the hypoglycaemic agent",
      "Insulin and an ACE inhibitor",
      "A calcium channel blocker",
    ],
    correctIndex: 0,
    rationale: "An ACE inhibitor is used in hypertension and has been shown to reduce proteinuria in diabetes. It lowers blood pressure further, protects the kidneys, and slows the progression of diabetic nephropathy.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A 39-year-old man presents with epigastric fullness and discomfort worse after meals. He smokes but has no prior diagnosis of ulcer disease. Which is the best diagnostic approach?",
    options: [
      "Initial eight-week trial of a proton pump inhibitor",
      "Breath testing for H. pylori and treatment if positive",
      "Empiric antimicrobial treatment of H. pylori",
      "Immediate upper gastrointestinal endoscopy",
    ],
    correctIndex: 0,
    rationale: "An initial trial of a proton pump inhibitor is the first-line diagnostic and treatment approach for most patients with dyspepsia. If symptoms improve the patient is unlikely to have an ulcer and further investigation is unnecessary.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A 3-year-old is admitted with valvular heart disease. In which valvular heart disease can there be a backward flow of blood?",
    options: [
      "Valvular regurgitation",
      "Valvular prolapse only",
      "Valvular stenosis",
      "Valvular stenosis and prolapse",
    ],
    correctIndex: 0,
    rationale: "Valvular regurgitation is the backward flow of blood through an improperly closing valve, decreasing cardiac efficiency. Prolapse can cause regurgitation, while stenosis narrows the valve and impedes forward flow.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A 40-year-old with type 2 diabetes, hypertension and a recent acute myocardial infarction has an LDL cholesterol of 195 mg/dL, previously unchecked for five years. Which is true?",
    options: [
      "He should be treated to achieve at least a 50% reduction in his LDL cholesterol",
      "Because he is diabetic his LDL should be targeted to less than 130 mg/dL",
      "He should be treated to achieve a 30% reduction in LDL cholesterol",
      "No treatment is needed as his cholesterol was previously normal",
    ],
    correctIndex: 0,
    rationale: "For patients with diabetes after an acute myocardial infarction, the recommended target is at least a 50% reduction in LDL cholesterol from baseline, regardless of the starting level, to reduce the risk of further cardiovascular events.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A 40-year-old female has paroxysmal pain she describes as 12/10 and 'like an electrical shock' shooting from the corner of her mouth to the angle of her jaw, lasting several seconds and confined to the right side. It begins after chewing or drinking hot coffee. She is afebrile with a normal examination. What is the most likely diagnosis?",
    options: ["Trigeminal neuralgia", "Cluster headache", "Migraine headache", "Temporomandibular joint disorder"],
    correctIndex: 0,
    rationale: "Trigeminal neuralgia affects the trigeminal nerve, which supplies sensation to the face. Electric shock like pain triggered by chewing or hot drinks, with no neurological deficits, suggests trigeminal neuralgia.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "A 40-year-old female with moderate intermittent asthma is treated for an exacerbation with an albuterol nebuliser without success. Systemic corticosteroids are being considered. Which is TRUE about systemic corticosteroids?",
    options: [
      "The mechanism of action in treating an asthma exacerbation is suppression of inflammation",
      "Parenteral therapy is preferable to oral therapy in acute exacerbation",
      "The maximum dose of prednisone for an adult is 40 mg daily",
      "They act primarily as bronchodilators",
    ],
    correctIndex: 0,
    rationale: "Systemic corticosteroids such as prednisone treat moderate to severe asthma exacerbations through their anti-inflammatory properties, reducing airway inflammation, mucosal oedema and mucus hypersecretion. The oral route is preferred.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "A 40-year-old male presents with sudden onset of severe headache that increases with movement of the head. Which diagnosis would be considered?",
    options: ["Subarachnoid haemorrhage", "Cluster headache", "Migraine headache", "Tension headache"],
    correctIndex: 0,
    rationale: "Subarachnoid haemorrhage can present with sudden onset of severe headache that worsens with movement, due to bleeding in the space between the brain and the tissue covering it.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "A 42-year-old woman has difficulty breathing while receiving a venous infusion. Which action by the nurse will confirm that she has pulmonary oedema?",
    options: [
      "Auscultating the lungs for crackles",
      "Placing the client in the sitting up position",
      "Checking the fluid balance on the chart",
      "Measuring the blood pressure",
    ],
    correctIndex: 0,
    rationale: "Auscultating crackles is characteristic of pulmonary oedema. Checking the fluid balance chart does not provide information about the client's current condition.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A 42-year-old man experienced a tonic-clonic seizure during history taking. What is the first line management for a convulsive seizure?",
    options: [
      "Lorazepam 0.1 mg/kg IV",
      "Phenytoin 20 mg/kg IV",
      "Phenobarbital 20 mg/kg IV",
      "Carbamazepine orally",
    ],
    correctIndex: 0,
    rationale: "Lorazepam 0.1 mg/kg IV is a fast acting benzodiazepine that controls seizure activity, but is a short-term measure. Phenytoin and phenobarbital are used for longer term management.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "A 43-year-old banker reports four episodes of vomiting bright red blood with no pain, feeling light-headed and weak. Which is the appropriate test to confirm the diagnosis?",
    options: [
      "Endoscopy of the digestive system",
      "Computed tomography scan",
      "Magnetic resonance imaging",
      "Abdominal ultrasound",
    ],
    correctIndex: 0,
    rationale: "Vomiting bright red blood, known as haematemesis, is a medical emergency that can indicate serious gastrointestinal bleeding. Endoscopy is the most appropriate step to visualise the gastrointestinal tract and identify the source.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A 43-year-old female with chronic diabetes and hypertension complains of progressive dyspnoea on exertion and recent paroxysmal nocturnal dyspnoea. Examination reveals an aortic murmur and echocardiogram shows aortic stenosis. Which condition most likely led to the aortic stenosis?",
    options: ["Rheumatic fever", "Hypertension", "Diabetes", "Atherosclerosis"],
    correctIndex: 0,
    rationale: "Aortic stenosis is typically caused by progressive wear and tear of the valve with age or calcification, but can also be caused by congenital heart defects, rheumatic fever and other conditions.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A 48-year-old female has taken ciprofloxacin for a urinary tract infection for three days and now reports watery stools with abdominal cramping and bloating. Clostridium difficile toxin is positive. Which antibiotic is recommended as first line therapy?",
    options: ["Vancomycin 125 mg", "Levofloxacin 750 mg", "Metronidazole 500 mg", "Ciprofloxacin 500 mg"],
    correctIndex: 0,
    rationale: "The client has antibiotic associated diarrhoea due to Clostridium difficile infection. First line treatment is oral vancomycin. Levofloxacin and metronidazole are not effective for this infection.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A 48-year-old man reports drooping of the face and difficulty speaking for 48 hours. There is paralysis of the upper and lower face on the right side, he cannot raise his eyebrows or close his eye tightly, the right side of the mouth droops and the nasolabial fold is smoothed out. Which is true about the most likely diagnosis?",
    options: [
      "Facial nerve paralysis",
      "Upper motor neuron lesion",
      "Cerebrovascular accident",
      "Trigeminal neuralgia",
    ],
    correctIndex: 0,
    rationale: "These are classic signs of Bell's palsy, or facial nerve paralysis. A cerebrovascular accident can cause facial paralysis but is typically associated with additional neurological symptoms such as hemiparesis and sensory deficits, which were not described.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "A 50-year-old woman with constipation, hypertension and diabetes has a family history of colon cancer. Colonoscopy showed mild diverticular disease and two 2 mm hyperplastic polyps removed from the rectum. What is the APPROPRIATE interval for the next colonoscopy?",
    options: ["3 years", "1 year", "5 years", "10 years"],
    correctIndex: 0,
    rationale: "For average risk individuals with normal colonoscopy findings the recommended interval is ten years. With a family history of colon cancer and two small non-cancerous polyps, the recommended interval is shortened to three years.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A 50-year-old with hypertension, seizures and alcohol use presents after two weeks of productive cough, fever and chills. Examination shows a fluid level in the right upper lobe, with a presumptive diagnosis of lung abscess and treatment with ampicillin. What is the MOST appropriate nursing care?",
    options: [
      "Monitor and observe the client's vital signs, record and report any changes",
      "Assist the client into a comfortable position and record changes only",
      "Perform adequate drainage using a chest tube and report changes",
      "Encourage early discharge with oral antibiotics",
    ],
    correctIndex: 0,
    rationale: "Close monitoring and observation of vital signs such as temperature and heart rate during antibiotic treatment for a lung abscess is crucial for identifying complications, adverse reactions and deterioration early.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "A 52-year-old woman is referred by a urologist for a 3 cm right adrenal mass found on abdominal scan. She has stable weight, no hirsutism, acne, proximal myopathy or easy bruising, but has felt depressed. She reports diaphoresis and occasional headaches without palpitations. Diabetes is controlled by diet. What is the best initial strategy?",
    options: [
      "Overnight dexamethasone suppression test",
      "Determine aldosterone to plasma renin activity ratio",
      "Serum testosterone and androstenedione levels",
      "Immediate adrenalectomy",
    ],
    correctIndex: 0,
    rationale: "The best initial strategy for an adrenal mass with symptoms suggestive of adrenal dysfunction is an overnight dexamethasone suppression test to evaluate for cortisol excess, the most common cause of adrenal masses in non-smoking women.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "A 53-year-old man with chronic pancreatitis from chronic alcohol use complains of acute worsening of epigastric pain and dizziness. His pain has been hard to control despite analgesia, and he has melaena stool. Which care is MOST appropriate?",
    options: [
      "Observe changes in vital signs, stool and vomitus and report promptly",
      "Monitor for changes in condition and record only",
      "Check vital signs four hourly and record only",
      "Encourage oral fluids and review in the morning",
    ],
    correctIndex: 0,
    rationale: "The new symptoms of acute worsening epigastric pain, dizziness and melaena stool suggest a more severe complication such as necrosis or gastrointestinal bleeding. Observing changes in vital signs, stool and vomitus and reporting promptly is the most appropriate intervention.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A 54-year-old admitted with heart failure complains of difficulty breathing. Which nursing interventions should be put in place to aid breathing?",
    options: [
      "Auscultate the lungs, place in high Fowler's position and administer oxygen as per protocol",
      "Auscultate the lungs and place in high Fowler's position only",
      "Place in high Fowler's position and administer diuretics only",
      "Administer diuretics and encourage fluids",
    ],
    correctIndex: 0,
    rationale: "Auscultation assesses for abnormal breath sounds or congestion, positioning reduces pressure on the diaphragm to improve lung expansion, and oxygen improves oxygenation and reduces respiratory distress.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A 55-year-old presents with confusion and fever after an acute inferolateral myocardial infarction and coronary angioplasty. He is febrile, disoriented, and had a tonic-clonic seizure with an hour-long postictal state. Haematocrit 24%, platelets 1,000/mm3, LDH 900 U/L, direct Coombs negative. What is the NEXT step in diagnosis?",
    options: [
      "Peripheral blood smear review",
      "Intravenous fluid resuscitation",
      "Pulmonary artery catheterization",
      "Lumbar puncture",
    ],
    correctIndex: 0,
    rationale: "These findings raise suspicion of thrombotic thrombocytopenic purpura, a medical emergency requiring urgent diagnosis. A peripheral blood smear identifies red cell fragments called schistocytes, which are characteristic of the condition.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A 55-year-old is admitted with chronic renal failure which has resulted in inadequate production of erythropoietin. The patient can develop?",
    options: ["Anaemia", "Acidosis", "Calcium imbalance", "Hypertension"],
    correctIndex: 0,
    rationale: "Erythropoietin is a hormone produced by the kidneys that stimulates red blood cell production in the bone marrow. In chronic renal failure insufficient erythropoietin leads to decreased red cell production and subsequent anaemia.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A 55-year-old female has stage II hypertension with trace bilateral pedal oedema and clear lungs. ECG reveals second-degree heart block. Which medication should be avoided?",
    options: ["Calcium channel blockers", "Diuretics", "Angiotensin receptor blockers", "Thiazide diuretics"],
    correctIndex: 0,
    rationale: "Calcium channel blockers should be avoided because they can worsen second-degree heart block by slowing cardiac electrical conduction, potentially leading to greater blockage of electrical signals.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A 55-year-old banker is admitted with acute cardiac tamponade. What is the MOST important intervention?",
    options: [
      "Fluid resuscitation",
      "Heart massage",
      "Epinephrine administration",
      "Pericardiocentesis",
    ],
    correctIndex: 0,
    rationale: "The most important intervention in acute cardiac tamponade is to relieve the compression on the heart caused by fluid accumulation in the pericardial sac, typically achieved by draining the fluid with pericardiocentesis.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A 56-year-old woman on the ward has polydipsia, a fruity breath odour, polyuria, and is disorientated and confused. How would she be diagnosed?",
    options: ["Diabetic ketoacidosis", "Diabetes insipidus", "Gestational diabetes", "Hyperosmolar hyperglycaemic state"],
    correctIndex: 0,
    rationale: "These symptoms are characteristic of diabetic ketoacidosis, a potentially life-threatening complication of diabetes occurring when the body produces high levels of blood acids called ketones due to insulin deficiency. Blood ketone measurement confirms the diagnosis.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "A 56-year-old has been diagnosed with gout. In explaining the cause, you would mention that gout occurs as a result of the accumulation of what in the blood?",
    options: ["Uric acid", "Creatinine", "Purine", "Urea"],
    correctIndex: 0,
    rationale: "Gout occurs as a result of accumulation of uric acid in the blood, which can form crystals that deposit in the joints and cause pain, inflammation and other symptoms.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A 6-year-old girl from a rural area is brought in because she cannot play with her peers and always squats after a short period of activity. Assessment shows clubbed fingers. Clubbing of the fingers occurs in which condition?",
    options: ["Congenital heart disease", "Anaemia", "Bronchitis", "Asthma"],
    correctIndex: 0,
    rationale: "Clubbing is a condition in which the fingertips become enlarged and the nail bed curves, giving a club-like appearance. It is commonly associated with congenital heart disease, lung cancer and other conditions causing chronic hypoxia.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A 64-year-old man reports a severe headache beginning five hours ago as a unilateral dull ache over the left eye and temporal region with nausea and photophobia. Paracetamol and ibuprofen gave no relief. The left sclera is erythematous with a fixed mid-dilated pupil, and head CT without contrast is normal. What is the most likely diagnosis?",
    options: [
      "Acute angle-closure glaucoma",
      "Age-related macular degeneration",
      "Diabetic retinopathy",
      "Migraine",
    ],
    correctIndex: 0,
    rationale: "Acute angle-closure glaucoma is a medical emergency with severe headache, eye pain, nausea, vomiting, visual disturbance, redness and tearing, caused by sudden blockage of the eye's drainage system raising intraocular pressure. Prompt treatment is needed to avoid irreversible vision loss.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A 66-year-old beer bar operator with a history of tobacco abuse and obesity has an elevated haematocrit of 51% on routine testing. She has occasional headaches and no history of thrombosis. What is the next step in investigation and management?",
    options: [
      "Serum erythropoietin screening",
      "Continued observation",
      "Phlebotomy and aspirin",
      "Bone marrow biopsy",
    ],
    correctIndex: 0,
    rationale: "When haematocrit is raised, serum erythropoietin screening is needed to determine the underlying cause. Elevated erythropoietin suggests secondary erythrocytosis, while low levels suggest primary erythrocytosis such as polycythaemia vera.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A 67-year-old woman on the ward has insomnia. Sleep is characterised by a cyclical alternation between rapid eye movement and non-rapid eye movement sleep with a period of?",
    options: ["90 to 110 minutes", "30 to 50 minutes", "60 to 80 minutes", "120 to 140 minutes"],
    correctIndex: 0,
    rationale: "This period allows sufficient time for the various stages of sleep to occur, including deep slow wave sleep and rapid eye movement sleep, which are both essential for restorative functions and cognitive processing.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A 67-year-old is diagnosed with infective endocarditis. As the nurse on duty, which nursing diagnosis is correct?",
    options: [
      "Decreased cardiac output related to reduced mechanical function of the heart muscle",
      "Decreased cardiac output related to decreased pumping action of the heart",
      "Decreased function of the activity of the heart related to infective endocarditis",
      "Impaired gas exchange related to reduced cardiac output",
    ],
    correctIndex: 0,
    rationale: "Infective endocarditis is an infection of the heart's endocardial surface including the valves, which can damage the valve and reduce the heart's ability to pump blood effectively. This reduced mechanical function leads to decreased cardiac output.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A 69-year-old male presents for a routine examination. He has gout with a recent exacerbation, and also has hypertension and diabetes. Which blood pressure medication could exacerbate his gout?",
    options: ["Hydrochlorothiazide", "Amlodipine", "Lisinopril", "Atenolol"],
    correctIndex: 0,
    rationale: "Hydrochlorothiazide is a thiazide diuretic that decreases excretion of uric acid, raising serum uric acid levels and potentially triggering gout exacerbations.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A 70-year-old female is admitted with a urinary tract infection. Which factors contributed to the infection in this patient?",
    options: [
      "Frequent use of antimicrobial agents, incomplete emptying of the bladder, and prolonged confinement to bed",
      "Presence of an infected wound on the leg, incomplete bladder emptying and prolonged bed rest",
      "Frequent use of antimicrobial agents, presence of an infected leg wound, and prolonged bed rest",
      "Incomplete bladder emptying, infected leg wound, and frequent antimicrobial use",
    ],
    correctIndex: 0,
    rationale: "The presence of an infected wound on the leg is not a direct contributing factor to the development of a urinary tract infection. Antimicrobial use, incomplete bladder emptying and immobility all contribute.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A 70-year-old male with coronary artery disease and hypertension is receiving treatment for acute low back pain. Which drug should be avoided in this patient due to cardiovascular concerns?",
    options: ["Naprosyn", "Hydrocodone", "Acetaminophen", "Codeine"],
    correctIndex: 0,
    rationale: "Naprosyn is a nonsteroidal anti-inflammatory drug shown to increase the risk of cardiovascular events such as heart attack and stroke, and can further raise blood pressure, increasing strain on the heart.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A 72-year-old male admitted with severe diarrhoea was recently discharged after four days in hospital for giardiasis treated with metronidazole. He is diagnosed with Clostridium difficile infection. Which is TRUE regarding C. difficile?",
    options: [
      "It is an anaerobic gram-negative, spore-forming, toxin-producing bacillus",
      "It is most commonly transmitted by airborne transmission",
      "A common predisposing risk factor is recent metronidazole use",
      "It is a gram-positive coccus",
    ],
    correctIndex: 0,
    rationale: "C. difficile is an anaerobic gram-negative, spore-forming, toxin-producing bacillus commonly associated with antibiotic use, which disrupts normal gut flora allowing proliferation and infection. It is transmitted by the faecal-oral route, not airborne.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A 72-year-old man with liver cirrhosis is on dietary modification. He has ascites with severe hepatic dysfunction. His diet should be high in?",
    options: ["Carbohydrate, low sodium", "Sodium, low protein", "Protein, low carbohydrate", "Fat, low carbohydrate"],
    correctIndex: 0,
    rationale: "For clients with ascites and severe hepatic dysfunction from cirrhosis, dietary modification including reduced protein intake and sodium restriction is recommended to minimise the build-up of toxic substances and reduce complications such as fluid accumulation, oedema and hyponatraemia.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A 72-year-old female is scheduled for a CT scan with contrast. Which medication should be withheld?",
    options: ["Metformin", "Lantus", "Glipizide", "Amlodipine"],
    correctIndex: 0,
    rationale: "Metformin is withheld to reduce the risk of kidney damage, as contrast material can harm kidney function and metformin can further worsen this by reducing kidney function.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A female with hypertension and type 2 diabetes presents to the emergency department with onset of epigastric pain. She is diaphoretic and nauseated, and the pain is unrelieved by antacids. Blood pressure is 135/90 mmHg, heart rate 80 bpm, respiratory rate 20. Which test should be ordered first?",
    options: ["ECG", "Amylase", "Lipase", "Chest x-ray"],
    correctIndex: 0,
    rationale: "An ECG is the most appropriate initial test because the symptoms and medical history are more suggestive of a cardiac event, which can be confirmed by ECG. Amylase and lipase could be considered later if the ECG is normal.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A 72-year-old man with alcoholic cirrhosis and recurrent ascites was admitted five days ago with haematemesis and dark-coloured urine. He has bilateral lower limb oedema. What is the MOST likely explanation of his condition?",
    options: [
      "Hepatorenal syndrome",
      "Acute tubular necrosis",
      "Contrast nephropathy",
      "Chronic glomerulonephritis",
    ],
    correctIndex: 0,
    rationale: "The most likely explanation is hepatorenal syndrome, a reversible renal failure that can occur in patients with cirrhosis.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A 74-year-old female complains of abdominal pain for three days. Temperature 37.6 degrees Celsius, pulse 88 bpm, blood pressure 112/70 mmHg. Examination shows left lower quadrant tenderness without rebound, guarding or palpable masses. Laboratory studies are normal. What is the next step in evaluation and management?",
    options: [
      "CT scan of the abdomen",
      "Abdominal x-rays",
      "Trial of liquid diet only",
      "Immediate laparotomy",
    ],
    correctIndex: 0,
    rationale: "A CT scan provides a more detailed image of the abdomen including organs, blood vessels and other structures, helping identify the underlying cause of the symptoms.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A 75-year-old woman is brought to the Community Eye Clinic by her children. Ocular assessment shows decreased vision, photophobia and conjunctival injection. Slit-lamp findings reveal cells in the aqueous humour and keratic precipitates. Which diagnosis would you expect in the client's folder?",
    options: ["Anterior uveitis", "Posterior uveitis", "Diffuse uveitis", "Acute conjunctivitis"],
    correctIndex: 0,
    rationale: "The symptoms and findings are consistent with anterior uveitis, inflammation of the iris and ciliary body. Posterior and diffuse uveitis involve inflammation of the posterior uvea and typically present with different symptoms and findings.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A 78-year-old on diuretics to manage mild heart failure is to receive oral diuretics. You are sure to administer it in the morning to avoid?",
    options: ["Night sleep interference", "Drug interaction", "Adverse reactions", "Hypertension"],
    correctIndex: 0,
    rationale: "Administering diuretics in the morning allows increased urinary output during the day, preventing the need to get up frequently at night to pass urine and avoiding sleep interference.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A 78-year-old complains of left lower abdominal pain for five days. The practitioner suspects diverticulitis. Which imaging study should be ordered to confirm the diagnosis?",
    options: ["CT abdomen", "Colonoscopy", "Barium enema", "Abdominal ultrasound"],
    correctIndex: 0,
    rationale: "CT abdomen provides detailed images of the abdominal organs and can accurately diagnose diverticulitis, which is a common cause of abdominal pain in older adults.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A 78-year-old with morning headaches and blood pressure 160/90 mmHg was diagnosed with hypertension and put on hydrochlorothiazide 25 mg daily. On follow-up he says that since the headaches stopped he is no longer taking the medication. What is the BEST course of action?",
    options: [
      "Educate the patient on the importance of taking the medication daily",
      "Advise the patient to continue not taking hydrochlorothiazide",
      "Tell the patient the dose will be reduced to 12.5 mg daily",
      "Change the medication immediately",
    ],
    correctIndex: 0,
    rationale: "Hypertension is a chronic condition requiring ongoing management to prevent complications. Discontinuing medication without consulting a healthcare professional leads to uncontrolled hypertension and increases the risk of complications.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A 7-year-old is admitted with valvular heart disease. Assessment reveals dyspnoea on exertion, haemoptysis and fatigue. He is probably suffering from mitral valve?",
    options: ["Stenosis", "Prolapse", "Regurgitation", "Prolapse with regurgitation"],
    correctIndex: 0,
    rationale: "Mitral valve stenosis occurs when the mitral valve becomes narrowed, making it difficult for blood to flow from the left atrium to the left ventricle. This causes dyspnoea on exertion, haemoptysis and fatigue, and may also cause chest pain and palpitations.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A client arrives at the emergency room with an impacted cerumen in the left ear. Which intervention would the nurse anticipate performing initially?",
    options: [
      "Instillation of olive oil",
      "Irrigation of the ear",
      "Instillation of antibiotic ear drops",
      "Manual removal with forceps",
    ],
    correctIndex: 0,
    rationale: "The initial intervention for impacted cerumen is to soften the wax and allow it to come out naturally. Instillation of olive oil is a common method used to soften the wax and facilitate removal.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A client was admitted to the medical ward with gastroenteritis. In planning care, which of the following is NOT a diagnostic finding for gastroenteritis?",
    options: ["Abdominal x-ray", "Endoscopy", "Full blood count", "Stool culture"],
    correctIndex: 0,
    rationale: "Abdominal x-ray is not typically used to diagnose gastroenteritis as it does not provide much information about the digestive tract. X-rays can be useful for complications such as blockages or foreign bodies but are not a diagnostic finding for gastroenteritis itself.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A compound in a solution that usually dissociates into discrete particles is known as?",
    options: ["Electrolytes", "Anions", "Cations", "Isotopes"],
    correctIndex: 0,
    rationale: "Electrolytes are important in the body as they conduct electricity in solution, helping regulate fluid balance, muscle and nerve function, and acid-base balance by separating into positively charged cations and negatively charged anions when dissolved in water.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A CT scan report for a client revealed a progressive disease of the heart characterised by fat formation affecting the intimal and medial layers of large and midsize arteries. The client is likely to be diagnosed with?",
    options: ["Atherosclerosis", "Arteriosclerosis", "Arteriogenic", "Aneurysm"],
    correctIndex: 0,
    rationale: "Atherosclerosis is characterised by the progressive formation of fat deposits in the intimal and medial layers of large and midsize arteries.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A definitive diagnosis of sickle cell disease is based on which diagnostic result?",
    options: [
      "Haemoglobin electrophoresis",
      "Bone marrow aspiration",
      "Full blood count",
      "Peripheral blood smear",
    ],
    correctIndex: 0,
    rationale: "Haemoglobin electrophoresis is the definitive test for diagnosing sickle cell disease, as it identifies sickle haemoglobin, the hallmark of the disease.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A disease with an unknown cause is usually described as which type of disease?",
    options: ["Idiopathic", "Iatrogenic", "Communicable", "Congenital"],
    correctIndex: 0,
    rationale: "The term idiopathic refers to a medical condition of unknown or spontaneous origin, emphasising that the cause is not identifiable.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A disorder of the internal ear characterised by recurrent attacks of severe vertigo, nausea, vomiting, tinnitus and progressive hearing loss is called?",
    options: ["Meniere's syndrome", "Acute otitis media", "Mastoiditis", "Otosclerosis"],
    correctIndex: 0,
    rationale: "The symptoms are characteristic of Meniere's syndrome, a disorder of the inner ear affecting balance and hearing, which can be debilitating for the affected individual.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A farmer who self-medicates with both herbal and orthodox medicines is rushed in with severe flank pain, tingling of the fingers and toes and muscle twitching. He is diagnosed with acute renal failure. The tingling and muscle twitching are caused by?",
    options: ["Potassium retention", "Acidosis", "Calcium depletion", "Sodium loss"],
    correctIndex: 0,
    rationale: "In acute renal failure the kidneys cannot remove excess potassium from the body, causing hyperkalaemia, which disrupts normal nerve and muscle function and causes these symptoms.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A female patient aged 31 is admitted with ulcerative colitis. Which enzyme is NOT present in the small intestine?",
    options: ["Chymotrypsinogen", "Enterokinase", "Erepsin", "Lactase"],
    correctIndex: 0,
    rationale: "Chymotrypsinogen is not present in the small intestine but rather in the pancreas.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A female patient had a severe drug reaction after receiving her medication. Her lips were swollen and she had difficulty breathing. This reaction is known as?",
    options: [
      "Anaphylactic reaction",
      "Drug intolerance",
      "Medication reaction",
      "Side effect",
    ],
    correctIndex: 0,
    rationale: "Anaphylaxis is a severe and potentially life-threatening allergic reaction to a substance such as a medication, food or insect sting. Symptoms include swollen lips, tongue or throat, difficulty breathing, hives, rash, nausea, vomiting and a rapid or weak pulse.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A female patient being discharged after treatment of a urinary tract infection. Which information would prevent recurrence of the condition?",
    options: [
      "Clean the perineum with warm soapy water after each bowel movement, empty the bladder regularly every three to four hours, and maintain adequate fluid intake of at least three litres daily",
      "Clean the perineum after bowel movements and empty the bladder regularly only",
      "Maintain adequate fluid intake and clean the perineum only",
      "Empty the bladder every six hours and reduce fluid intake",
    ],
    correctIndex: 0,
    rationale: "Adequate fluid intake helps flush out bacteria and prevents concentrated urine, while cleaning the perineum after bowel movements prevents spread of bacteria from the anus to the urethra.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A group of students contracted typhoid fever. Salmonella typhi, the causative organism, could have been transmitted through?",
    options: [
      "Consumption of contaminated food or water",
      "Droplets from an infected person through coughing or sneezing",
      "Having unprotected sex with an infected person",
      "Direct skin contact with an infected person",
    ],
    correctIndex: 0,
    rationale: "Typhoid fever is transmitted through consumption of contaminated food or water because Salmonella typhi is found in the faeces of infected individuals and can easily contaminate food and water sources.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A known diabetic patient must be taught sick day rules for the condition when ill. The MOST important to teach the patient includes?",
    options: [
      "Consume frequent small carbohydrate-containing meals",
      "Limit fluid intake as necessary",
      "Increase the insulin dose when vomiting",
      "Stop all medication until recovered",
    ],
    correctIndex: 0,
    rationale: "Sick day rules for managing diabetes include frequent monitoring of blood glucose, continuing to take insulin or other diabetes medication as prescribed, staying hydrated, consuming small frequent meals with carbohydrate, and keeping a list of emergency contact numbers.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "A known hypertensive female reports with severe abdominal pain and is diagnosed with acute gastritis. Which statement regarding acute gastritis is true?",
    options: [
      "It can be the result of chronic intake of nonsteroidal anti-inflammatory analgesics",
      "It is primarily caused by lack of dietary fibre",
      "The gold standard for evaluation is colonoscopy",
      "It is caused by excess bile production",
    ],
    correctIndex: 0,
    rationale: "Acute gastritis can be caused by several factors including chronic use of nonsteroidal anti-inflammatory drugs, alcohol consumption, infections and other factors causing irritation or inflammation of the stomach lining.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Laboratory investigation of a client revealed protozoa, helminths and bacteria as causative agents of his condition, and the doctor diagnosed concomitant infections. This indicates the presence of?",
    options: [
      "Two or more parasites in one host",
      "A parasite in one host",
      "Several parasites in separate hosts",
      "A single parasite in one host",
    ],
    correctIndex: 0,
    rationale: "Concomitant infections refer to the simultaneous presence of two or more infections in a single host. In this case the client had protozoa, helminths and bacteria, indicating two or more parasites in one host.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A major objective of nursing patients with acute lymphocytic leukaemia on chemotherapeutic protocols is to?",
    options: [
      "Avoid contact with persons with infections",
      "Obtain baseline data for monitoring",
      "Improve the patient's response to change in nursing actions",
      "Encourage a high visitor volume",
    ],
    correctIndex: 0,
    rationale: "This is due to the immunosuppressive effects of chemotherapy, which place the client at high risk of infection.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A male patient aged 35 was admitted with a severe sinus infection and meningitis, and develops acute renal failure due to drug interactions. Which nursing intervention should be put in place?",
    options: [
      "Ensure adequate hydration of the patient",
      "Check vital signs four hourly and report",
      "Monitor the patient for signs of fluid volume excess",
      "Restrict all fluids completely",
    ],
    correctIndex: 0,
    rationale: "Adequate hydration maintains renal perfusion and increases urine output, promoting elimination of drugs and metabolic wastes, preventing electrolyte imbalance and improving renal function.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A male patient aged 52 is admitted and not yet diagnosed. During general assessment you observe an involuntary flapping movement of the hands usually associated with metabolic liver dysfunction. This is known as?",
    options: ["Asterixis", "Dystonia", "Parkinsonism", "Chorea"],
    correctIndex: 0,
    rationale: "Asterixis is an involuntary flapping movement of the hands usually observed in clients with metabolic liver dysfunction such as hepatic encephalopathy, due to the liver's inability to detoxify ammonia, causing a build-up of toxins affecting the brain.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A male patient reports to the hospital with a history of untreated urethral discharge. Untreated urethral discharge in men will lead to which of the following?",
    options: [
      "Chancroid, epididymo-orchitis and urethral strictures",
      "Chancroid, infertility and urethral strictures",
      "Epididymo-orchitis, infertility and chancroid",
      "Infertility alone with no other complication",
    ],
    correctIndex: 0,
    rationale: "Untreated urethral discharge in men can lead to chancroid, epididymo-orchitis and urethral strictures. Infertility is not caused directly but by other related complications such as pelvic inflammatory disease in partners.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A male patient attends the outpatient department and is diagnosed with Vincent's angina. The BEST treatment of choice is?",
    options: ["Penicillin", "Azithromycin", "Amoxicillin", "Metronidazole"],
    correctIndex: 0,
    rationale: "Vincent's angina, an acute necrotising ulcerative gingivitis caused by bacterial infection including Fusobacterium and Borrelia species, is treated with antibiotics, primarily penicillin, to control infection and prevent complications such as ulceration, bleeding and necrosis of the gums and oral mucous membranes.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A middle-aged man is accompanied by his wife to the medical emergency with difficulty breathing. Initial assessment reveals a collection of fluid in his lungs. What position will the nurse place the patient in to facilitate breathing?",
    options: ["Semi-Fowler's position", "Fowler's position", "Prone position", "Trendelenburg position"],
    correctIndex: 0,
    rationale: "The semi-Fowler's position, with the head of the bed elevated at 45 degrees, promotes ease of breathing by opening the airways and reducing fluid accumulation in the lungs.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A minibus driver suddenly stopped the vehicle complaining of severe excruciating eye pain and inability to see clearly. History reveals tunnel vision and coloured halos around lights. Assessment shows a frosted corneal appearance and acute angle-closure glaucoma is diagnosed. The intraocular pressure may rise to?",
    options: ["50 mmHg", "22 mmHg", "29 mmHg", "42 mmHg"],
    correctIndex: 0,
    rationale: "The intraocular pressure in acute angle-closure glaucoma can rise as high as 50 mmHg, which can lead to optic nerve damage and vision loss.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A mother brought her 16-year-old teenager to hospital with suspected meningitis. Which may be present during the initial phase of meningitis?",
    options: [
      "Headache, nausea and vomiting",
      "Fever and headache only",
      "Headache and neck stiffness only",
      "Rash and joint pain only",
    ],
    correctIndex: 0,
    rationale: "Headache, nausea and vomiting are common symptoms of inflammation of the membranes surrounding the brain and spinal cord, which can be caused by bacterial, viral or fungal infections.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A newly diagnosed 42-year-old diabetic client is to be discharged on medication and diet. During education she is advised to include fibre in her diet. Fibre plays a role in?",
    options: [
      "Lowering total cholesterol and low density lipoprotein",
      "Lowering total cholesterol and high density lipoprotein",
      "Increasing total cholesterol and low density lipoprotein",
      "Raising triglycerides only",
    ],
    correctIndex: 0,
    rationale: "Fibre lowers total cholesterol and low density lipoprotein by binding cholesterol in the gut and preventing its absorption, promoting excretion and reducing blood levels.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "A nurse educator is lecturing second year nursing students on which person stands at highest risk of developing pulmonary embolism?",
    options: [
      "A person with a coagulation disorder",
      "A person with prolonged immobilization",
      "A person with malignancy",
      "A person with controlled hypertension",
    ],
    correctIndex: 0,
    rationale: "Coagulation disorders such as deep vein thrombosis increase the risk of clots forming in the veins, which can then travel to the lungs and cause a pulmonary embolism.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "A nurse is educating a group of patients at the outpatient department on gout, and is asked which foods should be eaten. Which foods should the nurse recommend?",
    options: ["Banana and meat", "Sardine, banana, wheat bread and meat", "Sardine and wheat bread only", "Sardine and meat only"],
    correctIndex: 0,
    rationale: "A diet including bananas and meat, while limiting sardines and wheat bread, may help manage gout, because bananas are low in purines which can raise uric acid, and meat provides essential nutrients.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A nurse is evaluating a patient with macrocytic anaemia most likely due to vitamin B12 deficiency. Which of the following is associated with this type of anaemia?",
    options: [
      "Tingling and numbness in the feet",
      "Asterixis",
      "Hair thinning",
      "Brittle nails",
    ],
    correctIndex: 0,
    rationale: "Vitamin B12 is critical for proper functioning of the nervous system, and tingling and numbness in the feet result from deficiency of this vitamin.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A nurse is teaching bank workers how to prevent varicose veins. Which recommendation made by the nurse is MOST accurate?",
    options: [
      "Wear support hose or thromboembolic deterrent stockings",
      "Wear clean white cotton socks with shoes",
      "Engage in passive range of motion exercise",
      "Stand for longer periods to improve circulation",
    ],
    correctIndex: 0,
    rationale: "Varicose veins occur when veins become swollen and twisted, usually in the legs. Jobs requiring long periods of standing or sitting increase the risk. Compression stockings support blood flow in the legs, reduce swelling and help prevent clots.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A nurse is treating a 70-year-old male with a history of coronary artery disease and hypertension for acute low back pain. Which drug should be avoided due to cardiovascular concerns?",
    options: ["Naprosyn", "Acetaminophen", "Hydrocodone", "Tramadol"],
    correctIndex: 0,
    rationale: "Naprosyn is a nonsteroidal anti-inflammatory drug shown to increase the risk of cardiovascular events such as heart attack and stroke, and can further increase blood pressure, putting more strain on the heart and blood vessels.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A nurse is asked to develop a nursing care plan for a patient with a diagnosis of gout. What is the best nursing intervention?",
    options: [
      "Apply cold and warm compress on the affected foot daily",
      "Administer aspirin",
      "Provide food high in purines",
      "Encourage unrestricted alcohol intake",
    ],
    correctIndex: 0,
    rationale: "Cold and warm compresses help reduce the pain and inflammation associated with gout and promote healing of the affected joint.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A nursing diagnosis of fluid volume imbalance related to fluid loss or shifts is made for a patient with diabetic ketoacidosis. The nurse MUST set up which intravenous fluid for the patient?",
    options: [
      "0.9% normal saline",
      "Dextrose in saline",
      "4.3% dextrose in 1/5 normal saline",
      "5% dextrose in water",
    ],
    correctIndex: 0,
    rationale: "Diabetic ketoacidosis is characterised by high blood glucose causing diuresis, fluid loss and dehydration. Normal saline is preferred over hypotonic solutions because it provides controlled replacement in patients with ketoacidosis due to its isotonic nature.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "A nursing diagnosis of impaired communication related to brain damage is made for a patient with an ischaemic stroke. Which nursing action is MOST appropriate?",
    options: [
      "Establish eye contact when communicating with the patient",
      "Provide pen and paper for the patient to write",
      "Allow the patient to ask questions about what he does not understand",
      "Speak loudly and slowly to the patient",
    ],
    correctIndex: 0,
    rationale: "Establishing eye contact is crucial when communicating with a patient with brain damage, as it facilitates non-verbal communication and creates a supportive environment for communication.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "A nursing diagnosis of imbalanced nutrition less than body requirements is made for a patient with protein energy malnutrition. Which should the nurse consider when planning care?",
    options: [
      "Provide highly nutritious meals to make up for the deficit",
      "Modify the patient's favourite foods only",
      "Serve intravenous fluids if the patient averts food",
      "Withhold food until appetite returns",
    ],
    correctIndex: 0,
    rationale: "The aim is to improve nutritional status by providing highly nutritious meals that compensate for the deficit and supply the body with the nutrients needed to maintain good health.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A patient aged 40 was rushed to the emergency unit with a history of bronchial asthma and a key complaint of difficulty in breathing. Which nursing diagnosis would be correct?",
    options: [
      "Ineffective breathing pattern related to dyspnoea",
      "Impaired physical mobility related to dyspnoea",
      "Caregiver role strain related to dyspnoea",
      "Acute confusion related to hypoxia",
    ],
    correctIndex: 0,
    rationale: "In clients with respiratory problems such as bronchial asthma, ineffective breathing pattern is a common nursing diagnosis indicating impaired ventilation or gas exchange due to alteration in the depth, rate or rhythm of breathing, related to dyspnoea.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "A patient aged 44 is diagnosed with chronic renal failure and is experiencing metabolic acidosis. As the attending nurse you understand that metabolic acidosis usually occurs in chronic renal failure due to?",
    options: [
      "High hydrogen, low ammonia, low bicarbonate",
      "Low hydrogen, high ammonia, low bicarbonate",
      "Low hydrogen, low ammonia, high bicarbonate",
      "High hydrogen, high ammonia, high bicarbonate",
    ],
    correctIndex: 0,
    rationale: "In chronic renal failure the kidneys cannot excrete sufficient acid or maintain bicarbonate levels, causing acidosis. This is described by high hydrogen ion from accumulation of acidic substances, low ammonia from impaired conversion of ammonia by the kidneys, and low bicarbonate from retention.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A patient asks a nurse, 'Should I tell my husband that I am HIV positive?' What is the appropriate response?",
    options: [
      "'Are you having difficulty deciding what to say?'",
      "'This is a decision you need to make alone.'",
      "'You must tell him immediately.'",
      "'Do not tell him under any circumstances.'",
    ],
    correctIndex: 0,
    rationale: "This response acknowledges the client's concerns and allows them to take ownership of the decision-making process, rather than being told what to do.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A patient came to the medical ward from the outpatient department with a diagnosis of acidosis. Which would be the MOST noticeable sign or symptom she is likely to present with?",
    options: [
      "Altered mental status",
      "Convulsions",
      "Irregular heartbeat",
      "Severe headache",
    ],
    correctIndex: 0,
    rationale: "Acidosis is a condition in which there is increased acidity of the blood or decreased bicarbonate concentration, which helps maintain normal blood pH. It affects the central nervous system and can alter brain function, leading to changes in cognitive function and mental status.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "A patient complains of severe pain in the left and right wrist joints as a result of arthritis. Which non-pharmacologic nursing intervention would help alleviate the pain?",
    options: [
      "Assist the patient with a warm bath or shower",
      "Exercise the affected joints regularly",
      "Apply deep massage therapy to the joints",
      "Immobilise the joints completely",
    ],
    correctIndex: 0,
    rationale: "A warm bath or shower can help reduce pain and stiffness by promoting circulation and relaxation of the affected joints.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A patient diagnosed with chronic oesophagitis has been booked for oesophagogastroduodenoscopy. The nurse must teach the patient to be nil per os for how many hours prior to the examination?",
    options: ["6 to 8 hours", "10 hours", "12 hours", "24 hours"],
    correctIndex: 0,
    rationale: "The recommended time for a patient to be nil per os prior to oesophagogastroduodenoscopy is typically six to eight hours, to ensure the stomach is empty and allow better visualisation of the oesophagus, stomach and duodenum during the procedure.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A patient diagnosed with cirrhosis of the liver has laboratory results indicating varied levels of enzymes. Which of these is expected in this patient?",
    options: [
      "Raised serum glutamic oxaloacetic transaminase",
      "Increased serum albumin with normal prothrombin time",
      "Increased serum magnesium and prothrombin time",
      "Decreased serum bilirubin",
    ],
    correctIndex: 0,
    rationale: "Raised serum glutamic oxaloacetic transaminase, also known as aspartate aminotransferase, is a common finding in clients with liver cirrhosis and indicates liver damage.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A patient diagnosed with coeliac disease is admitted with severe abdominal pain, nausea, vomiting and diarrhoea. The nursing management would include the following EXCEPT?",
    options: [
      "Encourage intake of cereals, crackers, noodles and wheat",
      "Fluid and electrolyte replacement and administration of supplements",
      "Education on gluten free diet, vitamin and mineral supplementation",
      "Monitoring of weight and nutritional status",
    ],
    correctIndex: 0,
    rationale: "Encouraging intake of cereals, crackers, noodles and wheat is not appropriate in the management of coeliac disease, as these foods contain gluten and can exacerbate the client's symptoms.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A patient diagnosed with oesophageal varices begins to vomit large volumes of bright red fluid. You are called to the bedside because the patient seems to be out of breath. As the nurse on duty, what would be your immediate action?",
    options: [
      "Call for help, assess the level of consciousness, check vital signs and reassure the patient",
      "Call for help, check vital signs, resuscitate and position the patient",
      "Call for help, assess level of consciousness, check vital signs, secure access and reassure the patient",
      "Insert a nasogastric tube immediately",
    ],
    correctIndex: 0,
    rationale: "The client is already experiencing respiratory distress, so calling for help and reassessing signs is the first priority before securing intravenous access. Since the client is vomiting large volumes of blood, positioning to prevent aspiration and protect the airway is also important.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A patient diagnosed with leukaemia has been on chemotherapy for the past three weeks and reports pain, a burning sensation and difficulty swallowing. Examination shows mouth ulcers and a reddish beefy tongue, and the client is concerned about inability to eat or drink. Which intervention would you recommend?",
    options: [
      "Advise avoidance of hot beverages, salty foods and citrus fruits, take prescribed pain relievers, and gargle with cool water and suck ice pops",
      "Encourage spicy and hot foods, gargle with salt water, and take pain relievers",
      "Avoid all oral intake and rely on intravenous fluids",
      "Use alcohol based mouthwash three times daily",
    ],
    correctIndex: 0,
    rationale: "Clients with oral ulcers from chemotherapy should avoid hot beverages, salty and citrus foods, take prescribed pain relievers, and gargle with cool water and suck ice pops to promote pain relief, prevent irritation and promote healing.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "A patient diagnosed with meningitis is scheduled for a lumbar puncture. The nurse explains that the spinal needle will be introduced between the?",
    options: ["L3 and L4 vertebrae", "L1 and L2 vertebrae", "T12 and L1 vertebrae", "L5 and S1 vertebrae"],
    correctIndex: 0,
    rationale: "During a lumbar puncture the needle is inserted through the tissues of the lower back into the spinal canal to obtain a sample of cerebrospinal fluid. The needle is introduced between the L3 and L4 vertebrae because the spinal cord typically ends at the level of L1 to L2, making it safer to avoid penetrating the lower spinal segments.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A patient diagnosed with severe hypertension is admitted and being managed for both hypertension and gastritis. As the attending nurse, you understand the gastritis is a result of which of the following?",
    options: [
      "Medications and stress",
      "Disease condition and stress",
      "Excessive production of gastric juice",
      "Bacterial infection alone",
    ],
    correctIndex: 0,
    rationale: "The gastritis is likely due to a combination of medication use, such as nonsteroidal anti-inflammatory drugs for pain management, and the physiological stress associated with hypertension, which can increase gastric acid production and further irritate the stomach lining.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A patient experiencing an ischaemic stroke is to exhibit which of the following neurological symptoms?",
    options: ["Dysarthria", "Dyscrasia", "Dysthymia", "Dysmenorrhoea"],
    correctIndex: 0,
    rationale: "Ischaemic stroke is caused by blockage of blood flow to the brain, leading to neurological symptoms such as dysarthria, which is difficulty speaking or slurred speech.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "A patient admitted to the hospital with a diagnosis of bacterial meningitis develops a seizure. The nurse should?",
    options: [
      "Note body movement, time and length of the seizure",
      "Restrain the patient with stirrups",
      "Tepid sponge the patient to reduce pyrexia",
      "Insert an oral airway immediately",
    ],
    correctIndex: 0,
    rationale: "Recording body movement, time and length of the seizure provides important information for the medical team to determine the cause of the seizure and guide appropriate treatment.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "A patient is admitted to the ward with a diagnosis of hypocalcaemia. On assessment, the patient begins to twitch the facial muscles in response to tapping the facial nerve. This characteristic sign of hypocalcaemia is termed?",
    options: ["Chvostek's sign", "Romberg's sign", "Trousseau's sign", "Babinski's sign"],
    correctIndex: 0,
    rationale: "Twitching of the facial muscles in response to tapping the facial nerve is known as Chvostek's sign, a characteristic sign of hypocalcaemia due to increased neuronal excitability from low calcium levels.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "A patient is admitted to your ward with a history of haemoptysis, weakness and cough. Which respiratory disorder is the patient most likely to be diagnosed with?",
    options: ["Pneumonia", "Empyema", "Bronchiectasis", "Pleurisy"],
    correctIndex: 0,
    rationale: "The symptoms of haemoptysis, weakness and cough are commonly associated with pneumonia, an infection of the lung parenchyma, suggesting an inflammatory response to infection causing damage to lung tissue, potentially leading to haemoptysis and weakness.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "A patient is on admission with pericarditis. Which of the following could be causes of this condition?",
    options: [
      "Infections and renal failure",
      "Infections and brain injury",
      "Brain injury and renal failure",
      "Brain injury and hypertension",
    ],
    correctIndex: 0,
    rationale: "Pericarditis is inflammation of the pericardium, the sac-like membrane surrounding the heart. It can be caused by infections and renal failure, but not brain injury.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "A patient on the ward has jaundice. Which of the following is the nurse likely to observe in this patient?",
    options: ["Urine appears dark brown", "Fats in the stool", "Stool is clay coloured", "Pale urine"],
    correctIndex: 0,
    rationale: "In haemolytic jaundice, the breakdown of red blood cells and the resulting bilirubin is excreted in the urine, leading to dark brown urine, while stool colour is not affected.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "A patient with heart failure and diarrhoea is on admission. Which of the following drugs might be responsible for the diarrhoea?",
    options: ["Diuretics", "Antibiotics", "Antihypertensives", "Anticoagulants"],
    correctIndex: 0,
    rationale: "Diuretics are a common cause of diarrhoea and electrolyte disturbance in clients with heart failure.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
];
