/**
 * Past NMC examination questions - Medical Nursing paper (part 2).
 *
 * Transcribed from a real past paper supplied by the operator. Answers are
 * derived from the rationales printed in the paper, not from an official
 * answer key, so each is flagged verified: false for review.
 */

import type { PastQuestion } from "./past-paper-medical";

export const PAST_PAPER_MEDICAL_2: PastQuestion[] = [
  {
    stem: "Inusa White was rushed to the medical unit with chest pain, palpitations, sweating and unusual fatigue, and is diagnosed with acute coronary syndrome. To promote adequate tissue perfusion and reduce myocardial oxygen consumption, which action by the nurse would be most appropriate?",
    options: [
      "Ensuring bed rest during the initial phase",
      "Monitoring the peripheral pulse frequently",
      "Evaluating the client's temperature",
      "Encouraging early ambulation",
    ],
    correctIndex: 0,
    rationale: "Ensuring bed rest during the initial phase of acute coronary syndrome helps reduce physical exertion and minimise myocardial oxygen demand, thus promoting adequate tissue perfusion and reducing the risk of further cardiac injury.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Mr Adama, a lawyer, is at risk of developing a myocardial infarction due to significant narrowing of the coronary arteries. Which specific class of medicine would be chosen for Mr Adama?",
    options: [
      "Anti-platelet agents",
      "Loop diuretics",
      "Beta blockers only",
      "Antibiotics",
    ],
    correctIndex: 0,
    rationale: "Anti-platelet agents are given to prevent clots from forming in the blood and reduce the risk of myocardial infarction in a client with unstable angina, because of their anti-platelet properties.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Mr James Bossman was admitted with difficulty in breathing. A chest x-ray showed accumulation of purulent fluid in the pleural space. This can be documented as?",
    options: ["Empyema", "Lung abscess", "Pleural effusion", "Pneumonia"],
    correctIndex: 0,
    rationale: "Empyema is characterised by the accumulation of infected fluid, unlike pleural effusion which contains non-infected fluid, in the pleural space. It often results from an infection such as pneumonia and causes difficulty breathing, fever and chest pain.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "Mr James Brown, 61 years, is diagnosed with diabetes mellitus type II. In planning his management, the nurse should consider which of the following?",
    options: [
      "Diet, exercise and insulin",
      "Diet, exercise, insulin and antibiotics",
      "Diet and exercise only",
      "Insulin and antibiotics only",
    ],
    correctIndex: 0,
    rationale: "Diet and exercise are important components of diabetes management, while insulin is a common treatment option for clients with type II diabetes who cannot control their blood sugar levels with diet and exercise alone. Antibiotics are not part of routine management.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "Mr James Dawson, a 60-year-old carpenter, is being assessed for possible valvular heart disease. Which findings support this condition?",
    options: [
      "Previous surgical repair of an atrial septal defect, presence of a diastolic murmur, and hypertension for five years",
      "Previous surgery and being underweight only",
      "Hypertension and being underweight only",
      "Being underweight and a diastolic murmur only",
    ],
    correctIndex: 0,
    rationale: "Previous heart surgery increases the risk of developing heart valve problems, a murmur can indicate abnormal blood flow through the valves, and high blood pressure can damage the valves over time. Being underweight is not a known risk factor for valvular heart disease.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Mr John Ahidu, a 33-year-old driver diagnosed with a lung abscess, is being prepared for discharge. Which are established risk factors for his condition?",
    options: [
      "Aspiration, necrotising pneumonia and empyema",
      "Aspiration and necrotising pneumonia only",
      "Aspiration, necrotising pneumonia, empyema and chest trauma",
      "Chest trauma and empyema only",
    ],
    correctIndex: 0,
    rationale: "Aspiration, necrotising pneumonia and empyema are established risk factors for lung abscess as they can cause lung infection and tissue damage. Chest trauma is not always a consistent risk factor for lung abscess.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "Mr John Amevor, 42 years, is about to be discharged from the ward. Which feedback about his medications suggests the need for further teaching?",
    options: [
      "I will restart the medications when signs and symptoms of complications start",
      "I will keep the medications where they can easily be seen",
      "I will collect the medications from the pharmacy on my way home",
      "I will take my medications at the same time every day",
    ],
    correctIndex: 0,
    rationale: "It is important to take medications as prescribed even when signs and symptoms have resolved, to prevent recurrence of the condition or other complications. Stopping when symptoms resolve shows a need for further teaching.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Mr John Boachie, a 56-year-old farmer, has been diagnosed with heart failure and asked to limit fluid intake to two litres. Which action by the nurse is MOST appropriate to help him adhere?",
    options: [
      "Allow him to sip water or ice chips when thirsty",
      "Pour the required fluid into a two litre bottle",
      "Make two litres of intravenous infusions available every day",
      "Restrict all fluids until the next review",
    ],
    correctIndex: 0,
    rationale: "Allowing the client to sip water or ice chips provides relief from thirst and makes it easier to monitor and track fluid intake throughout the day, helping him adhere to the prescribed limit.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Mr Jones Armah reports to the eye clinic with blurred vision, eye pain, nausea and vomiting. Which pressure does the nurse expect to find?",
    options: [
      "Increased intraocular pressure",
      "Increased intracranial pressure",
      "Decreased intraocular pressure",
      "Normal intraocular pressure",
    ],
    correctIndex: 0,
    rationale: "These symptoms are indicative of acute angle-closure glaucoma, where a rapid increase in pressure inside the eye damages the optic nerve and can lead to vision loss if not treated promptly.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Mr Julius Peterson, a 38-year-old mechanic, accidentally hit his left arm with a hammer and was rushed in with a deep cut that was bleeding profusely. This type of injury is described as?",
    options: ["Impairment", "Handicap", "Disability", "Deformity"],
    correctIndex: 0,
    rationale: "Impairment refers to a temporary or permanent reduction or loss of function in a body part, which is relevant to the described injury caused by a deep cut on the left arm.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Mr Kay Oquaye, a 37-year-old farmer, is admitted with stiffness in the jaw and neck, fever, opisthotonos and severe generalised tonic spasms, and is diagnosed with tetanus. Which agent is used to control the severe spasms?",
    options: ["Benzodiazepines", "Barbiturates", "Neuromuscular blocking agents", "Antibiotics"],
    correctIndex: 0,
    rationale: "Benzodiazepines are commonly used to control severe spasms in clients with tetanus because they have muscle-relaxant properties and can alleviate muscle stiffness and spasm.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "Mr Kofi Agiriga, 72 years, admitted with chronic lymphocytic leukaemia, looks pale and confused with a haemoglobin of 6.2 g/dL and is scheduled for transfusion. The nurse understands that indications for transfusion include?",
    options: [
      "Anaemia, leucopenia and thrombocytopenia",
      "Anaemia and lymphocytosis only",
      "Anaemia and leucopenia only",
      "Thrombocytopenia and lymphocytosis only",
    ],
    correctIndex: 0,
    rationale: "Transfusion is indicated in chronic lymphocytic leukaemia where anaemia, leucopenia and thrombocytopenia are present, as these can result in decreased oxygen carrying capacity, decreased immune function and increased risk of bleeding.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "While planning the diet for Mr Kofi Alhassan, a client on the ward, the charge nurse advised increasing the quantity of fibre. Fibre in a diabetic diet plays a role in?",
    options: [
      "Lowering total cholesterol and low density lipoprotein",
      "Increasing total cholesterol and low density lipoprotein",
      "Lowering total cholesterol and high density lipoprotein",
      "Raising triglyceride levels",
    ],
    correctIndex: 0,
    rationale: "Fibre in a diabetic diet helps lower total cholesterol and low density lipoprotein levels. LDL is often referred to as bad cholesterol, and raised levels increase the risk of heart disease and stroke.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "Mr Kofi Lolonyo is on the ward with a history of obstruction in the common bile duct, yet to be diagnosed. What would you expect the client's stools to look like?",
    options: [
      "Clay coloured",
      "Black and tarry",
      "Greenish yellow",
      "Bright red",
    ],
    correctIndex: 0,
    rationale: "Obstruction of the common bile duct prevents bile from reaching the intestine, so the stool loses its normal brown colour and becomes pale or clay coloured.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Mr Kofi Ntow, 43 years, is on admission with chronic pancreatitis. During education towards discharge, the nurse focuses most on?",
    options: [
      "Encouraging him to abstain from alcohol",
      "Adhering to pancreatic enzyme replacement therapy",
      "Explaining the potential complications of the condition",
      "Teaching the signs of diabetes mellitus",
    ],
    correctIndex: 0,
    rationale: "Chronic pancreatitis is often associated with alcohol consumption, and abstinence from alcohol is one of the most effective ways to prevent further damage to the pancreas.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Mr Kofi Sei-Abudu, a 20-year-old farmer on the ward with nephrotic syndrome. Which of the following is characteristic of his condition EXCEPT?",
    options: ["Hyperalbuminaemia", "Proteinuria", "Hypoalbuminaemia", "Oedema"],
    correctIndex: 0,
    rationale: "Nephrotic syndrome is characterised by proteinuria, the loss of large amounts of protein in the urine, and hypoalbuminaemia, a low level of albumin in the blood. Hyperalbuminaemia goes against the characteristic features of nephrotic syndrome.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Mr Kojo Nsiah is on admission with chronic renal injury. The stages of chronic renal injury, starting from decreased renal reserve, progress in which order?",
    options: [
      "Renal insufficiency, renal injury, uraemia",
      "Renal insufficiency, uraemia, renal injury",
      "Renal insufficiency, renal failure, uraemia",
      "Uraemia, renal injury, renal insufficiency",
    ],
    correctIndex: 0,
    rationale: "The stages of chronic renal injury, starting from decreased renal reserve, then renal insufficiency, renal injury and finally uraemia, reflect the progressive loss of renal function over time and the increasing accumulation of metabolic waste products in the blood.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Mr Kwabena Fordjour, 66 years, reports urgency, frequency of micturition and dysuria. These complaints may be indicative of which conditions?",
    options: [
      "Urethral stricture and benign prostatic hyperplasia",
      "Glomerulonephritis",
      "Renal calculus",
      "Acute pyelonephritis only",
    ],
    correctIndex: 0,
    rationale: "Urgency, frequency of micturition and dysuria are common symptoms of lower urinary tract conditions such as urethral stricture, which is narrowing of the urethra, and benign prostatic hyperplasia, which is enlargement of the prostate gland.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Mr Kwame Nketsiah, a 40-year-old man admitted with an abdominal mass. To detect the size and density of the mass, the nurse should?",
    options: [
      "Deeply palpate the client's abdomen",
      "Auscultate all quadrants of the abdomen",
      "Percuss the client's abdomen",
      "Inspect the abdomen visually",
    ],
    correctIndex: 0,
    rationale: "A nurse would use deep palpation to detect the size and density of an abdominal mass, as this technique involves applying moderate pressure to the abdomen to feel for abnormalities.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Mr Kwasi Osokye, 40 years, reports severe pain, redness, swelling and warmth at the left big toe. Gout is diagnosed. Apart from pharmacologic treatment, which food should he reduce in his diet?",
    options: ["Sardine", "White bread", "Banana", "Rice"],
    correctIndex: 0,
    rationale: "The client should reduce intake of sardines, which are high in purines and can raise uric acid levels in the body, exacerbating the symptoms of gout.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Mr Lambon Seese, a 60-year-old admitted with rheumatoid arthritis, is to begin treatment with hydroxychloroquine (Plaquenil). Which should be done before the client begins this medication?",
    options: [
      "Fundoscopic examination",
      "Pulmonary function testing",
      "Serum creatinine",
      "Liver biopsy",
    ],
    correctIndex: 0,
    rationale: "A fundoscopic examination is recommended before starting hydroxychloroquine to assess for retinal toxicity, as the medicine has the potential side effect of causing retinal damage, and early detection can help prevent vision loss.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Mr Leonard Elson is receiving loop diuretics (furosemide) as treatment for hypertension. Loop diuretics are important in the management of hypertension because they?",
    options: [
      "Block reabsorption of sodium and water in the kidneys",
      "Impair synthesis of norepinephrine",
      "Block the effect of angiotensin II",
      "Increase cardiac output",
    ],
    correctIndex: 0,
    rationale: "Loop diuretics block reabsorption of sodium and water in the kidneys by inhibiting the activity of the sodium-potassium-chloride cotransporter in the thick ascending limb of the loop of Henle.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Mr Mawusi Alovi, a 60-year-old man admitted with atelectasis. Which measures would enhance adequate lung expansion?",
    options: [
      "Encourage voluntary deep breathing manoeuvres",
      "Change the client's position frequently",
      "Encourage early ambulation from bed to chair",
      "Administer prescribed bronchodilators",
    ],
    correctIndex: 0,
    rationale: "Encouraging voluntary deep breathing exercises, such as deep breathing and coughing, helps remove trapped air in the lungs, expand the alveoli and improve gas exchange, promoting adequate lung expansion in clients with atelectasis.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "Mr Maxwell Sogah is admitted with pulmonary embolism. The charge nurse explains to the student nurses that the most common cause of pulmonary embolism is a?",
    options: ["Thrombus", "Thrombin", "Embolus", "Air bubble"],
    correctIndex: 0,
    rationale: "A thrombus is a blood clot that has formed in the bloodstream and broken free to travel to the lungs, causing a blockage and resulting in a pulmonary embolism.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "Mr Ofori Yeboah is receiving treatment on the ward for cirrhosis of the liver. Which of the following is TRUE about his condition?",
    options: [
      "Raised serum glutamic oxaloacetic transaminase",
      "Increased serum magnesium",
      "Normal prothrombin time",
      "Decreased serum bilirubin",
    ],
    correctIndex: 0,
    rationale: "In cirrhosis of the liver the liver cells are damaged, leading to an increase in alanine aminotransferase, an enzyme mainly found in liver cells. The rise in enzyme levels indicates liver damage and is a sign of cirrhosis.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Mr Okoto works in a stone quarry and has been diagnosed with pleural effusion. He is to undergo thoracocentesis. The nurse on duty explains that the procedure is to?",
    options: [
      "Remove fluid from the pleural space",
      "Remove air from the lungs",
      "Prevent recurrence of the disease",
      "Drain pus from the lung tissue",
    ],
    correctIndex: 0,
    rationale: "Thoracocentesis is a medical procedure that involves insertion of a needle or catheter through the chest wall into the pleural space, between the lungs and the chest wall, to remove excess fluid such as that seen in pleural effusion.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "Mr Oluwa, aged 57 years, diagnosed with lung cancer and admitted with pleural effusion, complains of severe chest pain and is to undergo thoracentesis. To avoid trauma to the pleura and lung, the nurse will?",
    options: [
      "Ensure strict aseptic technique",
      "Expose the client's entire chest",
      "Encourage the client to refrain from coughing",
      "Position the client supine",
    ],
    correctIndex: 0,
    rationale: "Strict aseptic technique helps prevent infection and contamination, which is crucial during thoracentesis to avoid trauma to the visceral pleura and lung and ensure safe and effective removal of fluid from the pleural space.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "Mr Opoku Kyere with advanced AIDS has been brought to the emergency department by his family. The nurse needs additional information regarding his?",
    options: [
      "Last review date",
      "Social life",
      "Dietary intake",
      "Family support",
    ],
    correctIndex: 0,
    rationale: "It is crucial in managing advanced AIDS to know the last time the client had a comprehensive evaluation and what medications he was receiving, as this information can impact the current treatment plan and guide further management.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "Mr Oswald Obeng is diagnosed with haemolytic jaundice. Which of the following is the nurse likely to observe?",
    options: [
      "Urine appears dark brown",
      "Stool is clay coloured",
      "Skin is hot and dry",
      "Stool is pale and greasy",
    ],
    correctIndex: 0,
    rationale: "In haemolytic jaundice red blood cells are destroyed faster than they can be produced, leading to raised bilirubin levels. The urine appears dark brown because of the high levels of bilirubin being eliminated through the urine.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Mr Paul Glah has been on the ward with gout and is due for discharge. To prevent recurrence of the condition, health education on his diet would encourage Mr Glah to take in more?",
    options: ["Vegetables", "Water", "Lean meat", "Sardines"],
    correctIndex: 0,
    rationale: "Vegetables are a key component of a gout-friendly diet because they are low in purines, nitrogen-containing compounds found in many foods that can lead to elevated uric acid levels and trigger gout attacks.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Mr Peter Amedor reported to the emergency unit with right upper quadrant pain and heartburn. What would be the MOST likely diagnosis?",
    options: ["Acute gastric ulcer", "Chronic gastric ulcer", "Chronic pancreatitis", "Cholecystitis"],
    correctIndex: 0,
    rationale: "Acute gastric ulcer is the most likely diagnosis given the presence of right upper quadrant pain with heartburn, which are common symptoms of an acute gastric ulcer.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Mr Phillip Sosa is on the ward with diabetes mellitus. You are preparing a tray for neurological assessment of this client. Which item would you include to test for sensation?",
    options: ["Pin", "Cotton wisp", "Fine brush", "Tuning fork"],
    correctIndex: 0,
    rationale: "A pin provides a sharp, distinct sensation that helps assess the client's ability to differentiate types of pain. This helps determine whether there is nerve damage or neuropathy, which can occur in individuals with diabetes mellitus.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "Mr Salifu Nkasah has been put on metolazone 10 mg. Which class of medicine does this fall under?",
    options: ["Diuretic", "Antibiotic", "Antihistamine", "Antihypertensive only"],
    correctIndex: 0,
    rationale: "Metolazone is prescribed to reduce fluid build-up and swelling in conditions such as heart failure and high blood pressure, by blocking absorption of salt and water in the kidneys and leading to increased urine production.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Mr Salisu Amanor has been scheduled for an ECG examination and is anxious to know the reason. Which is the BEST response from the nurse?",
    options: [
      "It shows the presence of myocardial infarction",
      "It determines the client's potential target heart rate",
      "It shows how the heart performs when at rest",
      "It measures the oxygen saturation",
    ],
    correctIndex: 0,
    rationale: "Electrocardiograms are performed to monitor the electrical activity of the heart and identify potential heart conditions such as myocardial infarction.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Mr Standish Blankson, a 53-year-old farmer, was rushed to the accident and emergency unit by his wife with a history of dysuria, urgency and hesitancy of micturition for five days. A student nurse asks what amount of urine in the bladder makes it percussible?",
    options: ["140 mL", "130 mL", "150 mL", "100 mL"],
    correctIndex: 0,
    rationale: "When the bladder is empty it lies entirely within the pelvis and cannot be percussed. As it fills it expands upwards and can be felt as a rounded mass above the pubic symphysis, becoming percussible with a dull sound when there is around 140 mL of urine.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Mr Stephen Bimbo, 57 years, admitted with diabetes mellitus type I and on insulin therapy, understands that insulin lowers blood glucose by which mechanisms?",
    options: [
      "Decreasing the release of glucose from the liver, and increasing the utilisation of glucose by muscle and fat cells",
      "Decreasing glucose release from the liver and sensitising pancreatic cells to produce more insulin",
      "Increasing glucose utilisation by muscle and fat cells, and sensitising pancreatic cells",
      "Sensitising pancreatic cells and increasing insulin production",
    ],
    correctIndex: 0,
    rationale: "Insulin lowers blood glucose by decreasing the release of glucose from the liver and increasing the utilisation of glucose by muscle and fat cells. Insulin does not sensitise pancreatic cells to produce more insulin.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "Mr Sulemana Osei has been diagnosed with end stage renal failure and is scheduled to undergo haemodialysis. Which should be considered when planning his diet?",
    options: [
      "Protein restriction",
      "High protein diet",
      "High calorific diet",
      "Unrestricted fluids",
    ],
    correctIndex: 0,
    rationale: "A low protein diet is recommended for individuals with end stage renal failure undergoing haemodialysis, to reduce the workload on the damaged kidneys and prevent accumulation of harmful waste products in the blood.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Mr Tobi, a 50-year-old teacher, has been managed on colchicine for gout for several years. Prolonged use of this medicine can result in which of the following?",
    options: [
      "Decreased vitamin B12 absorption",
      "Development of tophi",
      "Bone marrow depression",
      "Hepatic failure",
    ],
    correctIndex: 0,
    rationale: "Colchicine reduces pain and inflammation in gout but can cause gastrointestinal side effects including diarrhoea, nausea and vomiting. These can decrease absorption of vitamin B12 from the gut, leading to vitamin B12 deficiency over time.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Mr Valentine Osei was found unconscious in a hypertensive crisis, with his daughter hysterical beside him. To prevent infection or stomatitis, the nurse should clean his mouth?",
    options: ["As often as needed (P.R.N.)", "Daily", "Twice daily", "Once per shift"],
    correctIndex: 0,
    rationale: "Oral care in a client in a hypertensive crisis should be performed as needed. The priority is to stabilise the blood pressure and ensure the airway is clear and protected, and oral hygiene can be addressed once the client's condition is stabilised.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Mrs Lily Quaicoo, a 50-year-old banker, has been admitted to the medical ward with oedema of the feet and ankles. Which would you include in your nursing management?",
    options: [
      "A free sodium diet",
      "Wearing of stockings",
      "Daily weighing",
      "Restricting all activity",
    ],
    correctIndex: 0,
    rationale: "Oedema is often caused by fluid build-up in the tissues, and a diet low in sodium can help reduce fluid retention and relieve the symptoms of oedema.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Mr Yaw Asamoah, 28 years, is admitted with a diagnosis of pneumothorax. Which actions or instructions from the nurse could help re-expansion of the lungs?",
    options: [
      "Keeping him in a high Fowler's position and encouraging deep breathing and coughing exercises",
      "Administration of analgesics, keeping in high Fowler's position and encouraging fluids",
      "Keeping him in high Fowler's position and encouraging fluids only",
      "Encouraging fluids and administering analgesics only",
    ],
    correctIndex: 0,
    rationale: "Keeping the client in a high Fowler's position and encouraging deep breathing and coughing exercises can help re-expand the lungs in pneumothorax by increasing lung capacity, promoting better gas exchange and removing air from the pleural space.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "Mr Yaw Paintsil, 53 years, is admitted with chronic pancreatitis. In planning care, the nurse understands that the MOST common cause of this condition is?",
    options: ["Alcohol abuse", "Malnutrition", "Smoking", "Gallstones"],
    correctIndex: 0,
    rationale: "Chronic pancreatitis is most commonly caused by long-term alcohol abuse, as excessive alcohol consumption can lead to formation of pancreatic ductal stones and fibrosis, resulting in chronic inflammation and damage to the pancreas.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Mrs Arko Dann reports at the outpatient department with joint pain and stiffness that began in the small joints of the hands, wrists and feet, especially in the morning and lasting more than 30 minutes. What other possible symptom would you obtain to confirm rheumatoid arthritis?",
    options: [
      "Are you experiencing fatigue and fever as well?",
      "Is your pain aggravated by extremes of temperature?",
      "Does the pain worsen before bedtime?",
      "Do you have pain only after exercise?",
    ],
    correctIndex: 0,
    rationale: "Rheumatoid arthritis is a chronic autoimmune disease that primarily affects the joints but can also cause systemic symptoms such as fatigue and fever. Joint symptoms typically include pain, stiffness and swelling in the hands, wrists and feet, especially in the morning or after inactivity.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Mrs Abena Stephens, a 54-year-old known diabetic, was rushed to the emergency unit with severe vomiting, weakness and headache, a weak rapid pulse and lethargy. Diabetic ketoacidosis was diagnosed. The choice of intravenous fluid in the initial management would be?",
    options: [
      "0.9% sodium chloride",
      "5% dextrose",
      "0.45% sodium chloride",
      "Dextrose in saline",
    ],
    correctIndex: 0,
    rationale: "0.9% sodium chloride is preferred as it helps restore fluid balance and increase blood volume. 0.45% sodium chloride has a lower concentration and may not effectively treat the fluid loss.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "Mrs Adjoa Adusa, an 80-year-old, reports dyspnoea on exertion and increased swelling of both legs. Assessment reveals a systolic murmur at the second right intercostal space radiating to the apex. Mrs Adusa is likely to be diagnosed with?",
    options: [
      "Aortic stenosis",
      "Mitral valve stenosis",
      "Aortic regurgitation",
      "Mitral regurgitation",
    ],
    correctIndex: 0,
    rationale: "The presence of a systolic murmur at the second right intercostal space radiating to the apex is a classic finding of aortic stenosis, which is narrowing of the aortic valve causing obstruction of blood flow from the left ventricle to the aorta. This can lead to dyspnoea on exertion and leg swelling.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Mrs Akosua Boateng, 38 years, has been admitted with end-stage cancer of the breast and complains of severe pain. In assessing her pattern of pain, which would you take key note of?",
    options: [
      "Duration, time of onset, degree of pain and intervals without pain",
      "Duration and time of onset only",
      "Duration, time of onset and intervals without pain",
      "Degree of pain alone",
    ],
    correctIndex: 0,
    rationale: "It is important to note the duration, time of onset, degree of pain and intervals without pain when assessing a client's pain pattern, in order to effectively evaluate the effectiveness of pain management measures and make necessary adjustments for optimal pain control.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Mrs Akosua Inkoom, 31 years, is admitted with generalised oedema and asks about her condition. In explaining the diagnosis, the nurse mentioned which of the following as the main cause?",
    options: [
      "The kidneys are not regulating water and sodium balance well",
      "The skin is not excreting fluid since she is not sweating",
      "The heart is not moving water throughout the body well",
      "She is drinking too much water",
    ],
    correctIndex: 0,
    rationale: "Generalised oedema, the accumulation of excess fluid in the body tissues, is often caused by an imbalance between the forces regulating movement of fluid across capillary walls. In this case the kidneys are not regulating water and sodium balance well, resulting in excessive fluid accumulation in the tissues.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Mrs Alberta Mohammed, 52 years, is receiving oxygen therapy for respiratory distress and the oxygen saturation drops to 85%. The nurse's immediate actions should include?",
    options: [
      "Checking the oxygen apparatus for leaks, and assessing the airway for obstruction",
      "Checking for leaks, assessing the airway and increasing the oxygen dosage",
      "Assessing the airway, increasing the oxygen and propping up into high Fowler's position",
      "Increasing the oxygen dosage and propping up into high Fowler's position",
    ],
    correctIndex: 0,
    rationale: "Increasing the oxygen dosage may be inappropriate without first checking the oxygen apparatus and assessing the airway, because the issue may not be inadequate oxygen delivery but rather a problem with the equipment or the airway.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "Mrs Anokor Partey, a 53-year-old trader from a rural village, reported at the outpatient department with difficulty in swallowing, regurgitation and chest pain. In assessing Mrs Partey, the nurse should acknowledge that there is paralysis of the?",
    options: ["Lower oesophagus", "Left lung", "Mediastinum", "Pharynx"],
    correctIndex: 0,
    rationale: "Difficulty in swallowing, regurgitation and chest pain indicate a possible issue with the lower oesophagus, which can be caused by paralysis of the lower oesophagus.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Mrs Azara Nortey, 32 years, is admitted on account of diarrhoea with dehydration. The nurse recognises that the increased peristalsis resulting in diarrhoea can be related to?",
    options: [
      "Parasympathetic stimulation",
      "Sympathetic stimulation",
      "Mixing and propulsion",
      "Reduced intestinal motility",
    ],
    correctIndex: 0,
    rationale: "Diarrhoea is characterised by increased frequency of bowel movements, which can be caused by increased motility of the intestinal smooth muscle due to parasympathetic stimulation.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Mrs Barbara Cofie, 30 years, reported to the hospital with painful itchy blisters suspected to be herpes zoster. The nurse MUST consider requesting all of the following EXCEPT?",
    options: ["Blood glucose levels", "Complete blood count", "Haemoglobin test", "Viral serology"],
    correctIndex: 0,
    rationale: "The painful itchy blisters are characteristic of herpes zoster and are not indicative of a change in blood glucose levels, so a blood glucose test is not specifically required.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "Mrs Felicia Anson is on the ward with a cerebrovascular accident. Which of the following are causes of her condition?",
    options: [
      "Embolism and haemorrhage",
      "Aneurysm, embolism and haemorrhage",
      "Aneurysm only",
      "Aneurysm and embolism only",
    ],
    correctIndex: 0,
    rationale: "Cerebrovascular accidents can be caused by embolism, thrombosis or bleeding in the brain. Cerebral aneurysms are balloon-like bulges in the blood vessels supplying the brain but are not a direct cause of the accident itself.",
    category: "Neurological Nursing",
    verified: false,
  },
  {
    stem: "Mrs Fiona Sedor has been admitted with a provisional diagnosis of metabolic liver dysfunction pending further investigation. The involuntary flapping movement of the hands associated with her condition is called?",
    options: [
      "Asterixis",
      "Fetor hepaticus",
      "Budd-Chiari syndrome",
      "Balloon tamponade",
    ],
    correctIndex: 0,
    rationale: "Asterixis is an involuntary flapping movement of the hands associated with metabolic liver dysfunction. Fetor hepaticus is a musty breath odour in liver failure, and Budd-Chiari syndrome is a vascular disorder of the liver.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Mrs Francisca Abban, aged 47, reported with complaints of muscular weakness, constipation, anorexia, bradycardia and heart block. Which condition is the client suffering from?",
    options: ["Hypercalcaemia", "Hyperkalaemia", "Hypocalcaemia", "Hypokalaemia"],
    correctIndex: 0,
    rationale: "These symptoms are common in raised calcium levels. Calcium plays an important role in muscle contraction, nerve transmission and heart function, so elevated levels cause weakness, constipation, anorexia, bradycardia and heart block.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "Mrs Henrietta Finn, 56 years, is admitted with osteoporosis. Which factors would you consider during history taking?",
    options: [
      "History of alcohol intake, constant dieting, family history of osteoporosis and history of fractures",
      "History of alcohol intake, constant dieting and family history only",
      "History of alcohol intake and history of fractures only",
      "Family history and history of fractures only",
    ],
    correctIndex: 0,
    rationale: "All of these factors are considered when taking a history for osteoporosis, as they all contribute to the development of the condition.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Mrs Josephine Amakye, 55 years, a known asthmatic, was rushed to the emergency unit with complaints of cough and difficulty in breathing. The MOST appropriate intervention by the nurse would be to administer which of the following?",
    options: [
      "Salbutamol aerosol 4 mg",
      "Intranasal oxygen at 4 L",
      "Ventolin tablet",
      "Intravenous hydrocortisone",
    ],
    correctIndex: 0,
    rationale: "Salbutamol aerosol is a quick-acting bronchodilator that relieves asthma symptoms such as cough and difficulty breathing, by relaxing the smooth muscle in the airways and allowing more air to flow into the lungs.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "Mrs Mabel Manso, 33 years, reported with a history of difficulty sitting quietly, profuse sweating and heat intolerance. She is likely to be diagnosed with?",
    options: [
      "Hyperthyroidism",
      "Pituitary hyperfunctioning",
      "Adrenal hyperfunctioning",
      "Diabetes mellitus",
    ],
    correctIndex: 0,
    rationale: "Hyperthyroidism is caused by overactivity of the thyroid gland, which produces excessive thyroid hormone. Symptoms include difficulty sitting quietly, restlessness, sweating, heat intolerance, weight loss and rapid heartbeat.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "Mrs White is a 40-year-old client complaining of heartburn two or three days a week, with some relief from over-the-counter antacids. She occasionally feels food is stuck. She denies vomiting, weight loss, coughing or wheezing. Which is the MOST appropriate initial plan?",
    options: [
      "Proton pump inhibitor",
      "Lifestyle and diet modification",
      "Referral for oesophagoscopy",
      "Immediate surgery",
    ],
    correctIndex: 0,
    rationale: "The symptoms are suggestive of gastro-oesophageal reflux disease, which is commonly treated with proton pump inhibitors to reduce gastric acid production and relieve symptoms.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Mrs Monica Adotei, on the ward with acute renal failure, has suddenly developed oedema of the lower extremities. Which statements describe oedema?",
    options: [
      "Can occur as a result of increased capillary fluid pressure, increased interstitial oncotic pressure, and decreased removal of interstitial fluid",
      "Increased capillary oncotic pressure, increased interstitial oncotic pressure and decreased removal of interstitial fluid",
      "Increased capillary fluid pressure, increased capillary oncotic pressure and increased interstitial oncotic pressure",
      "Increased capillary oncotic pressure and decreased removal of interstitial fluid only",
    ],
    correctIndex: 0,
    rationale: "Oedema occurs as a result of increased capillary fluid pressure, increased interstitial oncotic pressure and a decrease in removal of interstitial fluid, but not as a result of increased capillary oncotic pressure.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Mrs Naadu Williams, a 47-year-old wife of a mechanic, was diagnosed with Raynaud's disease. Raynaud's phenomenon is best explained by which of the following?",
    options: [
      "Intermittent episodes of vasoconstriction of small arteries of the feet and hands, and may occur with scleroderma and systemic lupus erythematosus",
      "Generally unilateral and affects only one or two digits, with vasoconstriction of small arteries",
      "Intermittent vasoconstriction affecting only one or two digits",
      "Vasodilation of the small arteries of the feet and hands",
    ],
    correctIndex: 0,
    rationale: "Raynaud's phenomenon is characterised by intermittent vasoconstriction of small arteries, can occur in the feet and hands, and may also occur as a symptom of other autoimmune disorders such as scleroderma and systemic lupus erythematosus. It is not generally unilateral.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Mrs Rita Agyei is diagnosed with acute pyelonephritis. During physical examination the nurse would elicit tenderness at which angle?",
    options: ["Costovertebral", "Costophrenic", "Lumbosacral", "Costochondral"],
    correctIndex: 0,
    rationale: "Tenderness at the costovertebral angle can indicate acute pyelonephritis, as the kidney is located in this area and may become inflamed in this condition.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Mrs Serena Mensah, a 36-year-old pharmacist, has been admitted with angina pectoris and placed on nitroglycerin tablets 2.5 mg three times daily. What instruction would you give her regarding administration of the medication?",
    options: [
      "Place the tablet under the tongue, do not swallow, and suck it slowly",
      "Crush the tablet in a little water on a spoon and swallow it",
      "Swallow the tablet with a full glass of water",
      "Chew the tablet before swallowing",
    ],
    correctIndex: 0,
    rationale: "Nitroglycerin is a vasodilator that works by relaxing the smooth muscle in blood vessels, increasing blood flow and reducing the workload of the heart. Crushing and swallowing it causes the medicine to be absorbed too quickly, which can lead to a sudden drop in blood pressure and other serious side effects.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Mrs Terkiba Duku, a 50-year-old teacher, is receiving treatment for arthritis on an outpatient basis. While educating her on steroids as part of her medications, you would emphasise the need to take the medication with meals because?",
    options: [
      "It will decrease gastric irritation",
      "The medication is ineffective in an acid medium",
      "It will serve as a reminder to take the medicine",
      "It increases absorption of the medicine",
    ],
    correctIndex: 0,
    rationale: "Steroids taken orally can cause gastrointestinal side effects such as acid reflux, heartburn and nausea. Taking the medicine with food helps decrease gastric irritation and reduces the risk of these side effects.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Ms Abiba Mansah has been rushed to the unit bleeding through her nose. Which action by the nurse can stop the bleeding immediately?",
    options: [
      "Instruct her to compress the nose between her fingers",
      "Allow her to lean forward",
      "Place her in an upright position",
      "Pack the nose with cotton wool",
    ],
    correctIndex: 0,
    rationale: "The client should be instructed to sit up straight and lean forward slightly, then compress the soft part of the nose against the septum using the thumb and index finger and hold for five to ten minutes. Leaning forward alone is not enough to stop the bleeding.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Ms Alima Boamah, 26 years, is admitted with severe anaemia and is being transfused with whole blood. Nurse Boateng was asked to remain with her for the first 15 minutes. What is the main reason for this?",
    options: [
      "Detect early transfusion reaction",
      "Collect a blood sample for haemoglobin level",
      "Ensure blood is flowing as regulated",
      "Reassure the client",
    ],
    correctIndex: 0,
    rationale: "The first 15 minutes of a blood transfusion are critical because most acute transfusion reactions occur within this time frame, and early detection allows prompt intervention to prevent the reaction from worsening.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Ms Atswei Kpekpeye had an ECG which revealed third degree atrioventricular block. She is likely to develop the following complications EXCEPT?",
    options: [
      "Cardiac tamponade",
      "Thromboembolic event",
      "Cardiac arrest",
      "Syncope",
    ],
    correctIndex: 0,
    rationale: "Cardiac tamponade is a condition caused by fluid accumulation in the sac around the heart, impairing filling of the heart chambers. Third degree atrioventricular block impairs the electrical conduction system instead.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Ms Baaba Daisy was given phenylephrine hydrochloride as part of the management of epistaxis. The purpose of administering this medication is to?",
    options: [
      "Narrow blood vessels",
      "Promote breathing",
      "Relieve nasal congestion",
      "Reduce pain",
    ],
    correctIndex: 0,
    rationale: "Phenylephrine hydrochloride is a nasal decongestant that constricts blood vessels in the nasal passages, reducing blood flow and inflammation. This helps reduce bleeding from the site of the nosebleed and promotes formation of clots to stop the bleeding.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Ms Barbara Sessi reported to the outpatient department with an itchy vulva and purulent offensive discharge. A vulval swab for culture revealed candidiasis. Which medication is MOST appropriate for treatment?",
    options: ["Nystatin", "Clindamycin", "Doxycycline", "Ciprofloxacin"],
    correctIndex: 0,
    rationale: "Nystatin is the most appropriate medicine for vulvovaginal candidiasis because it is an antifungal that acts on the Candida fungus, stopping its growth and relieving the symptoms of infection.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "Ms Foli reported to the outpatient department with right upper quadrant pain that worsens on eating fatty foods. Which condition would you suspect?",
    options: ["Cholecystitis", "Hepatitis", "Pancreatitis", "Gastritis"],
    correctIndex: 0,
    rationale: "Right upper quadrant pain that worsens after eating fatty foods suggests cholecystitis, which is inflammation of the gallbladder and a common cause of such symptoms.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Ms Dolly Sunu, a 25-year-old commercial sex worker, has been diagnosed with HIV infection. What are the implications of a positive HIV test result for this patient?",
    options: [
      "Antibodies to HIV are present in the blood, HIV is active in the body and can be transmitted to others, the person does not necessarily have AIDS, and the person is not immune to HIV",
      "Antibodies are present and the person is immune to HIV only",
      "The person has AIDS and cannot transmit the virus",
      "Antibodies are present but HIV is inactive in the body",
    ],
    correctIndex: 0,
    rationale: "A positive HIV test means the person has been infected with the virus, the virus is active in the body and can be transmitted to others, and they do not have immunity to it, although they may not necessarily have AIDS.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "Ms Esinam Togbor developed blister-like eruptions on her upper lip and nostrils after suffering from malaria. Investigations revealed herpes zoster virus. Which nerve is likely to be attacked by the virus?",
    options: ["Sensory nerve", "Mixed nerve", "Motor nerve", "Autonomic nerve"],
    correctIndex: 0,
    rationale: "Herpes zoster affects sensory nerves because it is caused by reactivation of the varicella-zoster virus in nerve cells, leading to a painful rash along the distribution of the affected nerve.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "Ms Evelyn Menaku was admitted from the medical outpatient department with swelling of the anterior part of the neck and was diagnosed with goitre. Which of the following is a sign or symptom of her condition EXCEPT?",
    options: [
      "Electrolyte imbalance",
      "Hoarseness of the voice",
      "Choking may occur with a monstrous goitre",
      "Difficulty in swallowing",
    ],
    correctIndex: 0,
    rationale: "Electrolyte imbalance is not usually considered a sign or symptom of goitre. It is usually a result of other medical conditions and not directly related to swelling of the anterior neck caused by goitre.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "Ms Felicia Kantanka, a 68-year-old woman, is on the ward with heart failure and receiving treatment. She started having abdominal pain, diarrhoea and vomiting. Which medication would you suspect to be responsible for these manifestations?",
    options: ["Diuretics", "Digoxin", "Hydralazine", "Anticoagulants"],
    correctIndex: 0,
    rationale: "These signs and symptoms could be caused by diuretics, as these medicines can cause electrolyte imbalance and dehydration, leading to gastrointestinal symptoms.",
    category: "Cardiovascular Nursing",
    verified: false,
  },
  {
    stem: "Ms Jane Fynn, a 30-year-old trader, was admitted to the ward. She presented with anaemia, and assessment revealed bone marrow failure resulting in pancytopenia. This type of anaemia is?",
    options: ["Aplastic", "Anaplastic", "Pernicious", "Iron deficiency"],
    correctIndex: 0,
    rationale: "Aplastic anaemia is caused by failure of the bone marrow, leading to a reduction in red blood cells, white blood cells and platelets in the body, which is called pancytopenia, a deficiency of all three types of blood cells.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Ms Joanna Boakye is admitted with chronic nasal sinusitis congestion. Which nursing action can relieve the congestion?",
    options: [
      "Inhalation of steam",
      "Application of warm compress",
      "Cold compress to the forehead",
      "Lying flat with the head raised",
    ],
    correctIndex: 0,
    rationale: "Inhalation of warm steam relieves nasal congestion by loosening and thinning mucus, promoting sinus drainage, reducing inflammation and swelling in the nasal passages and promoting easier breathing. This can be achieved through a steamy shower, a warm towel or a humidifier.",
    category: "Respiratory Nursing",
    verified: false,
  },
  {
    stem: "Ms Joy Salaam, a 32-year-old trader, is being assessed following treatment of Hashimoto's thyroiditis, an autoimmune disease. Which finding may suggest hypothyroidism?",
    options: [
      "Increased sensitivity to cold",
      "Chronic indigestion",
      "Massive weight loss",
      "Heat intolerance",
    ],
    correctIndex: 0,
    rationale: "Hypothyroidism causes decreased metabolism and energy production, leading to increased sensitivity to cold.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "Ms Joyce Anderson, 48 years, has been admitted with a diagnosis of hypothyroidism. During assessment the nurse should expect the following signs and symptoms EXCEPT?",
    options: ["Nervousness", "Weight gain", "Fatigue", "Cold intolerance"],
    correctIndex: 0,
    rationale: "Nervousness is a symptom associated with hyperthyroidism, not hypothyroidism. Weight gain and fatigue are commonly seen in individuals with hypothyroidism.",
    category: "Endocrine Nursing",
    verified: false,
  },
  {
    stem: "Ms Julie Moore, 28 years old, reported to the hospital with diarrhoea for three days. She was also observed to have dermatitis and appeared demented, with additional complaints of poor appetite and inability to sleep at night. The doctor described the clinical manifestations as a triad comprising?",
    options: [
      "Diarrhoea, dermatitis and dementia",
      "Diarrhoea, dermatitis and sleeplessness",
      "Diarrhoea, dermatitis and poor appetite",
      "Dermatitis, dementia and insomnia",
    ],
    correctIndex: 0,
    rationale: "The triad of diarrhoea, dermatitis and dementia suggests a systemic illness such as a metabolic or neurological disorder causing these symptoms together, as they are not typically seen in isolation and may indicate a more serious underlying condition.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Ms Juliet Torgbe, 36 years, has been diagnosed as having syphilis. Which organism causes Juliet's condition?",
    options: [
      "Treponema pallidum",
      "Chlamydia trachomatis",
      "Haemophilus ducreyi",
      "Neisseria gonorrhoeae",
    ],
    correctIndex: 0,
    rationale: "Treponema pallidum is the bacterium responsible for causing syphilis, which is a sexually transmitted infection with various clinical manifestations.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "Ms Linda Armah has been diagnosed with hypertension and placed on treatment on an outpatient basis. What would be the MOST effective way to increase the probability that she will implement a self-care regime at home?",
    options: [
      "Identify the client's coping mechanism at home",
      "Provide adequate education on heart healthy living",
      "Refer the client to a public health nurse in her community",
      "Give written instructions only",
    ],
    correctIndex: 0,
    rationale: "Identifying a client's coping mechanism at home helps tailor the self-care plan to the client's individual needs, strengths and weaknesses, which can increase motivation and ability to follow the plan.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Ms Mary Addison was diagnosed with cholelithiasis. During assessment she was seen to be jaundiced and her stools were clay coloured. These features are due to?",
    options: [
      "Decreased bile flow into the intestine",
      "Increased production of urobilinogen",
      "Increased bile and bilirubin in the blood",
      "Increased red cell destruction",
    ],
    correctIndex: 0,
    rationale: "Cholelithiasis, the presence of gallstones in the gallbladder or bile ducts, can obstruct the bile ducts, resulting in decreased bile flow into the intestine. This leads to inability to absorb fats and causes clay coloured stools, and also causes jaundice from accumulation of bilirubin in the blood.",
    category: "Gastrointestinal Nursing",
    verified: false,
  },
  {
    stem: "Mrs Serwaa Okoto, a 25-year-old vegetarian, has been admitted with megaloblastic anaemia. On discharging her home, you would encourage her to supplement her diet with vitamin?",
    options: ["B12", "B3", "B6", "C"],
    correctIndex: 0,
    rationale: "She should supplement her diet with vitamin B12 to treat her megaloblastic anaemia, as it helps in the formation of red blood cells and proper nerve function.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Ms Sylvia Ayittey, a 21-year-old sickle cell disease client, reported to the hospital with a sore on the right leg for the past year. All efforts made for the wound to heal proved futile. Poor wound healing in a client with sickle cell disease may be due to?",
    options: ["Hypoxia", "Poor compliance", "Anaemia", "Infection"],
    correctIndex: 0,
    rationale: "Sickle cell disease causes blocking of blood vessels, leading to decreased oxygen to tissues and organs including the wound site, impairing the body's ability to repair damaged tissue and promote wound healing.",
    category: "Renal Nursing",
    verified: false,
  },
  {
    stem: "Ms Tina Sampson reported to the hospital with complaints of dizziness, easy fatiguability and palpitations which started after her last menstrual period. Iron deficiency anaemia is suspected. Which MAIN clinical feature would you look out for to confirm your suspicion?",
    options: [
      "Smooth and shiny tongue",
      "Peripheral neuropathy",
      "Decreased bleeding time",
      "Spoon shaped nails",
    ],
    correctIndex: 0,
    rationale: "A smooth and shiny tongue can occur due to a lack of papillae, the small bumps on the tongue, which can be caused by a low red blood cell count and low iron levels.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Which feature distinguishes multiple myeloma from other cancers of the haematologic system?",
    options: ["Bone pain", "Genetics", "Common in Caucasians", "Splenomegaly"],
    correctIndex: 0,
    rationale: "Multiple myeloma is distinguishable by the presence of bone pain, resulting from abnormal plasma cells in the bone marrow destroying bone tissue.",
    category: "Fundamentals of Nursing",
    verified: false,
  },
  {
    stem: "Nurse Adama is assessing Mr Kwabena Doku, a 33-year-old fisherman with typhoid fever. She observes fever with rose coloured spots on the abdomen. These signs indicate Mr Doku is in which week of the infection?",
    options: ["Second week", "First week", "Third week", "Fourth week"],
    correctIndex: 0,
    rationale: "This rash appears in the second week of the illness. It is known as a typhoid rash and is caused by the bacterium Salmonella typhi.",
    category: "Infection Prevention",
    verified: false,
  },
  {
    stem: "Nurse Agnes Boateng is planning nursing care for Mr Peter Quarcoo who has a haemothorax. Which nursing goal is MOST important?",
    options: [
      "Relieving respiratory distress",
      "Improving hydration status",
      "Achieving maximum comfort",
      "Preventing infection",
    ],
    correctIndex: 0,
    rationale: "Relieving respiratory distress is the most important nursing goal, as haemothorax can lead to breathing difficulties and inadequate oxygenation of the body.",
    category: "Respiratory Nursing",
    verified: false,
  },
];
